### ISSUE TITLE
Inconsistent python version availability with Use Python Version task under Ubuntu 16.04

### ISSUE THREAD

**Issue by techalchemy** [microsoft/azure-pipelines-image-generation#1003]
**Describe the bug**
The Python Version available under the *Use Python Version* task is inconsistent under **Ubuntu 16.04** builds, which is causing build failures for us.  For example, the [documentation](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/linux/Ubuntu1604-README.md) indicates availability of python `3.7.3`, but our builds are failing [highly intermittently](https://dev.azure.com/pypa/pipenv/_build/results?buildId=8621) to find `3.7.3` (running old versions of the hosted agent I'm guessing)

**Expected behavior**
Documentation/agent rollout/tooling updates should all happen perfectly harmoniously and without incident and I should magically see whatever the documentation says in my hosted agents without having to do anything besides change the number in my config files :cake:

**Actual behavior**
I'm guessing this may relate to our agent pools being long-lived? Not too sure though

1. Run your agent pools for a long time?
2. Run tests using `Ubuntu 16.04` VM images
3. Declare explicit python version usage with the `UsePythonVersion` task
4. Watch the tests intermittently fail due to old tool directories

**Image impacted**
Ubuntu 16.04

**Comment by kcorrigan1** [comment]
I'm having the same issue with the 'Use Ruby Version' task on the Microsoft Hosted Ubuntu 1604 Agent. The documentation indicates that Ruby 2.6.2 is available, but we frequently have build failures with the following error message: 

```
##[error]Version spec ~> 2.6.2 for architecture %s did not match any version in Agent.ToolsDirectory.
Available versions: /opt/hostedtoolcache
2.3.7,2.4.4,2.5.1
```

**Comment by pombredanne** [comment]
Do we know where are the scripts that built these Python binaries in the first place?

**Comment by kaylangan** [comment]
This issue should be fixed now. We had deployed a buggy version of Python and had to roll back the version. During that deployment, we encountered some issues which is likely why you saw inconsistent versions of Python on the Ubuntu image.

@kcorrigan1 are you still seeing this for Ruby? If so, can you create a new issue? 

@pombredanne The scripts that built the Python binaries are not currently in this repo.

**Comment by kcorrigan1** [comment]
@kaylangan No, I'm not seeing this anymore for Ruby.

**Comment by pombredanne** [comment]
@kaylangan you wrote

> The scripts that built the Python binaries are not currently in this repo.

Could you publish these? there are likely several other issues with these, such as narrow vs wide build on 2.7.  To have any confidence in these, I would like to see the build scripts.
Thanks!
