### ISSUE TITLE
Update/Add [SqlPackage]

### ISSUE THREAD

**Issue by matlus** [microsoft/azure-pipelines-image-generation#1009]
**Tool information**
- Tool name: DacFramework
- Add or update? add
- Desired version: Latest Version
- If this is an add request:
  - Brief description of tool: I'd like to be able to deploy my database project to LocalDB using the DACPAC that is generated as an artifact of building my database project. This used to work earlier in Visual studio online. In Azure Pipeline it looks like the DacFramework is not installed on the hosted agent.
**Areas and ecosystems**
- [X] Database servers or clients
- [X] .NET Core or .NET Desktop

**Image impacted**
Add the appropriate label for the image or images that should be updated (e.g., macOS 10.13, macOS 10.14, ubuntu, VS2017, VS2019, WINCON).

**Workaround**

**Are you willing to submit a PR?**

**Comment by kaylangan** [comment]
Can you specify which images you're looking for this on?

**Comment by matlus** [comment]
This should be available on any image where local Db can be installed. Certainly Hosted VS2017 and Hosted Windows 2019 with VS2019. I know that MS SQL can be installed on MacOS now, but I've not been staying on the top of things for MacOS and Linux.

**Comment by MatthewSteeples** [comment]
Can this issue be re-opened, or am I better off creating a new issue? MSI installer can be found [here](https://docs.microsoft.com/en-us/sql/tools/sqlpackage-download?view=sql-server-ver15) which should be fairly straightforward to put into the image

**Comment by MatthewSteeples** [comment]
Ignore this, just realised it's not in this repo anymore
