### ISSUE TITLE
[Xamarin.Android] Cannot build Android project

### ISSUE THREAD

**Issue by sescandell** [microsoft/azure-pipelines-image-generation#1011]
**Describe the bug**
With a freshly new generated image of VS2019 we are not anymore able to compile Android projects.

Until now, we use a custom generated image from VS2017 (generated on October, 2018). But with freshly new images, we faced several issues and one that we do not succeed to fix: building an Android project.

Other issues fixed:

 * JDK capability not auto-detected. Solved by adding it in DevOps
 * Xamarin.Android capability not auto-detected. Solved by adding it in DevOps

**Expected behavior**
Being able to build an Android project

**Actual behavior**
Getting the following issue on a Xamarin.Android Build Task (version 1.151.0):

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(721,2): Error XA5300: The Android SDK Directory could not be found. Please set via /p:AndroidSdkDirectory.
Process 'msbuild.exe' exited with code '1'.
```

**Image impacted**
Windows VS2019

We tried to add, into the Xamarin.Android Task the following additional build argument `/p:AndroidSdkDirectory="C:\Program Files (x86)\Android\android-sdk"` but still getting the same issue (we also tried with a more dynamic, but equivalent way, and get the same results: `/p:AndroidSdkDirectory=$(ANDROID_HOME)`)

Something we do not explain (and not sure we can rely on) is, in the execution logs, we got the following logs:

```
##[debug]Entering Invoke-VstsTool.
##[debug] FileName: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe'
##[debug] Arguments: '"D:\agent10\_work\2\s\Test.Mobile.Droid\Test.Mobile.Droid.csproj" /nologo /nr:false /t:"Clean" /dl:CentralLogger,"D:\agent10\_work\_tasks\XamarinAndroid_27edd013-36fd-43aa-96a3-7d73e1e35285\1.151.0\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll";"RootDetailId=54c627b6-6df6-4e2a-a0ec-a45e5fab545b|SolutionDir=D:\agent10\_work\2\s\Test.Mobile.Droid"*ForwardingLogger,"D:\agent10\_work\_tasks\XamarinAndroid_27edd013-36fd-43aa-96a3-7d73e1e35285\1.151.0\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll" /p:AndroidSdkDirectory="C:\Program Files (x86)\Android\***-sdk" /p:configuration="Debug" /p:_MSDeployUserAgent="VSTS_d21a8d71-c8f0-40a3-8764-738ea6a9bda3_build_120_0" /t:PackageForAndroid /p:OutputPath="D:\agent10\_work\2\b/Debug"'
##[debug] RequireExitCodeZero: 'True'
##[command]"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe" "D:\agent10\_work\2\s\Test.Mobile.Droid\Test.Mobile.Droid.csproj" /nologo /nr:false /t:"Clean" /dl:CentralLogger,"D:\agent10\_work\_tasks\XamarinAndroid_27edd013-36fd-43aa-96a3-7d73e1e35285\1.151.0\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll";"RootDetailId=54c627b6-6df6-4e2a-a0ec-a45e5fab545b|SolutionDir=D:\agent10\_work\2\s\Test.Mobile.Droid"*ForwardingLogger,"D:\agent10\_work\_tasks\XamarinAndroid_27edd013-36fd-43aa-96a3-7d73e1e35285\1.151.0\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll" /p:AndroidSdkDirectory="C:\Program Files (x86)\Android\***-sdk" /p:configuration="Debug" /p:_MSDeployUserAgent="VSTS_d21a8d71-c8f0-40a3-8764-738ea6a9bda3_build_120_0" /t:PackageForAndroid /p:OutputPath="D:\agent10\_work\2\b/Debug"
```

Take care of the command log. We don't understand why part of the argument is replaced with stars (*) into the `/p:AndroidSdkDirectory`.

We also tried to add an AndroidSdkDirectory environment variable through the Pipeline Variables but still hitting the same issue.

Diving into the execution path, it seems that [Xamarin.Android.Build.Tasks.ResolveSdks](https://github.com/xamarin/xamarin-android/blob/e624434344ed54f39ed174d4c3a46a6cb06a7302/src/Xamarin.Android.Build.Tasks/Tasks/ResolveSdksTask.cs#L59) doesn't succeed. But we have no clue if `RefreshAndroidSdk` is throwing an exception, or simply doesn't return any path for any other reason.

Of course, all of this is working as expected with hosted images using exactly the same pipeline (without specific variable, neither additional argument).

Does anyone else succeed to run a Xamarin.Android Build from a generated agent?

Thanks for your help,

**Comment by developer9969** [comment]
Hi 
Is there any workaround about this android error? It's failing .Do we have to revert to vs2017 image?
Thanks

**Comment by kaylangan** [comment]
@developer9969 does this help: https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2019-Server2019-Readme.md#known-issues ?

**Comment by developer9969** [comment]
Hi there thanks for replying.I did follow that link in the first place and did not work for me. May be I am doing something wrong. 

I am using the designer using vs 2019 image  and in my Xamarin Android task I have done as pic below but my build keeps failing. I am not sure about the  Additional arguments section. Is "JAVA_HOME_8_X64 a predifined variable. What should I put there? in vs2017 it just worked not defining anything.

![image](https://user-images.githubusercontent.com/16970109/60482337-f1ef7c00-9c88-11e9-9f81-016a577c1124.png)

 Is there a fix coming soon?

Thanks for your help

**Comment by madhurig** [comment]
@developer9969 -You don't need to pass both MSBuild arguments (which seems to be missing the closing ") and the JDK options. Can you try just setting the JDK option and clearing out the Additional msbuild arguments.

 The fix will be coming with the next update of the VM when we put a new version of VS2019 but we recommend specifying the Java version explicitly to avoid issues with default Java version changing. 

If you are seeing issues with the workaround, please post the error details.

**Comment by developer9969** [comment]
@madhurig thanks for your reply. Honestly I got so desperate because so many pipelines just broke that  I tried everything.

 **I get errors with the Visual build solution task:**
![image](https://user-images.githubusercontent.com/16970109/60563174-a0abbf00-9d52-11e9-8033-e7de11fd9475.png)

**Agent pool set as follows**
![image](https://user-images.githubusercontent.com/16970109/60563072-1bc0a580-9d52-11e9-90cc-fb982f2c8950.png)

**Build solution task that errors:** (do I need to put build arguments here for JDK)
![image](https://user-images.githubusercontent.com/16970109/60563543-29772a80-9d54-11e9-90eb-c88a17211c73.png)


Xamarin Android task set as follows (**but did not get this far as my build solution is executed first**):
![image](https://user-images.githubusercontent.com/16970109/60563100-4579cc80-9d52-11e9-9137-313e9a9a3859.png)


Is there anything I need to do with the Build solution task? I was concentrating on the xamarin android task but I never get that far.
Thanks for any suggestions

**Comment by madhurig** [comment]
In VSBuild, pass /p:JavaSdkDirectory=$(JAVA_HOME_8_X64) for `MSBuild Arguments`

**Comment by developer9969** [comment]
@madhurig  thanks for your reply now I am getting  

MSBUILD : error MSB1008: Only one project can be specified.
g]Invoke-VstsTool : Process 'msbuild.exe' exited with code '1'.

I have added as follows in the Visual studio build task
![image](https://user-images.githubusercontent.com/16970109/61205342-b40e4100-a6e7-11e9-80f0-db0a1670b34c.png)

Am i missing the obvious?  many thanks for  your prompt response

**Comment by madhurig** [comment]
@developer9969 - that is due to a space in the JAVA 8 path, you can pass `/p:JavaSdkDirectory="$(JAVA_HOME_8_X64)"` to handle the space.

**Comment by developer9969** [comment]
@madhurig. THANKS!!! works now. thanks for your time.I can relax a bit now. I had so many pipelines broken and people were moaning at me.

**Comment by madhurig** [comment]
[Xamarin Android team has made a fix](https://developercommunity.visualstudio.com/content/problem/606218/error-xa5300-the-java-sdk-directory-could-not-be-f.html?childToView=640176) that will not required the JavaSdkDirectory path to be set in a new version of VS. 

Till then this workaround will help unblock the builds.

**Comment by sescandell** [comment]
Hi,

Sorry but even with the argument it is still not working (we already tried this before opening the issue).

We tried with a fresh new compiled machine but still getting the same issue. We tried several things, several configurations, Xamarin.Android Task and Visual Studio Tasks but nothing works.

Discussions with support are in progress...

**Comment by dotMorten** [comment]
I'm seeing the same thing. The workaround doesn't work for me either: https://github.com/dotMorten/NmeaParser/blob/6b8781e27f6b7d11617da4565c3f520bb6d3f24a/azure-pipelines.yml#L30
Also seeing the exact same issue when using Github Actions.

**Comment by kaylangan** [comment]
@madhurig sounds like the workaround may not longer work. Can you take a look?

**Comment by dotMorten** [comment]
If you want to test, feel free to make a PR against that repo for testing it (it'll kick of on any PR against master)

**Comment by madhurig** [comment]
@jonpryor - the workaround is helping some customers but not everyone. Is there something else we can try or do we have to update to VS 2019 16.3 build?

**Comment by helzgate** [comment]
For those that came here by way of Google, and for those running TFS 2018 SP3, I also had to change the Java version from 8, to default, then it worked.

**Comment by EmilAlipiev** [comment]
it is still happening java 8 or java default bot failing for me. I have no chance in my pipeliness yaml and i didnt do a release a month or more and today wanted to make release build and failing with this message.
