### ISSUE TITLE
Addition of Rust to images is broken in a few ways

### ISSUE THREAD

**Issue by johnterickson** [microsoft/azure-pipelines-image-generation#1012]
See @alexcrichton's super detailed comments in  #900 !

Summarized here:
- rustup/cargo/rust are installed to non-default locations
  - Causes permissions issues
  - is unnecessarily (as far as I can tell) confusing
- rustup/cargo/rust are missing from OSX and VS2015 images.  OSX is especially painful.
- Should we have this installed by default or have a good task instead?

**Comment by asottile** [comment]
I believe https://github.com/microsoft/azure-pipelines-image-generation/issues/988 is related :+1:

**Comment by johnterickson** [comment]
I've put together some sample YAML in the interim here:
https://github.com/microsoft/azure-pipelines-image-generation/issues/1024#issuecomment-504104621

**Comment by johnterickson** [comment]
Hi @alexcrichton - 

Because of how our VMs get staged, installing tools directly to $HOME doesn't work well.  Here's what we're thinking on how to proceed. Would love your thoughts!

John

Windows:
- Set a default Rust folder to C:\Rust
  - C:\Program Files\Rust -> C:\Rust
- Grants Everyone Full Access permissions to C:\Rust
  - icacls C:\Rust /t /grant “Everyone:(OI)(CI)F”            
- Explicitly set %RUSTUP_HOME% & %CARGO_HOME% to their default locations
- Update warmup scripts(MMS.Provisioner) to pre-create symlinks
  - mklink /D C:\Rust\.rustup %USERPOFILE%\.rustup
  - mklink /D C:\Rust\.cargo %USERPOFILE%\.cargo

Ubuntu/OSX:
- Grants Everyone Full Access permissions to /usr/local/rustup & /usr/local/cargo
  - chmod -R 0777 $RUSTUP_HOME
  - chmod -R 0777 $CARGO_HOME
- Explicitly set $RUSTUP_HOME & $CARGO_HOME to their default locations
- Update warmup scripts(MMS.Provisioner) to pre-create symlinks
  - ln -s /usr/local/rustup $HOME\.rustup 
  - ln -s /usr/local/cargo $HOME\.cargo

**Comment by alexcrichton** [comment]
That all sounds reasonable to me! That satisfies the most important part of being installed on all platforms and allowing addition of new components and toolchains. To boot it even makes common paths continue to work!

I saw y'all already at some point updated the images with rust 1.35 updated from 1.34, so regular updates will also help ensure everyone's got the latest stable too!

**Comment by johnterickson** [comment]
Partially addressed by https://github.com/microsoft/azure-pipelines-image-generation/pull/1056

**Comment by alexcrichton** [comment]
As a small update on this, https://github.com/microsoft/azure-pipelines-image-generation/issues/1224  also covers the permission issue on Windows, and otherwise the lack of macOS installation is the only remaining issue.

For the last unresolved question in the top post:

> Should we have this installed by default or have a good task instead?

I've come around to having `rustup` and the stable toolchain installed on the image by default, it makes builds extra speedy because you don't even have to download a toolchain in most cases!
