### ISSUE TITLE
Vs2015-Server2012 doesn't have build tools for Windows7.1SDK

### ISSUE THREAD

**Issue by adnan-kamili** [microsoft/azure-pipelines-image-generation#1022]
VS2010 64 bit compilation of C++ project fails due to missing Windows7.1SDK.

**Expected behavior**
Windows7.1SDK should be installed on the image.

**Actual behavior**
The compilation fails with the following error:

```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): 
error MSB8020: The build tools for Windows7.1SDK (Platform Toolset = 'Windows7.1SDK') cannot be found. 
To build using the Windows7.1SDK build tools, please install Windows7.1SDK build tools. 
Build FAILED.
```

**Image impacted**
vs2015-win2012r2

**Comment by kaylangan** [comment]
Closing since we are no longer making updates to the VS2015 image.
