### ISSUE TITLE
Add Xcode 11 betas to macOS images

### ISSUE THREAD

**Issue by jpsim** [microsoft/azure-pipelines-image-generation#1028]
**Tool information**
- Tool name: Xcode 11 beta 2 (and onward)
- Add or update? Add, since other Xcode versions should also remain available
- Desired version: Xcode 11 beta 2 (and onward)
- If this is an add request:
  - Brief description of tool: It's Xcode
  - URL for tool's homepage: https://developer.apple.com/xcode/

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [x] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
macOS 10.14 or macOS 10.15

**Workaround**
It may be possible to install Xcode 11 using something like https://github.com/xcpretty/xcode-install during jobs, but it would probably take 30+ minutes to download, extract and install it.

**Are you willing to submit a PR?**
I'd love to work on this! Unfortunately, from what I can tell grepping for "xcode" through this repository, this doesn't seem to be something that's managed by this repository. If it's possible for members of the public to contribute enhancements like this, please let me know.

**Comment by jpsim** [comment]
It'd be great to get some visibility into this process. 27 days have elapsed since the first Xcode 11 beta was made available, but we still haven't heard from the Azure Pipelines team whether or not this is something that they even want or can do, when we can expect availability, how the community can help, or even an acknowledgement that this has been requested.

Looking forward to hearing from someone on this soon. Thanks!

**Comment by alvarhansen** [comment]
@jpsim, they posted in the forums that they are working on it: https://developercommunity.visualstudio.com/content/problem/624594/xcode-11-in-azure-devops-pipeline.html

**Comment by jpsim** [comment]
ok, thanks for sharing that. Now I know that the forums are a better place to discuss this.

**Comment by nrajpurkar** [comment]
Beta is on the image now and being updated as new ones roll out. Closing this issue.

**Comment by jpsim** [comment]
Thanks @nrajpurkar. Any chance you could respond to my initial comment asking how members of the community can contribute to this?

> *Are you willing to submit a PR?*
> I'd love to work on this! Unfortunately, from what I can tell grepping for "xcode" through this repository, this doesn't seem to be something that's managed by this repository. If it's possible for members of the public to contribute enhancements like this, please let me know.

**Comment by nrajpurkar** [comment]
@jpsim the macOS images are currently not something we take community contributions to.
