### ISSUE TITLE
Update/Add JDK 1.7

### ISSUE THREAD

**Issue by praries880** [microsoft/azure-pipelines-image-generation#1029]
**Tool information**
- Tool name: JDK 1.7
- Add or update? Add
- Desired version: 
- If this is an add request:
  - Brief description of tool: JDK 1.7
  - URL for tool's homepage: 

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ X] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
Add the appropriate label for the image or images that should be updated (e.g., macOS 10.13, macOS 10.14, ubuntu, VS2017, VS2019, WINCON).
https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md
https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2019-Server2019-Readme.md

**Workaround**
None

**Are you willing to submit a PR?**
Maybe?

This is currently blocking the onboarding of the [azure-libraries-for-java](https://github.com/Azure/azure-libraries-for-java) repo onto ADO. We need support for java 1.7. Refer this [file](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2019-Server2019-Readme.md) in the [PR](https://github.com/Azure/azure-libraries-for-java/pull/750)

**Comment by praries880** [comment]
@madhurig is this something you can look at? If not, would you happen to know who would?

**Comment by praries880** [comment]
Thanks @kaylangan / @davidstaheli

**Comment by madhurig** [comment]
We will not be adding JDK 1.7 on the hosted VMs since it is out of support. If you need it, please use the [JavaToolInstallerTask](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/java-tool-installer) to download it as part of your pipeline.

**Comment by praries880** [comment]
@madhurig 
Azul java SDK 7 is under long term support :
https://azure.microsoft.com/en-us/blog/microsoft-and-azul-systems-bring-free-java-lts-support-to-azure/

download from https://www.azul.com/downloads/azure-only/zulu/

Can you kindly re-open the issue and add support for the jDK 1.7 version from Azul?
