### ISSUE TITLE
Update VS2017/Svr2016 Hosted agent with Xamarin.Android to version 9.3 to resolve known crash on Samsung S10(+)

### ISSUE THREAD

**Issue by rt-miller** [microsoft/azure-pipelines-image-generation#1046]
**Tool information**
- Tool name: Xamarin.Android 
- Add or update? update
- Desired version: 9.3.0.23+
https://docs.microsoft.com/en-us/xamarin/android/release-notes/9/9.3

**Areas and ecosystems**

- [x ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [x ] Xamarin
- [ ] Other

**Image impacted**
Add the appropriate label for the image or images that should be updated 
VS2017

**Workaround**
NONE

**Are you willing to submit a PR?**
NO

**Comment by PaulARoy** [comment]
This would also help fix https://github.com/xamarin/xamarin-android/issues/1162

I can't deploy any longer since I migrated to netstandard projects…

**Comment by PaulARoy** [comment]
still needing the fix to deploy netstandard projects
