### ISSUE TITLE
Building analysis tabular projects on hosted (Microsoft.AnalysisServices.Deployment.exe)

### ISSUE THREAD

**Issue by cnyborg** [Microsoft/azure-pipelines-image-generation#105]
I'm trying to build .xmla-scripts from .asdatabase-files with:
`"C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\Microsoft.AnalysisServices.Deployment.exe"
`

However it seems to be missing from the image. Is it possible to request that functionality?

**Comment by cnyborg** [comment]
Since I haven't received any feedback regarding this I've been trying to pursue a different approach. However this endeavor isn't exactly going well. I'm including the executable mentioned above and all its dependencies with my build artifacts and executing with Powershell. 

I've attached a picture with all DLL's I've included so far. I'm grasping in the dark here though, because I don't get any feedback from the Powershell. The executable just hangs. Is it possible to get any help with this approach? I'd need to know what DLL-files to include.

![dependencies](https://user-images.githubusercontent.com/1458242/38620270-5b0a1704-3d9e-11e8-97ee-963ef3e5782d.PNG)

**Comment by lokesh755** [comment]
SQL Management studio is not installed on the Agent. We'll try to install it in next release of image. But in meantime if you want to know the complete list of DLL files, you can try installing SQL management studio on your local and check out the dll files.

**Comment by chrisrpatterson** [comment]
I am not excited about adding SSMS to the image as it really does not seem like a build tool.  I have asked the SQL tools team to see if there is another delivery vehicle for this tool.

**Comment by cnyborg** [comment]
Why is this issue closed @bryanmacfarlane ? What is the solution?

**Comment by bryanmacfarlane** [comment]
While we investigate, the solution is to acquire a VM in azure, install the agent on it, and install whatever tools you need on it.  The issue we face with the current images is the disk budget is almost completely used so we have to be careful about installing large user applications (like management studio) to get some build time tools.
