### ISSUE TITLE
Update/Add Azure Storage Emulator

### ISSUE THREAD

**Issue by tli2** [microsoft/azure-pipelines-image-generation#1052]
**Tool information**
- Tool name: Azure Storage Emulator
- Add or update? Add (an apparently unofficial copy of the software at version 5.7.0.0 exists on the `vs2017-win2016` image)
- Desired version: 5.9.0.0
- If this is an add request:
  - Brief description of tool: Provides fake access to Azure storage services 
  - URL for tool's homepage:  https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator

**Areas and ecosystems**
Azure Storage. Testing

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [x] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [x] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
VS2017

**Workaround**
Downloading and installing at the start of the pipeline.

**Are you willing to submit a PR?**
No

**Comment by roycornelissen** [comment]
There is an even newer version of the Emulator out now, 5.10. We actually need it, because we're using Blob Storage client libraries that require newer API versions. Works with 5.10 on our own servers, but not on the hosted agents :(

Any plans for doing this soon?

**Comment by SamWhitby** [comment]
I'm running into this issue now too. This is really inconvenient as I now have to disable all integration tests that require the storage emulator when running on a hosted pipeline.

Specific error is "Microsoft.Azure.Storage.StorageException : The REST version of this request is not supported by this release of the Storage Emulator. Please upgrade the storage emulator to the latest version. Refer to the following URL for more information: http://go.microsoft.com/fwlink/?LinkId=39223"
