### ISSUE TITLE
Wix not available on VS2019

### ISSUE THREAD

**Issue by kaylangan** [microsoft/azure-pipelines-image-generation#1065]
First reported on [Developer Community](https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/1535755).

**Describe the bug**
README says Wix is installed on VS2019 but it's not.

**Expected behavior**
Either Wix is installed or it's not and the README reflects that.

**Actual behavior**
README says Wix is installed on VS2019 but it's not.

**Image impacted**
VS2019

Appears that the validation step is reporting a version for Wix even though it's [not yet installed b/c it's in preview](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/win/scripts/Installers/Vs2019/Install-Wix.ps1#L52).

Related to #826

**Comment by mbreckon** [comment]
The link to the Developer Community post in this issue doesn't navigate to a viewable page but I did find this issue from Developer Community (maybe a permissions thing?). 

Is there any plan for adding the Wix extension to the "Hosted Windows 2019 with VS2019" agents within Azure DevOps?

**Comment by kaylangan** [comment]
> Is there any plan for adding the Wix extension to the "Hosted Windows 2019 with VS2019" agents within Azure DevOps?

See #826

**Comment by mbreckon** [comment]
> Is there any plan for adding the Wix extension to the "Hosted Windows 2019 with VS2019" agents within Azure DevOps?
> 
> See #826

My apologies, I hadn't quite understood the relationship between the items here.

**Comment by kaylangan** [comment]
Closing. Wix was added in #826
