### ISSUE TITLE
Epic Games Launcher ?!

### ISSUE THREAD

**Issue by Allendorf231** [microsoft/azure-pipelines-image-generation#1070]
I generated a image using the guide from this repo, connected on to the machine and found "Epic Games Launcher" to be installed not sure how and for what application this is needed… maybe someone wants to play Fornite on their BuildServer?!

![image](https://user-images.githubusercontent.com/41143773/60824172-6b1b3180-a1a9-11e9-8230-b3932714fd60.png)

**Image impacted**
VS2019

**Comment by nelsonjchen** [comment]
It's probably needed for downloading the Unreal SDK. Imagine my surprise to find a Fortnite button in my "Unreal Engine SDK Launcher" way back.

**Comment by nelsonjchen** [comment]
I guess it serves the same purpose as the *other* commonly used for games engine on that desktop.

**Comment by Allendorf231** [comment]
Right! like its included in a bundle, didnt think of that, that's probably it.

Thank you.

**Comment by nelsonjchen** [comment]
Epic went backwards and added games to their SDK launcher. Valve stuff was the other way.

Anyway, it's neat that these images have those. I came here to report some other issue and it's neat to see this.
