### ISSUE TITLE
Ubuntu 1804 image contains only one version of .Net Core tool

### ISSUE THREAD

**Issue by bishal-pdMSFT** [microsoft/azure-pipelines-image-generation#1073]
**Describe the bug**
Ubuntu 1804 image contains only one version of .Net Core tool.

**Expected behavior**
Multiple available versions should be installed - a is done for ubuntu 1604 image

**Actual behavior**
Only one version of .Net Core SDK/runtime is available for tasks/scripts

**Image impacted**
ubuntu 1804

**Comment by kaylangan** [comment]
Related: https://github.com/microsoft/azure-pipelines-image-generation/issues/506#issuecomment-509425015
