### ISSUE TITLE
nvm not installed

### ISSUE THREAD

**Issue by josersleal** [microsoft/azure-pipelines-image-generation#1077]
**Describe the bug**
nvm is not installed
**Expected behavior**
commands such as 'nvm use [version number] work
**Actual behavior**

error is generated:
##[section]Starting: nvm use 12.4.0
==============================================================================
Task         : Shell++
Description  : Execute bash script
Version      : 0.3.1
Author       : ms-devlabs
Help         : [More Information](https://github.com/openalm/Extension-UtilitiesPack)
==============================================================================
[command]/bin/bash /Users/vsts/agent/2.153.2/work/155/s/user_script.sh
/Users/vsts/agent/2.153.2/work/155/s/user_script.sh: line 1: nvm: command not found
/bin/bash failed with return code: 127
return code: 1
##[section]Finishing: nvm use 12.4.0

1. Step 1
using an hosted macOS image

2. Step 2

add a bash task with 'nvm use 12.4.0'

queue

**Image impacted**
Add a label for each image that has the bug (e.g., ubuntu, mac, window)

Hosted macOS

**Comment by ericdrobinson** [comment]
This is still a problem.

Recommend either fixing `nvm` to actually work in hosted macOS agents or simply removing it from the [Installed Software](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md#installed-software) list. That may seem extreme but it winds up simply costing us time trying to figure out why the Pipeline fails.

**Comment by nrajpurkar** [comment]
@josersleal are you still seeing this issue?

**Comment by bkapitein4ps** [comment]
Still seeing this issue on macOS-10.14 hosted agent.

**Comment by maxim-lobanov** [comment]
Hi @bkapitein4ps ,
To use NVM, you should add line `. ${NVM_DIR}/nvm.sh` at the begin of your script. This command will initialize NVM and after that it will be available.

The reason, why you need to initialize it by yourself, is how `Shell` and `Command Line` tasks invoke `bash`. Currently, they invoke bash like `/bin/bash ~/user_script.sh` but it should be invoked via `login` option `/bin/bash --login ~/user_script.sh` to enable NVM and initialize it.

Actually, VM image contains NVM initialization logic into `~/.bashrc` / `~/.bash_profile` but it doesn't invoked due to the issue above.

**Comment by ericdrobinson** [comment]
> Currently, they invoke bash like `/bin/bash ~/user_script.sh` but it should be invoked via `login` option `/bin/bash --login ~/user_script.sh` to enable NVM and initialize it.

Wow, excellent find! Hopefully someone on the team sees this and fixes the setup soon.

Without it, the feature appears to be simply _missing_ unless you somehow understand the above...

**Comment by bkapitein4ps** [comment]
Adding ` . ${NVM_DIR}/nvm.sh` does run nvm. Tnx! Unfortunately `nvm use node` or any other `nvm use` command runs into another problem:

```
nvm is not compatible with the npm config "prefix" option: currently set to "/usr/local"
Run `npm config delete prefix` or `nvm use --delete-prefix v6.17.1 --silent` to unset it.
nvm is not compatible with the npm config "prefix" option: currently set to "/usr/local"
Run `npm config delete prefix` or `nvm use --delete-prefix v10.16.3` to unset it.

##[error]Bash exited with code '11'.
```

To fix this I added `npm config set prefix $NVM_DIR/versions/node/v6.17.1` (don't know if I should use this version or the 10.16.3 version) to the bash script.
Now I can use `nvm use ...` but the NPM task and the IonicCommand task are still using 6.17.1.

**Comment by ericdrobinson** [comment]
While there are manual workarounds, the pipelines team should definitely make this work out-of-the-box. If not, then proper usage should be documented somewhere.

@nilofer can you have someone look into correcting this? Presumably it should be a pretty quick fix.

**Comment by nilofer** [comment]
@vijayma can you provide some more information here please?

**Comment by vtbassmatt** [comment]
nvm works against the way Azure Pipelines manages multiple versions of installed software. We have the `UseNodeVersion` task which does what nvm wants to do, but does it in a way that doesn't require re-loading it in each shell session.

I'll update the docs to point out the preferred mechanism and provide this workaround for people who're stuck with nvm.

**Comment by vtbassmatt** [comment]
... all that said, I'm not sure why we ship nvm on the macOS image. @nilofer can we just get it removed and tell people to use the NodeTool task?

**Comment by ericdrobinson** [comment]
>I'll update the docs to point out the preferred mechanism and provide this workaround for people who're stuck with nvm.

@vtbassmatt Were the docs updated as you described? If so, can you link to the new docs? That will help facilitate the determination as to whether a similar issue should be opened in the new repository or not.

**Comment by vtbassmatt** [comment]
@ericdrobinson yes, see https://docs.microsoft.com/azure/devops/pipelines/ecosystems/javascript#troubleshooting
