### ISSUE TITLE
python sqlite missing JSON1 and FTS5 extensions

### ISSUE THREAD

**Issue by JakaKokosar** [microsoft/azure-pipelines-image-generation#1083]
**Describe the bug**
Running tests on Windows and Ubuntu fail because sqlite3 extension are not enabled. This is not the case on macOS image.

Windows:
```
>           match = cursor.execute(self._query_exact(input_identifier)).fetchall()
E           sqlite3.OperationalError: no such function: json_extract
```

Ubuntu:
```
>           match = cursor.execute(self._query_exact(input_identifier)).fetchall()
E           sqlite3.OperationalError: no such module: FTS5
```

[More details on failing build.](https://dev.azure.com/orange-biolab/orange3-bioinformatics/_build/results?buildId=125)

**Image impacted**
ubuntu, window

**Comment by brcrista** [comment]
From https://docs.python.org/3.7/library/sqlite3.html#f1:

> The sqlite3 module is not built with loadable extension support by default, because some platforms (notably Mac OS X) have SQLite libraries which are compiled without this feature. To get loadable extension support, you must pass --enable-loadable-sqlite-extensions to configure.

So it sounds like we need to do that for Ubuntu, though it's surprising that Windows doesn't have it.

**Comment by JakaKokosar** [comment]
Any updates on this?
