### ISSUE TITLE
Update Xamarin.Android on macOS Hosted Agent

### ISSUE THREAD

**Issue by cosminstirbu** [microsoft/azure-pipelines-image-generation#1084]
**Tool information**
- Tool name: Xamarin.Android
- Update
- Desired version: [Xamarin.Android 9.3.0.23](https://docs.microsoft.com/en-us/xamarin/android/release-notes/9/9.3#june-20-2019--xamarinandroid-93023)

**Areas and ecosystems**

- [x] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [x] Xamarin
- [ ] Other

**Comment by wcoder** [comment]
The current Xamarin.Android v9.2.3.0 contains major bug https://github.com/xamarin/xamarin-android/issues/2521

Need update asap! https://github.com/xamarin/xamarin-android/issues/2521#issuecomment-501879477

**Comment by nrajpurkar** [comment]
@wcoder @cosminstirbu thanks for creating this, we're working on updates to latest stable Xamarin.Android at the moment. Thanks for your patience!

**Comment by cosminstirbu** [comment]
Hi @nrajpurkar,

Any news on this item?

Thank you,
Cosmin

**Comment by nrajpurkar** [comment]
Hi @cosminstirbu, latest deployment of the [High Sierra image](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.13-Readme.md#xamarinandroid-sdk) has this version of Xamarin.Android. Closing out the issue.

**Comment by cosminstirbu** [comment]
Hi @nrajpurkar - has the image actually been deployed?

We've ran a build minutes ago and it still didn't have this version installed.

Thank you,
Cosmin

**Comment by wcoder** [comment]
Hi @nrajpurkar, as I can see the current macOS image still have v9.2.3

(Pipeline > Agent pool > Pool information)
![Screen Shot 2019-07-23 at 22 41 28](https://user-images.githubusercontent.com/766193/61742404-b59cd080-ad9b-11e9-89d9-f7491877b5eb.png)

**Comment by deyupopp** [comment]
@nrajpurkar  Any news on this? The latest version is still 9.2.3

**Comment by nrajpurkar** [comment]
Apologies, looks like we were out of sync on docs and deploys. Xamarin.Android should be up to 9.3 now, working on 9.4 next.
