### ISSUE TITLE
`sudo` `secure_path` overrides PATH modified by Use {tool} Version tasks

### ISSUE THREAD

**Issue by smurawski** [microsoft/azure-pipelines-image-generation#1092]
**Describe the bug**

On a hosted linux agent:

When using a tool version selector task, like "Use Ruby Version" with `addToPath`, the `ruby` command is symlinked to `/usr/bin/ruby` and `/opt/hostedtoolcache/Ruby/2.5.5/x64/bin` is added to the path.

This makes the resulting path `/opt/hostedtoolcache/Ruby/2.5.5/x64/bin:/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin`

When one would `sudo` as part of the task, the path is overwritten by the `secure_path` default in `/etc/sudoers` or configuration files under `/etc/sudoers.d`.

This resets the path to `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin`

While the `ruby` command is still available while using `sudo`, `gem`, `bundle`, `rake` and other commands that are installed to  `/opt/hostedtoolcache/Ruby/2.5.5/x64/bin` are unavailable which greatly limits the usability of the selected tool.

**Expected behavior**

I expect that the tool version I selected will behave similarly when using `sudo` or not.  I expect the libraries and tools that are installed to that toolchain's path will be available when using `sudo`.

**Actual behavior**

While `ruby` is available, none of the libraries or tools installed to the bin directory of the selected runtime are available.

```
pool:
  vmImage: 'ubuntu-16.04'
steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: 2.5.5
      addToPath: true
  - script: |
      echo "ruby version:"
      ruby --version
      echo "gem version:"
      gem --version
    displayName: Show Ruby Version
  - script: |
      echo "ruby version:"
      sudo -E ruby --version
      echo "gem version:"
      sudo -E gem --version
    displayName: Sudo Show Ruby Version
```

**Image impacted**

ubuntu

**Comment by smurawski** [comment]
A possible resolution would be to add the `vsts` user's group to an exempted group in the `/etc/sudoers` configuration

```
Default exempt_group=group_of_the_vsts_user_here
```

**Comment by smurawski** [comment]
Possibly related to https://github.com/microsoft/azure-pipelines-image-generation/issues/185

**Comment by vtbassmatt** [comment]
(Note, this isn't specific to Ruby. Python and other toolscache tools experience the same thing.)

**Comment by smurawski** [comment]
This is still an open issue.
