### ISSUE TITLE
Update/Add CMake (or as apt package)

### ISSUE THREAD

**Issue by KirmesBude** [microsoft/azure-pipelines-image-generation#1097]
**Tool information**
- Tool name: CMake
- Add or update? Update
- Desired version: 3.13+

**Areas and ecosystems**

- [ ] Android
- [X] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
ubuntu 16.04, ubuntu 18.04

**Workaround**
We currently remove the manual installation of cmake in /usr/local/ and add the official cmake repository to get cmake 3.15 

**Implementation**
How do you want CMake to be handled now that there is a apt repository https://apt.kitware.com/? 
This would keep CMake updated. Alternatively I could just update the cmake script, that way you have more control over which version will actually be present. 
Let me know what you think. 

**Are you willing to submit a PR?**
Sure

**Comment by nevyn** [comment]
I second that request. 3.12 is over a year old, and `target_link_options` introduced in 3.13 is very useful. Thanks for considering.

**Comment by freesurfer-rge** [comment]
I believe this is the source of a problem I'm having with CMake and Boost on `ubuntu-latest`. While it finds the Boost headers without issue, if I try adding one of the component libraries which must be compiled beforehand - for example `program_options` - then CMake fails to find that component.

Setting `BOOST_Debug ON` in my `CMakeLists.txt`, I can see that Boost is looking for:
```
boost_program_options-gcc54-mt-1_69
boost_program_options-gcc54-mt
boost_program_options-mt-1_69
boost_program_options-mt
boost_program_options
```
However, if I list `$BOOST_ROOT/lib` I find:
```
libboost_program_options-mt-d-x64.a
libboost_program_options-mt-d-x64.so
libboost_program_options-mt-d-x64.so.1.69.0
libboost_program_options-mt-sd-x64.a
libboost_program_options-mt-s-x64.a
libboost_program_options-mt-x64.a
libboost_program_options-mt-x64.so
libboost_program_options-mt-x64.so.1.69.0
```
The architecture suffix appears to be giving the issue. Indeed, in the CMake 3.15.5 documentation, there is [a setting to specify the architecture suffix](https://gitlab.kitware.com/cmake/cmake/blob/v3.15.5/Modules/FindBoost.cmake#L158). This is missing in the [equivalent location of the CMake 3.12.4 documentation](https://gitlab.kitware.com/cmake/cmake/blob/v3.12.4/Modules/FindBoost.cmake#L144).
