### ISSUE TITLE
Add scoop package manager support for windows os

### ISSUE THREAD

**Issue by huiyifyj** [microsoft/azure-pipelines-image-generation#1110]
**Tool information**
- Tool name: Scoop
- Add or update? Add
- Desired version: No specified version, only master for git.
- If this is an add request:
  - Brief description of tool: Scoop is a command-line installer for windows.
  - URL for tool's homepage: https://github.com/lukesampson/scoop and https://scoop.sh

**Areas and ecosystems**
- [x] General purpose tools
- [x] Other

**Image impacted**
Add the appropriate label for the image or images that should be updated (e.g., macOS 10.13, macOS 10.14, ubuntu, VS2017, VS2019, WINCON).
`VS2017`, `VS2019`, `WINCON`

**Comment by huiyifyj** [comment]
**NOTE**: scoop only support `PowerShell Desktop 3.0+` and `PowerShell Core`.

**Comment by huiyifyj** [comment]
Hope to add `Scoop` as soon as possible.

**Comment by phil-opp** [comment]
I'm still interested in this issue.

**Comment by Pengxn** [comment]
Hope to support as soon as possible.
