### ISSUE TITLE
Add LocalDB 2017 on VS2019 image

### ISSUE THREAD

**Issue by guillaume86** [microsoft/azure-pipelines-image-generation#1116]
**Tool information**
- Tool name: LocalDB 2017
- Add or update? Add next to the LocalDB 2016 installed with Visual Studio
- Desired version: 14.0.3162.1
- If this is an add request:
  - Brief description of tool: SQL Server 2017 LocalDB
  - URL for tool's homepage: https://www.microsoft.com/en-us/sql-server/sql-server-downloads

**Areas and ecosystems**

- [x] Database servers or clients

**Image impacted**
VS2019 (optionnally VS2017).

**Workaround**
There's a chocolatey package which installs the SqlLocalDB.msi (v14.0.1000.169) provided in the SQL Server installation media (https://chocolatey.org/packages/sqllocaldb).
Unfortunately, that version is plagued with a bug that breaks a simple ´CREATE DATABASE [DbName]´ command because of a missing backslash somewhere, see [here](https://dba.stackexchange.com/questions/191393/localdb-v14-creates-wrong-path-for-mdf-files) or the error in the agent:

```
"Creating DBTests...\r\nMsg 5123, Level 16, State 1, Server fv-az664\\LOCALDB#1B04F10A, Line 1\r\nCREATE FILE encountered operating system error 5(Access is denied.) while attempting to open or create the physical file 'C:\\Users\\VssAdministratorDBTests.mdf'.\r\nMsg 1802, Level 16, State 4, Server fv-az664\\LOCALDB#1B04F10A, Line 1\r\nCREATE DATABASE failed. Some file names listed could not be created. Check related errors."
```

The easiest solution would be to have an updated SQLLocalDB.msi which includes the latest SQL Server cumulative update but I can't find one, maybe you guys can get in touch with the SQL Server team to provide it.

In my experience it is not possible to apply the cumulative update on a standalone LocalDB installation (the cumulative update requires a full instance of SQL 2017 running to proceed).

**Are you willing to submit a PR?**
I would gladly but I don't think it's possible with the current state of the SQLLocalDB/SQL Server cumulative update installer.

**Comment by oising** [comment]
I was able to apply the SQL CU fixing the "create database" path bug to my localdb, without needing to install full or express server.

**Comment by tymtam2** [comment]
> 
> 
> I was able to apply the SQL CU fixing the "create database" path bug to my localdb, without needing to install full or express server.

@oising Could you describe how? Thanks!

**Comment by tymtam2** [comment]
@guillaume86 Could you share how to install SqlLocalDB.msi?

**Comment by guillaume86** [comment]
> @guillaume86 Could you share how to install SqlLocalDB.msi?

I use chocolatey:

```
- task: CmdLine@2
            displayName: 'Install LocalDB 2017'
            inputs:
              script: 'choco install sqllocaldb -y'
              failOnStderr: true
```

**Comment by CodesharpJonas** [comment]
> I was able to apply the SQL CU fixing the "create database" path bug to my localdb, without needing to install full or express server.

If you could tell me how you did that I would be very grateful. I have the same scenario as @guillaume86 have.

I've spent a week for a client building tests based on sqllocaldb and now I can't get them to run on the build machine because of the mentioned bug.

**Comment by MatthewSteeples** [comment]
I don't know whether it will help at all, but SQL 2019 (with it's own LocalDB) has been released, so if you can install that as an MSI (or get it updated via Chocolatey) then that might be a solution

**Comment by oising** [comment]
Sorry everyone, the notifications for this thread were buried very deep under a ton of others that I am following. It seems people are having issues updating the localdb with the CU patch? What exactly is the problem? I don't recall having any major issues -- oh wait, does the CU check for full sql or sqlexpress? In that case what I likely did is fish out the MSI for localdb by running the setup bootstrapper but just leaving it open without proceeding; then navigating to the temporary folder where the setup file was extracted and finding the MSI for updating localdb only.

**Comment by MatthewSteeples** [comment]
I can't speak for everyone else, but this may actually be resolved. Out of the box, we're able to successfully do the following on the 2019 image

> [section]Starting: Create and Start LocalDB
> 
> Task         : Command Line
> Description  : Run a command line with arguments
> Version      : 1.1.3
> Author       : Microsoft Corporation
> Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
> 
> [command]"C:\Program Files\Microsoft SQL Server\130\Tools\Binn\SqlLocalDB.exe" create MSSQLLocalDB -s
> LocalDB instance "MSSQLLocalDB" created with version 13.1.4001.0.
>  
> LocalDB instance "MSSQLLocalDB" started.
>  
> [section]Finishing: Create and Start LocalDB
