### ISSUE TITLE
Update Visual Studio 2019 to 16.2

### ISSUE THREAD

**Issue by derjabkin** [microsoft/azure-pipelines-image-generation#1122]
Dear Azure Team,

please update the windows-2019 to Visual Studio 16.2.

Thanks,
Sergej Derjabkin.

**Comment by alepauly** [comment]
Closing this as the new image with VS2019 16.2 is rolling out now.
@derjabkin If it hasn't reached your org by end of next week(8/16), please let us know! Thank you.
