### ISSUE TITLE
Unable to build Win Server2016 VS2017 image

### ISSUE THREAD

**Issue by KasireddyAlekhya** [microsoft/azure-pipelines-image-generation#1125]
**Describe the bug**
After severals tries, I never succeeded to create a VS2017 image.
![image](https://user-images.githubusercontent.com/44359532/62110303-c2ee1980-b2cb-11e9-93a5-0e4b91bbf77e.png)
    vhd:
    vhd: SUCCESS: Specified value was saved.
==> vhd: Restarting Machine
==> vhd: Waiting for machine to restart...
    vhd: pkrvmvewyym4vdi restarted.
    vhd: #< CLIXML
    vhd: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> vhd: Machine successfully restarted, moving on
==> vhd: Provisioning with Powershell...
==> vhd: Provisioning with powershell script: C:\Users\v-alkas\Documents\GitHub\azure-pipelines-image-generation\images\win/scripts/Installers/Validate-AzureModules.ps1
    vhd: The Azure Modules finally present are:
    vhd: One or more required Azure modules are not present.
    vhd:
    vhd: Name  Version Path
    vhd: ----  ------- ----
    vhd: Azure 2.1.0   C:\Program Files\WindowsPowerShell\Modules\Azure\2.1.0\Azure.psd1
    vhd:
    vhd:
    vhd:
    vhd: One or more required Azure modules are not present
    vhd: At C:\Windows\Temp\script-5d3aa812-b3bd-e7b3-b1c0-604c97e4b087.ps1:24 char:5
    vhd: +     throw "One or more required Azure modules are not present."
    vhd: +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    vhd:     + CategoryInfo          : OperationStopped: (One or more req...re not present.:String) [], RuntimeException
    vhd:     + FullyQualifiedErrorId : One or more required Azure modules are not present.
    vhd:
==> vhd: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
==> vhd: Step "StepProvision" failed
==> vhd: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)? ==> vhd:
==> vhd: Cleanup requested, deleting resource group ...
==> vhd: Resource group has been deleted.
Build 'vhd' errored: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]

==> Some builds didn't complete successfully and had errors:
--> vhd: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.
**Expected behavior**
Successful generation of VS2017 image.

**Actual behavior**
A description with steps to reproduce the issue.
Failed the below location
 C:\Users\v-alkas\Documents\GitHub\azure-pipelines-image-generation\images\win/scripts/Installers/Validate-AzureModules.ps1

Note : Random failures : one time failed in Validate-Mercurial.ps1,Validate-Mercurial.ps1 and Docker.ps1 like that it is failed in different locations.

**Image impacted**
Windows 2016 - VS2017

**Comment by 20shivangi** [comment]
@kaylangan

As discussed with @KasireddyAlekhya , failure is not occurring in Validate-AzurePowerShellModules.ps1,
Instead it is occurring in  Validate-Mercurial.ps1 and Update-DockerImages.ps1 . Kindly assign this issue to their respective owners.
