### ISSUE TITLE
Update Server 2019 image to Windows version 1903

### ISSUE THREAD

**Issue by wilhen01** [microsoft/azure-pipelines-image-generation#1127]
Could you provide an ETA for the Server 2019 image on Azure DevOps Pipelines being updated to OS Build 1903? 

On a related note, OS Build Information in Release Notes would be really handy. It's impossible to tell at a glance what version of the OS is being used in the Windows images, other than `WindowsContainer1803`

**Comment by wilhen01** [comment]
Any chance of an update on this?

**Comment by wilhen01** [comment]
Still waiting for any response to this...

**Comment by ssa3512** [comment]
Windows 1909 is out now and we don’t have any way to build containers with semi-annual channel images on a ms hosted agent. Server 1803 is now out of support (as of November)

**Comment by wilhen01** [comment]
@ssa3512 1909 will be fine for our purposes.

Any thoughts on the documentation issue? It would be really useful to have visibility of the OS build used on the images (and timelines for that build changing)
