### ISSUE TITLE
Update Xamarin.iOS Version for on macOS

### ISSUE THREAD

**Issue by fuzzybinary** [microsoft/azure-pipelines-image-generation#1128]
**Tool information**
- Tool name: Xamarin.iOS
- Add or update? Add / Update
- Desired version: 12.14.0.110

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [x] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [x] Xamarin
- [ ] Other

**Image impacted**
macOS 10.14

**Workaround**

**Are you willing to submit a PR?**
Yes, if given direction.

**Comment by max-lobanov** [comment]
The VM image with Xamarin.iOS 12.14 was deployed recently.
I have closed the issue.
