### ISSUE TITLE
.NET Core: Update .NET Core SDK to 2.2.401 SDK (Windows)

### ISSUE THREAD

**Issue by thorhj** [microsoft/azure-pipelines-image-generation#1146]
**Tool information**
- Tool name: **.NET Core SDK**
- Update
- Desired version: **2.2.401 (latest)**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [X] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
Hosted Windows 2019 with VS2019

**Workaround**
Using the `UseDotNet@2` task ([link](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops)) to install the required SDK version.

**Are you willing to submit a PR?**
Yes

**Description**
The latest version of the .NET Core SDK on _Hosted Windows 2019 with VS2019_ is **2.2.105**. Looking at the [SDK download page](https://dotnet.microsoft.com/download/dotnet-core/2.2), this version does not support VS2019, but instead VS2017.

When building a C# project on this build agent with the `VSBuild@1` task, the build supports C# 7.3 features as expected, but when building the project using dotnet commands such as `dotnet publish`, the project will fail if using any C# 7.3 features. I believe the same is true for C# 7.1 and 7.2 features since VS2017 uses C# 7.0 per default, but I have not verified this.

I can reproduce the same behavior locally; using version 2.2.105 throws errors when using C# 7.3 features whereas the newer versions build successfully.

**Comment by thorhj** [comment]
In [Install-DotnetSDK.ps1](https://github.com/microsoft/azure-pipelines-image-generation/blob/414c999099215eb52c6b16cf8dbcec8ed8c74c30/images/win/scripts/Installers/Install-DotnetSDK.ps1) the dotnet releases are grabbed from this URL:

[https://raw.githubusercontent.com/dotnet/core/master/release-notes/releases.json](https://raw.githubusercontent.com/dotnet/core/master/release-notes/releases).

This document does **not** contain the latest versions of the 2.2 SDK. Rather, the latest versions of 2.2 can be found here:

[https://raw.githubusercontents.com/dotnet/core/blob/master/release-notes/2.2/releases.json](https://raw.githubusercontents.com/dotnet/core/blob/master/release-notes/2.2/releases.json)

**Comment by shibayan** [comment]
Hi, How is the progress?

If the new .NET Core SDK is not pre-installed, the NuGet package cache will not work as expected, causing problems with longer build times.

**Comment by hiyadav** [comment]
@thorhj Thanks for reporting the issue. We are looking into it.

Meanwhile, you can use UseDotNet (2.*) task to download the required version of .Net Core SDK and then continue with your build process. That should unblock your pipelines which are using dotnet tasks.

**Comment by shibayan** [comment]
@hiyadav Using `UseDotNet@2` increases the build time by over a minute because the initial installation process is executed.

If it is installed correctly on the VM, the build should take a few seconds. This is a very significant issue when using Build Validation.

**Comment by thorhj** [comment]
@shibayan In my case using `UseDotNet@2` takes about 15 seconds.

**Comment by shibayan** [comment]
@thorhj As you say, `UseDotNet@2` takes about 15 seconds. However, at the timing when `dotnet restore / build` is executed after that, the package cache is expanded and it takes more than 1 minute.

If `DOTNET_SKIP_FIRST_TIME_EXPERIENCE` is added, cache expansion will not be performed, but it will take time to restore the package because the cache is not available.

**Comment by hiyadav** [comment]
@shibayan @thorhj 
We have taken this issue into account and will be working on it this sprint (26/8 -13/9). This should be resolved with the next update for Hosted images.
I'll update you with the exact timeline later.

**Comment by hiyadav** [comment]
Hey @shibayan @thorhj 

We have made the changes. Latest version should start rolling out starting next week and will contain all latest SDK's of 2.1 and 2.2. 
3.0 SDK's will take some time to be installed on hosted agents.

**Comment by shibayan** [comment]
@hiyadav That is great news. Thank you for a great job!
