### ISSUE TITLE
Hosted MacOS - Update Mono Framework version to latest stable version (6.0.0.319)

### ISSUE THREAD

**Issue by GhostTigerXLI** [microsoft/azure-pipelines-image-generation#1163]
**Tool information**
- Tool name: Mono Framework
- Add or update? Update
- Desired version: 6.0.0.319

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [X] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [X] Xamarin
- [ ] Other

**Image impacted**
Hosted macOS

**Comment by ChaseFlorell** [comment]
The reason for this request is so that we can see if a newer version of mono will fix a NullReferenceException we're seeing when querying via EntityFramework.

https://github.com/mono/mono/issues/15852

**Comment by max-lobanov** [comment]
Mono 6.0 is available on VM image.
I am closing the issue. Please let me know if you have any questions

**Comment by ChaseFlorell** [comment]
@max-lobanov what is the path I need to use in order to access it? Here's my script

```bash
echo "Setting mono version to 5_18_1"
MONOVERSION=5_18_1
MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$MONOVERSION
echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"
echo "Appending AppleSdkRoot to Settings.plist"
mkdir -p /Users/vsts/Library/Preferences/Xamarin
cd /Users/vsts/Library/Preferences/Xamarin
echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"https://www.apple.com/DTDs/PropertyList-1.0.dtd\"><plist version=\"1.0\"><dict><key>AppleSdkRoot</key><string>/Applications/Xcode_10.3.app</string></dict></plist>" >> Settings.plist
echo "Setting Xcode version to 10.3 for Visual Studio for Mac"
sudo xcode-select -s /Applications/Xcode_10.3.app/Contents/Developer
sudo xcodebuild -showsdks
sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh $MONOVERSION
```

**Comment by fryette** [comment]
@ChaseFlorell try to use https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops with version 2.2.300+

Same issue here https://github.com/microsoft/azure-pipelines-image-generation/issues/1185

**Comment by max-lobanov** [comment]
@ChaseFlorell , please set  `MONOVERSION=6_0_0` in order to use Mono 6.0
