### ISSUE TITLE
Update/Add Component [Microsoft.VisualStudio.Component.VC] to v142

### ISSUE THREAD

**Issue by pavankanth6** [microsoft/azure-pipelines-image-generation#1164]
**According to documentation on MSFT page [VS Enterprise 2019 Workload and Component list](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?vs-2019&view=vs-2019) the workload Microsoft.VisualStudio.Workload.NativeGame requires Microsoft.VisualStudio.Component.VC.v142 but the image contains Microsoft.VisualStudio.Component.VC.v141 according to the image description here [Vs2019-Server2019 Software list](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2019-Server2019-Readme.md) **

- Tool name: Microsoft.VisualStudio.Component.VC.v142 
- Add or update? Update
- Desired version:  v142 

**Areas and ecosystems**

- [ ] Android
- [x] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
Hosted Windows 2019 with VS2019 image

**Workaround**
Remove the existing component and add it again using vs_enterprise.exe

**Are you willing to submit a PR?**
Yes

**Comment by kaylangan** [comment]
This will be updated automatically in the M156 deployment.

**Comment by pavankanth6** [comment]
@kaylangan When is M156 deployment scheduled for?
