### ISSUE TITLE
PowerShell Modules for AzureRM or Azure not installed in Windows 2019 

### ISSUE THREAD

**Issue by Ba4bes** [microsoft/azure-pipelines-image-generation#1173]
**Describe the bug**
Somewhere between 8 days ago and today, you can't get the AzureRM or Az module anymore when using Get-InstalledModule on the Windows2019-image. The 2016-image does show the modules. Doesn't matter whether you use AzurePowershell or regular Powershell

**Expected behavior**
In the 2016-image, you get the following output if you run 
`Get-InstalledModule | Select-object Name `
in the AzurePowershell task or the regular Powershell task. 

Starting: PowerShell |  
-- | --
  | ============================================================================== |  
  | Task : PowerShell |  
  | Description : Run a PowerShell script on Linux, macOS, or Windows |  
 
  | AzureRM.HDInsight |  
  | AzureRM.Insights |  
  | AzureRM.KeyVault |  
  | AzureRM.LogicApp |  
  | AzureRM.MachineLearning |  
  | AzureRM.Media |  
  | AzureRM.Network |  
  | AzureRM.NotificationHubs |  
  | AzureRM.OperationalInsights |  
  | AzureRM.PowerBIEmbedded |  
  | AzureRM.profile |  
  | AzureRM.RecoveryServices |  
  | AzureRM.RecoveryServices.Backup |  
  | AzureRM.RedisCache |  
  | AzureRM.Resources |  
  | AzureRM.Scheduler |  
  | AzureRM.ServerManagement |  
  | AzureRM.SiteRecovery |  
  | AzureRM.Sql |  
  | AzureRM.Storage |  
  | AzureRM.StreamAnalytics |  
  | AzureRM.Tags |  
  | AzureRM.TrafficManager |  
  | AzureRM.UsageAggregates |  
  | AzureRM.Websites |  
  | DockerMsftProvider |  
  | PackageManagement |  
  | PowerShellGet |  
  | PSWindowsUpdate |  
  | SqlServer |  
  |   |  
  |   |  
  | Finishing: PowerShell

**Actual behavior**
In the 2019 image, you get this output:

Starting: PowerShell |  
-- | --
  | ============================================================================== |  
  | Task : PowerShell |  
  | Description : Run a PowerShell script on Linux, macOS, or Windows |  
  | Version : 2.151.2 |  
  | Author : Microsoft Corporation |  
  | Help : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell |  
  | ============================================================================== |  
  | Generating script. |  
  | ========================== Starting Command Output =========================== |  
  | "C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'd:\a\_temp\39b62fd7-dbdf-4229-9143-6fc974186c0b.ps1'" |  
  |   |  
  | Name |  
  | ---- |  
  | DockerMsftProvider |  
  | PackageManagement |  
  | PowerShellGet |  
  | PSWindowsUpdate |  
  | SqlServer |  
  |   |  
  |   |  
  | Finishing: PowerShell

A description with steps to reproduce the issue.

This can be reproduced by running a PowerShell task or AzurePowerShell task (no difference in output for those tasks) with the following settings:

`    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'Get-installedModule | select Name'   `

**Image impacted**
Windows Windows-2019

I ran a pipeline 8 days ago that didn't have this issue in this image. 
This could also be a problem in the tasks, but since all three PowerShell tasks (PowerShell, AzurePowerShell@3 and AzurePowerShell@4) have the same issue and the 2016 image works without problems, I thought I'd start here. 

This is an issue for me as I use a PowerShell Module that checks if Az or AzureRM is used. That check now fails in the pipeline.

**Comment by poikjo** [comment]
I'm seeing something similar while using AzureRM in pipelines / release with Hosted VS2017 agents. Our script automatically updates AzureRM module if older version seems to be installed and yesterday we started to see following exception: "Module 'AzureRM' was not installed by using Install-Module, so it cannot be updated.".

**Comment by niadak** [comment]
@Ba4bes, @poikjo  Can you please use "Get-Module -Name Az* -ListAvailable" to check if AzureRM/Az modules are available/installed? Please refer to [Install-AzurePS.ps1](https://github.com/microsoft/azure-pipelines-image-generation/blob/6a4af9cceaced3841cd862374072543b4f3997f2/images/win/scripts/Installers/Install-AzureModules.ps1#L72) script where we are doing the same.

Context: We have recently stopped installing Azure modules (and using Save-Module) to support side by side availability of AzureRM and Az modules. So GetInstalled-Module command is not returning any Azure Module.

@poikjo , You can use Azure PowerShell task with "Use lasted installed" option set, this should allow you to use latest available AzureRM modules. We periodically updated the hosted agent with latest available azure modules.

**Comment by poikjo** [comment]
I'm getting following:
The AzureRM Modules initially present are:

Name                            Version Path                                                                           
----                            ------- ----                                                                           
Azure.Storage                   2.1.0   C:\Modules\azurerm_2.1.0\Azure.Storage\2.1.0\Azure.Storage.psd1                
AzureRM                         2.1.0   C:\Modules\azurerm_2.1.0\AzureRM\2.1.0\AzureRM.psd1                            
AzureRM.ApiManagement           2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.ApiManagement\2.1.0\AzureRM.ApiManagement.psd1
AzureRM.Automation              2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.Automation\2.1.0\AzureRM.Automation.psd1      
AzureRM.Backup                  2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.Backup\2.1.0\AzureRM.Backup.psd1              
AzureRM.Batch                   2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.Batch\2.1.0\AzureRM.Batch.psd1                
AzureRM.Cdn                     2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.Cdn\2.1.0\AzureRM.Cdn.psd1                    
AzureRM.CognitiveServices       0.3.0   C:\Modules\azurerm_2.1.0\AzureRM.CognitiveServices\0.3.0\AzureRM.CognitiveSe...
AzureRM.Compute                 2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.Compute\2.1.0\AzureRM.Compute.psd1            
AzureRM.DataFactories           2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.DataFactories\2.1.0\AzureRM.DataFactories.psd1
AzureRM.DataLakeAnalytics       2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.DataLakeAnalytics\2.1.0\AzureRM.DataLakeAna...
AzureRM.DataLakeStore           2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.DataLakeStore\2.1.0\AzureRM.DataLakeStore.psd1
AzureRM.DevTestLabs             2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.DevTestLabs\2.1.0\AzureRM.DevTestLabs.psd1    
AzureRM.Dns                     2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.Dns\2.1.0\AzureRM.Dns.psd1                    
AzureRM.HDInsight               2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.HDInsight\2.1.0\AzureRM.HDInsight.psd1        
AzureRM.Insights                2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.Insights\2.1.0\AzureRM.Insights.psd1          
AzureRM.KeyVault                2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.KeyVault\2.1.0\AzureRM.KeyVault.psd1          
AzureRM.LogicApp                2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.LogicApp\2.1.0\AzureRM.LogicApp.psd1          
AzureRM.MachineLearning         0.10.0  C:\Modules\azurerm_2.1.0\AzureRM.MachineLearning\0.10.0\AzureRM.MachineLearn...
AzureRM.Media                   0.2.0   C:\Modules\azurerm_2.1.0\AzureRM.Media\0.2.0\AzureRM.Media.psd1                
AzureRM.Network                 2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.Network\2.1.0\AzureRM.Network.psd1            
AzureRM.NotificationHubs        2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.NotificationHubs\2.1.0\AzureRM.Notification...
AzureRM.OperationalInsights     2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.OperationalInsights\2.1.0\AzureRM.Operation...
AzureRM.PowerBIEmbedded         2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.PowerBIEmbedded\2.1.0\AzureRM.PowerBIEmbedd...
AzureRM.profile                 2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.profile\2.1.0\AzureRM.profile.psd1            
AzureRM.RecoveryServices        2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.RecoveryServices\2.1.0\AzureRM.RecoveryServ...
AzureRM.RecoveryServices.Backup 2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.RecoveryServices.Backup\2.1.0\AzureRM.Recov...
AzureRM.RedisCache              2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.RedisCache\2.1.0\AzureRM.RedisCache.psd1      
AzureRM.Resources               3.1.0   C:\Modules\azurerm_2.1.0\AzureRM.Resources\3.1.0\AzureRM.Resources.psd1        
AzureRM.Scheduler               0.10.0  C:\Modules\azurerm_2.1.0\AzureRM.Scheduler\0.10.0\AzureRM.Scheduler.psd1       
AzureRM.ServerManagement        2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.ServerManagement\2.1.0\AzureRM.ServerManage...
AzureRM.SiteRecovery            2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.SiteRecovery\2.1.0\AzureRM.SiteRecovery.psd1  
AzureRM.Sql                     2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.Sql\2.1.0\AzureRM.Sql.psd1                    
AzureRM.Storage                 2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.Storage\2.1.0\AzureRM.Storage.psd1            
AzureRM.StreamAnalytics         2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.StreamAnalytics\2.1.0\AzureRM.StreamAnalyti...
AzureRM.Tags                    2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.Tags\2.1.0\AzureRM.Tags.psd1                  
AzureRM.TrafficManager          2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.TrafficManager\2.1.0\AzureRM.TrafficManager...
AzureRM.UsageAggregates         2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.UsageAggregates\2.1.0\AzureRM.UsageAggregat...
AzureRM.Websites                2.1.0   C:\Modules\azurerm_2.1.0\AzureRM.Websites\2.1.0\AzureRM.Websites.psd1          
Azure                           2.1.0   C:\Modules\azure_2.1.0\Azure\2.1.0\Azure.psd1                                  
Azure.Storage                   2.1.0   C:\Modules\azure_2.1.0\Azure.Storage\2.1.0\Azure.Storage.psd1                  
AzureRM.profile                 2.1.0   C:\Modules\azure_2.1.0\AzureRM.profile\2.1.0\AzureRM.profile.psd1              

# Trying update
Update AzureRM:
Required module AzureRM exists but version 6.9.0 is old
Updating module AzureRM version 6.9.0
Module 'AzureRM' was not installed by using Install-Module, so it cannot be updated.

Note: I cannot use Azure PowerShell task in this scenario as we are testing product installation which requires normal PS usage and specific versions.

**Comment by niadak** [comment]
@poikjo , We currently save AzureRM 2.1.0 module in C:\Modules\azurerm_2.1.0 folder and add the path to $env:PSModulePath to make the modules available.

You can try the following:
1. Remove C:\Modules\azurerm_2.1.0 from PSModule path or delete the folder to uninstall existing AzureRM
2. Install-AzureRM lastet version using Install-Module command (instead of Update-Module)

Please let us know if this helps.

**Comment by poikjo** [comment]
"Install-Module -Name AzureRM -AllowClobber -Force -RequiredVersion 6.9.0" works fine before actual product scripts but that needs to be in place on every Tasks and it's extra step that we need to add on builds.

**Comment by niadak** [comment]
I am not sure if i completely understand your scenario/pipeline structure, but in general, you need to do the "Install-Module" step only once per agent job, i.e at the beginning of the phase.

Again, you are already have the logic of updating azure PS in the scripts, I guess you just need to update the logic there.

**Comment by poikjo** [comment]
We initially check if the module already exists and if not then we do install. 

Now it (Get-Module -ListAvailable) returns module but it's not updatable anymore (Module 'AzureRM' was not installed by using Install-Module, so it cannot be updated).

So we need to change all of our builds so explicitly install AzureRM module and it causes more work to keep versions etc up to date.

**Comment by niadak** [comment]
The recent change of not installing AzureRM module is by design to support new Az module in hosted agent.

I guess you need to add the Install AzureRM step explicitly in the builds to fix the issue.

In hosted agent AzureRM 6.7.0 is available, you can use Azure PowerShell V3 task and use specific version 6.7.0 if possible subject to your company policy. Unfortunately we dont have AzureRM 6.9.0 available in hosted agent.

**Comment by Ba4bes** [comment]
I have changed my module to use Get-Module instead of Get-InstalledModule, which does work. 
So if this is by design I think that fixes my issue. 

Was there a way for me to know this beforehand? This was a breaking change for the module I use in my pipelines, it stopped working. The module is used quite a bit, so I had to fix stuff real quickly. Would like to know if I could have been prepared.

**Comment by niadak** [comment]
We dont do this changes very often. One thing we can do is to update the release note of the repo if there is any such changes in the installation process going forward.

**Comment by Ba4bes** [comment]
I have enabled the notifications for the releases. Would be great if you can mention changes like this one in the release notes. Thank you.
