### ISSUE TITLE
Generated file is empty

### ISSUE THREAD

**Issue by Tregan** [microsoft/azure-pipelines-image-generation#1174]
**Describe the bug**
Note: I know this is mostly about a custom task, and that those are not supported by Microsoft, but the behaviour on hosted agents is different from self-hosted agents. That's why I'm posting it here.

A bit of backstory: I'm building my flutter app using https://marketplace.visualstudio.com/items?itemName=aloisdeniel.flutter (source: https://github.com/aloisdeniel/vsts-flutter-tasks). I was missing an option to generate a code coverage file (Flutter supports running `flutter test --coverage` to run unit tests and create an lcov.info file), so I forked the source code and created a branch to add a toggle to the task (https://github.com/Tregan/vsts-flutter-tasks/tree/coverage). 

Now, when I run the task on a hosted agent, an empty lcov.info file is generated. The command runs correctly (`.../flutter.bat test --pub --coverage`), and the log says that coverage information is being collected: 

> Collecting coverage information...                                  36ms

The lcov.info file is generated, but it's empty. Adding an 'Inspect File Structure' task to the pipeline reveals the following:

> D:\a\1\s\coverage\lcov.info	8/15/2019 8:42:37 AM	0

I did manage to get it to generate a filled file once, when I enabled the `system.debug` variable and added `--verbose` to the flutter test command. However, even if I run that same configuration now, it merely generates an empty lcov.info file.

The weird parts:
- Adding a 'Command line' task that runs `$(FLUTTERTOOLPATH)/flutter test --coverage` generates a proper lcov.info file 100% of the time, but I'm missing the test summary
- Running the exactly same pipeline on a self-hosted machine (using latest build agent, 2.155.1) works 100% of the time, even if the 'Command line' task from ^ is not in the pipeline.

**Expected behavior**
- Behaviour of `.../flutter.bat test --pub --coverage` should work the same on hosted and self-hosted build agents
- On hosted agents, a non-empty lcov.info file should be generated

**Actual behavior**
- On hosted agents, an empty lcov.info file is generated.

1. Clone, configure and build (publish.sh) the following branch: https://github.com/Tregan/vsts-flutter-tasks/tree/coverage
2. Upload the task to the marketplace and add it to your organization
3. Create a pipeline for a basic Flutter project that includes a couple of tests
4. Add the `Flutter Install (Extended)`, `Flutter Test (Extended)` and `Inspect File Structure` tasks, make sure to enable the Coverage option in the test task.
5. Run the pipeline and notice that the build succeeds, all tests succeeded and that the log says coverage information was collected.
6. Check the summary -> Agent File Structure and search for the lcov.info file, notice that it has a size of 0.
7. Run the same pipeline on a self-hosted agent and notice that the lcov.info is not empty

**Image impacted**
- vs2017-win2016, windows-2019 agents from the Azure Pipelines pool
- Have not tested on other agents

Yours,
Bas Rops

**Comment by PBoraMSFT** [comment]
@Tregan - As you rightly said, the owners of the custom tasks are the right folks to investigate the issue. 
If you have a simplified CLI repro that doesn't involve custom tasks, our team can help take a look to see what's going on.
