### ISSUE TITLE
macOS framework libs out of sync (ref: #758)

### ISSUE THREAD

**Issue by svenevs** [microsoft/azure-pipelines-image-generation#1181]
**Describe the bug**
See also #758.  I've been updating a build system for a project and didn't know if I was causing these warnings, but I didn't.  Creating a new issue because the other was closed by the stale bot, but this is still an issue.  My understanding is this actually means that the xcode versions are getting mixed, which could be leading to more difficult to track build errors for users?  Not sure ... I don't do much with macOS let alone try to manage multiple XCode installations ... which is not exactly a seamless experience from when I did do that ;)

AKA feel free to close at your discretion, I'm just going to ignore the warnings, but it does seem like it's worth investigating more.  There's a [very thorough writeup on it here](http://sd.jtimothyking.com/2018/07/26/stub-file-and-library-file-out-of-sync/) if that is helpful.

**Expected behavior**
No warnings about possibly invalid XCode installation.

**Actual behavior**
Many warnings about possibly invalid XCode installation.

Reproduce:

- Build something that uses Cocoa, OpenGL, AppKit, etc frameworks.  See text dump below.
- I'm starting back in on finishing the [build system rewrite here](https://github.com/dscan/nanogui/tree/fix/modernize-cmake), but I think there are easier ways to reproduce this than that project, and I'll note that I will be force-pushing on that branch quite a bit in the future and then the fork will eventually be deleted.

**Image impacted**

`macOS-10.13` and `macOS-10.14`.

--------------------------------------------------

My warning dump:

```
ld: warning: text-based stub file /System/Library/Frameworks//Cocoa.framework/Cocoa.tbd and library file /System/Library/Frameworks//Cocoa.framework/Cocoa are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//OpenGL.framework/OpenGL.tbd and library file /System/Library/Frameworks//OpenGL.framework/OpenGL are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//IOKit.framework/IOKit.tbd and library file /System/Library/Frameworks//IOKit.framework/IOKit are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//AppKit.framework/Versions/C/AppKit.tbd and library file /System/Library/Frameworks//AppKit.framework/Versions/C/AppKit are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.tbd and library file /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.tbd and library file /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/PrivateFrameworks/UIFoundation.framework/Versions/A/UIFoundation.tbd and library file /System/Library/PrivateFrameworks/UIFoundation.framework/Versions/A/UIFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//ApplicationServices.framework/Versions/A/ApplicationServices.tbd and library file /System/Library/Frameworks//ApplicationServices.framework/Versions/A/ApplicationServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//Foundation.framework/Versions/C/Foundation.tbd and library file /System/Library/Frameworks//Foundation.framework/Versions/C/Foundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CoreGraphics.framework/Versions/A/CoreGraphics.tbd and library file /System/Library/Frameworks//CoreGraphics.framework/Versions/A/CoreGraphics are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CoreText.framework/Versions/A/CoreText.tbd and library file /System/Library/Frameworks//CoreText.framework/Versions/A/CoreText are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//ImageIO.framework/Versions/A/ImageIO.tbd and library file /System/Library/Frameworks//ImageIO.framework/Versions/A/ImageIO are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/ATS.tbd and library file /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/ATS are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CoreServices.framework/Versions/A/CoreServices.tbd and library file /System/Library/Frameworks//CoreServices.framework/Versions/A/CoreServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices.tbd and library file /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis.tbd and library file /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/Versions/A/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/Versions/A/CoreFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CFNetwork.framework/Versions/A/CFNetwork.tbd and library file /System/Library/Frameworks//CFNetwork.framework/Versions/A/CFNetwork are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList are out of sync. Falling back to library file for linking.
```

**Comment by max-lobanov** [comment]
Hi, @svenevs .
Do you have minimal app with repro of this issue?

My guess that it can be related to command line tools.
Could you please try to reinstall `command line tools` after switching Xcode?
(based on the [article](http://sd.jtimothyking.com/2018/07/26/stub-file-and-library-file-out-of-sync/))
```
sudo xcode-select -s /Applications/Xcode_10.2.1.app
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install
``` 
Please let us know if it resolves the warnings above

**Comment by svenevs** [comment]
Just wanted to send a quick reply, I should be able to setup a small demo
repo and test this out tonight.

I don't think deleting the command line tools and reinstalling them on each
build is a good idea. I think they're a couple hundred MB which shouldn't
be very time consuming to download, but it seems wasteful to do that for
both your build machines and apple servers. Will send back more info /
small demo repo after work :)

**Comment by svenevs** [comment]
Hey @max-lobanov,

I made a more concise [demo repo here](https://github.com/svenevs/microsoft-azure-pipelines-image-generation-issue-1181), GitHub / AzP are having some service delays but the master branch on there should build soonish but I grow tired of waiting ;).  The [builds are here](https://dev.azure.com/svenevs/microsoft-azure-pipelines-image-generation-issue-1181/_build?definitionId=6), the main point is that you need to link against one of these libraries to trigger the warning.  In that example I'm linking against Cocoa, which will trigger the warnings mentioned in the macOS builds.

I don't really know how to create a smaller example than this, it might be possible with other languages but I really only work with C++, and only indirectly with Cocoa via working on the project I linked with the bigger build system.  Hope this is helpful.

**Comment by svenevs** [comment]
Update: good news!  It seems it's actually only the 10.13 build.  The [master branch build is here](https://dev.azure.com/svenevs/microsoft-azure-pipelines-image-generation-issue-1181/_build/results?buildId=323), compare the `macOS_10_13`'s `CmdLine` output with the `macOS_10_14` one.  So maybe it will be easier to fix that since it seems to just be the one image?

**Comment by max-lobanov** [comment]
@svenevs, Thank you for repro app.
I have reproduced the issue, but unfortunately my advice above don't resolve the issue.

At the moment, the root cause is unclear for me, but I will take a look more and return back as soon as I find something.

**Comment by max-lobanov** [comment]
@svenevs
I think we have found the root cause of those warnings. They are caused by inconsistent MacOSX SDK.
To avoid warnings, we need to specify `SDKROOT` environment variable and point it to the selected Xcode:
```
export SDKROOT="$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
```
This command will set correct SDKROOT based on current Xcode version.

I have applied this solution for your test app and it passed without warnings on High Sierra.
Could you please confirm it from your side?

**Comment by jmn39** [comment]
The out of sync problem has to do with the .tbd file.   An examination of dates on, for example, CoreFoundation and CoreFoundation.tbd shows that the latter is much older.   It suggests that it can be ignored.  On 10.13.6 I deleted (changed name to oldxxx.tbd) in CoreFoundation and IOK which I use, and the problem immediately disappears.   It the tbd file is absent then it follows the error messages about out of sync will also disappear.   This seems the simplest solution of all the others that I have seen - many of which don't seem to work.
