### ISSUE TITLE
Cannot build Xamarin.Android on the latest (6.0.0) SDK

### ISSUE THREAD

**Issue by fryette** [microsoft/azure-pipelines-image-generation#1185]
**Describe the bug**
A clear and concise description of what the bug is, and why you consider it to be a bug.
Cannot build Xamarin.Android on the latest (6.0.0) Mono SDK

**Expected behavior**
A description of what you expected to happen.
Xamarin.Android should be built on the latest SDK version

**Comment by max-lobanov** [comment]
Hi @fryette ,
Mono 6.0 requires .NET Core SDK 2.2.300+ but default one on the VM image is 2.2.104.
Please try to add [NET Core Tool Installer task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops) to your build definition.
The reason why default .NET Core was not updated on VM image is that .NET Core 2.2.300 contains breaking change that breaks all older Mono versions.
