### ISSUE TITLE
Update Windows Driver Kit to 1903

### ISSUE THREAD

**Issue by reynoldsbd** [microsoft/azure-pipelines-image-generation#1192]
**Tool information**
- Tool name: Windows Driver Kit
- Add or update? Update
- Desired version: 1903

**Areas and ecosystems**

- [ ] Android
- [x] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**

VS2019

**Workaround**
No

**Are you willing to submit a PR?**
Sure, just point me in the right direction!

**Comment by loreggia** [comment]
To my knowledge building a driver project in VS2019 **requires** WDK 1903, so it prevents all driver projects from migrating from a hosted VS2017 to a hosted VS2019 pipeline (correct me if I'm wrong).

I expect this to be a pretty simple change (changing the URLs in the "[Install-WDK.ps1](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/win/scripts/Installers/Vs2019/Install-WDK.ps1)"-script) but I don't know if the public download link IDs from [here](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk) are subject to change, so I don't feel confident enough to create a PR.

(BTW, this is currently blocking a pipeline of mine, as the project contains both .NET Core 3 projects and a driver project.)

**Comment by reynoldsbd** [comment]
Ideally, the VS2019 image would have several recent versions of the WDK installed. This is already the case for the user-mode Windows SDK (which is installed as part of Visual Studio).

This is valuable because it allows us to test and validate new SDK versions on our own time without being forced to upgrade due to the CI image changing. For drivers, this predictability is not just valuable, it's critical! 😃

**Comment by kaylangan** [comment]
This is completed: https://github.com/microsoft/azure-pipelines-image-generation/pull/1437#issuecomment-568025163
