### ISSUE TITLE
Hosted macOS image (Visual Studio for Mac 8.2) build errors 

### ISSUE THREAD

**Issue by battepatikiran** [microsoft/azure-pipelines-image-generation#1193]
**Describe the bug**
Hosted macOS agents are failing with error 
The "GenerateDepsFile" task failed unexpectedly. [/Users/vsts/agent/2.155.1/]
/Users/vsts/.dotnet/sdk/2.2.105/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(129,5): error MSB4018: System.MissingMethodException: Method not found: System.Collections.Generic.IList

**Expected behavior**
https://docs.microsoft.com/en-us/visualstudio/mac/net-core-support?view=vsmac-2019
If you were previously using .NET Core v2.2.1xx with Visual Studio for Mac 8.0, you'll need to manually update to a supported version of .NET Core, as listed in the table above. We recommend either 2.1.700 or 2.2.300

**Actual behavior**
A description with steps to reproduce the issue.

https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md#xcode

Hosted agent only supports 
.NET Core SDK 1.0.1 1.0.4 1.1.10 1.1.11 1.1.12 1.1.13 1.1.4 1.1.5 1.1.7 1.1.8 1.1.9 2.0.0 2.0.3 2.1.100 2.1.101 2.1.102 2.1.103 2.1.104 2.1.105 2.1.2 2.1.200 2.1.201 2.1.202 2.1.300 2.1.301 2.1.302 2.1.4 2.1.400 2.1.401 2.1.402 2.1.403 2.1.500 2.1.502 2.1.503 2.1.504 2.1.505 2.2.100 2.2.101 2.2.102 2.2.103 2.2.104 2.2.105

Visual Studio for Mac 8.2 needs 2.1.700 or 2.2.300

**Image impacted**
Add a label for each image that has the bug (e.g., ubuntu, mac, window)
Hosted macOS build agents

**Comment by max-lobanov** [comment]
Hi @battepatikiran ,
Mono 6.0 requires .NET Core SDK 2.2.300+ but default one on the VM image is 2.2.104.
Please try to add [NET Core Tool Installer task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops) to your build definition and choose .NET Core version that you need (2.2.300 or 3.0)
The reason why default .NET Core was not updated on VM image is that .NET Core 2.2.300 contains breaking change that breaks all older Mono versions on VM image

**Comment by battepatikiran** [comment]
Hi @max-lobanov, resolution steps worked. thanks.

**Comment by max-lobanov** [comment]
I am closing issue, please reopen if you have any questions
