### ISSUE TITLE
Add .NET Framework SDK cached image to hosted images

### ISSUE THREAD

**Issue by giggio** [microsoft/azure-pipelines-image-generation#1194]
**Tool information**
- Tool name: .NET Framework Sdk Docker Image (cache)
- Add or update? Add
- Desired version: 4.8
- If this is an add request:
  - Brief description of tool: The .NET Sdk image
  - URL for tool's homepage: https://hub.docker.com/_/microsoft-dotnet-framework-sdk/

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [x] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**

* `windows-latest`
* `win1803`
* `vs2017-win2016`

**Workaround**
The workaround is to used an uncached image. It takes almost 15 minutes to pull the whole image.

**Are you willing to submit a PR?**
Yes, it seems to be a simple edit on https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/win/scripts/Installers/WindowsContainer1803/Update-DockerImages.ps1

**Comment by ArturDorochowicz** [comment]
+1 
Please update the net framework sdk image to 4.8.

The current state is somewhat problematic. `win1803` contains an image for 4.7.2 [1], which is out of date and actually discontinued [2]. And `windows-2019` doesn't have an sdk image at all, only runtime, but for 4.8 [3].

[1] https://github.com/microsoft/azure-pipelines-image-generation/blob/7e32d761ef51f8857da44db1024e030c51cff69a/images/win/scripts/Installers/WindowsContainer1803/Update-DockerImages.ps1
[2] https://github.com/microsoft/dotnet-framework-docker/issues/428
[3] https://github.com/microsoft/azure-pipelines-image-generation/blob/7e32d761ef51f8857da44db1024e030c51cff69a/images/win/scripts/Installers/Vs2019/Update-DockerImages.ps1

**Comment by giggio** [comment]
This is not stale.

**Comment by giggio** [comment]
As this has moved to another repo, and after checking that for the updated scripts, it seems that 4.8 was addes. See:
https://github.com/actions/virtual-environments/blob/master/images/win/scripts/Installers/Windows2019/Update-DockerImages.ps1
I am closing this issue, then.

**Comment by ArturDorochowicz** [comment]
@giggio Reopen. This issue is about .NET Framework **SDK**. The file you've linked is about the runtime image.

**Comment by giggio** [comment]
@ArturDorochowicz you are correct. It still isn't there.

**Comment by giggio** [comment]
I'm closing it again, it is being tracked here: https://github.com/actions/virtual-environments/issues/953
