### ISSUE TITLE
Add Xcode 11 beta 6

### ISSUE THREAD

**Issue by YahiaRagae** [microsoft/azure-pipelines-image-generation#1197]
**Tool information**
- Tool name: Xcode
- Add or update? Add
- Desired version: Xcode 11 beta 6
- If this is an add request:
  - Brief description of tool: It's Xcode
  - URL for tool's homepage: https://developer.apple.com/xcode/

**Areas and ecosystems**

- [√] iOS, macOS, and Apple-specific tools

**Image impacted**
macOS 10.14 or macOS 10.15

**Workaround**
It may be possible to install Xcode 11 using something like https://github.com/xcpretty/xcode-install during jobs, but it would probably take 30+ minutes to download, extract and install it.

**Are you willing to submit a PR?**
it seems it's not open for the public.

**Comment by YahiaRagae** [comment]
Xcode 11 beta 7 just got released, if you are adding it's better to be 7

**Comment by max-lobanov** [comment]
@YahiaRagae , Xcode 11 beta 6 is on image.

**Comment by YahiaRagae** [comment]
it's working, Thanks
