### ISSUE TITLE
Mono 6.0.0 is missing from Hosted macOS

### ISSUE THREAD

**Issue by diegostamigni** [microsoft/azure-pipelines-image-generation#1201]
**Describe the bug**
Mono 6.0.0 is missing from Hosted macOS but according to latest https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md it should be present.

**Expected behavior**
Mono 6.0.0 should be installed on hosted VM.

**Actual behavior**
A simple bash ls of /Library/Frameworks/Mono.framework/Versions showed the missing 6.0.0

**Image impacted**
macOS 10.14

**Comment by diegostamigni** [comment]
I'm closing this as I can see now the changes in the VM reflecting the changelog. Cheers!

**Comment by max-lobanov** [comment]
@diegostamigni , the changes were deployed today. Sorry for delay and inconvenience.
