### ISSUE TITLE
Ruby 2.6.2 is not available in macOS-10.14

### ISSUE THREAD

**Issue by diogot** [microsoft/azure-pipelines-image-generation#1203]
I'm using `UseRubyVersion` to select version 2.6.2 on macOS for more than a month.
Today started to fail:

![Screen Shot 2019-08-29 at 14 46 31](https://user-images.githubusercontent.com/885516/63963611-cd870480-ca6b-11e9-9385-64aa0c15886b.png)

The [documentation](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md#pre-cached-tools) still report that it's supported.

My CI is stoped until we fix it.
What is the policy for installed Ruby versions?

Thanks

**Comment by kaylangan** [comment]
We're rolling out a new image that bumped Ruby 2.6.2 to 2.6.3. Docs updates are coming shortly.

As for expectations--you can expect that we'll have one version of each x.x version, but the patch version will move.

**Comment by diogot** [comment]
OK, thanks.
