### ISSUE TITLE
Add support for latest SQL Package.exe and in MSBuild

### ISSUE THREAD

**Issue by kmkumaran** [microsoft/azure-pipelines-image-generation#1206]
update SQLPackage.exe and latest MSBuild

**Comment by kevinvngo** [comment]
Here's the latest DacFx (18.3): That's released on the download center: https://go.microsoft.com/fwlink/?linkid=2102893

**Comment by Ajay-MS** [comment]
@kevinvngo 

I will raise PR for for the update for SQLPackage.exe itself.

**Comment by Ajay-MS** [comment]
PR for DacFx - https://github.com/microsoft/azure-pipelines-image-generation/pull/1222

**Comment by Ajay-MS** [comment]
closing as the corresponding PR already merged.
