### ISSUE TITLE
Ubuntu Az Module missing

### ISSUE THREAD

**Issue by dirkslab** [microsoft/azure-pipelines-image-generation#1208]
**Describe the bug**

According to Linux Image readme Az Module should be available.
Readme: https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/linux/Ubuntu1604-README.md

The following software is installed on machines in the Hosted Ubuntu 1604 pool
Az Module (1.0.0)
Az Module (1.6.0)

**Expected behavior**

run az module command in powershell core, without needing to install az module.

**Actual behavior**

Name                           Value
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Linux 4.15.0-1055-azure #60-Ubuntu SMP Thu Aug …
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Connect-AzAccount : The term 'Connect-AzAccount' is not recognized as the name of a cmdlet, function, script file, or operable program

workaround: 
  - pwsh: |
      Install-Module Az -Force -AllowClobber
    displayName: 'install az module'

**Image impacted**

ubuntu-latest and ubuntu-16.04

**Comment by RoopeshNair** [comment]
@20shivangi / @niadak

**Comment by niadak** [comment]
The Az Modules are saved in /usr/share/az_{version} folder. This is to support multiple Az module version side by side. You need to update the $env:PSModule path with the folder path to use the module.

Currently available versions are /usr/share/az_1.0.0, /usr/share/az_1.6.0, /usr/share/az_2.3.2 and /usr/share/az_2.6.0.

BTW, recommened way to run Azure PowerShell scripts in pipeline is using AzurePowerShell task.

**Comment by dirkslab** [comment]
Thanks, will test this out. Will post response for others on the process
when done.

"BTW, recommend way to run Azure PowerShell scripts in pipeline is using
AzurePowerShell task." ...

 ...thanks, at the time I swapped from Task as it did not do what I needed
to do. Might revisit as updates to the tasks might now make them
sufficient.

**Comment by dirkslab** [comment]
have attempted the following based on feedback above in yml pipeline template. All subsequent az calls still fail. Any ref to documentation would be much appreciated.

attempted:
$env:PSModulePath = $env:PSModulePath + ";/usr/share/az_2.6.0"
$env:PSModulePath = $env:PSModulePath + ":/usr/share/az_2.6.0"
$env:PSModulePath = $env:PSModulePath + ":/usr/share/az_2.6.0/Modules"

example:
  - pwsh: |
      $env:PSModulePath
      $env:PSModulePath = $env:PSModulePath + ":/usr/share/az_2.6.0/Modules"
      $env:PSModulePath
      #Install-Module Az -Force -AllowClobber

**Comment by niadak** [comment]
Can you try the following?
$env:PSModulePath = "/usr/share/az_2.8.0:" + $env:PSModulePath;

You can refer to the az module[ validation logic](https://github.com/microsoft/azure-pipelines-image-generation/blob/97c5347e8ea2628cc61e7c6cf482ae39fe47f22c/images/linux/scripts/installers/1804/azpowershell.sh#L23
)

**Comment by dirkslab** [comment]
Thanks so much for the feedback. Your suggestion work and I suspect some of my previous attempts might work as well. 

What we learned:
Updating the module path as per this thread, updates the pwsh session that is running, where as install-module AZ seems to be more global. Using install module will result in AZ being available in all subsequent pwsh sessions in your deployment task, where updating the module path you need to do at the start of any pwsh session that might need Az.

I have added $env:PSModulePath = "/usr/share/az_2.6.0:" + $env:PSModulePath; to my default pwsh yaml template to make it available every time.

I am sure there is a more elegant way to do this, for now this will be perfect.

This might be a small change, but saving a minute on every deploy adds up to be significant. Thanks again!!
