### ISSUE TITLE
Initialize containers - task taking too long then expected in ADO

### ISSUE THREAD

**Issue by aammirmirza** [microsoft/azure-pipelines-image-generation#1210]
**Describe the bug**
In the DevOps pipeline "Initialize containers" job with the cached image "sha256:af2ba65cf68152c7b745e3253137ece34ead87df9e451755ae8226c1acacb38a" is taking more than 8 mins to PULL. Few days back it was PULLing in 6 Seconds.
I am using the latest CACHE image "Azure Pipelines Windows Container 1803 image" from below link.
https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/win/WindowsContainer1803-Readme.md

Because of IMAGE PULL my pipelines are taking 8-10 mins extra. Which is the cause of downloading image from repo instead of using the CACHED

**Expected behavior**
**As I am using CACHED images it should finish the Initialize task in few seconds as it was doing earlier (9 Sec)**

**Actual behavior**
Use the below containerized job yaml to reproduce it
*********************************************************
jobs:
- job: MyTestJob
  pool:
    vmImage: 'win1803'
  container:
    image: "microsoft/dotnet-framework:4.7.2-sdk-windowsservercore-1803@sha256:af2ba65cf68152c7b745e3253137ece34ead87df9e451755ae8226c1acacb38a"
  steps:
  - template: 'your_template.yaml'
    parameters:
      result: 'abc'
*********************************************************
**Image impacted**
"microsoft/dotnet-framework:4.7.2-sdk-windowsservercore-1803@sha256:af2ba65cf68152c7b745e3253137ece34ead87df9e451755ae8226c1acacb38a"

**Comment by aammirmirza** [comment]
Dear friends,
Any progress on this ?

**Comment by shashankbarsin** [comment]
Apologies for the delay in response (Argh I seriously need to find a way to streamline my GitHub notifications so that I don't miss out on important ones like this 🙈). @vtbassmatt and his team drive the work on container jobs. Assigning the issue to Matt to take a look at this

**Comment by vtbassmatt** [comment]
@aammirmirza sorry for bouncing you around like this. I understand the frustration due to regressing the time your jobs take to start. I'm asking around to figure out what changed in the hosted image, and where we publish such notifications so that you can update your pipeline. It's not really a job container concern; it's all about what images are pre-cached on the hosted image.

@kaylangan @thejoebourneidentity @alepauly @shadyysf can any of you help me understand what changed in the payload on the hosted image?

**Comment by kaylangan** [comment]
We pull the latest at time of image generation. Here's the diff for the last update: https://github.com/microsoft/azure-pipelines-image-generation/commit/e3b2f474c976a6b356eb7cd3038e8de04a3ea0d6#diff-bb4a511d2b74c4e4fefd5b6186c54881

**Comment by vtbassmatt** [comment]
Pinning to a particular SHA of an image will mean that, as caches get updated with newer versions of the same image label, pull times may regress like this.
