### ISSUE TITLE
Clarify version of Docker on Ubuntu 16.04 and 18.04

### ISSUE THREAD

**Issue by kaylangan** [microsoft/azure-pipelines-image-generation#1218]
**Describe the bug**
Because we have to use http://github.com/azure/moby on our Linux images due to docker licensing issues the version shows up as 3.0.x instead of the expected 19.03 style version. We should update the docs about our virtual environments with a note about the docker version and why it is different.

**Expected behavior**
Clarification on what version is being used so user's understand how recent it is.

**Image impacted**
Add a label for each image that has the bug (e.g., ubuntu, mac, window)
Ubuntu 16.04 and Ubuntu 18.04

**Comment by davvid1986** [comment]
Need my 2 million gbp going into my broker

**Comment by davvid1986** [comment]
Þ
[10EX 2019-08-03 15_16 activity (1).pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594017/10EX.2019-08-03.15_16.activity.1.pdf)

**Comment by davvid1986** [comment]
[logo-00b6f95f-d138-4b3f-8914-6ff8b954aa9a.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594075/logo-00b6f95f-d138-4b3f-8914-6ff8b954aa9a.pdf)

> ### ### 
[logo-6217fbf4-0d59-4ddb-81cc-6eba14c71dca.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594076/logo-6217fbf4-0d59-4ddb-81cc-6eba14c71dca.pdf)
[image.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594077/image.pdf)
[theme-7e22de0a-44aa-474b-a22a-8a079c50cf0d.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594078/theme-7e22de0a-44aa-474b-a22a-8a079c50cf0d.pdf)
[theme-b2811a14-90ef-4435-977d-f904ec079e85.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594079/theme-b2811a14-90ef-4435-977d-f904ec079e85.pdf)

[image158212.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594081/image158212.pdf)
[logo-2a82c02e-4c9c-4c55-b201-f8d1ffb78cce.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594082/logo-2a82c02e-4c9c-4c55-b201-f8d1ffb78cce.pdf)
[logo-bf754f78-586e-44d9-86b6-004fe3e16cb1.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594083/logo-bf754f78-586e-44d9-86b6-004fe3e16cb1.pdf)
![AVSE-Coin-BrightColorUp](https://user-images.githubusercontent.com/50857334/64590406-5c1a5080-d39f-11e9-8bb5-3cd83aa66eee.jpg)

[theme-f9a57d54-76c7-4400-b8b3-788934e7e1bc.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594084/theme-f9a57d54-76c7-4400-b8b3-788934e7e1bc.pdf)



[9r39q4710f1722ec248fca9df55dbfe8e62c8.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594086/9r39q4710f1722ec248fca9df55dbfe8e62c8.pdf)
[image140816.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594088/image140816.pdf)
[Escrow+Internet+Domain+Index+Q1+2019.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594089/Escrow%2BInternet%2BDomain%2BIndex%2BQ1%2B2019.pdf)
[logo-f189ad84-3c06-4519-b59c-b1c9995b3f24.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594090/logo-f189ad84-3c06-4519-b59c-b1c9995b3f24.pdf)
[9r39q12ace379c5cb424485786247ae836595.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594091/9r39q12ace379c5cb424485786247ae836595.pdf)

[theme-64e50f79-8f2c-48e7-a8d1-c8d7790e1144.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594093/theme-64e50f79-8f2c-48e7-a8d1-c8d7790e1144.pdf)



[theme-0be412d7-1ced-414e-9529-17f7666549bf.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594094/theme-0be412d7-1ced-414e-9529-17f7666549bf.pdf)
[image397803.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594095/image397803.pdf)
[9r39q5b680c34aaab4a1c99e68988c6a2823f.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594096/9r39q5b680c34aaab4a1c99e68988c6a2823f.pdf)
[image990238.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594097/image990238.pdf)
[SHA256SUMS.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594098/SHA256SUMS.pdf)
[theme-09e770c9-f7da-4c78-9c93-6647f94e6cb1.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594099/theme-09e770c9-f7da-4c78-9c93-6647f94e6cb1.pdf)
[!PayKickstart_Affiliate_Quickstart_Guide.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594100/PayKickstart_Affiliate_Quickstart_Guide.pdf)
![IMG_20190413_104615](https://user-images.githubusercontent.com/50857334/64590446-70f6e400-d39f-11e9-8f99-7fe1f809b487.jpg)


[9r39qa746532e31aa4c7bbdc6cf51c30d53b2.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594101/9r39qa746532e31aa4c7bbdc6cf51c30d53b2.pdf)
[image613954.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594102/image613954.pdf)
[theme-c0ceaeb8-5792-4e71-bf9d-6975e40d89f0.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594103/theme-c0ceaeb8-5792-4e71-bf9d-6975e40d89f0.pdf)
[logo-b6c0b1db-d4bc-4ff2-8048-20ccf8956a2c.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594104/logo-b6c0b1db-d4bc-4ff2-8048-20ccf8956a2c.pdf)
[logo-612735d3-29ba-43bb-a3da-e05493937230.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594105/logo-612735d3-29ba-43bb-a3da-e05493937230.pdf)
[logo-b591b5f2-c9d1-42d9-a82e-fce3e4e9570e.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594106/logo-b591b5f2-c9d1-42d9-a82e-fce3e4e9570e.pdf)
[theme-c757b6be-6509-474d-880a-8ad86ef65cd5.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594107/theme-c757b6be-6509-474d-880a-8ad86ef65cd5.pdf)
[image535776.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594108/image535776.pdf)

[commissiongorilla.zip](https://github.com/microsoft/azure-pipelines-image-generation/files/3594109/commissiongorilla.zip)
[GDPR_DPA_for_AC_Customers.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594110/GDPR_DPA_for_AC_Customers.pdf)
[logo-98e8ac83-2924-4924-8fb2-e4bf143107e5.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594111/logo-98e8ac83-2924-4924-8fb2-e4bf143107e5.pdf)
[image199090.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594112/image199090.pdf)

[bitcoin.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594113/bitcoin.pdf)
[9r39qdff05bfffe1d4001a49ebf2d88b3d1cb.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594114/9r39qdff05bfffe1d4001a49ebf2d88b3d1cb.pdf)
[Beneficiary:.txt](https://github.com/microsoft/azure-pipelines-image-generation/files/3594115/Beneficiary.txt)
[Readme-master.zip](https://github.com/microsoft/azure-pipelines-image-generation/files/3594116/Readme-master.zip)
[logo-67265fcf-2d25-4382-9821-b3a82a4f8f8e.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594117/logo-67265fcf-2d25-4382-9821-b3a82a4f8f8e.pdf)

[theme-8dfc53fa-6af7-440a-91bb-0417b88db5b2.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594119/theme-8dfc53fa-6af7-440a-91bb-0417b88db5b2.pdf)

[logo-014828f7-40a4-4995-b5fc-5b00ac40ba08.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594120/logo-014828f7-40a4-4995-b5fc-5b00ac40ba08.pdf)



[Scan 30 Aug 2019 (1).pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594122/Scan.30.Aug.2019.1.pdf)

[logo-cc0483b4-5725-4221-9f58-549acd98f246.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594126/logo-cc0483b4-5725-4221-9f58-549acd98f246.pdf)

[theme-69ae9c18-9026-4be6-80a5-73c2b15bcf73.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594128/theme-69ae9c18-9026-4be6-80a5-73c2b15bcf73.pdf)
[theme-c7498876-bd4b-442d-abec-e2a490eb8357.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594130/theme-c7498876-bd4b-442d-abec-e2a490eb8357.pdf)
[10EX 2019-08-03 15_16 activity (1).pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594131/10EX.2019-08-03.15_16.activity.1.pdf)
[theme-6bc52caf-4bba-415d-a5af-8aee07d7caa3.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594132/theme-6bc52caf-4bba-415d-a5af-8aee07d7caa3.pdf)
[Beneficiary:.txt](https://github.com/microsoft/azure-pipelines-image-generation/files/3594133/Beneficiary.txt)
[theme-a9e75675-5518-4cf2-a483-8820ad5bfea7.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594134/theme-a9e75675-5518-4cf2-a483-8820ad5bfea7.pdf)


[Push your results.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594136/Push.your.results.pdf)
[theme-1635d528-8259-4df1-867f-2f6c17c3a453.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594137/theme-1635d528-8259-4df1-867f-2f6c17c3a453.pdf)
[9r39qecf8fdd2ffc04c94921aefafff749237.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594138/9r39qecf8fdd2ffc04c94921aefafff749237.pdf)
[logo-c3c8dcfb-470d-4e1c-b346-cd5475a8369a.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594140/logo-c3c8dcfb-470d-4e1c-b346-cd5475a8369a.pdf)


[logo-9104f7b5-8f38-4ff1-844b-5bc6431751bc.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594141/logo-9104f7b5-8f38-4ff1-844b-5bc6431751bc.pdf)

[Your Invoices.xlsx](https://github.com/microsoft/azure-pipelines-image-generation/files/3594142/Your.Invoices.xlsx)
[theme-dabb62d7-9735-43be-b562-42c44454df15.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594143/theme-dabb62d7-9735-43be-b562-42c44454df15.pdf)
[Copy of Invoice Template - 501c6.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594144/Copy.of.Invoice.Template.-.501c6.pdf)

[logo-fa55ba8d-1bc3-486f-85dd-17b8888a30d4.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594145/logo-fa55ba8d-1bc3-486f-85dd-17b8888a30d4.pdf)



[theme-fad110b4-4033-4feb-8bd4-4fa5d025ae5d.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594147/theme-fad110b4-4033-4feb-8bd4-4fa5d025ae5d.pdf)
[bitcoin.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594148/bitcoin.pdf)
[logo-4e4edb49-b11f-47fd-aa42-597770848584.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594149/logo-4e4edb49-b11f-47fd-aa42-597770848584.pdf)
[theme-48f9d867-c0a0-4cc1-a9da-c954cf94d9a3.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594150/theme-48f9d867-c0a0-4cc1-a9da-c954cf94d9a3.pdf)
[logo-438fca42-8c12-463d-a6fc-15820b807e78.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594151/logo-438fca42-8c12-463d-a6fc-15820b807e78.pdf)
[DataMonetization-BasicOverview.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594152/DataMonetization-BasicOverview.pdf)

[theme-d2ce5c65-4dfc-4c99-88c6-d0fc008e310e.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594153/theme-d2ce5c65-4dfc-4c99-88c6-d0fc008e310e.pdf)
[theme-0779b45f-3ae3-4fcf-a33f-f83e1b949e10.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594154/theme-0779b45f-3ae3-4fcf-a33f-f83e1b949e10.pdf)

[9r39q87125e4a850e45dca227c725612df5fb.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594156/9r39q87125e4a850e45dca227c725612df5fb.pdf)
[logo-4aabbf40-dfd4-414c-b028-aaa2f24a5704.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594157/logo-4aabbf40-dfd4-414c-b028-aaa2f24a5704.pdf)

[Web Application Overview_200119.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594158/Web.Application.Overview_200119.pdf)
[SHA256SUMS.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594159/SHA256SUMS.pdf)
[theme-ad554ad7-4888-4045-aa69-85ab6c221ad3.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594160/theme-ad554ad7-4888-4045-aa69-85ab6c221ad3.pdf)
[logo-67502d10-ce0d-49d7-b6eb-f92730f9a5c8.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594161/logo-67502d10-ce0d-49d7-b6eb-f92730f9a5c8.pdf)

[theme-a4ff6aee-3d75-48b5-b7f3-e47e7554c4af.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594162/theme-a4ff6aee-3d75-48b5-b7f3-e47e7554c4af.pdf)
[logo-5c94c7ea-d931-4069-9163-26ad05dd63d8.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594163/logo-5c94c7ea-d931-4069-9163-26ad05dd63d8.pdf)

[image006597.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594164/image006597.pdf)
[theme-274e165d-3a65-4f82-b585-9e3476f6ea66.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594165/theme-274e165d-3a65-4f82-b585-9e3476f6ea66.pdf)
[logo-391d0ea2-dd56-43fb-913e-c5c0af6ee5a3.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594166/logo-391d0ea2-dd56-43fb-913e-c5c0af6ee5a3.pdf)

[FCA approved MTFs, OTFs, DRSPs and notified SIs (1).xlsx](https://github.com/microsoft/azure-pipelines-image-generation/files/3594167/FCA.approved.MTFs.OTFs.DRSPs.and.notified.SIs.1.xlsx)

[logo-389687eb-ebc7-49ea-a485-d25c8c5088eb.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594168/logo-389687eb-ebc7-49ea-a485-d25c8c5088eb.pdf)
[logo-83108975-9cbb-4f5f-8f98-e7b9e69d4132.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594169/logo-83108975-9cbb-4f5f-8f98-e7b9e69d4132.pdf)
[theme-6d6c3966-0ef2-4da6-87c7-98ce2bc32313.pdf](https://github.com/microsoft/azure-pipelines-image-generation/files/3594170/theme-6d6c3966-0ef2-4da6-87c7-98ce2bc32313.pdf)

**Comment by bryanmacfarlane** [comment]
I've reported the spam ^^.  Leave for a bit then delete
