### ISSUE TITLE
Switch to Go 1.13 as default version

### ISSUE THREAD

**Issue by bishal-pdMSFT** [microsoft/azure-pipelines-image-generation#1219]
**Describe the bug**
Go 1.1.3 is added via PR but is not being made default as 1.13 has been released very recently. Switch to this version as default in near future

**Image impacted**
Ubunut16.04, Ubuntu 18.07, VS2017, VS2019

**Comment by kaylangan** [comment]
@bishal-pdMSFT Do you think we're good to make Go 1.13 the default? Seems like it's had a good amount of mileage at this point.
