### ISSUE TITLE
Update/Add the ubuntu 1604 cached image to the ubuntu 1604 hosted agent

### ISSUE THREAD

**Issue by StingyJack** [microsoft/azure-pipelines-image-generation#1220]
**Tool information**
Trying to pull the ubuntu 1604 base image takes long enough that the default build timeout is easily exceeded.   It just makes sense to include it as part of the ubuntu hosted agent

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [X ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
ubuntu 

**Workaround**
Its taking more than 20 minutes so far. I'm not sure how long it will ultimately take yet but 20 minutes is too long just to pull that image. 

**Are you willing to submit a PR?**
I would if I knew how to go about this.

**Comment by StingyJack** [comment]
@stale[bot] - go away. Few things are as community destructive as poorly conceived bots like you and your more evil relative, docker-desktop-robot.

**Comment by StingyJack** [comment]
Get deprogrammed stale bot

**Comment by maxim-lobanov** [comment]
Hello @StingyJack ,
This repository is not maintained anymore. According to the repository readme, please create the issue in [virtual-environments](https://github.com/actions/virtual-environments) repository.

**Comment by StingyJack** [comment]
@maxim-lobanov this issue was opened well before this repo moved. I didn't create it after. Whomever is maintainer just didn't do the responsible and ethical thing of moving the open issues, or at least have the common courtesy of notifying anyone with an open issue that it was moving.

**Comment by StingyJack** [comment]
The maintainer needs to move the open issues.
