### ISSUE TITLE
Rust self-update will block builds

### ISSUE THREAD

**Issue by alepauly** [microsoft/azure-pipelines-image-generation#1224]
Rust self-updates and permissions issues when a new Rust version comes out can unexpectedly fail builds. See [this](https://github.com/alexcrichton/jobserver-rs/runs/216328290) for example.

**Expected behavior**
Rust call succeeds even if an update is available.

**Actual behavior**
Call fails with:
```
error: could not remove 'setup' file: 'C:\Users\runneradmin\.cargo\bin/rustup-init.exe'
info: caused by: Access is denied. (os error 5)
```

**Image impacted**
VS2017 and VS2019

**Comment by alepauly** [comment]
not stale.

**Comment by kaylangan** [comment]
Closing in favor of: https://github.com/actions/virtual-environments/issues/246
