### ISSUE TITLE
Add Android emulator images

### ISSUE THREAD

**Issue by eric-labelle** [microsoft/azure-pipelines-image-generation#1225]
**Tool information**
- Tool name: android emulator images
- Add or update? Add
- Desired version: That would depend on the community. I'd expect the following ideally but some might have other needs.
```
- system-images;android-23;default;x86
- system-images;android-23;google_apis;x86
- system-images;android-24;google_apis;x86
- system-images;android-24;google_apis_playstore;x86
- system-images;android-25;google_apis;x86
- system-images;android-25;google_apis_playstore;x86
- system-images;android-26;google_apis;x86
- system-images;android-26;google_apis_playstore;x86
- system-images;android-27;google_apis;x86
- system-images;android-27;google_apis_playstore;x86
- system-images;android-28;default;x86
- system-images;android-28;google_apis;x86
- system-images;android-28;google_apis_playstore;x86
- system-images;android-29;google_apis;x86
- system-images;android-29;google_apis_playstore;x86

```
- If this is an add request:
  - Brief description of tool: These are all the system images used by the Android emulator
  - URL for tool's homepage: https://developer.android.com/studio/run/managing-avds

**Areas and ecosystems**
- [X] Android

**Image impacted**
Ideally, all images I would assume. But at least **macOS 10.14**

**Workaround**
Manually download and install the image every time the pipeline runs.

**Are you willing to submit a PR?**
Yes. Although I'm not sure how the osx images are generated. I can only find the linux and windows script and there is no contribution guide for OSX images.
--> Linux: /images/linux/scripts/installers/{1604-1804}/android.sh
--> Windows: /images/win/scripts/Installers/Update-AndroidSDK.ps

**Comment by sphanley** [comment]
Seconding this! I'm a developer on a large, enterprise project hosted in Azure DevOps and it would be super helpful to have these emulator images available.

**Comment by sphanley** [comment]
Commenting to keep this from being auto-closed, as I'm still hopeful you'll consider this request.

**Comment by jonsamwell** [comment]
Yep this would be great!

**Comment by eric-labelle** [comment]
New issue was created on the new repository https://github.com/actions/virtual-environments/issues/1509
