### ISSUE TITLE
Add Xcode 11 GM

### ISSUE THREAD

**Issue by diogot** [microsoft/azure-pipelines-image-generation#1230]
**Tool information**
- Tool name: Xcode
- Add or update? Add
- Desired version: 11 GM
- If this is an add request:
  - Brief description of tool: Golden Master version with support to iOS 13 SDK that can be used to submit builds with support to iOS to App Store
  - URL for tool's homepage: https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_11_GM_Seed/Xcode_11_GM_Seed.xip

**Areas and ecosystems**

- [X] iOS, macOS, and Apple-specific tools

**Image impacted**
macOS 10.14

**Workaround**
There is no workaround that I know of.

**Are you willing to submit a PR?**
I never did that before, but I can do it with some guidance.

**Comment by diogot** [comment]
Xcode 11 GM seed 2 it was just released:
https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_11_GM_Seed_2/Xcode_11_GM_Seed_2.xip

**Comment by max-lobanov** [comment]
@diogot, Mojave image was updated with `Xcode 11 GM seed 1`.
 
cc: @nrajpurkar

**Comment by diogot** [comment]
Oh, do this update just the documentation?
Is the updated image already available?

**Comment by max-lobanov** [comment]
Yes, the updated image is already available.
Documentation update is in progress.

**Comment by diogot** [comment]
Awesome, thanks!

**Comment by diogot** [comment]
Should I close this issue and open another to seed two or update this one?

**Comment by max-lobanov** [comment]
@diogot, Yes, please
