### ISSUE TITLE
Add Xcode 11 GM Seed 2

### ISSUE THREAD

**Issue by diogot** [microsoft/azure-pipelines-image-generation#1238]
**Tool information**
- Tool name: Xcode
- Add or update? Add
- Desired version: 11 GM Seed 2
- If this is an add request:
  - Brief description of tool: Golden Master version 2 with support to iOS 13 SDK that can be used to submit builds with support to iOS to App Store. The seed 1 can't be used to submit builds to App Store anymore.
  - URL for tool's homepage: https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_11_GM_Seed_2/Xcode_11_GM_Seed_2.xip

**Areas and ecosystems**

- [X] iOS, macOS, and Apple-specific tools

**Image impacted**
macOS 10.14

**Workaround**
There is no workaround.

**Comment by nrajpurkar** [comment]
Thanks for the issue @diogot, we're in the process of updating the agents to Xcode 11 GM 2 at the moment.

**Comment by diogot** [comment]
Awesome, thanks!

**Comment by meteorra** [comment]
@nrajpurkar , is there any news on when the update will be ready?

**Comment by max-lobanov** [comment]
@meteorra , the new image with `Xcode 11 GM seed 2` is deploying right now. Not sure how much time it will take

**Comment by max-lobanov** [comment]
@diogot, @meteorra , deployment is finished.
`Xcode 11 GM seed 2` is available on image.

**Comment by diogot** [comment]
Thanks!
