### ISSUE TITLE
Update Xamarin.iOS to 13

### ISSUE THREAD

**Issue by merckxite** [microsoft/azure-pipelines-image-generation#1239]
We're looking to build against the new Xcode 11 APIs with Xamarin.iOS 13. Latest version ([13.2.0.42](https://docs.microsoft.com/en-us/xamarin/ios/release-notes/13/13.2#september-18-2019---xamarinios-132042)) has support for > GM Seed 2. Cheers!

**Tool information**
- Tool name: Xamarin.iOS
- Add or update? Update
- Desired version: [13.2.0.42](https://docs.microsoft.com/en-us/xamarin/ios/release-notes/13/13.2#september-18-2019---xamarinios-132042)

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [x] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [x] Xamarin
- [ ] Other

**Image impacted**
macOS 10.14

**Are you willing to submit a PR?**
Yes, with direction

**Comment by merckxite** [comment]
[13.2.0.42](https://docs.microsoft.com/en-us/xamarin/ios/release-notes/13/13.2#september-18-2019---xamarinios-132042) is now the latest release version of Xamarin.iOS

**Comment by nrajpurkar** [comment]
Hey @merckxite, we're working on getting that version into our images at the moment. You should see this in the next deployment.

**Comment by maxim-lobanov** [comment]
@merckxite , @nrajpurkar , Image deployment has finished.
The following bundle is available on VM images:
```
Symlink: '6_4_0'
Mono: '6.4.0.198'
Xamarin.iOS: '13.2.0.42'
Xamarin.Android: '10.0.0.43'
Xamarin.Mac: '6.2.0.42'
```
