### ISSUE TITLE
Add Xcode 11

### ISSUE THREAD

**Issue by valeriy-kolodiy** [microsoft/azure-pipelines-image-generation#1254]
**Tool information**
- Tool name: Xcode
- Add or update? Add
- Desired version: 11
- If this is an add request:
  - Brief description of tool: Xcode 11 includes Swift 5.1 and SDKs for iOS 13, tvOS 13, watchOS 6, and macOS Catalina 10.15
  - URL for tool's homepage: https://apps.apple.com/ua/app/xcode/id497799835

**Areas and ecosystems**
- [x]  iOS, macOS, and Apple-specific tools

**Image impacted**
macOS 10.14
macOS 10.15

**Comment by max-lobanov** [comment]
@valeriy-kolodiy , Xcode 11.0 is already available on macOS 10.14 (Mojave) image.
Please find the list of all available Xcode versions in [docs](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md#xcode).

`Xcode 11.0 GM seed 2` was released as a final version of Xcode 11.0.

**Comment by maxim-lobanov** [comment]
Docs were updated. `macOS 10.14` (Mojave) contains `Xcode 11.0`.
I am closing the issue. Feel free to reopen it if you have any questions
