### ISSUE TITLE
Update Visual Studio 2019 to 16.3.0

### ISSUE THREAD

**Issue by joaopgrassi** [microsoft/azure-pipelines-image-generation#1260]
**Tool information**
- Visual Studio
- Update
- 16.3.0 (latest)

**Areas and ecosystems**
- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [x] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
windows-latest OR windows-2019 as seen here: [Use a Microsoft-hosted agent](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent)

*Description of the issue*

After upgrading our solution to use Entity Framework 6.3, and migrated the project to use the new SDK style running migrations fails with: `System.Resources.MissingManifestResourceException`. I have opened an issue over on EF repo [here](https://github.com/aspnet/EntityFramework6/issues/1269) and you can check all the related issues from there. For instance, this one on `msbuild` https://github.com/microsoft/msbuild/issues/4695 is probably the culprit.

The same issue was happening on my local machine, but after updating Visual Studio to version 16.3.0 the migrations commands work again as normal since it uses now a new version of MSBuild.

**Comment by glennawatson** [comment]
I believe this is related to #1256

**Comment by BM78** [comment]
Similarly, C# 8 features are still considered 'in Preview' and cause issues, e.g. 
```The feature 'recursive patterns' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.```

**Comment by joaopgrassi** [comment]
We got the new version now in our agents.. so I'm going to close this. Thanks!
