### ISSUE TITLE
No current user owned `${XDG_CONFIG_HOME}` (aka `${HOME}/.config`) directory

### ISSUE THREAD

**Issue by ivailop** [microsoft/azure-pipelines-image-generation#1271]
**Describe the bug**
The hosted "Ubuntu 16.04" image has no current user owned `${XDG_CONFIG_HOME}` (aka `${HOME}/.config`) directory.

**Expected behavior**
Have existing `${XDG_CONFIG_HOME}` (aka `${HOME}/.config`) pre-created with current user (i.e. `vsts`) being the owner of it.

**Actual behavior**
`${XDG_CONFIG_HOME}` (aka `${HOME}/.config`) directory does not exist. As being a de-facto location for storing user-specific configuration, installing dependencies using `sudo` would automatically create it with `root` being the owner of it. Subsequent non-sudo access to it would fail with `Permission denied`.

To reproduce:
```
- script: |
    ls -lsa ~/.config # -> ls: cannot access '/home/vsts/.config': No such file or directory
    sudo npm install -g eslint
    ls -lsa ~/.config # -> ls: cannot open directory '/home/vsts/.config': Permission denied
```

**Image impacted**
Ubuntu 16.04

**Comment by ivailop** [comment]
I think this issue is still relevant and would be good to be addressed appropriately.

**Comment by alepauly** [comment]
Moved here: https://github.com/actions/virtual-environments/issues/491, sorry for the delay.
