### ISSUE TITLE
Update/Add SQL Server Data Tools to windows-2019

### ISSUE THREAD

**Issue by nprieto95** [microsoft/azure-pipelines-image-generation#1274]
**Tool information**
- Tool name: SQL Server Data Tools
- Add or update? Add
- Desired version: 16.x
- If this is an add request:
  - Brief description of tool: SQL Server Data Tools is a modern development tool for building SQL Server relational databases, Azure SQL databases, Analysis Services (AS) data models, Integration Services (IS) packages, and Reporting Services (RS) reports.
  - URL for tool's homepage: https://docs.microsoft.com/en-us/sql/ssdt/download-sql-server-data-tools-ssdt?view=sql-server-ver15

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [X] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
windows-2019

**Workaround**
There might be a way to install it during the build but it would probably be very difficult and expensive.

**Are you willing to submit a PR?**
I have the will to do it but lack the knowledge. Open to learning.

**Comment by bbakermmc** [comment]
Isnt SSDT installed by default with 2019?

> Changes in SSDT for Visual Studio 2019
> 
> With Visual Studio 2019, the required functionality to enable Analysis Services, Integration Services, and Reporting Services projects has moved into the respective Visual Studio extensions. The core SSDT functionality to create Database Projects has remained integral to Visual Studio (you need to select the Data storage, and processing workload during install). There's no more standalone SSDT installation required.


The installer says install all workloads.  I know the host versions have SSDT support, in the middle of rolling our own server but I dont see why it wouldnt be there.
$WorkLoads = '--allWorkloads --includeRecommended ' + `
              '--add Component.Dotfuscator ' + `
              '--add Component.Linux.CMake ' + `
              '--add Component.UnityEngine.x64 ' + `
              '--add Component.UnityEngine.x86 ' + `
              '--add Component.Unreal.Android ' + `
              '--add Microsoft.Component.Azure.DataLake.Tools ' + `
              '--add Microsoft.Component.CookiecutterTools ' + `
              '--add Microsoft.Component.PythonTools.Miniconda ' + `
              '--add Microsoft.Component.PythonTools.Web ' + `
              '--add Microsoft.Component.VC.Runtime.UCRTSDK ' + `
              '--add Microsoft.Net.ComponentGroup.4.6.2.DeveloperTools ' + `
              '--add Microsoft.Net.ComponentGroup.4.7.1.DeveloperTools ' + `
              '--add Microsoft.Net.ComponentGroup.4.7.DeveloperTools ' + `
              '--add Microsoft.VisualStudio.Component.AspNet45 ' + `
              '--add Microsoft.VisualStudio.Component.Azure.Kubernetes.Tools ' + `
              '--add Microsoft.VisualStudio.Component.Azure.MobileAppsSdk ' + `
              '--add Microsoft.VisualStudio.Component.Azure.ServiceFabric.Tools ' + `
              '--add Microsoft.VisualStudio.Component.Azure.Storage.AzCopy ' + `
              '--add Microsoft.VisualStudio.Component.Debugger.JustInTime ' + `
              '--add Microsoft.VisualStudio.Component.DslTools ' + `
              '--add Microsoft.VisualStudio.Component.EntityFramework ' + `
              '--add Microsoft.VisualStudio.Component.FSharp.Desktop ' + `
              '--add Microsoft.VisualStudio.Component.LinqToSql ' + `
              '--add Microsoft.VisualStudio.Component.PortableLibrary ' + `
              '--add Microsoft.VisualStudio.Component.TeamOffice ' + `
              '--add Microsoft.VisualStudio.Component.TestTools.CodedUITest ' + `
              '--add Microsoft.VisualStudio.Component.TestTools.WebLoadTest ' + `
              '--add Microsoft.VisualStudio.Component.UWP.VC.ARM64 ' + `
              '--add Microsoft.VisualStudio.Component.VC.ATL.ARM ' + `
              '--add Microsoft.VisualStudio.Component.VC.ATLMFC ' + `
              '--add Microsoft.VisualStudio.Component.VC.ATLMFC.Spectre ' + `
              '--add Microsoft.VisualStudio.Component.VC.CLI.Support ' + `
              '--add Microsoft.VisualStudio.Component.VC.CMake.Project ' + `
              '--add Microsoft.VisualStudio.Component.VC.DiagnosticTools ' + `
              '--add Microsoft.VisualStudio.Component.VC.MFC.ARM ' + `
              '--add Microsoft.VisualStudio.Component.VC.MFC.ARM.Spectre ' + `
              '--add Microsoft.VisualStudio.Component.VC.MFC.ARM64 ' + `
              '--add Microsoft.VisualStudio.Component.VC.MFC.ARM64.Spectre ' + `
              '--add Microsoft.VisualStudio.Component.VC.Runtimes.ARM.Spectre ' + `
              '--add Microsoft.VisualStudio.Component.VC.Runtimes.ARM64.Spectre ' + `
              '--add Microsoft.VisualStudio.Component.VC.Runtimes.x86.x64.Spectre ' + `
              '--add Microsoft.VisualStudio.Component.VC.TestAdapterForBoostTest ' + `
              '--add Microsoft.VisualStudio.Component.VC.TestAdapterForGoogleTest ' + `
              '--add Microsoft.VisualStudio.Component.VC.v141 ' + `
              '--add Microsoft.VisualStudio.Component.Windows10SDK.16299 ' + `
              '--add Microsoft.VisualStudio.Component.Windows10SDK.17134 ' + `
              '--add Microsoft.VisualStudio.Component.Windows10SDK.17763 ' + `
              '--add Microsoft.VisualStudio.Component.Windows10SDK.18362 ' + `
              '--add Microsoft.VisualStudio.ComponentGroup.Azure.CloudServices ' + `
              '--add Microsoft.VisualStudio.ComponentGroup.Azure.ResourceManager.Tools ' + `
              '--add Microsoft.VisualStudio.ComponentGroup.Web.CloudTools ' + `
              '--add Microsoft.VisualStudio.Workload.Azure ' + `
              '--add Microsoft.VisualStudio.Workload.Data ' + `
              '--add Microsoft.VisualStudio.Workload.DataScience ' + `
              '--add Microsoft.VisualStudio.Workload.ManagedDesktop ' + `
              '--add Microsoft.VisualStudio.Workload.ManagedGame ' + `
              '--add Microsoft.VisualStudio.Workload.NativeCrossPlat ' + `
              '--add Microsoft.VisualStudio.Workload.NativeDesktop ' + `
              '--add Microsoft.VisualStudio.Workload.NativeGame ' + `
              '--add Microsoft.VisualStudio.Workload.NativeMobile ' + `
              '--add Microsoft.VisualStudio.Workload.NetCoreTools ' + `
              '--add Microsoft.VisualStudio.Workload.NetCrossPlat ' + `
              '--add Microsoft.VisualStudio.Workload.NetWeb ' + `
              '--add Microsoft.VisualStudio.Workload.Node ' + `
              '--add Microsoft.VisualStudio.Workload.Office ' + `
              '--add Microsoft.VisualStudio.Workload.Python ' + `
              '--remove Component.CPython3.x64 ' + `
              '--add Microsoft.VisualStudio.Workload.Universal ' + `
              '--add Microsoft.VisualStudio.Workload.VisualStudioExtension'

**Comment by AlexKeySmith** [comment]
+1 from me. Also it would be super handy if when this is installed that it's the one compatible with SQL Datawarehouse. 

https://docs.microsoft.com/en-us/azure/sql-data-warehouse/sql-data-warehouse-install-visual-studio
