### ISSUE TITLE
Add macOS 10.15

### ISSUE THREAD

**Issue by coder3101** [microsoft/azure-pipelines-image-generation#1277]
XCode 11 comes with new Apple Clang Compiler that fully supports C++17 features including library features such as `std::filesystem` but unfortunately the older image macOS 10.14 does not have some library features implemented such as `std::filesystem::path`. AppleClang 11 reports that this was added in macOS 10.15. It would be great if this new image is added so that we could fully utilize the features offered by XCode11 toolchains

**Tool information**
- Tool name: macOS 10.15
- Add or update? add
- Desired version: 10.15

**Areas and ecosystems**

- [ ] Android
- [x] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [x] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
macOS 10.15

**Workaround**
No

**Are you willing to submit a PR?**
Yes

**Comment by diogot** [comment]
We should adopt macOS 10.15 later this month, so have it available on CI will make things much easier.

**Comment by nrajpurkar** [comment]
Hi @diogot, we'll be working to support Catalina soon but don't have an ETA to share at this time.

**Comment by nrajpurkar** [comment]
Hi @ladislas, no ETA at the moment.

**Comment by SeanAsby** [comment]
We also rely on Azure build pipelines for CI, and are unable to build mac catalyst versions of our SDKs and apps because of not having macOS 10.15 available. This is a big blocker for us since it is basically preventing us from shipping those versions of our products.

**Comment by rob8861** [comment]
over 85% of our user base has adopted iOS 13. Not only that you don't support Mac OS Catalina, you also don't support XCode 11, which prevents us from migrating.
This is ridicules. Every CI/CD competitor has already adopted both.
Can we please get an updated ETA on this issue

Thanks,

**Comment by MaxDesiatov** [comment]
Xcode 11 and all its stable patch versions are actually available in the 10.14 image as shown in [this list](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md#xcode).

**Comment by SeanAsby** [comment]
> over 85% of our user base has adopted iOS 13. Not only that you don't support Mac OS Catalina, you also don't support XCode 11, which prevents us from migrating.
> This is ridicules. Every CI/CD competitor has already adopted both.
> Can we please get an updated ETA on this issue
> 
> Thanks,

You can set Xcode version to `Specify Path`, then set `Xcode developer path` to `/Applications/Xcode_11.2.1.app/Contents/Developer` to use the latest version of Xcode in your build pipeline.

**Comment by coder3101** [comment]
> You can set Xcode version to `Specify Path`, then set `Xcode developer path` to `/Applications/Xcode_11.2.1.app/Contents/Developer` to use the latest version of Xcode in your build pipeline.

As mentioned in the issue the full potentials of this tool-chain (Xcode 11) is limited by macOS 10.14. The problem is the version of the operating system and not the tool-chain.

For instance see [this](https://github.com/coder3101/licenser/blob/ed3ce624cfb5d0c89f25243dae9a366f11aea197/azure-pipelines.yml#L140), it uses correct toolchain that supports the feature but the build logs report that tool-chain requires macOS 10.15

**Comment by henkrehorst** [comment]
Any news or timeframe? 🙂

**Comment by nrajpurkar** [comment]
@henkrehorst no timeline to report just yet, but we're actively working on firming up news at the moment. We'll be sure to update the thread when we have details.

**Comment by tskippervold** [comment]
For now, it works by using macos 10.14 and specify to use `/Applications/Xcode_11.3.app` 👍

**Comment by lloeki** [comment]
> For now, it works by using macos 10.14 and specify to use /Applications/Xcode_11.3.app 👍

Only if you want to use that for iOS 13, but if you want to test that macOS software actually operates correctly on 10.15 you're out of luck.

**Comment by karimhm** [comment]
> For now, it works by using macos 10.14 and specify to use `/Applications/Xcode_11.3.app` 👍

How you did that, what is the variable name?
Thanks in advance .

**Comment by janten** [comment]
@nrajpurkar With macOS 10.15 now available for GitHub Actions, is there any news for Azure DevOps?

**Comment by nrajpurkar** [comment]
@janten we're working up some details to share of 10.15 support coming to Azure DevOps. We'll share that out soon!

**Comment by tristanmason** [comment]
@nrajpurkar Anxiously awaiting this! Thanks!

**Comment by PatrickGaissert** [comment]
+1

**Comment by lloeki** [comment]
So, does [that](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.15-Readme.md) mean 10.15 is good to go?

**Comment by nilofer** [comment]
@lloeki yes, 10.15 is available for use! Closing out this issue.
