### ISSUE TITLE
The confusing and less informative YAML agent image names started showing up in build pipelines dropdown list

### ISSUE THREAD

**Issue by StingyJack** [microsoft/azure-pipelines-image-generation#1287]
I was asked to transfer this report https://github.com/MicrosoftDocs/vsts-docs/issues/5828 to here. 

This list is now less clear and is confusing where it was not before. The YAML names do not include the version of visual studio used. I have had to field questions about it at least three times in the last day from coworkers about "where is the VS 2019 option?" and "We can only use VS 2017 now?"

Nobody should have to go look up the docs pages to figure out something that was plain and obvious before.  Software and user experience should be improved with a change, not worsened.  This was not confusing before, but it sure is now.

As this came without any advance notice on or near that UI component, I'm reporting this as a bug. Also in the hope it was accidental and someone didnt make a noobish/snobbish choice on purpose.

**Comment by StingyJack** [comment]
@kaylangan - 9 days later, it appears the assignees are clearly too busy to tend to correcting this simple issue.

To get the regression addressed in a timely manner, please assign someone who has time, or just rollback whatever change created this unexpected, unwanted, and confusing result.

If enough people can't be allocated to address this, then it can only be because you have many large fires burning because regressions should not be happening. (Hopefully one of those fires is restoring the build history and version control labels that were deleted en masse and without warning by the bungled "streamlining" of build retention settings, but I doubt that is the case). 

Thanks in advance for your assistance!

**Comment by vijayma** [comment]
Andrew, here is the [release notes](https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-154-update#single-hosted-pool) that talked about this change. It was done to avoid huge confusion about how parallel jobs are consumed and shared across all the different images in the hosted pool. The one activity that we do have on our backlog is to show the information about what each image has. We will be picking that up soon.

**Comment by StingyJack** [comment]
@vijayma - I get that you did a pool consolidation in an attempt to remove confusion, but what resulted was that one confusion was replaced with a more immediate confusion and then had some more on top with the surprise of it.

Before I may have scratched my head a bit about why a build is still queued, but everyone still would always know exactly what build agent to pick.

If you were planning to fix the names then this feature was incomplete when delivered. Fixing the names should have been a trivial inclusion.

You guys _almost_ , _sometimes_ have the right idea with the way to communicate upcoming changes. There should have been a note right on the related pages in DevOps that explains and depicts the proposed change. If you really want to do it right, you would send a separate notification to project and build administrators informing them of what you are proposing  and accepting the risk that those stakeholders might shoot it down.

**Comment by vijayma** [comment]
1. Two out of three windows images with vs version in their names: vs2015-win2012r2, vs2017-win2016, and windows-2019. We will add an alias called vs2019-win2019 to the last one.

2. We are doing more and more specs and development in the open. Here are two repos where you will find specs for some of the larger features that we are working on:
https://github.com/microsoft/azure-pipelines-yaml/tree/master/design
https://github.com/microsoft/azure-pipelines-agent/tree/master/docs/design
You can submit PRs or raise issues on these repos.

**Comment by azureDaveOps** [comment]
@StingyJack based on the amount of feedback you provide, you should definitely read the release notes each sprint.  I think it would save you a lot of headache.

**Comment by StingyJack** [comment]
@vijayma - you had friendly names already. Based on the overall experience regarding this, I dont get the impression that this was specifically planned and expected to happen. I'm not really interested in learning how to do yaml builds, If i wanted that kind of experience I would be programming in notepad all day.

@azureDaveOps - the thing reported in this issue is not in the release notes linked. 

Generally speaking release notes contain a bunch of things I'm not using/need to use that I have to sort through. They are published on a schedule I am not familiar with. The schedule for release notes and deployments doesnt generally align with my availability to read and digest the release notes and make arrangements that the update may require along with completing work I already had in progress. 

Also release notes are always too late because by the time they are available to me, you have already expended time and effort into something and arent going to want to make alterations or withdraw it, and I'm going to be stuck with whatever it is, however useful or not it is, however detrimental or not it is. (they are also too late because I think we are on the outermost ring for deployments, so anything enabled for us today has been in prod for others for weeks).

My suggestions resolve all those problems and the headache, and could be as simple as a "Gold Bar" notice for whatever affected pages with a link that describes what is being proposed and voting options.  

> based on the amount of feedback you provide,
The amount of feedback I provide hasn't been measureable by the feeedback tools shortly after reporting issue number 280 or so.  The actual total last time I checked was over 600 (not counting GH issues),

**Comment by StingyJack** [comment]
1 month with no comment or response proves a point; we can give you all the feedback we can but you aren't listening to the most important feedback - the feedback that shows you where you have made a mistake. Failure is the best teacher, feeding a confirmation bias teaches nothing of value.
