### ISSUE TITLE
boost\geometry.hpp is missing from VS2017 image

### ISSUE THREAD

**Issue by alarobric** [microsoft/azure-pipelines-image-generation#1288]
**Describe the bug**
File boost\geometry.hpp is missing from the Hosted VS2017 image, causing build failures

**Expected behavior**
Since boost 1.69 is included in the image, expect all files to be included and usable in a build.

**Actual behavior**
Error C1083: Cannot open include file: 'boost\geometry.hpp': No such file or directory

Running a test script step in the build to list files in the directory confirms that it is missing. Why is the boost folder included in the image different than if I download a fresh copy of boost from boost.org?
> tree $env:BOOST_ROOT\boost /F

**Image impacted**
VS2017 Windows

**Comment by alarobric** [comment]
I've now noticed that there is an include folder containing these missing headers.
What is the reason for moving the boost code normally found under boost\* to include\*?
Similarly, we had to introduce some symlinks in our build to get around boost libs being under lib\* not stage\lib\* as is documented by boost.
Can these deviations from boost documentation be documented in the pipeline documentation somewhere at least so we don't have to find them out the hard way?

**Comment by AlenaSviridenko** [comment]
Hi @alarobric !
We have investigated this issue, you should use
`BOOST_ROOT\include\boost\geometry.hpp` location and add  `BOOST_ROOT\include` to the headers search path. 

Thank you for the notice about Boost documentation, we definitely should have it and currently we are looking for a correct place for it.

please, let me know if you have any questions.
