### ISSUE TITLE
Add Script To Add To Pool

### ISSUE THREAD

**Issue by bbakermmc** [microsoft/azure-pipelines-image-generation#1290]
Can you add a script where we can enter the info to add the server to an azure pipeline pool so we dont need to login and do this.
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops

**Areas and ecosystems**
DevOps
- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
None
**Workaround**
No
**Are you willing to submit a PR?**
No

**Comment by kaylangan** [comment]
I'm not sure I understand what you're asking for. Can you explain your scenario more fully? If you're using self-hosted agents, you'll need to log in to manage them.

**Comment by bbakermmc** [comment]
@kaylangan Add the azure build agent and provide a helper script to add the VM to one of our pools.  This way we dont need need to login to the VM to configure it.

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops
