### ISSUE TITLE
Add Prebuilt Images

### ISSUE THREAD

**Issue by bbakermmc** [microsoft/azure-pipelines-image-generation#1291]
There is a lot of overhead in building this custom image.  Why cant you guys just release the images to the gallery so when we want a new VM we can just choose the image.  I understand if we want custom versions, but the stock version works well in most cases.

**Comment by kaylangan** [comment]
Are you using this repo to build the image for your own self-hosted VMs? Or are you using Azure Pipelines hosted VMs? I'm not sure I understand the "so when we want a new VM we can just choose the image. I understand if we want custom versions, but the stock version works well in most cases".

**Comment by bbakermmc** [comment]
@kaylangan We use both, but MS offers a store where you can upload pre-buillt images so I can say I have a new vm and I want it preinstalled with SQL Server 2019, etc.  Why cant these images be pre built and put there?   

It should be in the public images.
![image](https://user-images.githubusercontent.com/30090055/66172183-d6de3080-e618-11e9-93ab-619c0fb9a639.png)

**Comment by bbakermmc** [comment]
@kaylangan Unless you have a way for the private paid build hosts to access things on our private network with a VPN/managed instatnce

**Comment by kaylangan** [comment]
Got it. I understand now. We've considered this, but it's not a priority at the moment.

**Comment by bbakermmc** [comment]
@kaylangan should be I assume you guys use the same image, should be easy to automate putting on your store so people can use it and you get more $$

**Comment by kaylangan** [comment]
There are licensing and distribution considerations and we need to make sure we're legally compliant. 🙂

**Comment by bbakermmc** [comment]
Dont you still face them now :)  It just takes someone a few hours to wait for it to build.

**Comment by kaylangan** [comment]
They're similar scenarios, but not quite the same so the legal considerations are different.

**Comment by baatch** [comment]
I was also looking for the same. I have many customers asking why it is not in the public gallery. 

Can you comment on what the legal considerations are so that we and all the customers can better understand what the blocking issue is?

**Comment by bbakermmc** [comment]
@kaylangan Why do public repo get access to 10 build servers, yet private get 0.  And even when you pay you only really get 1,  it just removes the time limited of the 1 free one everyone gets.  Seem like if I'm giving you money I should get MORE than what I could get for free right ....
