### ISSUE TITLE
Pre-built boost is missing zlib support

### ISSUE THREAD

**Issue by alarobric** [microsoft/azure-pipelines-image-generation#1294]
**Tool information**
- Tool name: Boost
- Add or update? Update
Pre-built Boost 1.69 is available on the hosted agents, however the zlib support is missing. For instance, I get build errors like 
`Error LNK1104: cannot open file 'libboost_zlib-vc141-mt-x32-1_69.lib'"`

Can zlib support be added to the boost build as per boost documentation?

**Areas and ecosystems**

- [ ] Android
- [x] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
VS2017, VS2019

**Workaround**
No?

**Are you willing to submit a PR?**
If technically possible, sure. I think the pre-built libs comes from outside this repo though?

**Comment by greglandrum** [comment]
This would be really, really helpful
