### ISSUE TITLE
CocoaPods in MacOS 10.14 agent updated to 1.8.1 without notice

### ISSUE THREAD

**Issue by ronplanken** [microsoft/azure-pipelines-image-generation#1303]
**Describe the bug**
When running our pipelines on the macOS-10.14 agent yesterday we had version 1.7.5 of the CocoaPods running. After we did a build today the builds suddenly started failing. After some debugging we noticed that CocoaPods were updated to 1.8.1 without any notice or changelog. 

**Expected behavior**
We expect the macOS agent to stay on version 1.7.5 untill we can actually upgrade our project to use CocoaPods 1.8.1.

**Actual behavior**
Create a new pipeline with the macOS-10.14 and add a CocoaPods step. This step will use version 1.8.1

Yesterday:
```
/usr/local/lib/ruby/gems/2.6.0/bin/pod --version
1.7.5
```

Today:
```
/usr/local/lib/ruby/gems/2.6.0/bin/pod --version
1.8.1
```

**Comment by SimonGolms** [comment]
Had the same issue and found this workaround https://github.com/microsoft/appcenter-sdk-cordova/issues/118#issuecomment-540397102

```
sudo gem uninstall cocoapods
sudo gem install cocoapods -v 1.7.5
pod setup
```

**Comment by ronplanken** [comment]
Not really a proper solution unfortunatly, this easily adds 15 minutes to the whole build pipeline!

**Comment by DominicBoettger** [comment]
This is a major problem for cordova based projects as it will not work with 1.8.
