### ISSUE TITLE
Documentation - Updates/Azure pipeline config

### ISSUE THREAD

**Issue by bbakermmc** [microsoft/azure-pipelines-image-generation#1304]
Can you provide details on how we should go about redeploying these images when there are updates.  It would also probably be beneficial if you could provide a walk thru on how to automate some of this in Pipelines.

Things like:
Check Repo for available Update -> Trigger build of vmdk.
Scripts To Add To Domain
Script To Add To Azure Build Pools

**Comment by timoline** [comment]
I'm also very interested in this, 

Why isn't this image-generation in a pipeline yet, or how can we do that?
Why not using DSC for machine configuration ?
