### ISSUE TITLE
Documentation for VS-2019 is incomplete re: supported .NET Core versions

### ISSUE THREAD

**Issue by laynew** [microsoft/azure-pipelines-image-generation#1307]
**Describe the bug**
I believe the documentation or the VS-2019 image is incomplete. According to the documentation the latest supported version of .NET Core is 2.2.105. However I was able to build a project with 3.0.100 using this image.

**Expected behavior**
The documentation for the image should indicate that .NET Core 3.x.x is supported

**Actual behavior**
The documentation indicates that  2.2.105 is the latest supported version

**Image impacted**
`images/win/Vs2019-Server2019-Readme.md`

**Comment by alepauly** [comment]
Verified that the docs are missing info. Also affects Ubuntu images

**Comment by hiyadav** [comment]
Thanks for pointing that out. @alepauly can you let me know if the doc files need to be updated manually or should they be updated using generated doc files from the production build ?

**Comment by alepauly** [comment]
> 
> 
> Thanks for pointing that out. @alepauly can you let me know if the doc files need to be updated manually or should they be updated using generated doc files from the production build ?

@hiyadav The docs should be autogenerated and not updated manually. I think the scripts that install dotnet core and generate the output have some bugs since they are missing the latest. We should fix the scripts.

**Comment by simonauner** [comment]
Same issue as https://github.com/microsoft/azure-pipelines-image-generation/issues/1301 (if you want to close either as duplicate)

**Comment by hiyadav** [comment]
We are working on it. PR should be merged soon.

**Comment by hiyadav** [comment]
We have updated the installer scripts for both Windows and Linux images, and should start reflecting latest SDK's (in image and documentation) from next release.
