### ISSUE TITLE
Ubuntu1804-README.md is empty...

### ISSUE THREAD

**Issue by tusharb86** [microsoft/azure-pipelines-image-generation#1313]
**Describe the bug**
The readme file for the Ubuntu 18.04 image is empty. It would be great to know what versions of specific packages are available:
https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/linux/Ubuntu1804-README.md

**Expected behavior**
I expected to see a full list of packages installed on the Ubuntu 18.04 image just like the page for Ubuntu 16.04:
https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/linux/Ubuntu1604-README.md

[UbuntuReadmes.zip](https://github.com/microsoft/azure-pipelines-image-generation/files/3719990/UbuntuReadmes.zip)

**Comment by kaylangan** [comment]
Should be fixed now! Thanks for the patience.
