### ISSUE TITLE
Add Python 3.8

### ISSUE THREAD

**Issue by vtbassmatt** [microsoft/azure-pipelines-image-generation#1317]
**Tool information**
- Tool name: Python
- Add or update? Add
- Desired version: 3.8
- If this is an add request:
  - Brief description of tool: Python 3.8 just GA'd
  - URL for tool's homepage: https://python.org

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [x] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
Add the appropriate label for the image or images that should be updated (e.g., macOS 10.13, macOS 10.14, ubuntu, VS2017, VS2019, WINCON).
- macOS-10.13
- macOS-10.14
- VS2017
- VS2019
- ubuntu-16.04
- ubuntu-18.04

**Workaround**
Not really - it takes 30+ minutes to build and install Python on Windows

**Are you willing to submit a PR?**
sure

**Comment by lmazuel** [comment]
Hello, I did a thumb but I want to emphasize that Python 3.8 being released yesterday, it's the new default for a tons of people, and having CI to ensure our product are compatible is really important.
Thanks !!!

**Comment by henryiii** [comment]
I'm using Azure to build wheels for the packages in Scikit-HEP, and Windows wheels depend on the built-in Pythons - would be great to have this in Azure so I can build 3.8 wheels! I also have a popular post on building wheels in Azure. (macOS has to download installers anyway, and linux uses ManyLinux docker). Also needed for test pipelines, which use these.

**Comment by hugovk** [comment]
> I also have a popular post on building wheels in Azure.

Please could you share the link? Thanks!

**Comment by henryiii** [comment]
@hugovk, sure: https://iscinumpy.gitlab.io/categories/azure-devops/

**Comment by laike9m** [comment]
Can someone help me confirm whether 3.8 has been offically supported in Azure pipelines? Appreciate it 🙏

**Comment by kaylangan** [comment]
We have finished the feature but haven't fully deployed yet

**Comment by laike9m** [comment]
> We have finished the feature but haven't fully deployed yet

Thanks for confirming. May I ask the ETA for deployment?

**Comment by jiasli** [comment]
Has the image been deployed? Azure CLI's CI is already showing

```
==============================================================================
Task         : Use Python version
Description  : Use the specified version of Python from the tool cache, optionally adding it to the PATH
Version      : 0.151.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/use-python-version
==============================================================================
Found tool in cache: Python 3.8.0 x64
Prepending PATH environment variable with directory: /Users/runner/hostedtoolcache/Python/3.8.0/x64
Prepending PATH environment variable with directory: /Users/runner/hostedtoolcache/Python/3.8.0/x64/bin
```

**Comment by hugovk** [comment]
Not yet, or not fully, I get:
```
##[section]Starting: UsePythonVersion
==============================================================================
Task         : Use Python version
Description  : Use the specified version of Python from the tool cache, optionally adding it to the PATH
Version      : 0.151.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/use-python-version
==============================================================================
##[error]Version spec 3.8 for architecture x64 did not match any version in Agent.ToolsDirectory.
Versions in C:/hostedtoolcache/windows:
2.7.16 (x86)
3.4.4 (x86)
3.5.4 (x86)
3.6.8 (x86)
3.7.4 (x86)
2.7.16 (x64)
3.4.4 (x64)
3.5.4 (x64)
3.6.8 (x64)
3.7.4 (x64)
If this is a Microsoft-hosted agent, check that this image supports side-by-side versions of Python at https://aka.ms/hosted-agent-software.
If this is a self-hosted agent, see how to configure side-by-side Python versions at https://go.microsoft.com/fwlink/?linkid=871498.
##[section]Finishing: UsePythonVersion
```
(Ubuntu, get similar with macOS and Windows.)

**Comment by asvetlov** [comment]
BTW, would you consider upgrading PyPy as well: #1363

**Comment by vtbassmatt** [comment]
@asvetlov and others: since this was my first time altering the Python packages on the image, I'd like to wait til it's fully deployed. Assuming it goes through without a hitch, then I will be happy to upgrade PyPy :)

**Comment by asvetlov** [comment]
Thanks, your position is pretty understandable.

**Comment by njsmith** [comment]
@vtbassmatt @kaylangan Thanks for working on this!

So it sounds like the status is that right now, the new image with py38 is getting incrementally deployed across the fleet, so some builds will see it and some won't? Is that right? And is there any way for outsiders to track the progress of that deployment without hassling you for updates? I think what makes people antsy isn't the slowness *per se*, but that the process is so opaque it's hard to tell what's happening.

**Comment by laike9m** [comment]
> @vtbassmatt @kaylangan Thanks for working on this!
> 
> So it sounds like the status is that right now, the new image with py38 is getting incrementally deployed across the fleet, so some builds will see it and some won't? Is that right? And is there any way for outsiders to track the progress of that deployment without hassling you for updates? I think what makes people antsy isn't the slowness _per se_, but that the process is so opaque it's hard to tell what's happening.

Totally agree

**Comment by kaylangan** [comment]
We're currently working on an external status page, but we don't have anything more official than comments yet 😕

**Comment by clinton-hall** [comment]
@vtbassmatt @kaylangan 
Thanks for the support... Python 3.8 working for me on vmImage: 'Ubuntu-16.04'

**Comment by hugovk** [comment]
Confirmed available on `Ubuntu-18.04` and `xcode9-macos10.13` but not yet `vs2017-win2016`:

* https://github.com/hugovk/pypistats/pull/82/checks?check_run_id=293898406

**Comment by vtbassmatt** [comment]
I think we're close enough to full rollout that I can close this issue. It may still be a few days before 100% of the service sees it.

**Comment by laike9m** [comment]
@vtbassmatt My 3.8 tests fail on Windows & Mac, 
https://dev.azure.com/laike9m/laike9m/_build/results?buildId=87
Somehow it's using Linux command on Windows & Mac. I'm not sure what the root cause is.

**Comment by vtbassmatt** [comment]
The problem seems to be in [the template](https://github.com/tox-dev/azure-pipelines-template/blob/b0e7a6f5d7aa2bd11fdf046d0081f686ad35b54b/run-tox-env.yml#L91) which special-cases `py38`. It appears to be [fixed in `master`](https://github.com/tox-dev/azure-pipelines-template/blob/f1f14589b8c4f809cb07b07a7824a8ca0e1a82c3/run-tox-env.yml#L89) so  consider updating the [`ref` in your pipeline](https://github.com/laike9m/Cyberbrain/blob/02e0a9e1b823ed0c793409e4e7c28456d6ce0059/azure-pipelines.yml#L11).

**Comment by laike9m** [comment]
Thanks so much, issue solved 😁
