### ISSUE TITLE
Update Python 3.7.4 to 3.7.5

### ISSUE THREAD

**Issue by kaylangan** [microsoft/azure-pipelines-image-generation#1320]
**Tool information**
- Tool name: Python
- Add or update? Update
- Desired version: 3.7.5
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [x] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
Add the appropriate label for the image or images that should be updated (e.g., macOS 10.13, macOS 10.14, ubuntu, VS2017, VS2019, WINCON).
All except WINCON

**Workaround**

**Are you willing to submit a PR?**

**Comment by vtbassmatt** [comment]
In progress

**Comment by vtbassmatt** [comment]
Complete, I believe.
