### ISSUE TITLE
Keeping track of installed software versions

### ISSUE THREAD

**Issue by SanderHolvoet** [microsoft/azure-pipelines-image-generation#1323]
Not a "real" issue, but rather a question.

How do you keep track of which software (and which specific version of that software) is installed on each image? I'm aware of the [markdown](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2019-Server2019-Readme.md) files which holds an overview of all installed software on particular image, but how do you automatically update this?

I've been able to generate a **static** list of installed software, Windows features and Visual Studio workloads by using the following PS commands.

```powershell
# List installed software
Add-Content $agentInfo "##Installed software"
Get-ItemProperty HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\* | Sort-Object -Property DisplayName | ForEach-Object {
        if ($_.DisplayName.length -gt 0) {
                Add-Content $agentInfo "- $($_.DisplayName) $($_.DisplayVersion)"
        }  
}

# List installed Windows features
Add-Content $agentInfo "##Installed Windows features"
Get-WindowsFeature | Where Installed | Sort-Object -Property DisplayName| ForEach-Object {
     Add-Content $agentInfo "- $($_.DisplayName)"
}

# List Visual Studio workloads
Add-Content $agentInfo "##Installed Visual Studio workloads"
Install-Module VSSetup -Scope CurrentUser -Force
(Get-VSSetupInstance | Select-VSSetupInstance -Product *).packages | Sort-Object -Property Id | ForEach-Object {
     Add-Content $agentInfo "- $($_.Id) $($_.Version)"
}
```

The real question however: how can you automate this process in order to automatically detect newly installed or upgraded software?

This is an issue we are currently facing on our self-hosted build agent, and I'm curious to find out how you guys deal with this on the Microsoft-hosted machines.

**Update:**

I've been looking at this a bit more into detail and I've noticed you guys are using Packer to generate VM images which are then used to create new Azure VM. So these images are created from scratch and Packer is responsible for installing all required software (through chocolatey for example). Every piece of installed software + corresponding version then gets added to the markdown file (*C:/InstalledSoftware.md*) during installation once a validation is done that the software has been installed successfully.

However, at the top of these markdown files, there's a section:

> **Components marked with * have been upgraded since the previous version of the image.**

So my question(s) remain:

- How do you guys keep track of which version has been updated (since the previous version of the image)? Manually?
- Is the process of updating certain software / packages somehow automated?

Thanks.

**Comment by jimhess** [comment]
I'd love to know the outcome and thanks for the scripts and I have been relying upon the vs2017-win2016 image and beginning of October 2019, there was an update and now we are getting block by pending MSI installs (we need to add sqlcmdlineutils to get sqlcmd.exe of all things).
