### ISSUE TITLE
Add docker to Mac

### ISSUE THREAD

**Issue by jeronimo13** [microsoft/azure-pipelines-image-generation#1324]
**Tool information**
- Tool name: docker
- Add or update? add
- Desired version: latest
- If this is an add request:
  - Brief description of tool: Securely build, share and run modern applications anywhere
  - URL for tool's homepage: https://www.docker.com/

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [+] Go
- [+] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [+] .NET Core or .NET Desktop
- [+] PHP
- [+] Python
- [+] Ruby
- [+] Rust
- [+] Scala
- [+] Testing and code coverage
- [+] Xamarin
- [+] Other

**Image impacted**
macOS 10.13
macOS 10.14

**Workaround**
https://medium.com/@yutafujii_59175/a-complete-one-by-one-guide-to-install-docker-on-your-mac-os-using-homebrew-e818eb4cfc3

**Are you willing to submit a PR?**
No

I want to execute docker in a shell script in macOS, just like in Ubuntu:
docker pull mycoolimage:latest

This is important because my build script relies on docker

**Comment by MaceWindu** [comment]
azp team already refused to do so https://github.com/microsoft/azure-pipelines-image-generation/issues/738#issuecomment-519571491 before

Hope they will reconsider it, as existing workaround will stop working at same point - it stuck with 2.0.x docker for mac version. Installing recent versions (2.1.x) fails without any useful logs, so we cannot even find out what's wrong.

**Comment by jeronimo13** [comment]
@MaceWindu thanx for the heads up. I hope too. I've managed to work around in my case, though

**Comment by shashankbarsin** [comment]
We are not able to add Docker to our Microsoft hosted Mac agents because of the [End User License Agreement](https://www.docker.com/legal/docker-software-end-user-license-agreement). As a result, we recommend setting up [self-hosted Mac agent](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-osx?view=azure-devops) and installing [Docker for Mac](https://docs.docker.com/docker-for-mac/install/) on the same manually.

**Comment by MaceWindu** [comment]
@shashankbarsin no idea how general docker license applies only to osx images (and don't really care), but at least it shouldn't prevent from fixing agent compatibility with docker for mac 2.1+
