### ISSUE TITLE
Add specific Android NDK versions

### ISSUE THREAD

**Issue by paulthomson** [microsoft/azure-pipelines-image-generation#1325]
In summary, when you run the `sdkmanager` to install the `ndk-bundle` as seen here:

https://github.com/microsoft/azure-pipelines-image-generation/blob/bce8976438866ee932a17ecdcbd3c9042781d322/images/linux/scripts/installers/1604/android.sh#L28

I believe it will get the latest Android NDK. This means working builds could end up breaking when you update the image, as the NDK version could change. We also cannot target a specific version of the NDK because only one version is present. Instead, you can manually download specific versions of the Android NDK and extract them to different locations (it does not have to be `$ANDROID_SDK_ROOT/ndk-bundle`). This would allow us to pick a specific version, and will ensure builds continue to work as new NDK versions are released. 

**Tool information**
- Tool name: Android NDK (all versions).
- Add or update? Add additional versions.
- Desired version: All of them, or at least the last few.
- If this is an add request:
  - Brief description of tool: The Android NDK.
  - URL for tool's homepage: https://developer.android.com/ndk/downloads/

**Areas and ecosystems**

- [x] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
Add the appropriate label for the image or images that should be updated (e.g., macOS 10.13, macOS 10.14, ubuntu, VS2017, VS2019, WINCON).

Probably all of them.

**Workaround**
You can install it during the build.

**Are you willing to submit a PR?**
Maybe!

**Comment by trajano** [comment]
@paulthomson  do you have a YAML snippet that shows how to install it?

**Comment by paulthomson** [comment]
[Here](https://github.com/google/gfbuild-amber/blob/e38f8f0b8baef8b0b6837954734f505ce6187f24/build.sh#L240) is one approach to downloading and "installing" the NDK. However, I think the `sdkmanager` from the Android SDK has been updated so that you can now use `sdkmanager` to download different versions of the NDK and install them side-by-side. Not sure if that is easier or harder, though.
