### ISSUE TITLE
cloudfoundry 404 on Windows

### ISSUE THREAD

**Issue by riezebosch** [microsoft/azure-pipelines-image-generation#1333]
> Note: cf CLI 6.47 release does not include the Windows installer because we are in the middle of renewing the certificate. We are currently working to include the Windows installer in the next release. Please reach out on Slack Cloud Foundry #cli if you have feedback or questions. We've removed the links below and will be updating them once we have the cert. Thanks for your patience.

https://github.com/cloudfoundry/cli#installers-and-compressed-binaries

The cloudfoundry installer is currently not available for Windows and 404's when building the images for vs2017 and vs2019.

**Comment by kaylangan** [comment]
Should be fixed with #1335

**Comment by kaylangan** [comment]
Fixed on the cloud foundry side
