### ISSUE TITLE
Selenium scripts are getting failed due to chrome driver compatible issue v75

### ISSUE THREAD

**Issue by pradeepks780** [microsoft/azure-pipelines-image-generation#1340]
As mentioned in the windows 2019, am using chrome driver v75 for triggering scripts, but which is getting failed due to compatible issue.

Can anyone please let me know the chrome browser version which is running on windows server 2019
![image](https://user-images.githubusercontent.com/56922610/67394283-89266980-f5c1-11e9-956c-99d6818d509b.png)

**Comment by DanielHabenicht** [comment]
You have to update the chromedrive to a matching version see: 
https://stackoverflow.com/a/55201365/9277073

**Comment by pradeepks780** [comment]
> You have to update the chromedrive to a matching version see:
> https://stackoverflow.com/a/55201365/9277073
> RELATED: #861

But Im not sure about the browser version which is running in windows server 2019

**Comment by DanielHabenicht** [comment]
Than, a heartly welcome to the party! Nobody knows, could be anything between 75 and 78.

**Comment by DanielHabenicht** [comment]
Just try different chromedriver version for chrome 76 and 77. My best guess would be chrome 77 or 78

**Comment by koskila** [comment]
I ran into this same issue this week - the version listed in the documentation is wrong. However, in case you're using YAML to configure your pipeline, you can find out the version of Chrome installed on the machine by adding this step:

- powershell: |
   (Get-Item "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe").VersionInfo 
  displayName: 'We want to know the Chrome version installed on this machine'

For me, it was 77, so I changed my WebDriver to be 77.0.3865.40. I suppose that's compatible with whatever's on the images now.

However, you should also be able to use the WebDriver already installed on the machine after you add it to PATH environment variable - again, in case you're using YAML to configure your pipelines, you can add the WebDriver's location to the PATH variable roughly like so:

- pwsh: |
   echo "##vso[task.prependpath]$env:CHROMEWEBDRIVER"
  displayName: Adds ChromeWebDriver for Selenium to PATH 

(CHROMEWEBDRIVER is an environment variable that should be set in the images by default).

This configuration got our pipeline to work, would be interested in hearing if it helps out anyone else! I posted a longer explanation with more code examples here:
https://www.koskila.net/how-to-use-the-right-version-of-the-webdriver-on-hosted-agents-in-azure-devops/

**Comment by koskila** [comment]
This has been resolved due to a subsequent round of image & docs generation, so this issue can be safely resolved. @kaylangan
