### ISSUE TITLE
`UsePythonVersion` on macOS-10.13 image activates interpreter built for 10.14

### ISSUE THREAD

**Issue by ihnorton** [microsoft/azure-pipelines-image-generation#1342]
**Describe the bug**
The Python version activated by the `UsePythonVersion` task in the `macOS-10.13` image was built with `MACOSX_DEPLOYMENT_TARGET=10.14`. This seems to be a recent change, and makes this Python build partially incompatible with the macOS-10.13 image -- at very least for the purposes of distutils.

I say it seems to be a recent change, because I had a successful build on 10/18, (https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=1375), but manually building exactly the same hash now (last night, 10/22) fails (https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=1405&view=logs).

The short explanation of why the deployment target mismatch is a problem, is that `distutils` caches the value of `MACOSX_DEPLOYMENT_TARGET` and associated flags/feature selections, and uses these when building extensions in order (presumably) to ensure ABI compatibility with the current python interpreter.

A much longer dive, with code links, into how this breaks `setup.py install` for extension builds may be found in this comment: https://github.com/numpy/numpy/pull/14758#issuecomment-545531021

**Expected behavior**
`UsePythonVersion` installs a python interpreter that is compatible with the selected image.

**Actual behavior**
As above, `UsePythonVersion` installs an incompatible interpreter in the `macOS-10.13` image.

This causes failing CI for projects using the `macOS-10.13` image:
- my builds here: https://github.com/TileDB-Inc/TileDB-Py/pull/214 (builds fine locally on macOS 10.14)
- several numpy builds, in particular including: https://github.com/numpy/numpy/pull/14758

Minimal repro of the config output:
1. test repository: https://github.com/ihnorton/azure-mac-py-version
2. example build pipeline output: https://dev.azure.com/isaiahnorton/isaiahnorton/_build/results?buildId=228 (see `Print env` task, search for `MACOSX_DEPLOYMENT_TARGET`)

**Image impacted**
`macOS-10.13`

**Comment by v-mitim** [comment]
@ihnorton issue has been fixed. Could you check that everything is ok, please?

**Comment by ihnorton** [comment]
Yes, works. Thank you!
