### ISSUE TITLE
Enable "Assistive Access" on MacOS image

### ISSUE THREAD

**Issue by MatejStraka** [microsoft/azure-pipelines-image-generation#1343]
**Describe the bug**
I was trying to run applescript which contains code `tell application "System Events" ` on Microsoft hosted Mac OS agent in pipeline. I created bash task in pipeline which used osascript command to run script,  `osascript MyApplescript.scpt ` from terminal but It is not allowed by MacOS because it requires "Assistive Access" for osascript/terminal. There is no way how to add "Assistive Access" to terminal or any other app on Microsoft hosted MacOS agent. It can be done only manually on real device in "System Preferences > Security & Privacy > Privacy > Accessibility" - there is no way how to do it on Microsoft hosted  Mac Os agents. 

**Expected behavior**
There should be a way to enable "Assistive Access" for an application on Microsoft hosed Mac OS agent or terminal should have set "Assistive Access" on Mac OS agent by default .

**Actual behavior**
A description with steps to reproduce the issue.

1. Create applescript which contains code `tell application "System Events"`
2. Run applescript using osascript command from terminal (using Bash task in pipeline containing  `osascript MyApplescript.scpt `)
3.  Execution of previous step returns error which says "Assistive Access" is needed for osascript
4. It is not possible to add "Assistive Access" to osascript or terminal

**Image impacted**
Microsoft hosted Mac OS

**Comment by AlenaSviridenko** [comment]
Hi @MatejStraka !
We are trying to reproduce your issue on images (both Mojave and High Sierra), but with no luck by this time.
We are using the following script to reproduce error:
```
echo 'tell application "System Events"' > MyApplescript.scpt
echo 'end tell' >> MyApplescript.scpt
osascript MyApplescript.scpt
```
 Could you please clarify some details:
1. Are we missing something in the script? Does it match with the script you are running to get the error?
2. What MacOS version do you use for your script? We have tried both Mojave and High Sierra but script finished successfully for both versions.
3. Is it possible for you to provide a part of logs with the error related to "Assistive Access"?

Please, let me know if you have any questions.

Thanks!

**Comment by MatejStraka** [comment]
Hi @AlenaSviridenko 
To reproduce the issue use this script:
`tell application "Safari" to activate
delay 2
tell application "System Events"
    tell application process "Safari"
        keystroke "," using command down
        set frontmost to true
        tell window 1
            click button "Advanced" of toolbar 1
            delay 2
            set theCheckbox to checkbox 4 of group 1 of group 1 of it
            tell theCheckbox
                if not (its value as boolean) then click theCheckbox
            end tell
            delay 2
            keystroke "w" using command down
            delay 2
        end tell
        tell menu bar item "Develop" of menu bar 1
            click
            delay 2
            click menu item "Allow Remote Automation" of menu 1
            delay 2
        end tell
    end tell
end tell
tell application "Safari" to quit`
Behavior is different on Mojave and High Sierra.
It throws timeout exception in Mojave:
![image](https://user-images.githubusercontent.com/11321940/67947289-aa9bdc80-fbe3-11e9-90e9-d0009f34fdb5.png)
And shows this exception in High Sierra 
![image](https://user-images.githubusercontent.com/11321940/67947360-c7381480-fbe3-11e9-83d6-8c3846d2d638.png)

Simple script with tell application "System Events" like this one:
`tell application "System Events"
end tell` 
works without problems. I am not sure why simple script works and why more complex one does not but the issue is still there -  There is no way how to add "Assistive Access" to terminal or any other app on Microsoft hosted MacOS agents.

**Comment by AlenaSviridenko** [comment]
Hi @MatejStraka!
We have deployed new Mojave and HighSierra image with required permissions for Assistive Access.
Our tests are green, so could you, please, check if the problem was resolved for you too?

Please, let me know if you see any issues.
Thanks!
