### ISSUE TITLE
Show Agent Software Versions in Azure Pipelines

### ISSUE THREAD

**Issue by DanielHabenicht** [microsoft/azure-pipelines-image-generation#1344]
**Describe the bug**
Debugging a build that was previously running just fine and is now failing (because the agent image got updated) is a very tedious job because you can only speculate on what software version is running on the agent. 
So seeing the capabilities would be a live saver.

**Expected behavior**
The capabilites tab should be filled with everything that is in currently written in the readmes, e.g.: https://github.com/microsoft/azure-pipelines-image-generation/blob/4894fb13e8a0917206b9b762069355e00bc04754/images/linux/Ubuntu1604-README.md 

**Actual behavior**
Nothing is shown.
![image](https://user-images.githubusercontent.com/13590797/67429341-3f00b080-f5e0-11e9-85de-35e23290e800.png)

**Solution**
Show the capabilities in the agent tab. 
Another solution would be to log a link to the readme of the agent at startup: 
![image](https://user-images.githubusercontent.com/13590797/67429854-4e342e00-f5e1-11e9-9d0f-d2a6d1842d20.png)

**Image impacted**
ubuntu mac windows

**Comment by DanielHabenicht** [comment]
Please take another look :)

**Comment by alepauly** [comment]
Current Image Version should now be visible in Initialize Job stage.

**Comment by DanielHabenicht** [comment]
Thank you very much!
