### ISSUE TITLE
Cannot install .net48 

### ISSUE THREAD

**Issue by majorvin** [microsoft/azure-pipelines-image-generation#1345]
**Describe the bug**
Cannot install .net48

**Expected behavior**
A description of what you expected to happen.

**Actual behavior**
I just pull the latest release VS2017/20191009.1 and still getting the same error.
```
==> vhd: Provisioning with powershell script: C:\Users\*\Downloads\devops-pipeline-agent-VS2017-20191009.1\azure-pipeline-image-generation\images\win/scripts/Installers/Install-NET48.ps1
    vhd: Downloading NDP48-DevPack-ENU.exe...
    vhd: Starting Install NDP48-DevPack-ENU.exe...
    vhd: Non zero exit code returned by the installation process : -1073741819.
    vhd: -1073741819
```
**Image impacted**
Add a label for each image that has the bug (e.g., ubuntu, mac, window)

**Comment by riezebosch** [comment]
+1. Opened an issue a while ago #973 but that was closed for no apparent reason.

**Comment by ryanspletzer** [comment]
I am seeing this as well.

**Comment by ryanspletzer** [comment]
Something I tried today: I went to download center and got a fresh URL for download:

`https://download.visualstudio.microsoft.com/download/pr/014120d7-d689-4305-befd-3cb711108212/0307177e14752e359fde5423ab583e43/ndp48-devpack-enu.exe`

And put it here:

https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/win/scripts/Installers/Install-NET48.ps1#L10

And it worked. Maybe the exe file at the current URL that's being used has an issue.

**Comment by majorvin** [comment]
I'll give that a shot. Im very curious how others are not reporting this as a big issue as it is a blocker for both 2017 and 2019

**Comment by riezebosch** [comment]
Put into a PR?

**Comment by majorvin** [comment]
we'll see if this will get approve or not. 
https://github.com/microsoft/azure-pipelines-image-generation/pull/1440/files

**Comment by majorvin** [comment]
this can be closed now. as its merged in action/virtual_env
