### ISSUE TITLE
Add FS-iSCSITarget-Server to Windows image

### ISSUE THREAD

**Issue by vtbassmatt** [microsoft/azure-pipelines-image-generation#1353]
**Tool information**
- Tool name: FS-iSCSITarget-Server (feature of Windows)
- Add or update? add
- Desired version: whatever comes with each Windows version
- If this is an add request:
  - Brief description of tool: allows for putting temp directory in a RAMdisk
  - URL for tool's homepage: n/a, it's an optional feature of Windows

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [x] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
VS2019, possibly VS2017 if space allows

**Workaround**
Install during the build; adds 30 seconds to every build.

**Are you willing to submit a PR?**
see https://github.com/pypa/pip/pull/7263#issuecomment-546973933 for customer request

**Comment by chrahunt** [comment]
This would still be good to have. For our integration tests the relative benefit is lower, but for unit tests the installation of "FS-iSCSITarget-Server" takes about 1/3 of the total time. See [here](https://dev.azure.com/pypa/pip/_build/results?buildId=17904&view=logs&jobId=a2c5995e-6442-53e0-0a3c-0440b1291bf0&j=2d388672-64b2-5f6c-0be2-18aa56452904&t=a29af80d-a7cc-5261-3d83-7305f46aa195) for example.

**Comment by pradyunsg** [comment]
Hi, this would be great to have.
