### ISSUE TITLE
Azure Pipeline Ubuntu image "Could not find part of the path '/home/vsts/agents/2.159.2/_diag/pages/c703dbde-017f-4116-b8e6-5d8a124ee2e5_1.log"

### ISSUE THREAD

**Issue by wilzer** [microsoft/azure-pipelines-image-generation#1357]
**Describe the bug**
I am having an issue running Ubuntu as an image in my Azure Pipelines. It is returning the following error "Could not find a part of the path '/home/vsts/agents/2.159.2/_diag/pages/c703dbde-017f-4116-b8e6-5d8a124ee2e5_1.log" where the Filename would be different for each run. Here is a link to one of the runs https://dev.azure.com/warehouse-anywhere/Platform/_build/results?buildId=55&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&l=327

**Expected behavior**
The expected behavior is for the pipeline to finish successfully

**Actual behavior**
Here is the exact yaml file and project setup I am using - https://github.com/MikeDodaro/azure-vote-devops/blob/master/azure-pipelines.yml

1. I am following the Microsoft bedrock fabricate tutorial - https://github.com/microsoft/bedrock/blob/master/docs/devops/README.md 
2. I setup my pipeline to use this yaml file
3. I have another repo to receive the manifests.

Is there a way I can login to the vm to troubleshoot? Thanks

**Comment by alepauly** [comment]
@wilzer Unfortunately there's no way for you to login to the vm to troubleshoot. As an alternative, you could setup your own VM and register it as a [self-hosted agent](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops#install), then run the build against that to troubleshoot.

**Comment by wilzer** [comment]
@alepauly Thanks for the suggestion. I tried running on my local machine as a self-hosted agent and found that the log file in question is not being created at all, but the directory leading up to it is. The yaml file I am using is running this script, which might contain the issue, but not sure where.

https://raw.githubusercontent.com/Microsoft/bedrock/master/gitops/azure-devops/build.sh

**Comment by wilzer** [comment]
Solved the issue, it was a problem with my git repo variable. I removed the user name portion which allowed the git script to add in its own user during the build.
