### ISSUE TITLE
Update/Add Az 2.8.0

### ISSUE THREAD

**Issue by Lutando** [microsoft/azure-pipelines-image-generation#1359]
**Tool information**
- Tool name: Az Module
- Add or update? Update or Add?
- Desired version: 2.8.0

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [x] Other

**Image impacted**
In my case I use the Ubuntu images but I guess

**Workaround**
Currently I am not sure how to workaround this. The big fixes and new APIs in Az 2.8.0 are very much needed in my case

**Are you willing to submit a PR?**
I can

**Comment by ncthbrt** [comment]
@alepauly, any updates on this?

**Comment by Lutando** [comment]
@alepauly

**Comment by alepauly** [comment]
@Lutando sorry for the delay responding to this, if you can submit a PR to update it that would be great. cc @ncthbrt, fyi @kmkumaran

**Comment by Lutando** [comment]
Done the PR over at https://github.com/microsoft/azure-pipelines-image-generation/pull/1426

**Comment by Lutando** [comment]
Closed via https://github.com/actions/virtual-environments/pull/143
