### ISSUE TITLE
Update/Add PyPy 7.2.0

### ISSUE THREAD

**Issue by asvetlov** [microsoft/azure-pipelines-image-generation#1363]
**Tool information**
- Tool name: PyPy (alternative Python implementation) 
- Add or update? Add
- Desired version: 7.2.0
- If this is an add request:
  - Brief description of tool: PyPy 7.2.0 has Python 3.6 official support (were 3.5 and 3.6 beta)
  - URL for tool's homepage: https://pypy.org

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [x] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
Add the appropriate label for the image or images that should be updated (e.g., macOS 10.13, macOS 10.14, ubuntu, VS2017, VS2019, WINCON).

- macOS-10.13
- macOS-10.14
- VS2017
- VS2019
- ubuntu-16.04
- ubuntu-18.04

**Workaround**

Download archive and unpack in explicitly.

**Are you willing to submit a PR?**

Sorry, no. The configuration looks pretty complex; I have no knowledge of configuring macos at all.

**Comment by vtbassmatt** [comment]
I'll do this after my CPython 3.7.5/3.8.0 changes make it through all the rings.

**Comment by asvetlov** [comment]
@vtbassmatt thanks!
