### ISSUE TITLE
Latest versions of Xamarin on Mac Agents

### ISSUE THREAD

**Issue by gary-allan** [Microsoft/azure-pipelines-image-generation#137]
Hi,

Are you able to advise your timeframes for adding new versions once a stable version is released?
Currently we require iOS SDK 11.10.X but the MacOS agent only has 11.9.X. This would also apply in the future to all the other software that makes up the Agent.

Thanks

**Comment by alexsorokoletov** [comment]
Please update MacOS image to include latest stable Xamarin iOS
