### ISSUE TITLE
Add GPG on macOS

### ISSUE THREAD

**Issue by ethomson** [microsoft/azure-pipelines-image-generation#1371]
gpg is installed by default on ubuntu and windows runners.  Would be nice to have on macOS as well.

**Tool information**
- Tool name: gpg
- Add or update? add
- Desired version: latest
- If this is an add request:
  - Brief description of tool: gpg (gnu privacy guard) for some crypto work - in particular, it may be useful for validating signatures of files
  - URL for tool's homepage: https://www.gnupg.org/

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [X] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
macOS-latest

**Workaround**
install during the build

**Are you willing to submit a PR?**
maybe

**Comment by ladislas** [comment]
any news on this?

**Comment by kaylangan** [comment]
Moved to https://github.com/actions/virtual-environments/issues/134
