### ISSUE TITLE
ubuntu-latest vmImages gives xenial, not bionic

### ISSUE THREAD

**Issue by jwillemsen** [microsoft/azure-pipelines-image-generation#1379]
**Describe the bug**
We are using vmImage image-latest and because of issue #506 we expect to now get bionic, but it seems our builds are still running with xenial

**Expected behavior**
Run with ubuntu 18.04

**Actual behavior**
It runs with xenial, see 
https://dev.azure.com/docgroup/7b69f3ee-d437-48a9-8919-c18f00e558ad/_apis/build/builds/1216/logs/271
https://dev.azure.com/docgroup/ACE_TAO/_build?definitionId=7&_a=summary
https://github.com/DOCGroup/ACE_TAO/blob/master/azure-pipelines.yml

**Image impacted**
ubunt-latest

**Comment by bestbeforetoday** [comment]
Same problem here. Specifying `ubuntu-18.04` correctly gives a Bionic (18.04) image but `ubuntu-latest` gives Xenial (16.04).

**Comment by samkearney** [comment]
Same, this is directly contradicting the [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops).

**Comment by estensen** [comment]
It seems like `ubuntu-18.04` now points to `ubuntu-19.04` and latest points to `ubuntu-18.04`
https://github.com/MicrosoftDocs/vsts-docs/issues/6518

**Comment by pasangh** [comment]
This is known - we want to give customers currently using Ubuntu-latest enough time to port to Ubuntu-18. We will send out a blog post and then make the switch.

Thanks for filing this!

**Comment by samkearney** [comment]
Thanks @pasangh . The only thing I'd request is that next time the documentation not be updated prematurely.
![image](https://user-images.githubusercontent.com/5142299/70772173-56832c80-1d39-11ea-977f-730fe985d68f.png)

**Comment by estensen** [comment]
I strongly disagree not having latest image. I know it doesn't have to be, but it's a leaky abstraction to me. It breaks my mental model of expected behavior. At least update the docs.

**Comment by jwillemsen** [comment]
When you want to have a stable version for users call it ubuntu-stable, latest gave me the idea (and that is also documented) that it is the latest version available

**Comment by samkearney** [comment]
So has this been changed yet? Can I switch my pipelines to using `ubuntu-latest` instead of `ubuntu-18.04`?

**Comment by estensen** [comment]
@samkearney Isn't it just better to pin `ubuntu-18.04` so you don't get any surprises when `ubuntu-latest` changes next time?

**Comment by samkearney** [comment]
@estensen For some applications, yes. For others, it's not as important and I'd rather stay on the bleeding edge. In any case, if the schema provides a value called `ubuntu-latest` which the docs claim points at `ubuntu-18.04`, it should not be a lie.

**Comment by estensen** [comment]
I think you have to update the version yourself if you want to stay on the bleeding edge. It took months for `ubuntu-latest` to point to `ubuntu-18.04` and it will probably be the same for the next version.

**Comment by samkearney** [comment]
@estensen Again, respectfully, [that is not what the documentation says](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent). That page claimed that `ubuntu-latest` and `ubuntu-18.04` were equivalent, long before that was actually true (if it is yet). All I am asking is that the documentation say things that are correct. I think that's a reasonable request.
