### ISSUE TITLE
Missing documentation to generate OSX images

### ISSUE THREAD

**Issue by eric-labelle** [microsoft/azure-pipelines-image-generation#1384]
I noticed that there is currently no guide on how to update OSX images and the script itself is missing too from the repository. Only markdown files are available [here](https://github.com/microsoft/azure-pipelines-image-generation/tree/master/images/macos)

 I can only find the linux and windows script
--> Linux: /images/linux/scripts/installers/{1604-1804}/android.sh 
--> Windows: /images/win/scripts/Installers/Update-AndroidSDK.ps

**Comment by kaylangan** [comment]
That's correct 🙂 

We currently only have the Windows and Linux scripts available, as explained [here](https://github.com/microsoft/azure-pipelines-image-generation#overview). We don't plan to add them to this repository in the near future, but do plan to open source them eventually.

**Comment by eric-labelle** [comment]
Allright, so there is no way for me to help building it and contribute to OSX image. Thanks for confirming it. It's unfortunate though :(

**Comment by eric-labelle** [comment]
Any chance you guys could prioritize this issue then? https://github.com/microsoft/azure-pipelines-image-generation/issues/1225
