### ISSUE TITLE
Procfs file-descriptor files missing on ubuntu-latest

### ISSUE THREAD

**Issue by Pr0methean** [microsoft/azure-pipelines-image-generation#1386]
While testing the fix/workaround from https://github.com/microsoft/azure-pipelines-tasks/issues/11334#issuecomment-533233625, I needed to tee the output from a subshell to the root shell's stdout, so that the log would still contain some information while the task was in progress. My solution, which seems to be pretty standard in Linux, is:

```
ROOT_SHELL=$$
(
# ...
) 2>&1 < prng_out | tee ../dieharder.txt /proc/${ROOT_SHELL}/fd/1 | (grep -m 1 'FAILED' &&\
(
  pkill dieharder
  pkill java
  exit 1
))
```

This works fine on my workstation. But when it runs on Azure Pipelines with the `ubuntu-latest` image, I get:
```
tee: /proc/7072/fd/1: No such device or address
```
This suggests that either the script's root shell has been replaced with a different process mid-task, or it has closed its stdout prematurely and started writing the log to a different fd, or procfs is somehow non-POSIX (or at least doesn't follow the same de-facto standards as bare-metal systems) on Azure. Is there still a way to write to the log from a stdout-redirected subshell, other than creating a named pipe for the purpose?

(Copied from https://github.com/microsoft/azure-pipelines-agent/issues/2532 as requested by @jtpetty .)

**Comment by Pr0methean** [comment]
Keep open

**Comment by glucaci** [comment]
Lately we have the same problem like in #11334 with a .NET Core Task
```
Starting: dotnet tool restore
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.164.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
/opt/hostedtoolcache/dotnet/dotnet tool restore --ignore-failed-sources --no-cache --verbosity normal

... restoring packages

Restore was successful.
The STDIO streams did not close within 10 seconds of the exit event from process '/opt/hostedtoolcache/dotnet/dotnet'. This may indicate a child process inherited the STDIO streams and has not yet exited.
```

and the task will remain blocked until build timeout expires.
