### ISSUE TITLE
Update Azul Zulu to JDK 13

### ISSUE THREAD

**Issue by Pr0methean** [microsoft/azure-pipelines-image-generation#1387]
**Tool information**
- Tool name: Azul Zulu
- Add or update? Update
- Desired version: 13.0.1+10

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [X] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
Add the appropriate label for the image or images that should be updated (e.g., macOS 10.13, macOS 10.14, ubuntu, VS2017, VS2019, WINCON).

ubuntu-latest

**Workaround**

Yes, one can install Zulu 13 and then use `update-java-alternatives` to update all symlinks in /usr/bin.

**Are you willing to submit a PR?**

TBD

**Comment by maxim-lobanov** [comment]
Azul OpenJDK 13 is available on macOS images ([10.13](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.13-Readme.md#language-and-runtime) and [10.14](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md#language-and-runtime))

**Comment by brunoborges** [comment]
The build agents should stick to the LTS Java 11 version. If customers want to move to 13 or any other non-LTS version, they should do it on a case-by-case basis.

**Comment by Pr0methean** [comment]
> The build agents should stick to the LTS Java 11 version. If customers want to move to 13 or any other non-LTS version, they should do it on a case-by-case basis.

We already get JDK 12, which is non-LTS.

**Comment by brunoborges** [comment]
You should rollback to 11.

**Comment by brunoborges** [comment]
The 12.x version is a Preview and should be adopted by customers on a case-by-case basis if they need/want. Azure Pipelines build agents should only be using LTS releases of Zulu Enterprise provided by Azul Systems for specific usage on Azure services:

https://docs.microsoft.com/en-us/azure/java/jdk/java-jdk-install
