### ISSUE TITLE
Unable to build Win Server2016 VS2017 image

### ISSUE THREAD

**Issue by KasireddyAlekhya** [microsoft/azure-pipelines-image-generation#1392]
Running packer image generation using  https://github.com/Microsoft/azure-pipelines-image-generation within Azure PowerShell.
Step 1 : Run the below script
"C:\Users\v-alkas\Documents\GitHub\azure-pipelines-image-generation"
GenerateResourcesAndImage.

Expected behavior
Successful generation of VS2017 image.

Actual behavior
PowerShell script was structed after sometime

==> vhd: Running builder ...
==> vhd: Getting tokens using client secret
    vhd: Creating Azure Resource Manager (ARM) client ...
    vhd: You have provided Object_ID which is no longer needed, azure packer builder determines this dynamically from the authentication token
==> vhd: Warning: You are using Azure Packer Builder to create VHDs which is being deprecated, consider using Managed Images. Learn more http://aka.ms/packermanagedimage
==> vhd: Creating resource group ...
==> vhd:  -> ResourceGroupName : 'packer-Resource-Group-f3qmtmoub9'
==> vhd:  -> Location          : 'SouthIndia'
==> vhd:  -> Tags              :
==> vhd: Validating deployment template ...
==> vhd:  -> ResourceGroupName : 'packer-Resource-Group-f3qmtmoub9'
==> vhd:  -> DeploymentName    : 'pkrdpf3qmtmoub9'
==> vhd: Deploying deployment template ...
==> vhd:  -> ResourceGroupName : 'packer-Resource-Group-f3qmtmoub9'
==> vhd:  -> DeploymentName    : 'kvpkrdpf3qmtmoub9'
==> vhd: Getting the certificate's URL ...
==> vhd:  -> Key Vault Name        : 'pkrkvf3qmtmoub9'
==> vhd:  -> Key Vault Secret Name : 'packerKeyVaultSecret'
==> vhd:  -> Certificate URL       : 'https://pkrkvf3qmtmoub9.vault.azure.net/secrets/packerKeyVaultSecret/19a90a4224f64102a70e083cdf4ad22b'
==> vhd: Setting the certificate's URL ...
==> vhd: Validating deployment template ...
==> vhd:  -> ResourceGroupName : 'packer-Resource-Group-f3qmtmoub9'
==> vhd:  -> DeploymentName    : 'pkrdpf3qmtmoub9'
==> vhd: Deploying deployment template ...
==> vhd:  -> ResourceGroupName : 'packer-Resource-Group-f3qmtmoub9'
==> vhd:  -> DeploymentName    : 'pkrdpf3qmtmoub9'
==> vhd: ERROR: -> InvalidTemplateDeployment : The template deployment 'pkrdpf3qmtmoub9' is not valid according to the validation procedure. The tracking id is '9ca3e3f4-a6a8-4788-a7cf-ab282c6fa09c'. See inner errors for details.
==> vhd: ERROR:   -> QuotaExceeded : The operation couldn't be completed as it results in exceeding quota limit of Core. Maximum allowed: 100, Current in use: 93, Additional requested: 8. Read more about quota limits at https://aka.ms/AzurePerVMQuotaLimits. Submit a request for Quota increase using the link https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters/%7B%22subId%22:%2232f750d1-2a53-4792-a857-b5a0ee599f96%22,%22pesId%22:%2206bfd9d3-516b-d5c6-5802-169c800dec89%22,%22supportTopicId%22:%22e12e3d1d-7fa0-af33-c6d0-3c50df9658a3%22%7D.
==> vhd:
==> vhd: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidTemplateDeployment" Message="The template deployment 'pkrdpf3qmtmoub9' is not valid according to the validation procedure. The tracking id is '9ca3e3f4-a6a8-4788-a7cf-ab282c6fa09c'. See inner errors for details." Details=[{"code":"QuotaExceeded","message":"The operation couldn't be completed as it results in exceeding quota limit of Core. Maximum allowed: 100, Current in use: 93, Additional requested: 8. Read more about quota limits at https://aka.ms/AzurePerVMQuotaLimits. Submit a request for Quota increase using the link https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters/%7B%22subId%22:%2232f750d1-2a53-4792-a857-b5a0ee599f96%22,%22pesId%22:%2206bfd9d3-516b-d5c6-5802-169c800dec89%22,%22supportTopicId%22:%22e12e3d1d-7fa0-af33-c6d0-3c50df9658a3%22%7D."}]
==> vhd: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidTemplateDeployment" Message="The template deployment 'pkrdpf3qmtmoub9' is not valid according to the validation procedure. The tracking id is '9ca3e3f4-a6a8-4788-a7cf-ab282c6fa09c'. See inner errors for details." Details=[{"code":"QuotaExceeded","message":"The operation couldn't be completed as it results in exceeding quota limit of Core. Maximum allowed: 100, Current in use: 93, Additional requested: 8. Read more about quota limits at https://aka.ms/AzurePerVMQuotaLimits. Submit a request for Quota increase using the link https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters/%7B%22subId%22:%2232f750d1-2a53-4792-a857-b5a0ee599f96%22,%22pesId%22:%2206bfd9d3-516b-d5c6-5802-169c800dec89%22,%22supportTopicId%22:%22e12e3d1d-7fa0-af33-c6d0-3c50df9658a3%22%7D."}]
==> vhd: Step "StepDeployTemplate" failed)

![image](https://user-images.githubusercontent.com/44359532/68577966-2117c480-0497-11ea-97e4-e2b3088b3c91.png)

**Comment by riezebosch** [comment]
Looks like that's on your side. Quota exceeded is you hitting resource limits inside your subscription.

**Comment by KasireddyAlekhya** [comment]
Sorry , we have resolved the issue. I will close this.

Thank you.
