### ISSUE TITLE
Did the agent images start using Nodejs 12.13.0 instead of 10.16.3 some time in the last few days?

### ISSUE THREAD

**Issue by StingyJack** [microsoft/azure-pipelines-image-generation#1393]
I have a bunch of build job that are failing now that were fine last week, and the culprit seems to be nodejs 12.13.0, It was the only difference between working and non working build logs, and adding a tool installer task to force 10.16.3 addresses the issue. 

Is this update expected?

**Comment by wis3guy** [comment]
@StingyJack I think your are correct. My npm builds are also failing since November 6th, with the following error:

```
Starting: Build web frontend
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.151.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /home/vsts/work/_temp/ff1649e6-d736-4a71-b5c3-8c5e262d2ad6.sh

> yorkie@2.0.0 install /home/vsts/work/1/s/node_modules/yorkie
> node bin/install.js

CI detected, skipping Git hooks installation

> node-sass@4.11.0 install /home/vsts/work/1/s/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-72_binding.node": 

HTTP error 404 Not Found

... etc ...
```

The exact same build ran fine on November 4th.

**Comment by StingyJack** [comment]
Ours started doing that a day or two later, but that's what it looks like just before a bunch of `node gyp` diagnotic statements that report the version of npm being different. 

I sure hope something else is at play, and that the pipeline image team didnt decide to jump a component two major versions without any kind of notice. Last time they bumped python from 3.6.7 to 3.6.8 I lost a few hours trying to get 3.6.7 working again.

**Comment by wis3guy** [comment]
Just as an update: I found a way to work around, by forcing a specific version of nodejs using the `Node.js tool installer` (https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops) as the first step of my build.

To stave the assumption that the build agent has changes, see this commit to the wiki for the recent changes: https://github.com/microsoft/azure-pipelines-image-generation/commit/d41f85143bb1fa38ffca75b456d94ca1cd326dea#diff-f87405c9dd43f633a04dd078666d61af

The commit date coincides with the moment my build stopped working.

**Comment by StingyJack** [comment]
Good detective work @wis3guy.

I wonder if a PM or PE will even recognize they are screwing up when they do this. It's probably time to open another support incident so they treat this as official.

**Comment by gep13** [comment]
@StingyJack @wis3guy nodejs is installed on the base image using Chocolatey, which you can see here:

https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/win/scripts/Installers/Install-NodeLts.ps1#L16

This is done using the command:

`choco install nodejs-lts -y --force`

On the 22nd October, the LTS version of the NodeJS Chocolatey package changed from 10.16.3 to 12.13.0 which is in line with the LTS release notes here:

https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.13.0

Since the Chocolatey command isn't pinned to install a specific version of the nodejs-lts package, it will simply install the latest available package, which as I mentioned is 12.13.0.  After the 22nd October, any execution of the Packer build for the build agents would result in 12.13.0 being installed.

Now, I am not saying that this is expected from a build agent point of view, but certainly, it is expected from the way that Chocolatey has been configured to install the package.  If you want an older version of node to be installed, you would need to change the Chocolatey installation command to be:

`choco install nodejs-lts -y --force --version 10.16.3`

**Comment by StingyJack** [comment]
@gep13 - please dont assume there is any kind of flippant tone to this response, instead take it as constructive feedback. 

As someone who pays for this service,  I shoudn't (and dont) really care what path things take to get to the end result of a hosted agent image. I'm also not going to go looking up release notes for things that I dont expect to have changed. 

You are really not at the mercy of some other thing upstream as your response suggests. Controlling the quality of your product is as simple as comparing the image you generate today with the one that is known good and identifying the differences. Are there differences that carry negative effects like breaking changes? You have a choice there to do a few things, but the correct choice is not the one where "things just happen" and come without any warning or analysis of impact to customers on your part. 

To spell it out, it is irresponsible and unacceptable to change the customers build environment without notification, but I think most of us would let you slide with minor or patch version updates. However upgrading something by two full breaking change major versions needs to be on the list of things you choose to not include in the image update. 

This team needs to do a lot better at communicating changes to the images, and the info and docs about them must precede the rollout of the image by at least 2 weeks.  And we will need to know two weeks ahead of time if the upcoming change is actually going to break our builds, so we have enough time to plan around it. 

Any build definition

**Comment by gep13** [comment]
@StingyJack I totally agree with you! 😄 

My explanation was really addressing the "way" that NodeJS is currently installed.  

As someone who works for Chocolatey, I wanted to make sure that there was no ambiguity in this area, i.e. it is just doing what it was told to.  My recommendation to do:

`choco install nodejs-lts -y --force --version 10.16.3`

was really aimed at the maintainers of this repository.  

Pinning to a specific version number gives you the most reliable, repeatable, way of creating the base build images, without inadvertently impacting users.  Jumping to the next version of an application should be something that is opted into, rather than something which happens by surprise.

**Comment by azureDaveOps** [comment]
The answer to the original question, yes, the version changed.

With hosted images we balance the tooling that is on the image against the size of the disks we have available.  Every tool we add is less space we have for the customer to use on the disk during their build.  We try to support as many ecosystems at as many versions as possible, but as you have found, the limitation is that we stop supporting older versions over time.  The workaround, which you already called out in this thread, is modify your build to install specific versions you have dependencies on.

The other end of the spectrum is to create your own private agents where you totally control the machine and all the installed software that runs your build.  I do understand that this can take effort on your part, it certainly isn't as easy as using a hosted machine.  But this approach does give full control to install software and run on hardware you require for your pipeline.

To close the gap between these extreme options, we are working on a "Bring Your Own Subscription" feature right now, with plans for General Availability early 2020.  The gist is to use a customer's VM Scale set in their Azure subscription (and eventually will also support Docker images) and have Azure DevOps manage the pool size using that image.  We believe this will bring the strengths of having Azure DevOps manage the elasticity of the machine pool AND give control of the image to the customer.

**Comment by StingyJack** [comment]
@azureDaveOps  - I've been authoring builds and installing / admin TFS servers since 2008 in all the different build systems, so  I'm not saying i cant do some kind of server or agent maintenance
 (even though maintenance is kind of expected in some fashion from a service provider). 

I am saying you cant keep surprising us with an every-build-in-the-organization-starts-breaking-one-day panic every few weeks. Its not right.

I'm not going to ask you to revert anything or restore from backup (still waiting on that btw), but I am going to expect that the product team recognizes the stress and productivity interrupt that gets created from this kind of event and starts working toward avoiding the patterns of behaviors and decisions that lead to this kind of scenario happening.  Can you close the gap in the meantime by giving some advance notice and documentation updates ahead of time, or at least trying to avoid jumping two major versions of a package at once? 

Maybe longer term you could pick a few random build defs and agents from the existing customer pool and run a few of their builds on the new image before GA

**Comment by wis3guy** [comment]
@azureDaveOps You clossed the issue, but i feel you are simplyfying the problem.

Regardles the fact that the agent always has the latest stable version of all this tooling installed, without the slightest notification of changes, the software installed should work. That is priority #1, right?

I feel that the installed node version is broken, given the logs that i included in the issue. Apparently the installed `npm` or `nodejs` version attempts to download a dependency, which does not exist. This is **not** done in my code, as i only run `npm i` as a first task.

I suggest you validate the correctness of the tooling.

**Comment by RicardoLans** [comment]
@azureDaveOps its understandable that you want the latest stable versions of tooling installed by default, but please make sure that the README's are also updated.... 
That makes looking for differences in why builds suddenly stopped working one day after another much easier...

current readme:
images/win/Vs2019-Server2019-Readme.md

stating that it still uses node.js version 10.16.3 but it is using 12.13.0

**Comment by StingyJack** [comment]
@azureDaveOps - 3.5 weeks after reporting this, the docs still out of date, and per the closure of this, I could expect that they will no longer be getting updated. Hopefully its not because everyone is working on the thing you explained above that does not solve the operational/process problem that is the root of this complaint. 

BYOS sounds like a push off resulting in more work for your customers have to expend just to account for a **service reliability issue**.  If we wanted the fun of managing a build server, we would have hosted one privately like the good old days of on prem TFS. We use the hosted agent because we are willing to pay a fee to avoid managing it. 

Also we want less complicated and reliable. Wiring in an Azure subscription into Devops is already kind of a mess with the service connection, it being a resource tied to a bill (so thus more tightly controlled by IT/OPS) and how it cant seem to share already established service connections with other admins in the project 

for posterity, docs still not updated 24 days after reporting it.
![image](https://user-images.githubusercontent.com/15381181/70206402-768d6d00-16f5-11ea-97f3-3625a1d437ab.png)

**Comment by azureDaveOps** [comment]
Please know that I and the rest of the product team hear you loud and clear on this, and we are aware of this gap.  The problem, and we realize it is a problem, is that the images are moving faster than is acceptable for some customers.  My previous post details the tension of our current options.  I am only closing this because it is by-design... currently. 

The first step we are taking is to provide that middle-ground of allowing a customer to control the image via VM scale-sets. That is planed to release early next year.  The next step is to give more options on hosted image selection, a "fast" image for latest toolsets, and also a more stable, more slowly changing stable image.  That work is bigger than a bug, which is why we are not tracking it here, it is on our roadmap for Q3 (Jan-March).

**Comment by StingyJack** [comment]
@azureDaveOps - Thanks for explaining that facet (a little more communication like this can prevent escalations and bad feelings almost every time).  Do you use Oct-Dec as Q2, or is that just a typo? 

To me, a VM scale set means yet another non-shareable connection with Azure cloud. Service connections are already this kind of headache since they require some kind of creation within a resource group and that means it could affect an invoice. Every time we need to add an AppService deploy task to a release pipeline we have to  request permission from IT and wait, then have the permission revoked when its setup and working. It would be different if service connections worked like the docs say, but they dont. Every developer can only see their own connections, nobody can reuse existing ones that someone else has already created.  I still dont think the VM scale set is the solution to the problem because it means the build agent is something I have to manage again instead of paying you all to manage it.  At least try not to replicate the service connection experience with whatever you eventually come up with.
