### ISSUE TITLE
Update Xcode 11.2.1

### ISSUE THREAD

**Issue by alombard** [microsoft/azure-pipelines-image-generation#1394]
**Tool information**
- Tool name: Xcode
- Add or update? Update
- Desired version: 11.2.1

**Areas and ecosystems**
 [x ] iOS, macOS, and Apple-specific tools

**Image impacted**
macOS (all)

**Workaround**
None. 

**Issue**
Apple now requires 11.2.1 to submit any builds is it possible to get this image updated? We have apps that can't be submitted at the moment.

Thanks in advance,

Andrew

**Comment by maxim-lobanov** [comment]
Hi, we are on track with this request. Xcode 11.2.1 will be available in a few days

**Comment by jeroenleenarts** [comment]
@maxim-lobanov Eagerly awaiting your work. :)

**Comment by maxim-lobanov** [comment]
Xcode 11.2.1 GM is available on macOS-10.14 machines

**Comment by jeroenleenarts** [comment]
Works on our builds. 👍

**Comment by alombard** [comment]
Thanks very much!

Andrew

________________________________
