### ISSUE TITLE
Update fastlane

### ISSUE THREAD

**Issue by dsw-jeremiah** [microsoft/azure-pipelines-image-generation#1396]
**Tool information**
- Tool name: fastlane
- Add or update? update
- Desired version: 2.135.2 or latest version

**Areas and ecosystems**

- [x] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [x] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [x] Xamarin
- [ ] Other

**Image impacted**
Currently using macos-latest

**Workaround**
As of Dec. 1st the version of fastlane will be using V2 of the Google Play Developer API which will be no longer supported. Fastlane has upgraded to a supported version in 2.135.0 and has also released two subsequent patch releases as well.

The workaround will be to manually upload APKs to the Play Console after Dec 1st.

**Are you willing to submit a PR?**
Yes, if someone points me in the right direction I would be happy to submit a PR to update this dependency.

**Comment by kaylangan** [comment]
fastlane is now at v2.139.0
