### ISSUE TITLE
Hosted MacOS agents appear to hang indefinitely

### ISSUE THREAD

**Issue by ChrisGheen** [microsoft/azure-pipelines-image-generation#1402]
**Describe the bug**
Hosted MacOS agents appear to hang indefinitely, no jobs are starting. They stay at "Acquiring an agent from the cloud: Waiting for a job." until they time out.  We have 2 jobs that use MacOS agents, one is labelled "Pool: Azure Pipelines Image: MacOS", the other is labelled "Pool: Hosted macOS". Neither gets started. Our other agent jobs all work successfully (ubuntu, hosted vs2017)

**Expected behavior**
Hosted MacOS agents start up correctly.

**Actual behavior**
Queue our Mobile build, the Ubuntu npm package job finishes correctly, then the two MacOS jobs hang.

**Image impacted**
Hosted MacOS, Azure Pipelines: MacOS

**Comment by diogot** [comment]
Same issue here, I had a couple started after more than 50 min in the queue.

**Comment by davidism** [comment]
There's an active event about this on their status page: https://status.dev.azure.com/_event/159022677
