### ISSUE TITLE
GenerateResourcesAndImage.ps1 doesn't work

### ISSUE THREAD

**Issue by snnn** [microsoft/azure-pipelines-image-generation#1403]
**Describe the bug**
GenerateResourcesAndImage.ps1 doesn't work

**Expected behavior**

**Actual behavior**
GenerateResourcesAndImage : Cannot bind parameter 'PasswordCredential'. Cannot convert the "System.Security.SecureStrin
g" value of type "System.Security.SecureString" to type "Microsoft.Azure.Commands.ActiveDirectory.PSADPasswordCredentia
l".
At line:1 char:1
+ GenerateResourcesAndImage  -SubscriptionId 8b3247dd-e2ef-4e7b-ad5f-e9 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [GenerateResourcesAndImage], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,GenerateResourcesAndImage

1. Step 1
Install Azure powershell module
2. Step 2
. .\GenerateResourcesAndImage  ...........

**Image impacted**
Windows

**Comment by snnn** [comment]
Seems it can be fixed by:

```patch
+       $secpassw = New-Object Microsoft.Azure.Commands.ActiveDirectory.PSADPasswordCredential -Property @{ StartDate=Get-Date; EndDate=Get-Date -Year 2024; Password=$ServicePrincipalClientSecret}
-    $sp = New-AzureRmADServicePrincipal -DisplayName $spDisplayName -Password (ConvertTo-SecureString $ServicePrincipalClientSecret -AsPlainText -Force)
+    $sp = New-AzureRmADServicePrincipal -DisplayName $spDisplayName -Password $secpassw
```

**Comment by drr1217** [comment]
I am still getting the same issue even with the code fix stated above. Anyone else find a resolution to this?

**Comment by haokanga** [comment]
@drr1217 A reminder that you need to rerun `. .\GenerateResourcesAndImage.ps1` to reimport the `Function GenerateResourcesAndImage`.
