### ISSUE TITLE
Add Rustup on macOS

### ISSUE THREAD

**Issue by fstephany** [microsoft/azure-pipelines-image-generation#1404]
**Tool information**
- Tool name: rustup
- Add or update? add
- Desired version: latest
- If this is an add request:
  - Brief description of tool: rustup is a (the?) rust toolchains installer
  - URL for tool's homepage: https://rustup.rs/

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [X] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
macos-latest

**Workaround**
Install during build. Having the latest stable Rust instead of Rustup is also an option. 

**Are you willing to submit a PR?**
Yes, but the code generating the macOS image does not seem to be public.

**Comment by kaylangan** [comment]
Related to: https://github.com/actions/virtual-environments/issues/6
