### ISSUE TITLE
Unable to connect to VSTS LocalDB instance

### ISSUE THREAD

**Issue by jannikbuschke** [microsoft/azure-pipelines-image-generation#1409]
Im trying to run integration tests with EF Core and mssqllocaldb inside an Azure build pipeline.

First the service needs to be started (i.e. with powershell):
`sqllocaldb start mssqllocaldb`

Using `Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=mydb;Integrated 
Security=True;Trusted_Connection=True` yields following error:

`System.Data.SqlClient.SqlException : Cannot open database "mydb" requested by the login. The login failed.
Login failed for user 'fv-az74\VssAdministrator'.
`

(I also tried without Integrated Security=True and Trusted_Connection=True)

related: #194 

Im not sure since when this happens.

**Comment by efleming18** [comment]
I am also seeing this issue. Although, it does not seem to happen consistently. One run will throw that error, the next won't.

**Comment by niadak** [comment]
@efleming18 , @jannikbuschke Are you facing this issue in VS2017 images also?

**Comment by jannikbuschke** [comment]
@niadak I face this issue on on vs2017-win2016 and windows-2019 (for me this happens consistently)

**Comment by niadak** [comment]
Can you please share the task debug logs with us for further investigation?

**Comment by niadak** [comment]
@jannikbuschke, @efleming18  Can you please share the debug logs of the failed pipeline? You can set System.Debug variable as True and run the pipeline to generate the debug log

**Comment by jannikbuschke** [comment]
@niadak I have sent a log to given email address.
I cancelt the pipeline run after 13 min, as it typically does not proceed after the failing sql login attempts.
I also tried to reproduce the issue with two newly create pipelines, one classic and one with yaml. There I was not able to reproduce the issue.

**Comment by jannikbuschke** [comment]
I probably have found my issue. I usually apply my EF Core migrations during startup of the application. My tests however do not execute this path, thats why my database just seems to be missing => "Login failed". As I am able to use mssqlocaldb within another pipeline, I assume the problem lies within my code.

**Comment by niadak** [comment]
Thanks @jannikbuschke for the update. We also didn't change anything from our side recently. Can you please close this issue as there is no AI on our side?

**Comment by efleming18** [comment]
I switched the "test" task that I was using in the Azure Pipeline build from VSTest, to running it from the DotNetCli task and since then, I've not seen the issue.
