### ISSUE TITLE
[Ubuntu] Failed to apt-get libmysqlclient-dev

### ISSUE THREAD

**Issue by ivailop** [microsoft/azure-pipelines-image-generation#1410]
**Describe the bug**
On Ubuntu 16.04, since today (11/20/2019), installation of `libmysqlclient-dev` errors out:
```
sudo apt-get libmysqlclient-dev
...
Err:87 http://security.ubuntu.com/ubuntu xenial-security/main amd64 libmysqlclient-dev amd64 5.7.27-0ubuntu0.16.04.1
  404  Not Found
...
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/m/mysql-5.7/libmysqlclient-dev_5.7.27-0ubuntu0.16.04.1_amd64.deb  404  Not Found

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Expected behavior**
Install successfully

**Actual behavior**
Errors out.

```
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/m/mysql-5.7/libmysqlclient-dev_5.7.27-0ubuntu0.16.04.1_amd64.deb  404  Not Found
```

**Image impacted**
ubuntu 16.04

**Comment by ivailop** [comment]
It looks like `5.7.27` has been superseded by `5.7.28` - see http://changelogs.ubuntu.com/changelogs/pool/main/m/mysql-5.7/mysql-5.7_5.7.28-0ubuntu0.16.04.2/changelog

**Comment by IceChaser24** [comment]
same problem, u know how to fix this?

**Comment by ivailop** [comment]
With the new [20191202.1](https://github.com/microsoft/azure-pipelines-image-generation/releases/tag/ubuntu16%2F20191202.1) release being deployed, now the issue appears to be resolved for me.
