### ISSUE TITLE
Add a "Planned rollout/timeframe" document

### ISSUE THREAD

**Issue by kelps** [Microsoft/azure-pipelines-image-generation#142]
It would be REALLY useful if there was a document here explaining how the rollout of new images work and showing the planned timeframe for adding/updating what goes in the images.

Explaining the rollout would be good to help us know how long it takes from accepting a pull request here to having the new images updated in VSTS. Having a planned timeframe would help VSTS users with planning there own updates. It would also reduce the number of timeframe related issues created in this repo.

Every time a new version of .NET, .NET Core, Visual Studio, etc comes out, we become "hostages" of a black box process because we don't know when those features will be available in the Hosted Agents. So, either we delay the usage of the new features by an unknown amount of time, until the hosted agent is updated or we are forced to create and maintain our own build agents (which many of us are trying really hard to avoid).

**Comment by vtbassmatt** [comment]
Hey @kelps, we agree. We'll try to get a roadmap put together here. It's going to take a bit of time (this is on my plate but I'm on leave for a little while) so I'll leave the issue open until we have something predictable.

**Comment by kelps** [comment]
Thanks @vtbassmatt.

**Comment by densto88** [comment]
@kelps Totally agree with the feedback, just wanted to mention that for the Hosted VS 2017 agents the builds now execute as an admin in an interactive session. No need to be held hostage for installs that should be relatively quick anymore.

**Comment by kelps** [comment]
@densto88 Unfortunately a .NET Framework install isn't quick and could have side effects in the hosted build agent. Yes, i can see that getting a new .NET Core release would be possible, but if my project relies on a new feature in the full .NET Framework or a new version of VS to build properly, I don't think installing during a build is a good idea, and I also don't like the idea of changing the build definition to include the installation of build tools if I can avoid it.

For example: right now we are waiting for the Hosted VS 2017 machines to start supporting .NET 4.7.2 in order to be able to start using 2 new features in ASPNET in one of our projects (the features are same-site cookies and DI support in web forms for a product we have that can't be upgraded to MVC). If there was a plan or an expected timetable we could better plan our changes and release schedule of the new features in our product.

**Comment by densto88** [comment]
@kelps You're right, it's not a great solution for larger installs like VS but it's there when you need it for the smaller stuff. The Tool Installer tasks can be a big help for this kind of thing and we pre-cache many of the tool versions on the images directly to minimize execution time.

This packer based workflow for our images is still a fairly new process for us but I think we've gotten to the point where we should be able to deliver more incremental updates. It's too easy to fall into the trap of trying to batch multiple software updates into a single image update and ending up with an issue/bug in one of them holding up the update of the rest. I'm pretty sure that's the case here.

**Comment by pundj** [comment]
Could we also get a way to subscribe to updates to a particular image?
