### ISSUE TITLE
.NET Core 3 on MacOS

### ISSUE THREAD

**Issue by jamers99** [microsoft/azure-pipelines-image-generation#1420]
**Tool information**
- Tool name: .NET Core
- Add or update? update!
- Desired version: 3.x
- If this is an add request:
  - Brief description of tool: It's .NET boys!
  - URL for tool's homepage: https://dotnet.microsoft.com/download

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [X] iOS, macOS, and Apple-specific tools
- [X] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [X] Testing and code coverage
- [X] Xamarin
- [ ] Other

**Image impacted**
macOS-latest

**Workaround**
Not use .NET Core 3 :(

**Are you willing to submit a PR?**
I can't, no :(

**Comment by maxim-lobanov** [comment]
Hi, 
You should use [Use .NET Core task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops) to switch .Net Core to 3.x
Please let me know if you have any questions.

```
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 3.0.100
```

**Comment by jamers99** [comment]
That worked but it's quite annoying and not very intuitive to have to do that.  Any plans on fixing it?

**Comment by maxim-lobanov** [comment]
No plans for now, because setting .Net Core 3.x by default will be breaking change for some old Mono versions.

I believe that using `Use *` tasks (like `Use Node`, `Use .NET Core`, `Use Ruby`, `Use Python` and etc) is the best practice since image can be updated suddenly and such tasks will ensure that build uses specific version.

**Comment by maxim-lobanov** [comment]
I am closing the issue. Feel free to reopen if you have any questions
