### ISSUE TITLE
Add .NET Core 3.1 SDK

### ISSUE THREAD

**Issue by chvrl** [microsoft/azure-pipelines-image-generation#1435]
**Tool information**
- Tool name: .NET Core SDK
- Add or update? add
- Desired version: 3.1.100
- If this is an add request:
  - Brief description of tool: self-explanatory
  - URL for tool's homepage: https://dotnet.microsoft.com/download/dotnet-core/3.1

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [x] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
ubuntu-latest, others that have .NET Core SDKs

**Workaround**
Our current mix of dependencies requires us to add steps to install both the .NET Core 2.1 and .NET Core 3.1 SDKs.

**Are you willing to submit a PR?**

**Comment by reyou** [comment]
Any Update on this?

I am installing the SDK manually, but this time I am receiving following error;

![image](https://user-images.githubusercontent.com/6571483/71501981-09bc4d00-2833-11ea-81c1-60f16b507eae.png)

![image](https://user-images.githubusercontent.com/6571483/71501995-1f317700-2833-11ea-86f4-b7f684d6f709.png)

**Comment by RobertDougan** [comment]
Is there an ETA for this?

**Comment by arthg** [comment]
In the mean time:
- task: UseDotNet@2  
  displayName: 'Get .NET Core 3.1 SDK'  
  inputs:  
    packageType: 'sdk'  
    version: '3.1.x'

**Comment by kaylangan** [comment]
This is being addressed in https://github.com/actions/virtual-environments/pull/164.

Once that's merged, it should take about a week to deploy.

**Comment by parrainc** [comment]
I just created https://github.com/actions/virtual-environments/issues/396 after I realized this issue was opened. the PR mentioned was merged 12 days ago, but still the SDK not available in the vmImage.

Any ETA when this could be available in azure devops?
