### ISSUE TITLE
PowerShell version needs to be updated on Hosted windows-2019

### ISSUE THREAD

**Issue by jalajmsft** [microsoft/azure-pipelines-image-generation#1436]
**Describe the bug**
Tasks are failing on the windows-2019 image while executing the PowerShell script that throws a warning message. The same script is running successfully on the windows-2016 image.

It seems like the issue is with Powershell version 5.1.17763 installed in windows-2019. The warning messages are written to the error stream return 1 as exit code instead of 0 resulting in the task to fail. 

**Expected behavior**
Powershell scripts should not fail on the warning messages.

**Actual behavior**
Powershell scripts fail on the warning messages.

**Image impacted**
windows-2019

This issue was reported in multiple channels
[Azure pipeline task repo](https://github.com/microsoft/azure-pipelines-tasks/issues/11543)
[Developer Community](https://developercommunity.visualstudio.com/content/problem/752118/az-cli-reports-warnings-that-breaks-releases.html)

**Comment by andrewtyped** [comment]
This is not stale, please leave open. I am unable to use warnings in custom PowerShell scripts in Azure PIpelines due to this issue.

**Comment by al-cheb** [comment]
Hello, @andrewtyped 
Could you please create a bug/issue at the repo https://github.com/microsoft/azure-pipelines-tasks/issues ?

**Comment by maxim-lobanov** [comment]
Hello,
Currently, Windows-2019 image contains Powershell 7.0. Check if the issue is resolved, if not - it is better to log the issue in azure-pipelines-tasks repository because it is not the image issue

**Comment by andrewtyped** [comment]
After re-testing, I am no longer able to reproduce the issue. Thank you!

**Comment by chenbojian** [comment]
@maxim-lobanov Can you provide some information about how you fixed this issue? We have the custom windows 2019 agent. We are encountering the same issue.

powershell 5.1.17763 in microsoft hosted agent finish successfully.
powershell 5.1.17763 in custom agent finish with NativeCommandError.

**Comment by maxim-lobanov** [comment]
Hello @chenbojian ,
We just updated PowerShell to latest version to fix this issue.
On hosted agents, we use the following code to install PS Core:
```
Invoke-Expression "& { $(Invoke-RestMethod https://aka.ms/install-powershell.ps1) } -UseMSI -Quiet"
```
Link: https://github.com/actions/virtual-environments/blob/master/images/win/scripts/Installers/Install-PowershellCore.ps1

It installs the latest version of PowerShell

**Comment by chenbojian** [comment]
@maxim-lobanov The powershell 7 did solve the problem. 

But we are using a feature called `workflow` which is not supported in powershell 7. So we have to use powershell 5. 

Here is the job I created to reproduce the issue. In microsoft hosted agent 2016 and 2019, the job will succeed. In my custom agent, the job will fail with NativeCommandError.
```
    - job: a6
      pool:
        name: XXX
        demands: XXX
      steps:
      - powershell: |
          $PSVersionTable
          cmd /c 'echo this will crash powershell 1>&2'
``` 

I printed the $PSVersionTable, it shows that my custom image is having the same powershell version.
```
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.17763.1007                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.17763.1007                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1   
```

I am trying to find the difference between my vm and microsoft hosted agent.

**Comment by chenbojian** [comment]
I would like to update my findings.
After I installed .net framework 4.8, the problem on powershell 5 solved.

But I didn't find any bugs/known issues related to .net framework 4.7.2 in https://github.com/microsoft/dotnet/tree/master/releases/net472 .

Can you help me to understand what is the root cause?

**Comment by maxim-lobanov** [comment]
@chenbojian, Sorry, I am not familiar with your environment so I can't diagnose issue with self-hosted agent. 
Based on official documentation, PowerShell 5 requires .net framework 4.5+.
Probably, you can ask in PowerShell repo about this issue: https://github.com/PowerShell/PowerShell
