### ISSUE TITLE
VS 2019 16.4 and .NET Core 3.1 hosted agent availability

### ISSUE THREAD

**Issue by msebolt** [microsoft/azure-pipelines-image-generation#1438]
Referenced from https://github.com/MicrosoftDocs/vsts-docs/issues/6565:

Hi there,

Just wanted to see if someone could share ETA for VS 2019 16.4 and .NET Core 3.1 hosted agent availability please.

Thanks in advance.

**Comment by msebolt** [comment]
Including @usysware

**Comment by IanKemp** [comment]
Hosted agent images should really be available with the latest .NET Core version on the day that version drops. I don't understand why this is so difficult for Microsoft to coordinate.

**Comment by IanKemp** [comment]
See also: https://github.com/microsoft/azure-pipelines-image-generation/issues/1435

If you need to use Core 3.1 right now in a pipeline, you need to use the [Use .NET Core](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops) task with the version specifier set to `3.1.x`:

```yaml
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
```

**Comment by msebolt** [comment]
@IanKemp The request was more along the lines of the [version](https://github.com/microsoft/azure-pipelines-image-generation#image-contents) info page.

Good with Visual Studio versioning, but no info on .NET Core.

**Comment by msebolt** [comment]
Great, thanks for the info.

From the reference above, the info can be found at https://github.com/microsoft/azure-pipelines-image-generation/blob/releases/vs2019/20191204/images/win/Vs2019-Server2019-Readme.md#net-core.
