### ISSUE TITLE
.NET Core 2.1 Global Tools need location in the path

### ISSUE THREAD

**Issue by onovotny** [Microsoft/azure-pipelines-image-generation#145]
.NET Core Global Tools need a location added into the path Windows, Linux, and macOS.

See here for details:
https://natemcmaster.com/blog/2018/05/12/dotnet-global-tools/#path-and-command-not-after-installing

**Comment by lokesh755** [comment]
I could see  "$env:USERPROFILE/.dotnet/tools" is getting added for Windows, Did you see it missing for Linux or macOS ?

**Comment by bryanmacfarlane** [comment]
@kmkumaran

**Comment by kmkumaran** [comment]
@sachinma can you take a look at this.

**Comment by DavidStaheli** [comment]
This appears to be fixed by [Microsoft/azure-pipelines-tasks#8432](https://github.com/Microsoft/azure-pipelines-tasks/pull/8432).  Can this issue be closed?

**Comment by sachinma** [comment]
Adding @bishal-pdMSFT

**Comment by bishal-pdMSFT** [comment]
https://github.com/Microsoft/azure-pipelines-tasks/pull/8432 fixes this problem only when .Net Core tool installer task is used. It does not fix the issue in hosted images.

**Comment by bishal-pdMSFT** [comment]
@DavidStaheli can you please add me to this repo so that I can assign the issue to myself and possibly raise PR.

**Comment by DavidStaheli** [comment]
@bishal-pdMSFT you should receive an email invite - thanks!

**Comment by bishal-pdMSFT** [comment]
I don't think we can set Global tools path for hosted image. Global tools are [user-specific](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools#install-a-global-tool). Any user specific path set in image generation scripts will be removed by Sysprep as it deprovisions the user. Also the agents run with a different user from the one Packer uses.

**Comment by bishal-pdMSFT** [comment]
> Also the agents run with a different user from the one Packer uses.
I might be wrong about this though. @lokesh755 does packer run with same user as hosted agent?

**Comment by bishal-pdMSFT** [comment]
@onovotny @scottaddie Given that this issue can't be fixed in hosted image, do you think an alternative would be to fix this in ".Net Core" task. This task will additionally add global tools path to PATH(for that release). By default this option will be turned off, but if a user chooses to use this task to install global tool, they can turn it on.

**Comment by hiyadav** [comment]
The Fix for this issue is merged and should roll-out with the next agent image update.
#670
