### ISSUE TITLE
Update Az.Accounts to 1.6.5 for ManagedServicesIdentity using AzurePowerShell v4 

### ISSUE THREAD

**Issue by grlima** [microsoft/azure-pipelines-image-generation#1455]
I am unable to use the Az.ManagedServiceIdentity with PowerShell because it requires Az.Accounts 1.6.5. This has recently stopped working, so I imagine there's a new version of Az.ManagedServiceIdentity which requires version 1.6.5 of Az,Accounts. The latest version available in hosted agents seem to be 1.6.2.

The same seems to have happened in the past with version 1.6.2. #1258 

Here's the error message I get upon issuing the following commands: 
Install-Module Az.ManagedServiceIdentity -Force
Import-Module Az.ManagedServiceIdentity

"This module requires Az.Accounts version 1.6.5. An earlier version of Az.Accounts is imported in the current PowerShell session. Please open a new session before importing this module. This error could indicate that multiple incompatible versions of the Azure PowerShell cmdlets are installed on your system. Please see https://aka.ms/azps-version-error for troubleshooting information."

**Comment by killercowuk** [comment]
I got around this limitation by explicitly sticking with version 0.7.2 for now;
ie.
`Install-Module -Name Az.ManagedServiceIdentity -RequiredVersion 0.7.2 -Force`
