### ISSUE TITLE
Update Windows Server 2019 Container image to 1909

### ISSUE THREAD

**Issue by snickler** [microsoft/azure-pipelines-image-generation#1457]
**Tool information**
- Tool name: Windows Server 2019
- Add or update? Update
- Desired version: 1909
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [X] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
WINCON

**Workaround**

No

**Are you willing to submit a PR?**

Yes.

**Comment by ssa3512** [comment]
Related #182 #802 and #1127
