### ISSUE TITLE
PyPy3 on MacOS is not working

### ISSUE THREAD

**Issue by lycantropos** [microsoft/azure-pipelines-image-generation#1460]
**Describe the bug**
Earlier using configuration
```yaml
  - job: 'MacOS'
    pool:
      vmImage: 'macOS-10.14'
    strategy:
      matrix:
        PyPy3:
          python.version: 'pypy3'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
```
worked fine before and
```yaml
      - script: python -m pip install "pytest>=5.2.0"
        displayName: 'Install tests requirements'
```
called an appropriate `PyPy3` executable, but now [it fails](https://dev.azure.com/lycantropos/robust/_build/results?buildId=1541&view=logs&j=45e13203-4192-52e5-41fd-d3a70dfaf12c&t=c30aceab-e8f0-56ec-db86-7b8d6146af97).

**Expected behavior**
I'm expecting it to work like for similar [Windows job](https://dev.azure.com/lycantropos/robust/_build/results?buildId=1541&view=logs&j=3cc2c57c-1447-5abb-98e0-1d61c99916d1&t=004d1565-0e92-59b5-942f-a67ae252abe6).

**Actual behavior**
1. Run plan with configurations like
```yaml
jobs:
  - job: 'MacOS'
    pool:
      vmImage: 'macOS-10.14'
    strategy:
      matrix:
        PyPy3:
          python.version: 'pypy3'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
      - script: python -m pip install "pytest>=5.2.0"
        displayName: 'Install tests requirements'
```
2. Wait.

In console we can see
```bash
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
ERROR: Could not find a version that satisfies the requirement pytest>=5.2.0 (from versions: 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.4.0, 2.4.1, 2.4.2, 2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.8.7, 2.9.0, 2.9.1, 2.9.2, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.2.4, 3.2.5, 3.3.0, 3.3.1, 3.3.2, 3.4.0, 3.4.1, 3.4.2, 3.5.0, 3.5.1, 3.6.0, 3.6.1, 3.6.2, 3.6.3, 3.6.4, 3.7.0, 3.7.1, 3.7.2, 3.7.3, 3.7.4, 3.8.0, 3.8.1, 3.8.2, 3.9.1, 3.9.2, 3.9.3, 3.10.0, 3.10.1, 4.0.0, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.2.0, 4.2.1, 4.3.0, 4.3.1, 4.4.0, 4.4.1, 4.4.2, 4.5.0, 4.6.0, 4.6.1, 4.6.2, 4.6.3, 4.6.4, 4.6.5, 4.6.6, 4.6.7, 4.6.8, 4.6.9)
ERROR: No matching distribution found for pytest>=5.2.0
```
so my guess is that `python` points to `python2.7` instead of `PyPy3`.

**Image impacted**
Tried on both `macOS-10.13` and `macOS-10.14`.

**Comment by maxim-lobanov** [comment]
Hi @lycantropos,
We have confirmed that it is issue on our side. Thank you for the report!
PyPy 3.x is available via `pypy` and `pypy3` but links to `python` and `python3` are broken.
As a temporary solution, you can invoke PyPy as `pypy` or `pypy3`.
Will try to fix the issue as soon as possible.

**Comment by lycantropos** [comment]
@maxim-lobanov: any progress/estimation on this?

**Comment by maxim-lobanov** [comment]
We have a fix but it will be deployed with next image-rollout (Approximately, at the middle of this week). Actual progress is tracked by this [issue](https://github.com/actions/virtual-environments/issues/249).

**Comment by hugovk** [comment]
Now macOS/PyPy3 passes and our DIY "Build system information" looks good, 3.6.9 + PyPy 7.3.0:

```
Run python .github/workflows/system-info.py
Build system information

sys.version		 ['3.6.9 (1608da62bfc7, Dec 23 2019, 10:50:17)', '[PyPy 7.3.0 with GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]']
os.name			 posix
sys.platform		 darwin
platform.system()	 Darwin
platform.machine()	 x86_64
platform.platform()	 Darwin-19.2.0-x86_64-i386-64bit
platform.version()	 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64
platform.uname()	 uname_result(system='Darwin', node='Mac-1333.local', release='19.2.0', version='Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64', machine='x86_64', processor='i386')
platform.mac_ver()	 ('10.15.2', ('', '', ''), 'x86_64')
```

https://github.com/python-pillow/Pillow/runs/392723770

Thanks!

**Comment by lycantropos** [comment]
mine builds are [failing still](https://dev.azure.com/lycantropos/hypothesis_geometry/_build/results?buildId=1643&view=logs&jobId=45e13203-4192-52e5-41fd-d3a70dfaf12c&j=45e13203-4192-52e5-41fd-d3a70dfaf12c&t=f268c2e9-0a24-5716-6755-467ac3f2b07c)

**Comment by hugovk** [comment]
Ah sorry, ours are on GitHub Actions. I guess the Azure Pipelines deploy should be coming soon.

**Comment by lycantropos** [comment]
it seems to be [working now](https://dev.azure.com/lycantropos/hypothesis_geometry/_build/results?buildId=1652&view=logs&jobId=3cc2c57c-1447-5abb-98e0-1d61c99916d1), thanks, closing issue
