### ISSUE TITLE
Update Visual Studio 2019 to 16.4.3

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/azure-pipelines-image-generation#1463]
VS 16.4.3 fixed a breaking codegen bug in the c++ compiler. This bug has caused our CI builds to be broken for over a month, along with many others, so this should be pushed as soon as possible.

**Comment by kaylangan** [comment]
We pull the latest version of VS that is available at the time of image generation and we deploy approximately weekly. The current version rolling out is 16.4.2. The deployment after will have 16.4.3+.

Also, we've moved development, so please create future issues here: https://github.com/actions/virtual-environments
