### ISSUE TITLE
Azure-Devopos CLI extensions is not installed on the Ubuntu 16.04 hosted agent

### ISSUE THREAD

**Issue by SiM22** [microsoft/azure-pipelines-image-generation#1478]
Opening as an issue alredy reporting this was closed without any response @olandese
https://github.com/microsoft/azure-pipelines-image-generation/issues/1314

According to the readme (https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/linux/Ubuntu1604-README.md) the Azure CLI DevOps extension should be installed Azure CLI (azure-devops 0.12.0).

Running pipeline on the hosted :

It seems that the azure-devops cli extensions is not installed on the Ubuntu 16.04 hosted agent

```WARNING: You have 2 updates available. Consider updating your CLI installation. Instructions can be found at https://docs.microsoft.com/en-us/cli/azure/install-azure-cli
azure-cli                         2.0.80 *

command-modules-nspkg              2.0.3
core                              2.0.80 *
nspkg                              3.0.4
telemetry                          1.0.4

Python location '/opt/az/bin/python3'
Extensions directory '/home/vsts/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Jan 13 2020, 05:03:40) 
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal```

It seems that the azure-devops cli extensions is not installed on the Ubuntu 16.04 hosted agent

**Describe the bug**
azure-devops cli extensions is not installed on the Ubuntu 16.04 hosted agent

**Expected behavior**
azure-devops cli extensions SHOULD BE installed on the Ubuntu 16.04 hosted agent

**Actual behavior**
azure-devops cli extensions is not installed on the Ubuntu 16.04 hosted agent

1. Step 1
2. Step 2

**Image impacted**
WINCON
<!--- PLEASE USE THIS REPO FOR REQUESTS RELATED TO THE WINDOWS CONTAINER IMAGE -->
<!--- The other images have moved to https://github.com/actions/virtual-environments -->

**Comment by SiM22** [comment]
anyone?

**Comment by SiM22** [comment]
ping

**Comment by maxim-lobanov** [comment]
Hi @SiM22, confirmed the issue.
I have created a ticket in [virtual-environments](https://github.com/actions/virtual-environments/issues/418) repo since it is the main repo for images for now.
This repository is not maintained anymore

**Comment by SiM22** [comment]
> Hi @SiM22, confirmed the issue.
> I have created a ticket in [virtual-environments](https://github.com/actions/virtual-environments/issues/418) repo since it is the main repo for images for now. Please track issue status there.
> This repository is not maintained anymore

Thanks!

**Comment by al-cheb** [comment]
Hello, @SiM22
I have prepared https://github.com/actions/virtual-environments/pull/442 PR.  Changes will be available after next image rollout (1-2 weeks approximately)
