### ISSUE TITLE
Error CS0234: The type or namespace name 'SharePoint' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by VerdonTrigance** [microsoft/azure-pipelines-image-generation#1479]
**Describe the bug**
Error CS0234: The type or namespace name 'SharePoint' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)

**Expected behavior**
Sharepoint 2013 succefull build (https://github.com/actions/virtual-environments/blob/master/images/win/Windows2016-Readme.md has SharePoint software on it)

**Actual behavior**
This is piece of yaml build template that leads to error
jobs:
- job: ${{ parameters.jobname }}
  displayName: 'Build solution ${{ parameters.solution }}'
  timeoutInMinutes: 60
  cancelTimeoutInMinutes: 15
  pool:
    vmImage: 'vs2017-win2016'

What pool I have to use to build sharepoint 2013 solution? I thought that one: https://github.com/actions/virtual-environments/blob/master/images/win/Windows2016-Readme.md

**Comment by maxim-lobanov** [comment]
Hello,
It looks like `SharePoint Client SDK` should be installed to use Microsoft.SharePoint library. Actually, it is not installed on the image.
Please log the issue on https://github.com/actions/virtual-environments to add it. `virtual-environments` is the main repository for images now.
