### ISSUE TITLE
Question: how to stick to the latest Mono version in macos-10.14 pipeline?

### ISSUE THREAD

**Issue by heng-liu** [microsoft/azure-pipelines-image-generation#1495]
Hi Team, we just transferred from a self-hosted agent pool to macos-10.14 pool.
We would like to run our builds on 
OS X 10.14.6 (18G3020) Mojave + 
Mono (6.4 above, and we would like to stick to the latest version if possible)
We just tried our first build by:
```
  pool:
    vmImage: macOS-10.14
    demands: sh
```
But the build failed as the specified agent has Mono 5.12 installed.
I checked the [doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml), and it only has example of specifying capabilities in demands.
May I know if there is a way for us to specify the latest version of Mono? Thanks!

**Comment by al-cheb** [comment]
Hello, @heng-liu

Please take a look at the Mono section - [Microsoft-hosted agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops) documentation how to switch mono.
 
Mono
To manually select a Mono version to use on the Hosted macOS agent pool, before your Mono build task, execute this script in each job of your build, replacing the Mono version number 5.4.1 as needed:

```
SYMLINK=5_4_1
MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"
```

All mono versions presented at -  https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md .

**Comment by heng-liu** [comment]
Thanks! @al-cheb
Yes, I tried the above script and it works :)
May I know if there is any way to stick to the latest version automatically? E.g. it's 6.6 for now, and when the latest version is 6.8, it will automatically change to 6.8.
It would be great if there is, as we can avoid hardcoding in yaml file.

**Comment by al-cheb** [comment]
@heng-liu
macOS 10.14 - the default mono version is 5.12.You should manually change mono version.
macOS 10.15 - the latest mono version `on the image` is the default (at the writing time mono 6.6) - https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.15-Readme.md

We follow the policy to preinstall only stable mono versions. Mono 6.8 is in preview status now.

**Comment by heng-liu** [comment]
That's very helpful! Thanks @al-cheb!
