### ISSUE TITLE
[cross-plat][py-39] Python 3.9 GA-ing soon

### ISSUE THREAD

**Issue by scbedd** [microsoft/azure-pipelines-image-generation#1530]
Hey folks, according to the [release schedule](https://www.python.org/dev/peps/pep-0596/) for Python 3.9, it will be GA on 10/5.

I understand that new issues should be filed on the github-actions repo, but I actually already followed this question over there. The [python manifest](https://github.com/actions/python-versions/blob/main/versions-manifest.json) that they support does _not_ match the versions that we can actually select on the AZDO agents.

Who do I talk to/what can I do to ensure that this support is added to our agents?

**Comment by hugovk** [comment]
I created https://github.com/actions/virtual-environments/issues/1740 at that repo.
