### ISSUE TITLE
Deployment: Update to Azure Storage Emulator 5.5 (or latest) and *add it to PATH*

### ISSUE THREAD

**Issue by LukeBillo** [microsoft/azure-pipelines-image-generation#165]
Hello,

I was redirected here - see Microsoft/vsts-tasks#7363
I currently have a VSTS build pipeline that has a set of integration tests using the Azure Storage Emulator. It seems to be installed on the build agents by default on a hard-coded path, and was wondering if it could be added to the PATH? See below.

![VSTS build pipeline](https://i.imgur.com/VGmAtSd.png)

This way, it allows the storage emulator to be started without specifying the absolute path, and would be more robust in case the location of the storage emulator ever changes. (Unlikely, but possible.)

**Comment by ColinLaws** [comment]
I'm wondering if this issue was ever resolved. We're looking at running our unit tests on an Azure DevOps build agent that rely on the Azure Storage Emulator.

**Comment by wboevink** [comment]
> I'm wondering if this issue was ever resolved. We're looking at running our unit tests on an Azure DevOps build agent that rely on the Azure Storage Emulator.

I was wondering about the exact some thing.

**Comment by kaylangan** [comment]
Re-opening due to interest
