### ISSUE TITLE
Deployment: Add AWS SDK for .NET with AWS Tools for Windows 3.3.69 (or latest) (Windows)

### ISSUE THREAD

**Issue by andyjcooperuk** [Microsoft/azure-pipelines-image-generation#166]
Would it be possible to add the AWS SDK Tools for .Net to the VSTS build agent servers. ( https://aws.amazon.com/sdk-for-net). We require this so that we can authenticate into our AWS environments from VSTS. We are currently working with AWS on the next version of the AWS Tools for VSTS which supports authenticating using AWS environment variables instead of VSTS provided service endpoints, but for this to work the AWS SDK for .Net needs to be installed on the build agent servers.

Thanks.

**Comment by DavidStaheli** [comment]
Note: it'd be good to add AWS tooling to all hosted images.

**Comment by RoopeshNair** [comment]
@andyjcooperuk  - you should be able to do so using NuGet? For extensions recommended way is to get in touch with the publisher to provide a tool installer task. That way you can get the latest updates and don't get locked with the version that is baked-in with the agent image
