### ISSUE TITLE
Request: Update Xamarin iOS SDK on macOS

### ISSUE THREAD

**Issue by nickginis** [Microsoft/azure-pipelines-image-generation#174]
Hi,

Is it possible to have Xamarin.iOS SDK 11.14.0.4 installed on the macOS image? It contains a crucial fix for using SignalR Client in Xamarin as detailed in https://github.com/aspnet/Announcements/issues/305 so it would be great for our CI build to be able to support this.

Thank you.

**Comment by ysmoradi** [comment]
The last stable release of Xamarin.iOS is 11.14.0.13
It allows us to use new asp.net core signalr client, entity framework core 2.1.2 and any other cool libraries which depend on new memory/span/buffer features.

**Comment by madhurig** [comment]
The Hosted macOS images are updated weekly with latest stable versions. Please check this page for updates: https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-Readme.md. The SDK version you are looking for is already on there. You can use a script to set the specific SDK version you want to target in your build process: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=vsts&tabs=yaml#xamarin

Thanks,
Madhuri
