### ISSUE TITLE
[Question] How to use installed node8 version instead node6 version on osx hosts

### ISSUE THREAD

**Issue by n1ru4l** [microsoft/azure-pipelines-image-generation#188]

**Comment by DavidStaheli** [comment]
Hi @n1ru4l .  Will it work for you to use the [Node.js Tool Installer](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=vsts) task at the beginning of your pipeline?

**Comment by n1ru4l** [comment]
Hey @DavidStaheli, is it possible to use the node.js tool installer with appcenter? If yo cloud you please provide an example, I could not find any information in the deocumentation.

**Comment by DavidStaheli** [comment]
Hi Laurin.  Sorry, I misunderstood and thought you were using Azure Pipelines.  @nrajpurkar do you know who can help Laurin use Node.js 8 on App Center instead of Node.js 6?

**Comment by n1ru4l** [comment]
Bunp

**Comment by n1ru4l** [comment]
Bump

**Comment by nrajpurkar** [comment]
@n1ru4l is this for React Native builds? We've added in the ability to select a specific Node.js version if so: 
![image](https://user-images.githubusercontent.com/12765610/62075610-6242dc00-b1fa-11e9-831d-c3ec82b8f016.png)

**Comment by n1ru4l** [comment]
@nrajpurkar thank you for answering my question, haven't tweaked my codebuild config in the last months, happy to see that this is finally possible!
