### ISSUE TITLE
VSTS Docker - Linux or Windows Containers

### ISSUE THREAD

**Issue by jongio** [Microsoft/azure-pipelines-image-generation#205]
Can you add to this doc whether you have Linux or Windows containers selected by default?

https://github.com/Microsoft/vsts-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md

**Comment by chrisrpatterson** [comment]
Docker EE on Server 2016 does not support Linux containers at all.

**Comment by jongio** [comment]
Do we have an agent that supports both Windows and Linux containers?

**Comment by chrisrpatterson** [comment]
You can build Windows Server 2016 based containers on the VS 2017 image and Server 1803 based containers on the Server 1803 based images and you can build Linux containers on the Ubuntu 1604 image.

**Comment by jongio** [comment]
Thanks! Do you have an example .yaml that does that?

**Comment by chrisrpatterson** [comment]
@jongio here is our current docs on building docker images https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker?view=vsts&tabs=yaml
