### ISSUE TITLE
Upgrade Service Fabric SDK to 3.2.176

### ISSUE THREAD

**Issue by Tadimsky** [Microsoft/azure-pipelines-image-generation#213]
There is a bug with the `3.2.162` version of the SF SDK which stops releases from succeeding with this error:
`Value does not fall within the expected range.`.

We need to upgrade the VSTS Agent to use 3.2.176. Here are the [release notes](https://msdnshared.blob.core.windows.net/media/2018/08/Microsoft-Azure-Service-Fabric-Refresh-1-Release-Notes-SDK-3.2-Runtime-6.3.pdf)

```
Service Fabric PowerShell
Version
Service Fabric PowerShell 3.2.176.9494
Bugs and Features
- The client-side tooling and cluster have a property called MaxMessageSize which determines the
chunk size in which data is sent from any PowerShell command to the cluster. Today, if the
MaxMessageSize property is changed on the cluster (via a config update), PowerShell
commands that are made can start failing. To fix this before this release, you must change the
property on your local cluster and start a config update in order for the PowerShell commands
to pick up the. The fix we have made in this release sends the MaxMessageSize from the cluster
to the client in the initial call the client makes to the cluster. This means you do not need to
change any property on your local cluster and do config updates. PowerShell commands can be
executed without having to worry about this property.
```

[Blog Entry](https://blogs.msdn.microsoft.com/azureservicefabric/2018/08/22/microsoft-azure-service-fabric-6-3-refresh-release-cu1-notes/).

**Comment by RoopeshNair** [comment]
@sachinma / @bishal-pdMSFT

**Comment by bishal-pdMSFT** [comment]
@Tadimsky are you completely blocked due to this? Can you take the workaround as mentioned in the blog. We don't have this update planned as of now and are bit constrained bandwidth wise.

**Comment by bishal-pdMSFT** [comment]
Service fabric SDK has been updated to version 3.2.176
