### ISSUE TITLE
Image should contain a script to run additional actions during factory disk creation

### ISSUE THREAD

**Issue by chrisrpatterson** [Microsoft/azure-pipelines-image-generation#22]
When VSTS MMS updates the pool with a new image it creates a factory-VM that is used as the snapshot base for all VMs in the pools.  As part of that process the local windows account that is used to run the agent is created.  

When the factory-vm is created and the build user exists the provisioner will call C:\UserConfig\Setup-UserProfile.ps1.  That script will run any other PS1 scripts contained in the UserConfig folder and copy the full contents of UserConfig into %USERPROFILE%.  

Any interesting data from %USERPROFILE% should be copied by the install script to C:\UserConfig as part of the packer process.

**Comment by DavidStaheli** [comment]
@lokesh755 should this remain open?  I see the last comment was in January.
