### ISSUE TITLE
Add Ansible for the Ubuntu image

### ISSUE THREAD

**Issue by mathieu-benoit** [Microsoft/azure-pipelines-image-generation#222]
Add Ansible for the Ubuntu image

Ansible allows to automate cloud provisioning, configuration management, and application deployments. The goal of this PR is to reinforce Ansible integration in Microsoft/Azure tools:

https://docs.microsoft.com/azure/ansible/

Official link to install Ansible on Ubuntu:

https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#latest-releases-via-apt-ubuntu

FYI: an associated PR Microsoft/vsts-agent-docker#140 has been created to add Ansible on the VSTS Docker image as well.

**Comment by mathieu-benoit** [comment]
Taken into account by this PR #220

**Comment by dakale** [comment]
Code merged, pending build + deployment to hosted pools

**Comment by ChristopheLav** [comment]
I have created the #229 PR because the Ansible script breaks the Ubuntu 1604 image generation after the merge related to this PR. Thanks.

**Comment by dakale** [comment]
This has been deployed
