### ISSUE TITLE
Scripting: Add/update to PowerShell Core 6.1.1 (or latest) (Windows)

### ISSUE THREAD

**Issue by sethvs** [Microsoft/azure-pipelines-image-generation#232]
It would be nice to have PowerShell Core installed in images.

**Comment by chrisrpatterson** [comment]
PowerShell  Core is already installed https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/linux/scripts/installers/powershellcore.sh

**Comment by sethvs** [comment]
Thanks.
Concerning Windows images?

**Comment by bergmeister** [comment]
@chrisrpatterson The Linux images have PowerShell Core but not the Windows images such as e.g. `Hosted VS 2017` (which one can test using `where.exe pwsh`). I recently added the option to optionally use PowerShell Core on Windows in the `PowerShellV2` task [here](https://github.com/Microsoft/vsts-tasks/pull/7913) (the change is rolling out today, see [here](https://github.com/Microsoft/vsts-tasks/issues/8386#issuecomment-424759332)), therefore it would make sense now to have PowerShell Core also available in the Windows images. cc @SteveL-MSFT @TravisEz13

**Comment by SteveL-MSFT** [comment]
@chrisrpatterson anything else that needs to be done so that customers can rely on PSCore across Linux, macOS, and Windows?

**Comment by kilasuit** [comment]
@chrisrpatterson / @DavidStaheli  has this been completed or is this still to be actioned on the VS2017 agents?

**Comment by albertodall** [comment]
As a temporary workaround, I used Chocolatey (already installed in the image) to install PowerShell Core:
I added a "Command LIne" task that executes the following command:
choco install powershell-core --version 6.1.1 -y
When I need to run my PowerShell Core script, I add a "Command Line" task that runs:
C:\Program Files\PowerShell\6\pwsh.exe myscript.ps1 [options]

**Comment by kilasuit** [comment]
@lokesh755 as you've assigned this to yourself, can you give any update on where this is currently at all?

**Comment by bergmeister** [comment]
Steve was kind enough to follow up internally and the response he got was 'Q1 2019'
https://twitter.com/Steve_MSFT/status/1074819873048485888?s=19

**Comment by natescherer** [comment]
So this appears to be (mostly) working now? However maybe 10% of the builds I run seem to have pwsh.exe missing on vs2017-win2016. Is this a bug or just a symptom of a phased rollout?

**Comment by svaenn** [comment]
> So this appears to be (mostly) working now? However maybe 10% of the builds I run seem to have pwsh.exe missing on vs2017-win2016. Is this a bug or just a symptom of a phased rollout?

I have 2 agent jobs containing a powershell task with 'Use PowerShell Core' option enabledrunning on Hosted VS2017 agents, the first job runs fine second fails with "The term 'pwsh.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

How can I make sure the hosted agent hast powershell core? Is it possible to set a demand for the agent?

**Comment by vtbassmatt** [comment]
@natescherer that's probably phased rollout.
@svaenn there's a different routing system for hosted agents, since (in theory) they're homogeneous so we don't respect demands. As a workaround, you can test for pwsh and `choco install` it if not present. Then, you only pay a speed penalty if you get put on an agent without it. (But in practice I wouldn't bother; the rollout should be complete soon.)

**Comment by DavidStaheli** [comment]
Verified that PowerShell Core exists on the VS2017 and VS2019 images.  It doesn't yet exist on the "Windows Container 1803" image, and pull request #720 addresses that.

**Comment by TravisEz13** [comment]
@DavidStaheli 	How do/will we use the VS2019 image?

**Comment by joebourneMS** [comment]
Hey Travis, we're currently working on deploying the VS 2019 image and will be posting on the Azure DevOps blog more instructions on how to use. Make sure to keep an eye on https://devblogs.microsoft.com/devops/

**Comment by felixfbecker** [comment]
Is there any way to tell the PowerShell task to use `pwsh` on Windows? https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops

**Comment by bergmeister** [comment]
In v2 of the task I added a `pwsh` property/checkbox that you set to true for that

**Comment by felixfbecker** [comment]
Oh, nice! It would be great if that had an explanation on https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops

**Comment by bergmeister** [comment]
Documentation seems to be partially auto-generated from the task itself, I suggest opening a PR for it [here](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/powershell.md) or [here](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/_shared/yaml/PowerShellV2.md)
For the moment, I think it might be good to just write a blog post about different ways of using it in yaml (file path vs inline) and then later open a PR.

**Comment by vtbassmatt** [comment]
I've got an (internal, unfortunately) PR up to fix this. Should be fixed this afternoon/evening.

**Comment by ihnorton** [comment]
Is there a reason this is not available in the VS2015 image?

**Comment by kaylangan** [comment]
@ihnorton we are not making any updates to the VS2015 image anymore.

**Comment by bergmeister** [comment]
@ihnorton
You can still install pwsh in a previous step if necessary.

**Comment by ihnorton** [comment]
@bergmeister 
> You can still install pwsh in a previous step if necessary.

Will that allow `- pwsh:` to work as a task heading? (seems to be documented as a supported syntax...)

**Comment by bergmeister** [comment]
Yes, I think so, all it really needs is pwsh being somewhere and the PATH env variable pointing to it.

**Comment by TravisEz13** [comment]
I have this which I use in a private build pool:
```
    - powershell: |
        $powerShellPath = Join-Path -Path $env:AGENT_TEMPDIRECTORY -ChildPath 'powershell'
        Invoke-WebRequest -Uri https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/install-powershell.ps1 -outfile ./install-powershell.ps1
        ./install-powershell.ps1 -Destination $powerShellPath
        $vstsCommandString = "vso[task.setvariable variable=PATH]$powerShellPath;$env:PATH"
        Write-Host "sending " + $vstsCommandString
        Write-Host "##$vstsCommandString"
      displayName: Install PowerShell Core
```
