### ISSUE TITLE
Strange race condition when using apt-get in Ubuntu 1604 agnet

### ISSUE THREAD

**Issue by chrisrpatterson** [Microsoft/azure-pipelines-image-generation#238]
numba/numba#3309

**Comment by dakale** [comment]
Related, possible duplicate of: https://github.com/Microsoft/azure-pipelines-image-generation/issues/185

**Comment by dakale** [comment]
Fixed by https://github.com/Microsoft/azure-pipelines-image-generation/commit/a1f27961f28e8a8f39f4eed27e81fddfe8caf05a#diff-7bbecaa0a2b1999de4d1ebdc3f1206cdR62
