### ISSUE TITLE
Running Xvfb on Hosted Ubuntu 1604 image

### ISSUE THREAD

**Issue by peterdanis** [Microsoft/azure-pipelines-image-generation#239]
Hi, I am trying to start Xvfb on hosted ubuntu agent as E2E testing an Electron.js application needs a virtual display. I am trying to run it as script in YAML file:

`- script: "Xvfb :99 -ac -screen 0 1600x900x24 &"`

But the script always times out. I've tried different screen&display&resolution settings but the issue persists. Any hints how to solve it? Thank you.

See my azure-pipelines.yml file below:
<details>

~~~~
name: $(BuildDefinitionName)_$(Build.Reason)_$(System.PullRequest.PullRequestNumber)_$(Rev:r)

jobs:
  - job: Linux
    timeoutInMinutes: 10
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - task: NodeTool@0
        displayName: "Use Node 10"
        inputs:
          versionSpec: 10.x
      - task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
        displayName: "Use Yarn 1.x"
        inputs:
          checkLatest: true
      - script: export DISPLAY=:99
      - script: "Xvfb :99 -screen 0 1600x900x24 &"
      - script: yarn
        displayName: "Yarn install"
      - script: yarn lint
        displayName: "Lint"
      - script: yarn cover
        displayName: "Run tests with coverage report"
      - script: npm -g i codecov
        displayName: "Install codecov"
      - script: codecov
        displayName: "Upload coverage report"
      - script: yarn build --x64
        displayName: "Build"
~~~~

</details>

**Comment by chrisrpatterson** [comment]
@peterdanis each time you specify - script you are getting a new process so any exported variables will not exist in the subsequent steps.  Also can you try redirecting the steams for xfvb?  It is possible it is holding on to the output stream and not letting the script complete.

**Comment by peterdanis** [comment]
Thanks for help. I've tried a lot of things until I found that Xvfb is running properly but Electron is not starting because of a missing dependency (`libgconf-2-4`) in the Ubuntu image.

**Comment by antonycourtney** [comment]
Hi @peterdanis Thanks for this info; I'm also trying to run electron in a build pipeline and finding that it exits immediately, even if I just run
```
ELECTRON_RUN_AS_NODE=true && electron --version
```

Two quick questions:

1. How did you determine that the issue with starting electron was the missing `libgconf` dependency? All I can immediately see is that my bash scripts exits at that point with exit code 1. Did you add a step to run `ldd` on the electron exectuable or something similar?
2. Did you find a workaround to get `libgconf` installed?  If so, what was it?

This is my first foray into setting up Azure CI so any help much appreciated!

**Comment by peterdanis** [comment]
Hi @antonycourtney. 

I've just used `electron .` and the error with missing `libgconf` appeared in the log.

You can install `libgcong` easily:
`- script: sudo apt-get update && sudo apt-get install libgconf-2-4 -y`

I am currently testing (using Spectron) and building (using electron-builder) on Win/Linux/MacOS using this config file: https://github.com/peterdanis/wrapbox/blob/master/azure-pipelines.yml

**Comment by antonycourtney** [comment]
Hi @peterdanis,

Thank you **so** much for this information and for sharing your pipeline configuration script. That is tremendously helpful and hugely appreciated!
