### ISSUE TITLE
C/C++: Add vcpkg 0.0.113 (or latest) (Linux, Windows)

### ISSUE THREAD

**Issue by qmfrederik** [Microsoft/azure-pipelines-image-generation#242]
I'm trying to migrate some of my open source projects from AppVeyor + Travis to Azure pipelines.

I've noticed [VCPKG](https://github.com/microsoft/vcpkg) is not installed by default on the Azure Pipeline images for VS.

It's installed by default on AppVeyor, hence I'm checking in to see whether there's a possibility of having it available in the Azure Pipeline images as well?

Installing VCPKG takes a while, and it may make sense to pre-compile some common librarys (say OpenSSL) as well.

**Comment by DominicCabral** [comment]
Any update on this?

**Comment by vSzemkel** [comment]
I'm using AppVeyor. They have a vcpkg preinstalled on build machines for quite a long time.
C'mon guys, this is MSFT orginated package manager. Add the support for this to Azure Pipelines, please.

**Comment by qmfrederik** [comment]
As a sidenode - it would make sense to pre-install some commonly used packages which take a while to compile. OpenSSL comes to mind; having it pre-installed in its x86 and x64 configuration could easily shave a couple of minutes off every build.

**Comment by DavidStaheli** [comment]
Work on this has begun.  :clap:

**Comment by DavidStaheli** [comment]
## Thank you, @vmapetr! 🥇

**Comment by SeanFarrow** [comment]
Is this available in the hosted windows image as yet?
Were any packages pre-installed in to the image?

**Comment by kaylangan** [comment]
This is available on the [Ubuntu 16.04](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/linux/Ubuntu1604-README.md) and the [VS2017](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md#vcpkg) images. It is currently rolling out on the [VS2019](https://github.com/microsoft/azure-pipelines-image-generation/blob/releases/VS2019/151.5/images/win/Vs2019-Server2019-Readme.md#vcpkg) image.

**Comment by SeanFarrow** [comment]
Hi,

Do we have an ETA as to when this will be available on the VS2019 images?
Also, are there plans to make this available on the Mac Osx images?
Thanks,
Sean.

**Comment by kaylangan** [comment]
> Do we have an ETA as to when this will be available on the VS2019 images?

Depends on which ring your account is on, but were currently on track for EOW for all rings.

> Also, are there plans to make this available on the Mac Osx images?
@nrajpurkar  can better answer this question than I can. 😄

**Comment by SeanFarrow** [comment]
Thanks, is there a way to get notifications when image updates occur?

**Comment by kaylangan** [comment]
@SeanFarrow with our next release, we will put the start date and estimated end date for our deployment in release details for each image: https://github.com/microsoft/azure-pipelines-image-generation/releases
