### ISSUE TITLE
Hosted macOS - Carthage installed but no pipeline actions to run it

### ISSUE THREAD

**Issue by kyanar** [Microsoft/azure-pipelines-image-generation#243]
The hosted macOS agents according to the image description have Carthage installed, but there are no Carthage actions to add to the pipeline, so we cannot actually update Carthage dependencies or build linked frameworks, which we need to be able to effectively manage package dependencies ala NuGet or NPM.

**Comment by DavidStaheli** [comment]
Ah yes, I see now.  @kyanar, can you please log this issue in the tasks repo?  That's where all the pipeline tasks live.  https://github.com/Microsoft/vsts-tasks
