### ISSUE TITLE
dotnet core SDK 2.1.4 but the runtime supports only up to 2.1.2

### ISSUE THREAD

**Issue by talhaashfaque** [Microsoft/azure-pipelines-image-generation#245]
I have a project using version .NET Core 2.1.4
The builds are working fine as the latest agent supports SDK 2.1.4, but I am having issues running unit tests on the latest agent as it supports runtime up to 2.1.2.

Is this something which is gonna fix anytime soon? Otherwise, I will have to downgrade my project to a previous version.
Release reference: August 2018 Image Updates https://github.com/Microsoft/azure-pipelines-image-generation/releases/tag/1808
![image](https://user-images.githubusercontent.com/24711587/45727365-c40fde00-bc06-11e8-89fe-4876556707ca.png)

**Comment by lokesh755** [comment]
We've generated new image, which has 2.1.4 runtime. We will update all the regions with latest image within a week.

**Comment by talhaashfaque** [comment]
Hey guys

Is there any update on this one?

**Comment by vtbassmatt** [comment]
This should be available now - have you tried it? It's even showing in the README.

**Comment by talhaashfaque** [comment]
> This should be available now - have you tried it? It's even showing in the README.

This is the latest release I can see: https://github.com/Microsoft/azure-pipelines-image-generation/releases/tag/1808

The latest Runtime as per the release notes is still 2.1.2

**Comment by vtbassmatt** [comment]
We haven't been consistent about adding a GitHub release for each monthly image, sorry about that.

When you run a job against the hosted pool, you should be getting the latest with 2.1.4. Also, in the product on the pool, you should see a readme which has 2.1.4. If that's not true, feel free to ping us again on this thread.
