### ISSUE TITLE
Unable to build VS2017 image

### ISSUE THREAD

**Issue by sescandell** [Microsoft/azure-pipelines-image-generation#249]
Hi everyone,

After severals tries, I never succeeded to create a VS2017 image.
I tried custom configurations (removing unused components) and your full one but getting the same results: the build fails on Install-SSDT.ps1 without any information.

Here is an extract of the Powershell output:

```bash
==> vhd: Provisioning with Powershell...
==> vhd: Provisioning with powershell script: C:\Users\steph\Downloads\azure-pipelines-image-generation-1808\images\win/scripts/Installers/Vs2017/Install-VS2017.ps1
    vhd: Downloading Bootstrapper ...
    vhd: Starting Install ...
    vhd: Installation successful
    vhd: Visual Studio version VisualStudio/15.8.5+28010.2036 installed
==> vhd: Restarting Machine
==> vhd: Waiting for machine to restart...
    vhd: A system shutdown is in progress.(1115)
    vhd: pkrvmmhcv2vcz3y restarted.
    vhd: #< CLIXML
    vhd: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules
 for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> vhd: Machine successfully restarted, moving on
==> vhd: Provisioning with Powershell...
==> vhd: Provisioning with powershell script: C:\Users\steph\Downloads\azure-pipelines-image-generation-1808\images\win/scripts/Installers/Vs2017/Install-SSDT.ps1
==> vhd:
==> vhd: Cleanup requested, deleting resource group ...
==> vhd: Resource group has been deleted.
Build 'vhd' errored: Script exited with non-zero exit status: 2147943515. Allowed exit codes are: [0 3010]

==> Some builds didn't complete successfully and had errors:
--> vhd: Script exited with non-zero exit status: 2147943515. Allowed exit codes are: [0 3010]

==> Builds finished but no artifacts were created.
```

As you can see in the log, this is based on the 1808 release.

Any advice on how to fix this or how to get more informations on what precisely failed?

The powershell command is executed from an Azure VM as an administrator.
I do not have access to the "generating VM" to check logs as it is automatically removed with the resource group on fail.

Thanks for your help,

**Comment by lokesh755** [comment]
Try to run with additional parameter "-on-error=ask"  as explained [here ](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/docs/debuggingFailedBuilds.md). So that you can choose not to delete packer VM. You can then login to packer vm as [installer user](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/vs2017-Server2016-Azure.json#L19) to debug.

**Comment by sescandell** [comment]
Going to try this.

Thanks,

**Comment by sescandell** [comment]
After some additional tries: still don't get additional informations.

Once the pack command wants to stop, I login to the VM and look for logs into the %TEMP% folder but nothing about SSDT script. To try to find out where the script is failing, I modified the SSDT with the following code (additional Write-Host):

```ps
################################################################################
##  File:  Install-SSDT.ps1
##  Team:  CI-Platform
##  Desc:  Install SQL Server Data Tools for Windows
################################################################################

Write-Host "******** SSDT SETUP Import-Module ********"
Import-Module -Name ImageHelpers -Force

#SSDT for Visual Studio 2017 (15.7.0)
$InstallerURI = 'https://download.microsoft.com/download/9/5/3/9533216D-FEE0-40A7-B351-9B5AAF111FAF/SSDT-Setup-ENU.exe'
$InstallerName = 'SSDT-Setup-ENU.exe'
$logFilePath = "$env:TEMP\ssdtlog.txt"
$ArgumentList = ('/install', 'INSTALLALL', '/passive', '/norestart', "/log `"$logFilePath`"")

Write-Host "******** SSDT SETUP Run Install-EXE ********"
$exitCode = Install-EXE -Url $InstallerURI -Name $InstallerName -ArgumentList $ArgumentList

if($exitCode -ne 0 -and $exitCode -ne 3010)
{
    Write-Host "******** SSDT SETUP LOG START ********"
    Write-Host $(Get-Content $logFilePath | Out-String)
    Write-Host "******** SSDT SETUP LOG END ********"
}

exit $exitCode
```

but none is displayed...

I juste notice, in the middle of all the VisualStudio component a log about SSDT. Is it possible the VS Install already include the SSDT and so the dedicated SSDT script fails?

I still continue to investigate on my side...

**Comment by sescandell** [comment]
Just saw [this issue](https://github.com/Microsoft/azure-pipelines-image-generation/issues/253)

Going to try the proposed fixe for SSDT

**Comment by sescandell** [comment]
Adding pauses to some steps seems to work... We never been so far in the build process. I'll let you know if it works as expected.

Thanks,

**Comment by sescandell** [comment]
Hi,

Adding pauses after restart steps as suggested in https://github.com/Microsoft/azure-pipelines-image-generation/issues/253 fix my different issues.

Closing this issue and will provide a PR next week if you are interested,
