### ISSUE TITLE
Validate-AzureCosmosDbEmulator.ps1 fails on non-existence of key HKCU:\SOFTWARE\Microsoft\CosmosDBEmulator

### ISSUE THREAD

**Issue by haimizrael** [Microsoft/azure-pipelines-image-generation#251]
When building vs2017-Server2016-Azure.json, Validate-AzureCosmosDbEmulator.ps1 fails on non-existence of key HKCU:\SOFTWARE\Microsoft\CosmosDBEmulator.  

It seems like this key is not present on the current Microsoft-hosted vs2017 images either.  How are those images built?

**Comment by riezebosch** [comment]
It's very recent. My guess is the installer was updated and doesn't write that registry key anymore.

**Comment by riezebosch** [comment]
Created #252
