### ISSUE TITLE
SSDT Installation fails on vs2017 Windows image

### ISSUE THREAD

**Issue by haimizrael** [Microsoft/azure-pipelines-image-generation#253]
/scripts/Installers/Vs2017/Install-SSDT.ps1 consistently fails when trying to create an image, with the provisioner returning error code 2147943515.  It seems like this is an issue executing the script right after a restart, so we got around it by adding the following to the configuration (e.g. on line https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/vs2017-Server2016-Azure.json#L147):
```json
"pause_before": "120s"
```
It may also work with a smaller delay, but we haven't tested that.

We are using packer version 1.3.1.

**Comment by majorvin** [comment]
this works like a charm. cheers!
