### ISSUE TITLE
C/C++: Add the latest 2 versions of Boost 1.68.0 - 1.69.0 (Linux, Windows)

### ISSUE THREAD

**Issue by vtbassmatt** [Microsoft/azure-pipelines-image-generation#263]
A customer is asking for precompiled Boost libraries (debug and release) on the hosted images: https://github.com/apache/arrow/pull/2674

I know that C++ compilation, especially highly-templated tools like Boost, is slow, so from that angle, this feels like a win. I'm not sure about Boost's versioning story, though, so I don't know how many customers we can satisfy with a single or limited range of versions.

@azureDaveOps I think your team owns C++, could you have someone investigate?

**Comment by vijayma** [comment]
Let us include the latest release version of Boost libraries on the hosted VS 2017 and Linux image. @DavidStaheli, @azureDaveOps , please have the imaging team work on a script for this.

**Comment by DavidStaheli** [comment]
Downloads for different versions:
https://www.boost.org/users/history/

1.69.0 installation for Linux:
https://www.boost.org/doc/libs/1_69_0/more/getting_started/unix-variants.html

1.69.0 installation for Windows:
https://www.boost.org/doc/libs/1_69_0/more/getting_started/windows.html
