### ISSUE TITLE
Request: Add Windows Server 2019 Image / run on V3 VM SKU

### ISSUE THREAD

**Issue by Iristyle** [Microsoft/azure-pipelines-image-generation#268]
Now that Windows Server 2019 has GA'd, we would like to run on top of that OS version.

We'd additionally like to be able to run LCOW from that	 environment. It's my understanding that agent pools will run on v3 VM SKUs in the future to help support this. Is there an ETA for that?

Thanks!

**Comment by vtbassmatt** [comment]
We can do the image gen work, but first @JoeBourneMS and Wil need to make the business decision.

**Comment by joebourneMS** [comment]
Hi Ethan,

We're putting together our roadmap for a Server 2019 image and will be sharing very soon. Support for running LCOW is on our radar.

**Comment by syedhassaanahmed** [comment]
+1 to this. Any ETA on this issue?

**Comment by joebourneMS** [comment]
Just to update folks, we are internally testing our preview of the VS2019 hosted pool. We were hoping to deploy it as part of our last sprint, but had a few delays. We should be deploying it as part of our current sprint. We're very close!

**Comment by glennawatson** [comment]
@joebourneMS What is your sprint schedule?

**Comment by joebourneMS** [comment]
Windows Server 2019 is live, currently we do not support nested virtualization and LCOW scenarios. We'll continue to monitor need for this and work on infrastructure to enable it.

**Comment by Iristyle** [comment]
Thanks @joebourneMS - is there a place that I can file an issue / track the hardware side of this request? i.e. the V3 SKUs in support of LCOW?

**Comment by joebourneMS** [comment]
@Iristyle , please go upvote https://developercommunity.visualstudio.com/idea/366304/support-for-docker-with-linux-containers-on-window.html

This is on our backlog, but we do not have it highly prioritized right now.
