### ISSUE TITLE
C/C++: Add/update to LLVM 7.0.0 (or latest) x64 (Linux, Windows)

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/azure-pipelines-image-generation#270]
The VS2017 image needs LLVM and Clang

**Comment by cstratopoulos** [comment]
Hey was about to open my own issue then saw this one. Having LLVM on Windows pre-installed would be great, but would it be possible to also add the [LLVM compiler toolchain extension](https://marketplace.visualstudio.com/items?itemName=LLVMExtensions.llvm-toolchain#overview) ? This would make it a lot easier to use `clang-cl` with the [CMake task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/cmake?view=azure-devops), one hopes e.g., by being able to pass `-T "llvm"` to `cmakeArgs`

**Comment by nicolasnoble** [comment]
Same with the vs2019 image actually.

**Comment by Keats** [comment]
I've just ran into that as well, a project update now requires LLVM which is built-in in Appveyor but is not available in Azure Pipelines.
This would have been a hard blocker for me if that update happened a few weeks ago, when I was investigating Azure Pipelines.

**Comment by reupen** [comment]
VS 2019 now comes with LLVM as an optional component. Is it possible for the `Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Llvm.Clang` VS component to be added to the VS 2019 image?

**Comment by kaylangan** [comment]
@reupen thanks for pointing that out! I've just opened #1297 to add it to the VS2019 image. We'll keep this issue open to track the other images.
