### ISSUE TITLE
Common tools: Add/update to Qt 5.11.2 (or latest) (Windows)

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/azure-pipelines-image-generation#272]
The VS2017 image needs QT

**Comment by karim** [comment]
This is a blocker for us at https://github.com/sqlitebrowser/sqlitebrowser. We need Qt, and not just for Windows, but for Linux and macOS as well.

Also, we need multiple versions of Qt and not just the latest. Our 32-bit build uses Qt v5.7.1 while the 64-bit build uses v5.11.3. We can't use the latest version (5.12) because of multiple bugs (already reported) affecting our application.

**Comment by bootress** [comment]
+1! I would love to move to Azure Pipelines from AppVeyor as Azure has LOTS of advantages, but we really need to have Qt available.

For reference, here is the set of versions that AppVeyor CI makes available on their Windows images: https://www.appveyor.com/docs/windows-images-software/#qt

**Comment by bootress** [comment]
This issue has several likes and I can't think of any reason why it would be no longer applicable or obsolete.

**Comment by karim** [comment]
@davidstaheli any update on this?

**Comment by chrispat** [comment]
https://github.community/t5/GitHub-Actions/Feature-request-Pre-installed-Qt-on-Windows/m-p/31004#M680

**Comment by luisangelsm** [comment]
For https://github.com/YACReader/yacreader/ I have been using `aqtinstall` https://github.com/miurahr/aqtinstall . I am having some intermitent issues with it (bad installations, I couldn't catch what's the problem yet), most of the times it works fine. But these kind of solutions are far from ideal.

It would be great to have Qt preinstalled, latest LTS and latest version at least in all the images.

**Comment by selmf** [comment]
This is still very much needed.

**Comment by kaylangan** [comment]
We've moved development over to https://github.com/actions/virtual-environments. Please follow the issue here: https://github.com/actions/virtual-environments
