### ISSUE TITLE
Common tools: Add/update to Coverity Scan 2017.07 (or latest) (Linux, Windows)

### ISSUE THREAD

**Issue by DavidStaheli** [Microsoft/azure-pipelines-image-generation#280]
(VS2017) Add Coverity Scan

**Comment by madhurig** [comment]
Coverity scan is only distributed to users after the user creates an account and registers a project. We need to review if we are allowed to put this on the "Hosted" VMs in Azure Pipelines.

**Comment by DavidStaheli** [comment]
Cutting this for now because of licensing issues with Coverity Scan.
