### ISSUE TITLE
(VS2017) Add vcpkg

### ISSUE THREAD

**Issue by DavidStaheli** [Microsoft/azure-pipelines-image-generation#282]
(VS2017) Add vcpkg

**Comment by adventworks** [comment]
@DavidStaheli Did you get this from some customers? What is the context here? Thanks.

**Comment by DominicCabral** [comment]
I think this is a duplicate of [#242](https://github.com/Microsoft/azure-pipelines-image-generation/issues/242)

**Comment by DavidStaheli** [comment]
You're right.  Thanks @DominicCabral!  Closing this duplicate...
