### ISSUE TITLE
Databases: Add PostgreSQL 11+195 (or latest) (Linux, Windows)

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/azure-pipelines-image-generation#287]
(VS2017) Add PostgreSQL

**Comment by lhendre** [comment]
Hi, Any update on this?

**Comment by lhendre** [comment]
Checking in again

**Comment by lhendre** [comment]
Any Update?

**Comment by lhendre** [comment]
Checking in one last time to see if there has been any update?  Going to assume this isnt going to be a priority anytime soon
