### ISSUE TITLE
Databases: Add MongoDB 4.0.1 (or latest) (Linux, Windows)

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/azure-pipelines-image-generation#291]
MongoDB installation instructions:

- [For Ubuntu](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/)
- [For Windows](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-windows/)

The installations should not automatically run as a service on the VM.  Instead, they should require to be started on-demand.

**Comment by Brooooooklyn** [comment]
any progress?
