### ISSUE TITLE
Add macOS Mojave 10.14

### ISSUE THREAD

**Issue by tonyarnold** [Microsoft/azure-pipelines-image-generation#300]
It would be good to make Mojave available for macOS builds. Apps compiled under 10.13 (even when targeting the 10.14 SDK) lose Mojave-specific features related to dynamic colours and light/dark mode.

## Tool info
- Tool name: macOS
- Add or update? Update
- Desired version: 10.14 (18A391)

## Areas and ecosystems

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [x] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

## Hosted pools

- [x] macOS
- [ ] Ubuntu
- [ ] Windows

**Comment by DavidStaheli** [comment]
Thank you for creating this issue @tonyarnold.  We're currently working on making Mojave available.

**Comment by tonyarnold** [comment]
That is excellent news, thanks for letting me know @DavidStaheli. Is there a time frame for this? It's something I'd like to trial with my organisation when it is ready.

**Comment by DavidStaheli** [comment]
@joebourneMS do you have a sense for when macOS-10.14 will be available?  I can ask the team creating the image if that's better.  Thanks!

**Comment by aahmed-se** [comment]
As a general comment could we expand the mac VM's available to cover older osx versions say 10.12 and 10.11 and have a rolling support target of (current - 3) versions available.

**Comment by kmhofmann** [comment]
macOS 10.14 also would bring much better C++17 support, since it ships with a later AppleClang C++ compiler (10.0 instead of 9.1 currently). Despite Xcode 10.1's presence on the current images, this apparently cannot be retrofitted.

**Comment by ikesyo** [comment]
Xcode 10.2 beta now requires Mojave so this is really important.

**Comment by kimdv** [comment]
@joebourneMS any new on this as new Xcode and Swift 5 release is coming

**Comment by nrajpurkar** [comment]
@kimdv the work to add Mojave is still ongoing, but we are aiming to have support for Xcode 10.2 stable available when that is released.

**Comment by kimdv** [comment]
Awesome @nrajpurkar 🚀

**Comment by spacebourne** [comment]
@nrajpurkar with Xcode 10.2 and Swift 5 now stable, any news on when this will be available?

**Comment by nrajpurkar** [comment]
@spacebourne top priority for us at the moment! We'll have it out as soon as possible with a goal of the end of the month as we [shared previously](https://devblogs.microsoft.com/devops/hosted-pipelines-announcements-vs-2019-mojave-and-more/).

**Comment by bazscott** [comment]
Any news on this? This is really getting ridiculous now.

**Comment by naknut** [comment]
@nrajpurkar is there any ETA on this? It's been over 2 weeks since the Xcode 10.2 and Swift 5 release. We really want to move our builds to Swift 5.

**Comment by nrajpurkar** [comment]
macOS Mojave is now available with Xcode 10.2 (and some prior versions) installed! Check out how to [switch to Mojave](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent) and the [compatible Xcode versions](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md#xcode) available.

**Comment by arek-avanade** [comment]
That's good news, but... this image still contains old Xamarin/Visual Studio 2017. I was surprised when I realized that, since it felt natural to me that new VS will be included in that image. I will open a new ticket for that in that case, this is critical to my team.

**Comment by nrajpurkar** [comment]
@arek-avanade Thanks for creating #857  to track this - like Nick mentioned, this will come out with our next update

**Comment by arek-avanade** [comment]
Thanks @nrajpurkar. Looking forward to this.
