### ISSUE TITLE
Initialize Visual Studio "Experimental Instance" (VS2017 image)

### ISSUE THREAD

**Issue by josetr** [Microsoft/azure-pipelines-image-generation#303]
This can be done using the following command:
`"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\devenv.exe" /rootsuffix exp /resetsettings general.vssettings /command File.Exit`

See
https://github.com/appveyor/ci/issues/1391
https://github.com/appveyor/ci/issues/2583

**Comment by pharring** [comment]
@sharwell and I encountered this trying to add functional tests for my VSIX.
Please add this to the VS2017 and VS2019 images to improve test speed.
