### ISSUE TITLE
Update Xamarin.iOS Version

### ISSUE THREAD

**Issue by heinst** [Microsoft/azure-pipelines-image-generation#304]
# Help us route

This is the template for requesting new or updated tools on the hosted images.
If you intended to file a bug, please switch to the Bugs template: https://github.com/Microsoft/azure-pipelines-image-generation/issues/new?template=bugs.md

# If this is a request for a new tool or tool version...

## Tool info
- Tool name: Xamarin.iOS (**Current Version**: 12.0.0.15)
- Add or update? Update
- Desired version: 12.2.0.26

## Areas and ecosystems

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [x] Xamarin
- [ ] Other

## Hosted pools

- [x] macOS
- [ ] Ubuntu
- [ ] Windows

**Comment by DavidStaheli** [comment]
@nrajpurkar, can this be addressed by your team on the public macOS image?

**Comment by nrajpurkar** [comment]
Hi @heinst, we currently only update to stable release versions of Xamarin.iOS. Xamarin.iOS 12.0.0.15 is part of the Preview version. Would you mind sharing more about your use case for requiring this version?

**Comment by heinst** [comment]
@nikunjragh Hi thanks for the response. I see that now. Where my confusion is coming is that I am trying to incorporate the Autofill OTP iOS 12 specific feature into our app. It builds fine locally, but when I submit the PR the build fails stating `error CS0117: 'UITextContentType' does not contain a definition for 'OneTimeCode'` Which leads me to believe there is something not up-to-date on the server as the `OneTimeCode` property is fairly new as is iOS 12.

**Comment by heinst** [comment]
These are the versions Im running locally....any help would be appreciated.

 === Visual Studio Community 2017 for Mac ===

Version 7.6.10 (build 27)
Installation UUID: 0e307d2b-1420-4cb8-9f1e-50377ca69236
Runtime:
	Mono 5.12.0.309 (2018-02/39d89a335c8) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000309

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 9.0.0.20 (Visual Studio Community)
Android SDK: /Users/theins/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Apple Developer Tools ===

Xcode 10.0 (14320.25)
Build 10A255

=== Xamarin.Mac ===

Version: 5.0.0.0 (Visual Studio Community)
Hash: b40230c0
Branch: 
Build date: 2018-09-27 11:41:37-0400

=== Xamarin.iOS ===

Version: 12.0.0.15 (Visual Studio Community)
Hash: 84552a46
Branch: xcode10
Build date: 2018-09-17 21:54:33-0400

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706100027
Git revision: 94dbd4d35daaa5a2ff6a51c3fd5cbb2308bd83ea
Build date: 2018-10-18 16:34:31+00
Build branch: release-7.6
Xamarin extensions: 3a9afc960ba73e5862829e8a0cd9369bcca43d70

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

**Comment by nrajpurkar** [comment]
Closing this as Xamarin.iOS is updated to [12.2 on hosted agents](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.13-Readme.md#xamarinios-sdk).
