### ISSUE TITLE
Testing: Add/update to Chrome 70.0.3538.102 (or latest) (Windows)

### ISSUE THREAD

**Issue by cor2879** [Microsoft/azure-pipelines-image-generation#307]
# Help us route

This is the template for requesting new or updated tools on the hosted images.
If you intended to file a bug, please switch to the Bugs template: https://github.com/Microsoft/azure-pipelines-image-generation/issues/new?template=bugs.md

# If this is a request for a new tool or tool version...

## Tool info
- Tool name: 
- Add or update? 
- Desired version: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 

## Areas and ecosystems

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ X] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

## Hosted pools

- [ ] macOS
- [ ] Ubuntu
- [X ] Windows

Hello, please update the version of Google Chrome from version: 68.0.3440.106 to 69.0.3497 or above.  Thank you.

**Comment by lerys** [comment]
How can we as community help in speeding this process ?
