### ISSUE TITLE
Consider installing VS2015/13/12 on the VS2017 image

### ISSUE THREAD

**Issue by josetr** [microsoft/azure-pipelines-image-generation#308]
✔️ A single VSIX package can target Visual Studio 2012/13/15/17
✔️ https://github.com/josetr/VsixTesting can be used to create/run integration tests on VS2012/13/15/17
❌ There is no CI where Visual Studio 2012/13/15/17 is installed

AppVeyor is the best place currently since they have VS2015 installed in their VS2017 image and they also have initialized their respective VS Experimental Instances (#303) but you can only partially test your extension and you may end up disabling/skipping tests like @sharwell had to do in his
https://github.com/tunnelvisionlabs/MouseFastScroll extension.

All the changes that would be required are in https://github.com/josetr/azure-pipelines-image-generation/tree/InstallVS so let me know if I should turn it into a pull request. I couldn't get a direct download link for VS2012 with Update 5 that's why I had to patch it but I'm hoping someone can help there.

If this is not possible, a good alternative would be creating a new image.

**Comment by Croydon** [comment]
Support for more VS versions would be great.

Somewhat related: We got custom docker container for VS2017 and VS2015 working but keep failing with VS2013. Did anyone got a container with VS2013 running?

**Comment by jaredpar** [comment]
The lack of contribution though is from the repository owners, not the contributors who opened the issue.

**Comment by jozefizso** [comment]
Having all VS 2010, 2012, 2013, 2015, 2017 and 2019 in a single image would help compile projects like https://github.com/wixtoolset/wix3 which need all Visual Studios in a single build machine.
