### ISSUE TITLE
Include the latest Windows SDKs and list them (VS2017-Win2016)

### ISSUE THREAD

**Issue by snap608** [Microsoft/azure-pipelines-image-generation#309]
I can not find any information of Windows SDKs installed in the Hosted Agent (VS2017) image.

I have a build that require The Windows SDK version 10.0.17763.0 that is not present. But I do not find any information about what is already installed.

## Hosted pools

- [ ] macOS
- [ ] Ubuntu
- [X] Windows

**Comment by DavidStaheli** [comment]
We should also make sure we've got the latest SDKs available.

**Comment by snap608** [comment]
Any updates? ;)

**Comment by crazydef** [comment]
Can I just add that the reason we need 10.0.17763.0 is because of dependencies here:  https://github.com/Microsoft/DirectX-Graphics-Samples/tree/master/Libraries/D3DX12

**Comment by snap608** [comment]
The latest updated pipelines solved our issue. Thanx! :)

**Comment by snap608** [comment]
Is this change pushed to all pipelines? I do see `The Windows SDK version 10.0.17763.0 was not found.` sometimes stil.
