### ISSUE TITLE
Java: Add Java Runtime Environment 8.0 (Linux, Windows)

### ISSUE THREAD

**Issue by rajbos** [Microsoft/azure-pipelines-image-generation#315]
# Help us route

This is the template for requesting new or updated tools on the hosted images.
If you intended to file a bug, please switch to the Bugs template: https://github.com/Microsoft/azure-pipelines-image-generation/issues/new?template=bugs.md

# If this is a request for a new tool or tool version...

## Tool info
- Tool name: Java Runtime Environment
- Add or update? Add
- Desired version: 8.0
- If this is an add request:
  - Brief description of tool: I needed the Java Runtime Environment to be able to run the `Run Analysis Task` from the SonarQube Azure DevOps [extension](https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarqube). The extension adds the demand 'java' to the build, which currently isn't supported from the JDK (that already is on the hosted agent).
  - URL for tool's homepage: https://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

## Areas and ecosystems

- [x] Testing and code coverage

## Hosted pools

- [x] Hosted agent
- [x] Hosted VS2017
- [ ] macOS
- [ ] Ubuntu
- [x] Windows

**Comment by DavidStaheli** [comment]
We also need to investigate why the 'java' capability isn't set with the currently available JDKs.

**Comment by DavidStaheli** [comment]
@rajbos, sorry for the delay on this issue.  The hosted agents now ignore all demands from tasks, so the lack of a "Java" capability shouldn't matter anymore.  We've been able to run the SonarQube task without errors.  If you still see something wrong, could you please re-open this issue?  Thank you for reporting it.
