### ISSUE TITLE
Define environment variable for current pulled docker images

### ISSUE THREAD

**Issue by heaths** [microsoft/azure-pipelines-image-generation#316]
We use docker containers for testing Microsoft/vswhere and Microsoft/vssetup.powershell as a means of isolation so the exact docker image tag doesn't really matter, but pulling instead does take time. I've parameterized the FROM commands to accept an argument/environment variable. If you were to define environment variables for current images (e.g. `DOCKER_WINDOWSSERVERCORE_IMAGE=@sha256:...` (or just use the tag name)) or build would be much faster and consume less time in the hosted pools.

## Areas and ecosystems

- [ ] Android
- [ ] C / C++
- [X] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

## Hosted pools

- [ ] macOS
- [ ] Ubuntu
- [X] Windows

(Thought any host OS could possibly benefit.)

**Comment by DavidStaheli** [comment]
@vtbassmatt would this be in your team's area, rather than the container ecosystem owners?

**Comment by dakale** [comment]
@vtbassmatt for question about the best experience for acquiring / consuming containers in a hosted agent context. 

This feature request seems to add functionality and expand what customers can do in a build without any real downside. 

Correct me if im wrong @heaths but it seems like the scenario ask is so you can build images based on the exact cached version to avoid pulling the container base? 

FROM and `docker run` with just an image name and no digest, with or without a tag will match the images cached locally by name (matching a tag, or latest respectively), so I think question is mostly around the experience when doing `docker pull`. Reason being, if a build programatically selects the image by a given digest, I think that is equivalent to simply specifying the image by name:tag, because both will slide versions without manually changing the version that your build locks to. 

Because you will have to either refer to documentation to discover which env vars to depend on, or discover them with some scripting in your build, I believe simply checking for which images are cached covers the same bases. 

Is there a specific scenario you can expand on @heaths ?

**Comment by vtbassmatt** [comment]
This seems valuable but narrow in terms of customers who will use it. To avoid proliferating environment variables, I wonder if we could make this one available only as a build variable. Much like a secret variable, you'd have to explicitly map it into your `env` if you require it. Thoughts?

```yaml
container: microsoft/dotnet:latest   # handwaving over the fact that we don't allow this type of declaration yet...

steps:
- script: echo $MY_CONTAINER_LABEL
  env:
    MY_CONTAINER_LABEL: $(Container.Label)
```

**Comment by heaths** [comment]
If the images are tagged `:latest` that could work (we don't explicitly pull), but that's not how the documentation reads, which documents only the SHA256 digests. But I'd worry if you have a local latest tag that differs from a remote, as people might end up getting the wrong image.

A build property would be fine as well, as @vtbassmatt suggested.

The main case is to avoid pulling an image, but keep otherwise working code working for a long time without change. We're merely using containers at test-time to construct an isolated environment without impacting the current machine state which may actually use the API we'd have to mock to locate build and/or test tools (many of your tasks do, often via vswhere which is one of the projects where I want to use this).

**Comment by heaths** [comment]
If you can do this dynamically that's great, but I'm not talking about how you create containers. As part of our test pass, we need to create containers and run tests inside those. To optimize for test run time, if we can use a suitable image already pulled locally it takes seconds as opposed to many minutes. A way to do that is to define some variable (environment or otherwise) that we can pass to our `docker-compose` command that populates the `FROM` directive, authored like so:

```Dockerfile
ARG IMAGE_BASE=microsoft/windowsservercore:ltsc2016
FROM ${IMAGE_BASE}
# …
```
Thus, passing `--build-arg IMAGE_BASE=microsoft/windowsservercore:1809` (for example) - if that's what's pulled (and it has to match the kernel version of the host) - wouldn't require pulling it. In our case we don't really care specifically what we run on since we support Win7 SP1+. I imagine, at least with Windows containers, many people may not have specific build version requirements (like anyone using `:latest`, which has a different meaning for Windows containers).

**Comment by vtbassmatt** [comment]
I'm still missing part of this ask, then. When you run a container on, say, the Windows 1803 (VM) image, you're telling us what container to pull. We don't (currently) have any Docker images pre-cached.

**Comment by heaths** [comment]
According to https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md, you have quite a few cached. And those need to match the kernel version of Windows.

**Comment by vtbassmatt** [comment]
Dang it, @heaths, how are you PMing this product better than me? ;-P I didn't realize we were including those images. Now that I'm caught up: does this suffice? `docker images --format "{{.Repository}}:{{.Tag}}"` (piped and filtered however you need to to pluck out a useful image).

@dakale @lokesh755 -- if @heaths reports that the above command won't work for him, then we should add environment variables pointing to the images. Something like DOCKER_IMAGE_<image>=<tag>.

**Comment by vtbassmatt** [comment]
If we're caching images, I would hope we're honoring the kernels-must-match contract. If we don't that's a bug.

**Comment by vtbassmatt** [comment]
@lokesh755 can you confirm that the images we cache on the Windows VM image have matching kernels with the VM itself.

**Comment by heaths** [comment]
@lokesh755, did you ever have a chance to make sure that kernel versions always match?
