### ISSUE TITLE
.NET Core: Support preview of dotnet 2.2 (Linux, Windows)

### ISSUE THREAD

**Issue by vchirikov** [Microsoft/azure-pipelines-image-generation#317]
## Tool info
- Tool name: dotnet
- Add or update? Update
- Desired version: v2.2.0-preview3
- If this is an add request:
  - Brief description of tool: dotnet sdk
  - URL for tool's homepage: https://www.microsoft.com/net/download/dotnet-core/2.2

## Areas and ecosystems

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [x] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

## Hosted pools

- [x] macOS
- [x] Ubuntu
- [x] Windows

---
Hi, also will be cool if you can support latest vs2017-preview.

**Comment by vchirikov** [comment]
Or it can be installed via:
```yml
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.0-preview3'
```
?

**Comment by DavidStaheli** [comment]
Closing... see also #372.
