### ISSUE TITLE
Python: Update to Python 3.7.1 (or latest 3.7.x) (Linux, Windows)

### ISSUE THREAD

**Issue by DavidStaheli** [Microsoft/azure-pipelines-image-generation#318]
https://blog.python.org/2018/10/python-371-and-367-are-now-available.html

**Comment by dakale** [comment]
@DavidStaheli Are there any differences between this and #319, #320, or #321 ? Lets collapse to a single issue

**Comment by DavidStaheli** [comment]
Hi @dakale.  All three issues are the side effect of me trying 3 times to create one issue last night when GitHub was having database issues.  :)  I'll consolidate... thanks.

**Comment by DavidStaheli** [comment]
Completed in hosted tool cache repo
