### ISSUE TITLE
Add Selenium drivers to hosted Ubuntu 16.04 agent

### ISSUE THREAD

**Issue by markhobson** [Microsoft/azure-pipelines-image-generation#322]
Issue #66 added Selenium drivers to the hosted Windows agent, so it'd be helpful to port this functionality to the Ubuntu agent too.

**Comment by DavidStaheli** [comment]
Hi @markhobson.  Thanks a lot for creating this issue.  I'm closing it here because we're creating an individual issue for each driver (#332, #378).
