### ISSUE TITLE
Image creation fails for ubuntu in release/1809

### ISSUE THREAD

**Issue by tomvo12** [Microsoft/azure-pipelines-image-generation#323]
I'm trying to create a hosted Ubuntu1604 build agent image using the provided release/1809.
However, image generation repeatedly fails with the following error:

    azure-arm: Need to get 43.3 MB of archives.
    azure-arm: After this operation, 260 MB of additional disk space will be used.
    azure-arm: Do you want to continue? [Y/n] Abort.
    azure-arm: update-alternatives: error: alternative path /usr/bin/clang++-6.0 doesn't exist
    azure-arm: update-alternatives: error: alternative path /usr/bin/clang-6.0 doesn't exist
    azure-arm: Testing to make sure that script performed as expected, and basic scenarios work
    azure-arm: clang was not installed

Full log file is attached.

Thanks in advance,
Tom Voss

[ubuntu.log](https://github.com/Microsoft/azure-pipelines-image-generation/files/2501889/ubuntu.log)

**Comment by dakale** [comment]
Please try building from master instead. It looks like that particular tag has a bad version of the clang installer.

**Comment by dakale** [comment]
Great. Sorry about that
