### ISSUE TITLE
Mysql client is missing in 2015 hosted agent

### ISSUE THREAD

**Issue by RoshanKumarMicrosoft** [Microsoft/azure-pipelines-image-generation#326]
## Mysql client is missing in 2015 hosted agent
We have the installation script in place for both [2015](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/vs2015-Server2012R2-Azure.json#L274) and [2017](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/vs2017-Server2016-Azure.json#L299).

## Impact
[Build canary ](https://buildcanary.visualstudio.com/CanaryBuilds/_build/results?buildId=100511&_a=summary&view=logs) has started failing. But for Hosted 2017 it is working fine.

Please have a look into it.

**Comment by dakale** [comment]
@RoopeshNair You have DBs

This canary hasnt actually in passed in over 6 months though

**Comment by RoshanKumarMicrosoft** [comment]
On  offline discussion with @lokesh755  they are going to depreciate Hosted 2015 pool which is currently only on buildcanary account. Due to this they are not updating 2015 pool. 

So closing this issue and it is available in Hosted 2017.
