### ISSUE TITLE
Deployment: Add Octopus CLI (octo) 4.31.3 (or latest) (Windows)

### ISSUE THREAD

**Issue by DavidStaheli** [Microsoft/azure-pipelines-image-generation#330]
AppVeyor has this tool preinstalled too.
Docs: https://octopus.com/docs/api-and-integration/octo.exe-command-line

**Comment by RoopeshNair** [comment]
@DavidStaheli  - We don't include them by default as we don't own the release cycles for them. This avoids breaks in our builds. Let me know if this has changed.

@kmkumaran  - fyi
