### ISSUE TITLE
Cannot create ubuntu image because terraform is failing

### ISSUE THREAD

**Issue by majorvin** [Microsoft/azure-pipelines-image-generation#333]
azure-arm: Hit:9 http://ppa.launchpad.net/apt-fast/stable/ubuntu xenial InRelease
    azure-arm: Hit:10 https://packages.microsoft.com/repos/azure-cli xenial InRelease
    azure-arm: Hit:11 https://packages.microsoft.com/ubuntu/16.04/prod xenial InRelease
    azure-arm: Hit:13 https://dl.yarnpkg.com/debian stable InRelease
    azure-arm: Hit:14 https://dl.hhvm.com/ubuntu xenial InRelease
    azure-arm: Hit:15 http://ppa.launchpad.net/git-core/ppa/ubuntu xenial InRelease
    azure-arm: Hit:16 https://cli-assets.heroku.com/apt ./ InRelease
    azure-arm: Hit:7 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
    azure-arm: Hit:17 https://download.docker.com/linux/ubuntu xenial InRelease
    azure-arm: Hit:18 http://ppa.launchpad.net/ondrej/php/ubuntu xenial InRelease
    azure-arm: Ign:12 http://packages.erlang-solutions.com/debian xenial InRelease
    azure-arm: Hit:20 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu xenial InRelease
    azure-arm: Hit:22 https://download.mono-project.com/repo/ubuntu stable-xenial InRelease
    azure-arm: Hit:21 http://packages.erlang-solutions.com/debian xenial Release
    azure-arm: Hit:23 https://packagecloud.io/github/git-lfs/ubuntu xenial InRelease
    azure-arm: Fetched 216 kB in 1s (149 kB/s)
    azure-arm: Reading package lists...
    azure-arm: Reading package lists...
    azure-arm: Building dependency tree...
    azure-arm: Reading state information...
    azure-arm: apt-fast is already the newest version (1.9.5-1~ubuntu16.04.1).
    azure-arm: The following packages were automatically installed and are no longer required:
    azure-arm:   linux-azure-cloud-tools-4.15.0-1023 linux-cloud-tools-4.15.0-1023-azure
    azure-arm:   shtool
    azure-arm: Use 'sudo apt autoremove' to remove them.
    azure-arm: 0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.
    azure-arm:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    azure-arm:                                  Dload  Upload   Total   Spent    Left  Speed
    azure-arm: 100   303  100   303    0     0   2058      0 --:--:-- --:--:-- --:--:--  2047
    azure-arm: Archive:  terraform_v0.11.10_linux_amd64.zip
    azure-arm:   End-of-central-directory signature not found.  Either this file is not
    azure-arm:   a zipfile, or it constitutes one disk of a multi-part archive.  In the
    azure-arm:   latter case the central directory and zipfile comment will be found on
    azure-arm:   the last disk(s) of this archive.
    azure-arm: Testing to make sure that script performed as expected, and basic scenarios work
    azure-arm: unzip:  cannot find zipfile directory in one of terraform_v0.11.10_linux_amd64.zip or
    azure-arm: Terraform was not installed or found on PATH
    azure-arm:         terraform_v0.11.10_linux_amd64.zip.zip, and cannot find terraform_v0.11.10_linux_amd64.zip.ZIP, period.
==> azure-arm:
==> azure-arm: Cleanup requested, deleting resource group ...
==> azure-arm: Resource group has been deleted.
Build 'azure-arm' errored: Script exited with non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> azure-arm: Script exited with non-zero exit status: 1

==> Builds finished but no artifacts were created.

**Comment by RoopeshNair** [comment]
As per @riezebosch   comments, I'm closing this.
