### ISSUE TITLE
Add Spectre-mitigated libraries on VS 2017 hosted agents

### ISSUE THREAD

**Issue by mahilleb-msft** [Microsoft/azure-pipelines-image-generation#334]
## Tool info
- Tool name: VS 2017 Spectre-mitigated libraries, e.g., CRT.
  See https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2017, for example Microsoft.VisualStudio.Component.VC.Runtimes.x86.x64.Spectre
- Add or update? add
- Desired version: optional component of Visual Studio 2017.
- If this is an add request:
  - Brief description of tool: these are Spectre-mitigated CRTs that are optional components for VS 2017. Cf. this blog entry: https://blogs.msdn.microsoft.com/vcblog/2018/01/15/spectre-mitigations-in-msvc/
  - URL for tool's homepage: https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2017
  - If ones follows Microsoft Security Development Lifecycle (SDL), when using a tool such as [binskim](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2017), even after adding the appropriate Spectre mitigations to user code, binskim will complain about the non-mitigated CRTs. To resolve, the mitigated libraries need to be used. It seems right now these optional components are yet installed with VS 2017 hosted agent, if would be helpful if they could be added.

## Areas and ecosystems

- [ ] Android
- [X] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

## Hosted pools

- [ ] macOS
- [ ] Ubuntu
- [X] Windows

**Comment by mahilleb-msft** [comment]
It seems this might be addressed by #624 ? Can you confirm? When would this be deployed?

Thanks, Mark

**Comment by mahilleb-msft** [comment]
@lokesh755 - could you comment? Thanks, Mark

**Comment by austin-jensen** [comment]
@mahilleb-msft The spectre-mitigated libraries should all be installed with #624 and #665 the ARM spectre mitigation libraries should roll out with the next agent update.

**Comment by mahilleb-msft** [comment]
Thanks I was able to validate.
