### ISSUE TITLE
Could you provide some info on how your agents are initialized and if what we see here is up-to-date?

### ISSUE THREAD

**Issue by riezebosch** [Microsoft/azure-pipelines-image-generation#336]
There are currently some strange differences in the images we build based on this repo and the capabilities that are available on the hosted agents.

For example, on the hosted is (already?) curl available and on ours there is not. I see there is een issue #275 for that but I cannot find it on the scripts that are available here.

Another big difference is that we got code coverage automatically working on the hosted agents but not on our private ones. Based on the issues here #284 with `e:Testing/code coverage` label applied on it suggests that you might be working on that part.

The most eye-catching difference is the number of capabilities that the agent discovers compared to the concise list that yours has.

Hosted:

Capability name | Capability value
-- | --
Agent.Name | Hosted Agent
Agent.Version | 2.140.2
AndroidSDK | C:\Program Files (x86)\Android\android-sdk
ant | C:\java\ant\apache-ant-1.9.7
AzurePS | 3.6.0
Cmd | C:\Windows\system32\cmd.exe
curl | C:\Program Files\Git\mingw64\bin\curl.exe
DotNetFramework | C:\Windows\Microsoft.NET\Framework64\v4.0.30319
GTK_BASEPATH | C:\Program Files (x86)\GtkSharp\2.12\
java | C:\Program Files (x86)\Java\jdk1.8.0_112
jdk | C:\Program Files (x86)\Java\jdk1.8.0_112
jdk_8 | C:\Program Files (x86)\Java\jdk1.8.0_112
maven | C:\java\maven\apache-maven-3.2.2
MSBuild | C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\
node.js | C:\Program Files\nodejs\node.exe
npm | C:\Program Files\nodejs\npm.cmd
SqlPackage | C:\Program Files\Microsoft SQL Server\140\DAC\bin\SqlPackage.exe
VisualStudio | C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\
VSTest | C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow
Xamarin.Android | 7.2.0.7

Private:

Capability name | Capability value
-- | --
AGENT_TOOLSDIRECTORY | C:/hostedtoolcache/windows
Agent.ComputerName | canary-wi000000
Agent.HomeDirectory | C:\agent1
Agent.Name | windows-agent-canary-34422-1081-000000-1
Agent.OS | Windows_NT
Agent.OSVersion | 10.0.14393
Agent.Version | 2.140.2
ALLUSERSPROFILE | C:\ProgramData
ANDROID_HOME | C:\Program Files (x86)\Android\android-sdk
ANDROID_NDK_HOME | C:\Microsoft\AndroidNDK64\android-ndk-r15c
ANDROID_NDK_PATH | C:\Microsoft\AndroidNDK64\android-ndk-r15c
AndroidSDK | C:\Program Files (x86)\Android\android-sdk
AndroidSDK_10 | C:\Program Files (x86)\Android\android-sdk\platforms\android-10
AndroidSDK_15 | C:\Program Files (x86)\Android\android-sdk\platforms\android-15
AndroidSDK_17 | C:\Program Files (x86)\Android\android-sdk\platforms\android-17
AndroidSDK_19 | C:\Program Files (x86)\Android\android-sdk\platforms\android-19
AndroidSDK_21 | C:\Program Files (x86)\Android\android-sdk\platforms\android-21
AndroidSDK_22 | C:\Program Files (x86)\Android\android-sdk\platforms\android-22
AndroidSDK_23 | C:\Program Files (x86)\Android\android-sdk\platforms\android-23
AndroidSDK_24 | C:\Program Files (x86)\Android\android-sdk\platforms\android-24
AndroidSDK_25 | C:\Program Files (x86)\Android\android-sdk\platforms\android-25
AndroidSDK_26 | C:\Program Files (x86)\Android\android-sdk\platforms\android-26
AndroidSDK_27 | C:\Program Files (x86)\Android\android-sdk\platforms\android-27
AndroidSDK_28 | C:\Program Files (x86)\Android\android-sdk\platforms\android-28
ant | C:\ProgramData\chocolatey\lib\ant\apache-ant-1.10.5
ANT_HOME | C:\ProgramData\chocolatey\lib\ant\apache-ant-1.10.5
APPDATA | C:\Windows\system32\config\systemprofile\AppData\Roaming
AzureGuestAgent | C:\WindowsAzure\GuestAgent_2.7.41491.895_2018-10-19_084347\GuestAgent\WindowsAzureGuestAgent.exe
AzurePS | 2.1.0
bower | C:\npm\prefix\bower.cmd
ChocolateyInstall | C:\ProgramData\chocolatey
ChromeWebDriver | C:\SeleniumWebDrivers\ChromeDriver
CLASSPATH | .;
Cmd | C:\Windows\system32\cmd.exe
COBERTURA_HOME | C:\cobertura-2.1.1
CommonProgramFiles | C:\Program Files\Common Files
CommonProgramFiles(x86) | C:\Program Files (x86)\Common Files
CommonProgramW6432 | C:\Program Files\Common Files
COMPUTERNAME | canary-wi000000
ComSpec | C:\Windows\system32\cmd.exe
ConfigSequenceNumber | 60
docker | C:\Program Files\Docker\docker.exe
DotNetFramework | C:\Windows\Microsoft.NET\Framework64\v4.0.30319
DotNetFramework_2.0 | C:\Windows\Microsoft.NET\Framework\v2.0.50727
DotNetFramework_2.0_x64 | C:\Windows\Microsoft.NET\Framework64\v2.0.50727
DotNetFramework_3.0 | C:\Windows\Microsoft.NET\Framework\v3.0
DotNetFramework_3.0_x64 | C:\Windows\Microsoft.NET\Framework64\v3.0
DotNetFramework_3.5 | C:\Windows\Microsoft.NET\Framework\v3.5
DotNetFramework_3.5_x64 | C:\Windows\Microsoft.NET\Framework64\v3.5
DotNetFramework_4.7.0 | C:\Windows\Microsoft.NET\Framework\v4.0.30319
DotNetFramework_4.7.0_x64 | C:\Windows\Microsoft.NET\Framework64\v4.0.30319
FORTIFY | c:\HPE_Fortify\HPE_Fortify_SCA_and_Apps\bin
GeckoWebDriver | C:\SeleniumWebDrivers\GeckoDriver
GRADLE_HOME | C:\ProgramData\chocolatey\lib\gradle\tools\gradle-4.10.2
grunt | C:\npm\prefix\grunt.cmd
gulp | C:\npm\prefix\gulp.cmd
IEWebDriver | C:\SeleniumWebDrivers\IEDriver
InteractiveSession | True
java | C:\Program Files\Java\jre7
java_7_x64 | C:\Program Files\Java\jre7
JAVA_HOME | C:\Program Files\Java\jdk1.8.0_192
JAVA_HOME_7_X64 | C:\Program Files\Java\jdk1.7.0_80
JAVA_HOME_8_X64 | C:\Program Files\Java\jdk1.8.0_192
JAVA_IBM_HOME_7_X64 | C:\IBMJDK\ibm_sdk71
JAVA_IBM_HOME_8_X64 | C:\IBMJDK\ibm_sdk80
jdk | C:\Program Files\Java\jdk1.8.0_192
jdk_7_x64 | C:\Program Files\Java\jdk1.7.0_80
jdk_8 | C:\Program Files (x86)\Java\jdk1.8.0_192
jdk_8_x64 | C:\Program Files\Java\jdk1.8.0_192
LOCALAPPDATA | C:\Windows\system32\config\systemprofile\AppData\Local
M2 | C:\ProgramData\chocolatey\lib\maven\apache-maven-3.5.4\bin
M2_HOME | C:\ProgramData\chocolatey\lib\maven\apache-maven-3.5.4
M2_REPO | C:\ProgramData\m2
maven | C:\ProgramData\chocolatey\lib\maven\apache-maven-3.5.4
MAVEN_OPTS | -Xms256m
MSBuild | C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\
MSBuild_15.0 | C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\
MSBuild_15.0_x64 | C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\amd64\
MSBuild_2.0 | C:\Windows\Microsoft.NET\Framework\v2.0.50727\
MSBuild_2.0_x64 | C:\Windows\Microsoft.NET\Framework64\v2.0.50727\
MSBuild_3.5 | C:\Windows\Microsoft.NET\Framework\v3.5\
MSBuild_3.5_x64 | C:\Windows\Microsoft.NET\Framework64\v3.5\
MSBuild_4.0 | C:\Windows\Microsoft.NET\Framework\v4.0.30319\
MSBuild_4.0_x64 | C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
MSBuild_x64 | C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\amd64\
MSMPI_BIN | C:\Program Files\Microsoft MPI\Bin\
node.js | C:\Program Files\nodejs\node.exe
npm | C:\Program Files\nodejs\npm.cmd
NPM_CONFIG_CACHE | C:\npm\cache
NPM_CONFIG_PREFIX | C:\npm\prefix
NUMBER_OF_PROCESSORS | 2
OS | Windows_NT
PATHEXT | .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
PowerShell | 5.1.14393.2515
PROCESSOR_ARCHITECTURE | AMD64
PROCESSOR_IDENTIFIER | Intel64 Family 6 Model 79 Stepping 1, GenuineIntel
PROCESSOR_LEVEL | 6
PROCESSOR_REVISION | 4f01
ProgramData | C:\ProgramData
ProgramFiles | C:\Program Files
ProgramFiles(x86) | C:\Program Files (x86)
ProgramW6432 | C:\Program Files
PROMPT | $P$G
PSExecutionPolicyPreference | Unrestricted
PSModulePath | WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Microsoft SQL Server\130\Tools\PowerShell\Modules\
PUBLIC | C:\Users\Public
PYTHON_HOME | C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64
SqlPackage | C:\Program Files\Microsoft SQL Server\140\DAC\bin\SqlPackage.exe
SystemDrive | C:
SystemRoot | C:\Windows
TEMP | C:\Windows\TEMP
TMP | C:\Windows\TEMP
USERDOMAIN | WORKGROUP
USERNAME | canary-wi000000$
USERPROFILE | C:\Windows\system32\config\systemprofile
VERBOSE_ARG | 'SilentlyContinue'
VisualStudio | C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\
VisualStudio_15.0 | C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\
VisualStudio_IDE | C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\
VisualStudio_IDE_15.0 | C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\
VS140COMNTOOLS | C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
VSTest | C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow
VSTest_15.0 | C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow
windir | C:\Windows
WindowsKit | C:\Program Files (x86)\Windows Kits\8.1\
WindowsKit_8.1 | C:\Program Files (x86)\Windows Kits\8.1\
WindowsSdk | C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A
WindowsSdk_7.1 | C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A
Xamarin.Android | 9.0.0

That's way more than the handful of additional items we install in our Packer build.

**Comment by lokesh755** [comment]
Capabilities on Hosted agents are not very accurate. To see the accurate details of software installed in hosted agents, please look  into "Details" tab after selecting particular hosted pool.

**Comment by riezebosch** [comment]
I'm wondering where the difference comes from compared to my custom build image using the exact same scripts.

**Comment by riezebosch** [comment]
We suddenly get coverage on our private agents presumably because of a fresh build of your repo on our site. So the main driver for this question is gone.
