### ISSUE TITLE
Deployment: Add/update to Ansible 2.7.0.0 (or latest) (Linux, Windows)

### ISSUE THREAD

**Issue by mathieu-benoit** [microsoft/azure-pipelines-image-generation#337]
The Ansible version installed is 2.0.0 but it's not the latest one (as we speak): 2.7.0.
We need to update the way we install Ansible:

Instead of:
```
apt-get install -y --no-install-recommends ansible
```
We should do:
```
apt-get install software-properties-common -y
apt-add-repository ppa:ansible/ansible -y
apt-get update && apt-get install ansible -y
```

Resources:

- https://docs.ansible.com/ansible/2.4/intro_installation.html#latest-releases-via-apt-ubuntu
- https://blog.programster.org/ubuntu-16-04-install-ansible

## Areas and ecosystems

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [X] Other

## Hosted pools

- [ ] macOS
- [X] Ubuntu
- [ ] Windows

**Comment by kaylangan** [comment]
Closing since Ansible 2.7.10 is available on Linux. Opened #954 for just Windows.
