### ISSUE TITLE
pip not found on Hosted VS2017

### ISSUE THREAD

**Issue by michaeljqzq** [Microsoft/azure-pipelines-image-generation#339]
# Help us route

This is the template for reporting a bug with image generation.
If you intended to request a new tool, please switch to the Tools template: https://github.com/Microsoft/azure-pipelines-image-generation/issues/new?template=tools.md

# If this is related to image generation...

## Description
Command `pip` is not found in Hosted VS2017 Agent.
From my side, pip is in the PATH in Hosted VS2017 agent.
But one of my customer reported that `pip` is not found in the PATH.
We both use agent version: 2.140.2 of Hosted VS2017

## Expected Behavior

pip is in the path.

## Actual Behavior

```
Unable to locate executable file: 'pip'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.
```

**Comment by brcrista** [comment]
Are you and your customer running the Use Python Version task?

**Comment by michaeljqzq** [comment]
> Are you and your customer running the Use Python Version task?

No. Actually our team maintains this extension https://marketplace.visualstudio.com/items?itemName=vsc-iot.iot-edge-build-deploy

In the extension, we use kind of this logic to install a python package:
```
tl.execSync("pip", "install xxx")
```

It works for `Hosted Linux Preview` agent. But for `Hosted VS2017` agent, it behaves different from my side and my customer, though with the same agent version. I checked with the [hosted agent dependency list](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md), the python is pre-installed. So I wonder why on some agent `pip` command is not found.

**Comment by bryanmacfarlane** [comment]
on a side note, you should do this if you want live console feedback (not buffered):

```
await tl.exec("pip", "install xxx");
```

**Comment by brcrista** [comment]
It's not going to be the agent version, the agent is just a piece of software that runs on the build VM.  But yes, Hosted VS2017 should have Pip in PATH.

Are you sure they're running on Hosted VS2017, or is it possible they're on their own build machine?  If they're running with YAML it's going to run on the pool specified in the YAML, not in the dropdown on the UI.

A few things you could ask them to do to debug:
* Run a build with system.debug=true to get verbose logs
* Run `script: where python` to see if Python is installed
* Run `script: dir C:\`

**Comment by michaeljqzq** [comment]
My customer reported that the issue no longer exists. Not sure if there's change in agent or customer had wrong settings. I'll close this issue and reopen it if meet the issue again, thanks
