### ISSUE TITLE
SessionNotCreatedError: session not created: Chrome version must be >= 69.0.3497.0

### ISSUE THREAD

**Issue by jakehockey10** [Microsoft/azure-pipelines-image-generation#340]
I'm very confused with this one.  I have two Angular CLI projects being built and tested in Azure DevOps and one gets through e2e tests just fine, while the other one doesn't.  The one that doesn't work fails with a message the same as the title of this issue.  I used the one that is working to build the one that isn't.  But I can't seem to find a way to choose the version that it is complaining is too low.  If this isn't something that can be updated for me, is there something that I can do to continue moving forward?  Thanks for the help!

## Tool info
- Tool name: ChromeDriver? 
- Add or update? Update 
- Desired version: >= 69.0.3497.0 

## Areas and ecosystems

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [x] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

## Hosted pools

- [ ] macOS
- [ ] Ubuntu
- [x] Windows

**Comment by betterze** [comment]
I also meet this problem. Any response?

**Comment by simplyTester** [comment]
I am also facing the same issue and could not upgrade chrome (currently version 68) due to corporate policies. What should I do now to run my  protractor tests.????

Thanks....

**Comment by ShreyasRmsft** [comment]
I was able to run a simple selenium test using the chromedriver on the hosted  pool and things worked fine.

![image](https://user-images.githubusercontent.com/25194518/48462383-f2242f80-e7fd-11e8-8946-0980ec7e04e9.png)


Can you please provide a sample repro project so that once we upgrade the version of chrome 
we can verify that this has been fixed?

**Comment by ShreyasRmsft** [comment]
Also as a workaround you can get a chromewebdriver compatible with the currently installed browser as part of your test project and change this environment variable (ChromeWebDriver) to point to the folder containing it if you were using the recommended sample template 

else just give the relative path to your chromedriver packaged along with the test dlls/sources when initializing the chromewebdriver.

**Comment by tomloake** [comment]
@ShreyasRmsft Judging by your screenshot, that agent was running ChromeDriver 2.40.565498 whereas the version running on the current "Hosted VS2017" agent is 2.43.600210 which requires >= 69.0.3497.0

**Comment by ShreyasRmsft** [comment]
Hmm, lemme take another look at this. The work around still holds good though. Will make sure we patch up the versions as soon as possible.

**Comment by kaadhina** [comment]
There is a compatible version of chrome driver that comes pre-installed in the hosted agents. You can access this from the location pointed to by the environment variable: ChromeWebDriver

**Comment by jakehockey10** [comment]
I apologize, I didn't recognize that as a solution.  The VS2017 Hosted build agent didn't seem like something I could choose the versions of components that that build agent consisted of.  I eventually got around this but I'm not sure how.  I don't know whether it was more specific rules in my package.json for versions, updated versions, or just that some of the build agents had the right version of chrome web driver on it while others did not.

What am I misunderstanding?

**Comment by pdemro** [comment]
I was able to resolve this for now in my node project by downgrading my dependency for chromedriver to 2.40.0

```
"dependencies": {
    "chromedriver": "2.40.0"
  }
```
