### ISSUE TITLE
[Feature Request] Run agents as an admin on Hosted agent pool

### ISSUE THREAD

**Issue by victorguo** [microsoft/azure-pipelines-image-generation#341]
## Description
My project needs to be built under Visual Studio 2015 so I have to choose **Hosted** agent pool. But it seems that I don't have administrative permissions on **Hosted**. When I try running the following cmdlet, 

`netsh http add urlacl url=http://+:<portNumber>/ user=%USERDOMAIN%\%USERNAME%
`

the error occurs:

> The requested operation requires elevation (Run as administrator).

I have checked the logon user is _buildguest_.

However, I found that when running the build on **Hosted VS2017** agent pool, the logon user would be _VssAdministrator_ as an administrator, which was stated at #54.

## Expected Behavior
Run the agent as an admin on **Hosted**.

## Actual Behavior
The agent is ran as a guest on **Hosted**.

**Comment by victorguo** [comment]
Any updates?

**Comment by victorguo** [comment]
Any updates?

**Comment by alepauly** [comment]
@victorguo Have you verified that this is still an issue? All agents including Default Hosted should be running under VssAdministrator. If this is not the case, please let me know your Azure DevOps org name and I can check into it.

**Comment by victorguo** [comment]
@alepauly Thanks for the information. I've checked and it is OK now.
