### ISSUE TITLE
VS2017 image - update MS-MPI version

### ISSUE THREAD

**Issue by rjbgoudie** [microsoft/azure-pipelines-image-generation#342]
Version 7.1.12437.25 from June 2016 is currently installed in C:\Program Files\Microsoft MPI

## Tool info
- Tool name: Microsoft MPI
- Add or update? Update
- Desired version: 10.0
- If this is an add request:
  - Brief description of tool: Microsoft MPI (MS-MPI) is a Microsoft implementation of the Message Passing Interface standard for developing and running parallel applications on the Windows platform.
  - URL for tool's homepage: https://docs.microsoft.com/en-us/message-passing-interface/microsoft-mpi

## Areas and ecosystems

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [x] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

## Hosted pools

- [ ] macOS
- [ ] Ubuntu
- [x] Windows

**Comment by letmaik** [comment]
Same issue: https://developercommunity.visualstudio.com/content/problem/446886/cannot-uninstall-microsoft-mpi-in-azure-pipeline-o.html

**Comment by rjbgoudie** [comment]
Just to note that the new 'windows-2019' image still has old MS-MPI, although it seems it can now be overwritten/uninstalled, unlike before. So, while it would still be useful to update MS-MPI, it is less crucial than before.
