### ISSUE TITLE
Deployment: Add Azure Cosmos DB Emulator 2.1.2 (or latest) (Windows)

### ISSUE THREAD

**Issue by ykonovalets** [microsoft/azure-pipelines-image-generation#343]
## Description
I want to add launching 'Azure CosmosDb Emulator' as a part of CI pipeline using following command line command:
"C:\Program Files\Azure Cosmos DB Emulator\CosmosDB.Emulator.exe" /noui /noexplorer

## Expected Behavior
'Azure CosmosDb Emulator' started successfully

## Actual Behavior
Command runs infinite amount of time without logs and then fails due to timeout.

**Comment by pulkitaggarwl** [comment]
@ykonovalets  thanks for reaching out earlier and apologies for a tardy reply.
I wanted to check with you if you have tried our marketplace task around this 
https://marketplace.visualstudio.com/items?itemName=azure-cosmosdb.emulator-public-preview

**Comment by da1rren** [comment]
@pulkitaggarwl It takes in excess of 6 minutes to pull that container on a vsts hosted agent.  Whereas the emulator should only take a moment to start.

I appreciate that using a private agent would alleviate the download but that seems besides the point.

**Comment by da1rren** [comment]
@ykonovalets It appears that you can start it in a background thread using something like:

```
$emulator = 'C:\Program Files\Azure Cosmos DB Emulator\Microsoft.Azure.Cosmos.Emulator.exe'
Start-Process $emulator  -ArgumentList '/DisableRateLimiting /NoExplorer /NoFirewall /NoUI'
```

**Comment by poveden** [comment]
I've tried @da1rren's approach, and although it runs locally, it still gets stuck on VSTS. Could it be that Cosmos DB requires admin privileges to run (as I get an elevation prompt locally), and the VSTS Agent is waiting forever for that prompt?

**Comment by wahyuen** [comment]
Given the issue was renamed, does this imply that this is an issue with the version that is currently deployed on the VS2017 Hosted Image? Would this be a non issue on the VS2019 hosted image?

**Comment by AnunnakiSelva** [comment]
@poveden  Am also facing same kind of issue , Have tried 3 ways to use mongo api from cosmos emulator still couldn't make it .

1)Tried to start  the cosmos emulator ".exe" from powershell, which works fine in local but not in both hosted machine  2017 and  2019 .

2) Installed the docker emulator from devops task, It perfectly installing and runs on the docker but when i try to access with https://{Docker_Name}:10255 it throws ssl error . with  localhost:10255 it throws "connection actively refused by remote host"

3) pulled cosmos emulator container and deployed that on a docker container . It perfectly works on my local on localhost: 10255 . But when i try to do same on hosted machine 2017 and 2019 it throws error saying "tty" (pseudo  terminal not supported and ask me to use winptty) . 

Thanks , looking for your advice ):

**Comment by kaylangan** [comment]
I got in touch with @milismsft offline. He said:
"The latest Hosted VS2017 seems to have Azure Cosmos Emulator installed; you just need to start it from an Administrator command prompt window (or PowerShell with Admin privileges). 

There’s an Azure Cosmos Emulator VSTS extension that can be added to your pipeline (https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb). Also instead of using port 10255 can the user try with port 10250?"

**Comment by AnunnakiSelva** [comment]
@kaylangan  I have tried with azure emulator in the pipeline , But it also throws timeout error when trying to use the local host connection  in my app.

**Comment by chrislangston** [comment]
@da1rren and @poveden   Were you able to get the locally installed Cosmos Emulator to startup?  

If you had to invoke Admin privileges in order to do so can you please share the syntax you had to take?

Thanks so much :-)

**Comment by chrislangston** [comment]
I was able to get the locally installed Emulator on the vmImage: 'windows-2019' using the following:

This is my emulator-setup.yml file

Note that it takes between 3 and 4 minutes every time for the local emulator to start for some reason.

This script waits up to 10 times to verify the status of a running local Emulator.

`
# File: emulator-setup.yml

steps:
  - pwsh:  |
        Write-Host "Starting Comsos DB Emulator" -ForegroundColor green 
        Start-Process "C:\Program Files\Azure Cosmos DB Emulator\CosmosDB.Emulator.exe" "/NoExplorer /NoUI /DisableRateLimiting /PartitionCount=100 /Consistency=Strong /enableRio /overrides=sqlAllowGroupByClause:true" -Verb RunAs
        Import-Module "C:\Program Files\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"
        Get-Item env:* | Sort-Object -Property Name
        for ($i=0; $i -lt 10; $i++) {
          $status=Get-CosmosDbEmulatorStatus 
          if ($status -ne "Running") {
            sleep 30;
            Write-Host "Cosmos DB Emulator Status: $status" -ForegroundColor yellow
          } else {
            break;
          }
        }
      
    displayName:  Starting Installed Cosmos DB Emulator
    failOnStderr:  true
    errorActionPreference:  stop
`

**Comment by milismsft** [comment]
For the locally installed emulator (MSI) you can use the PowerShell module to start the emulator and loop until it is fully initialized (see %PROGRAMFILES%\Azure Cosmos Db Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator)

**Comment by mattwiz** [comment]
@chrislangston with your start up steps (emulator-setup.yml) how do you know what port the emulator is running on?
