### ISSUE TITLE
(Hosted VS2017) MicrosoftWebDriver.exe is not compatible with the installed version of Windows 10

### ISSUE THREAD

**Issue by JayasreeAdukkadkam** [Microsoft/azure-pipelines-image-generation#344]
(Hosted VS2017) MicrosoftWebDriver.exe is not compatible with the installed version of Windows 10.

Existing versions: (not comatible)
 MicrosoftWebDriver : 6.17134 
Windows 10:  10.0.14393 N/A Build 14393

- [x] General purpose tools
- [x] Testing 

## Hosted pools

- [x] Windows

**Comment by JayasreeAdukkadkam** [comment]
Any updates on this please ?

**Comment by cltshivash** [comment]
@JayasreeAdukkadkam Can you please let us know the scenario/scaled down repro of the test project that you are trying to execute ?

**Comment by JayasreeAdukkadkam** [comment]
@cltshivash  I am trying to run automated tests on Edge browser and it seems the  version is older in the agent and the WebDriver installed is latest which  is not compatible 

The hosted agent has 
MicrosoftWebDriver : 6.17134  (This is the latest version)
Windows 10: 10.0.14393 N/A Build 14393  (old)
And hence not compatible

As per the page  https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/

Release 17134
MicrosoftWebDriverVersion: 6.17134 | Edge version supported: 17.17134

For Release 14393
MicrosoftWebDriverVersion: 3.14393 | Edge version supported: 14.14393 

Hope this helps. Thank you

**Comment by cltshivash** [comment]
@JayasreeAdukkadkam Hosted 2017 pool uses Server 2016 machines and Edge is not a supported browser on it. Please use a private agent if you want to test against the Edge browser.

"The Long-Term Servicing Branch (LTSB) versions of Windows, including Windows Server 2016, don't include Microsoft Edge or many other Universal Windows Platform (UWP) apps. These apps and their services are frequently updated with new functionality, and can't be supported on systems running the LTSB operating systems."

**Comment by JayasreeAdukkadkam** [comment]
@cltshivash Thank you for the update.

Could you please let me know if there any plan on having  hosted agent with Edge on it ?

**Comment by PBoraMSFT** [comment]
@DavidStaheli - do we have plans to make client OS based hosted agents available ?
