### ISSUE TITLE
Request: Update AzureRM module on Hosted VS2017

### ISSUE THREAD

**Issue by jude-chen** [microsoft/azure-pipelines-image-generation#347]
# Help us route

This is the template for requesting new or updated tools on the hosted images.
If you intended to file a bug, please switch to the Bugs template: https://github.com/Microsoft/azure-pipelines-image-generation/issues/new?template=bugs.md

# If this is a request for a new tool or tool version...

## Tool info
- Tool name: AzureRM PowerShell module
- Add or update? update
- Desired version: 6.9.0 or above
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 
  - Open source license type (Apache, MIT, GPL, etc.): 

## Areas and ecosystems

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [x] Other

## Hosted pools

- [ ] macOS
- [ ] Ubuntu
- [x] Windows

**Comment by scott1138** [comment]
@kmkumaran @RoopeshNair - Can we get an update on this?  It slows the process to have to install AzureRM everytime I want to run a build.  The command New-AzureRMDeployment doesn't exist in 6.7.

**Comment by kmkumaran** [comment]
Can you please hold updating any latest version of Azure RM modules. We will have to move to new Az modules which replaces the Azure RM modules. + @niadak to update with details on which Az module to be updated in hosted agent.

**Comment by scott1138** [comment]
@kmkumaran Any chance we could do both they way it is now and just import the module we need.  I still have a lot of scripts that use AzureRM and I am sure many others do as well.

**Comment by scott1138** [comment]
@kmkumaran Are we ever going to get an updated AzureRM or Az module on this build image?  It is sadly out of date.

**Comment by kmkumaran** [comment]
@scarlett2018 - The Az module is updated in hosted image. It is in the process of getting rolled out to rings. Depending on where your account is, you might see it this week or next. + @niadak

**Comment by scott1138** [comment]
@kmkumaran  - Is the AzureRM module being skipped?  Azure DevOps doesn't have a task for Deployments without a resource group defined so I used a marketplace task.  The person who wrote it uses AzureRM.  I am hoping the alias mode will work with Az, but it would be nice to have them both for now.

**Comment by niadak** [comment]
Yes. We are not updating AzureRM module in hosted agent and only new versions of Az module will be added going forward. However exiting supported AzureRM Module versions (1.0.2, 3.8.0, 4.2.1, 5.1.1, 6.7.0) will be still supported.

Alias mode should jut work. Can you share the market place task with us so that we can confirm?

**Comment by niadak** [comment]
We are not updating AzureRM module anymore given that Az module is already available in hosted agent.
We are making some change to ensure Enable-AzureRmAlias is working properly.
