### ISSUE TITLE
where is vcvarsall.bat?

### ISSUE THREAD

**Issue by andrewrk** [Microsoft/azure-pipelines-image-generation#351]
## Areas and ecosystems

- [ ] Android
- [x] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

## Hosted pools

- [ ] macOS
- [ ] Ubuntu
- [x] Windows

# Where is `vcvarsall.bat`?

I expect it to be: `C:\Program Files (x86)\Microsoft Visual Studio 15.0\VC\vcvarsall.bat` but this file does not exist. It is also not in `PATH`.

**Comment by andrewrk** [comment]
found it

`call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64`

**Comment by svenevs** [comment]
Hello, I was looking at the environment variables defined on azure pipelines for something else and noticed the following variables are exported:

```
******************************************** VCIDEINSTALLDIR:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\
******************************************** VCINSTALLDIR:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\
******************************************** VCTOOLSINSTALLDIR:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\
******************************************** VCTOOLSREDISTDIR:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Redist\MSVC\14.16.27012\
******************************************** VCTOOLSVERSION:
14.16.27023
******************************************** VISUALSTUDIOVERSION:
15.0
******************************************** VS140COMNTOOLS:
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
******************************************** VS150COMNTOOLS:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\
******************************************** VSCMD_ARG_APP_PLAT:
Desktop
******************************************** VSCMD_ARG_HOST_ARCH:
x64
******************************************** VSCMD_ARG_TGT_ARCH:
x64
******************************************** VSCMD_VER:
15.9.11
```

So you should be able to `call "%VCINSTALLDIR%\Auxiliary\Build\vcvarsall.bat" x64` for any hosted vs agent (I think, unless it's in a different place, I'm not very experienced with Visual Studio...).

Just including them here for anybody else finding this issue (thanks for hunting this down @andrewrk :) )
