### ISSUE TITLE
Add x86 versions of Python to the hosted tool cache

### ISSUE THREAD

**Issue by DavidStaheli** [Microsoft/azure-pipelines-image-generation#365]
See the original issue from @spacether here:
https://github.com/MicrosoftDocs/vsts-docs/issues/2216

Though the docs[ list x86 as a valid python system architecture](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=vsts), the tool cache is missing:
Python versions 3.5, 3.6, 3.7 for x86 architecture in Ubuntu 16.04 and macOS-10.13

Please add the x86 Python versions to the tool cache for the above operating systems.

**Comment by brcrista** [comment]
@spacether -- x86 is just for Windows.  macOS and Linux don't do x86 emulation like Windows does with SysWoW64.

I wrote the doc page for Use Python Version.  I was hoping that linking to the lists of installed software on the images would make clear what flavors are available, but looking at it again I can see why it might be confusing.

I'm going to reopen the original issue in the docs repo.
