### ISSUE TITLE
C/C++: Add Unreal Engine (Linux, Windows)

### ISSUE THREAD

**Issue by Ludea** [microsoft/azure-pipelines-image-generation#367]
Add Unreal Engine on all platform 

## Tool info
- Tool name: Unreal engine 
- Add or update? add
- Desired version: 4.24
- If this is an add request:
  - Brief description of tool: it is a game Engine, FPS oriented. 
  - URL for tool's homepage: https://www.unrealengine.com/en-US/what-is-unreal-engine-4
  - Open source license type (Apache, MIT, GPL, etc.): Unreal Engine Eula https://www.unrealengine.com/en-US/eula# Areas and ecosystems

- [ ] Android
- [x ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [x ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

## Hosted pools

- [ x] macOS
- [x ] Ubuntu
- [x ] Windows

**Comment by Ludea** [comment]
Why delete Mac support?

**Comment by GlennKintscher** [comment]
I would love to see this, please take another look!

**Comment by excitoon** [comment]
That would be awesome!

**Comment by Ludea** [comment]
any news on this ?

**Comment by FatDrone** [comment]
Should change the version to 4.22 at this point. :)

**Comment by kaylangan** [comment]
We don't currently have plans to add this in the short term. There's clearly demand--just a matter of timing and resourcing.

**Comment by IgazHarcos** [comment]
I will be mire than happy with this! Please add!

**Comment by kaylangan** [comment]
Not stale

**Comment by FatDrone** [comment]
Nope, we need this feature at some point!

**Comment by ruohki** [comment]
would love to see a azure implementation of this. What is the point in even using azure if you cant test your builds.

**Comment by kasp1** [comment]
Mmmm!

**Comment by ruohki** [comment]
So ignored for almost 2 years already.

**Comment by Ludea** [comment]
I recreate an [issue](https://github.com/actions/virtual-environments/issues/2003) since azure pipeline move to GH actions
