### ISSUE TITLE
Updated Xcode 10.1 path

### ISSUE THREAD

**Issue by macromania** [Microsoft/azure-pipelines-image-generation#370]
Xcode 10.1 path was wrong on the documentation website. This issue is to raise it and combining with 
PR https://github.com/Microsoft/azure-pipelines-image-generation/pull/369 in order to follow the process.

This is my first PR to this repo, I hope I'm following the process as expected.

## Tool info
- Tool name: Xcode Path
- Add or update? Update
- Desired version: 10.1
- If this is an add request:
  - Brief description of tool: `/Applications/Xcode_10.3.app` is the wrong path for Xcode 10.1
  - URL for tool's homepage: https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-Readme.md#xcode

## Areas and ecosystems

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [X ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

## Hosted pools

- [X ] macOS
- [ ] Ubuntu
- [ ] Windows

**Comment by DavidStaheli** [comment]
PR #369 is merged.  Thanks a lot, @macromania!
