### ISSUE TITLE
Service Fabric SDK needed on Ubuntu 16.04

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/azure-pipelines-image-generation#371]
Also requested on [Twitter](https://twitter.com/andrejmedic/status/1063795598720065543?s=12) and [Developer Community](https://developercommunity.visualstudio.com/idea/385310/service-fabric-cicd-support-for-linux-azure-devops.html).

To install on Ubuntu:
```bash
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-linux
sudo apt-get install -y apt-transport-https curl software-properties-common
sudo curl -s https://raw.githubusercontent.com/Azure/service-fabric-scripts-and-templates/master/scripts/SetupServiceFabric/SetupServiceFabric.sh | sudo bash
```

See [Prepare your development environment on Linux](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-linux).

**Comment by MedAnd** [comment]
Full request history: https://github.com/Microsoft/vsts-agent-docker/issues/145

**Comment by MedAnd** [comment]
Hi @DavidStaheli, just following up on this feature... any update? Thanks.

**Comment by sachinma** [comment]
@pulkitaggarwl can you comment on this request?

**Comment by MedAnd** [comment]
@davidstaheli @pulkitaggarwl  @sachinma - would be good to know why this is being closed, is there another approach or direction etc?

**Comment by pulkitaggarwl** [comment]
MedAnd, we have added this item to the backlog but haven't been able to prioritize it yet. Will try to get to this one as early as possible.   In the interim you can refer below steps on a private agent to connect to cluster.

> 

- Run: sudo pip install sfctl
- Add cluster endpoint, certificate and password information as secure variables in RD
- If certificate is pfx type, save the secure variable value of certificate in a pfs file and convert PFX to PEM using: 
-- openssl pkcs12 -in certificate.pfx -out mycert.pem -nodes
- Write a script using SFCTL to connect to cluster using secure variables defined in RD: 
-- sfctl cluster select --endpoint $(EndpointUrlSecureVariable) --pem ./mycert.pem --no-verify
- Deploy using SFCTL to the linux cluster: 
-- sfctl application upload --path ~/app_package_dir
-- sfctl application provision --application-type-build-path app_package_dir
-- sfctl application create --app-name fabric:/TestApp --app-type TestAppType --app-version 1.0

>

**Comment by MedAnd** [comment]
Appreciate the update @pulkitaggarwl and road-map clarity... will keep this open in case one day Service Fabric gets more priority....
