### ISSUE TITLE
.NET Core: Add .NET Core SDK 2.1.500 (Linux, Windows)

### ISSUE THREAD

**Issue by yhvicey** [Microsoft/azure-pipelines-image-generation#372]
VSTS feeds cannot be used with 2.1.500 and yaml pipeline, please upgrade it

## Tool info
- Tool name: DotNet SDK
- Add or update? Update
- Desired version: 2.1.500

## Areas and ecosystems

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [x] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

## Hosted pools

- [x] macOS
- [x] Ubuntu
- [x] Windows

**Comment by DavidStaheli** [comment]
The `macOS-10.13` image got this version today.

**Comment by ilmax** [comment]
Hi @DavidStaheli, do you have an estimated date about when the Ubuntu agents will receive the same upgrade?

**Comment by DavidStaheli** [comment]
Hi @ilmax.  It's an automatic process that the new versions are included, but @dakale do you know when the next Ubuntu-16.04 image will deploy with this version (released 2018-11-13)?

**Comment by ilmax** [comment]
Hey @DavidStaheli, @dakale my build still fails because of this, any update here? Any ETA?

**Comment by yhvicey** [comment]
@ilmax For now you can use `DotNetCoreInstaller` as a workaround:

```yml
steps:
# Install required SDK
- task: DotNetCoreInstaller@0
  displayName: Install SDK 2.1.500
  inputs:
    version: '2.1.500'
```

However this seems have some error. You can have a try to see if this works for you.

**Comment by ilmax** [comment]
Will try this out, thanks

**Comment by yhvicey** [comment]
It seems Ubuntu already have this sdk installed. Is there any update on Windows image?

**Comment by hiyadav** [comment]
New image for Hosted VS2017 is being rolled out, and should solve this for everyone within a weeks time.

**Comment by bishal-pdMSFT** [comment]
The rollout has been completed.
