### ISSUE TITLE
VS2015 image doesn't have Python in the PATH

### ISSUE THREAD

**Issue by jefgen** [Microsoft/azure-pipelines-image-generation#374]
The hosted VS2015 image does not contain Python in the PATH.

List of software installed contains Python 3:
https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2015-Server2012R2-Readme.md

However, it is not present in the PATH and the documentation doesn't even say where it is installed (path location) on the VM image.

Additionally, trying to run the "Python Version task" fails on VS2015 image as well:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=vsts

**Comment by vtbassmatt** [comment]
Hey @jefgen. The VS2015 image was never released to the Hosted pools, so it's not complete and not supported. I added a note to the README indicating this.

In the future, if we decide to move forward with the image, we'll fix this Python 3 issue. CC @joebourneMS

**Comment by vtbassmatt** [comment]
(The `vs2015-win2012r2` pool doesn't use this image. For Python3, I'd recommend the `vs2017-win2016` image for now.)

**Comment by jefgen** [comment]
Hey, thanks for the reply!

What image does the `vs2015-win2012r2` pool use then?

I'm a bit confused as the documentation on the official page [here](https://docs.microsoft.com/en-ca/azure/devops/pipelines/agents/hosted?view=vsts&tabs=yaml#software) links directly to the list that I [linked above](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2015-Server2012R2-Readme.md).

Is there some _other list_ of software that is installed on the `vs2015-win2012r2` image? (Or are you saying that the `vs2015-win2012r2` image is not supported?)

As for the issue of using vs2017 versus vs2015, there is already a build setup that is using the vs2015 image and that works fine (as the image has Python 3). However, I'm trying to provide build support/coverage using Visual Studio 2015 specifically, which is why I am interested in the vs2015 image.

**Comment by vtbassmatt** [comment]
The `vs2015` image is actually running an earlier, not-open-sourced image. We started porting over to the open source repo, but we had a working 2015 pool and other projects got in the way, so we never finished it. The list of software was identical at one point, which is why we pointed the docs there. Good catch, I'll get that fixed.

**Comment by jefgen** [comment]
Thanks!
Do you know if there is there any plan to update the images used for the `vs2015` pool at some point?

I'm wondering if I just need to sit and wait, or if I should start investigating using AppVeyor for VS2015 build support. (Or possibly download the Python 3 installer on the VM every time...) Thanks!

**Comment by jefgen** [comment]
No worries! Thanks again for your replies. :)

**Comment by mloskot** [comment]
There is `C:\Python27` as per https://github.com/Microsoft/azure-pipelines-image-generation/issues/374#issuecomment-440102868 but any attempt to use it fails:

```yaml
- task: UsePythonVersion@0
  displayName: 'Setup Python'
  inputs:
    versionSpec: '2.7'
    addToPath: true
```

I understand that "the vs2015-win2012r2 image receives little-to-no maintenance now" as per https://github.com/Microsoft/azure-pipelines-image-generation/issues/761#issuecomment-474323458

But the VS2015 is still an important C/C++ platform and having a usable Python on it would be extremely helpful (e.g. I'm unable to run tests of Boost.GIL library due to lack of Python).

**Comment by brcrista** [comment]
Use Python Version won't find it there, but I think that Python 2.7 is in PATH already?  If not, you can add it:

```yaml
- pwsh: |
    Write-Host "##vso[task.prependpath]C:\Python27"
    Write-Host "##vso[task.prependpath]C:\Python27\Scripts"
  displayName: Add Python 2.7 to PATH
```

**Comment by mloskot** [comment]
Right, it seems in the `PATH` indeed, but there seem to be no `pip` module installed. I need to figure out to get it in. Thanks.

**Comment by brcrista** [comment]
This should work:
```
python -m ensurepip
python -m pip install --upgrade pip
```

**Comment by mloskot** [comment]
Thanks for the tip, but that does not work for me

![image](https://user-images.githubusercontent.com/80741/54638383-39ac1800-4a8b-11e9-928f-a84bdcef453b.png)

(Full build log https://dev.azure.com/boostorg/gil/_build/results?buildId=266)

**Comment by brcrista** [comment]
Oh wow, 2.7.3 -- that's really old.  That's probably why it doesn't have ensurepip.

You could try the [Chocolatey package](https://chocolatey.org/packages/python2):
`choco install --yes python2`

**Comment by mloskot** [comment]
Oh, indeed! ensurepip is [New in version 2.7.9.](https://docs.python.org/2.7/library/ensurepip.html)

**Comment by mloskot** [comment]
Regardless that I got enthusiastic about Chocolatey and went for 3.7, there is no `choco`

![image](https://user-images.githubusercontent.com/80741/54639258-39ad1780-4a8d-11e9-9503-bcf814b63cdc.png)

I think best bet will be to run download `https://www.python.org/ftp/python/3.7.2/python-3.7.2-amd64.exe` and run it.

**Comment by jefgen** [comment]
FWIW, I eventually gave up an just downloaded the Python installer directly on the VM as part of the Azure Pipelines setup. (Though I'm using Python 3, the same would apply to Python 2 as well.)

Ex: https://github.com/unicode-org/icu/blob/master/.ci-builds/.azure-pipelines.yml#L97

```
    - powershell: 'Invoke-WebRequest https://www.python.org/ftp/python/3.7.1/python-3.7.1-amd64-webinstall.exe -OutFile c:\py3-setup.exe'
    - script: |
        c:\py3-setup.exe /quiet PrependPath=1 InstallAllUsers=1 Include_launcher=1 InstallLauncherAllUsers=1 Include_test=0 Include_doc=0 Include_dev=0 Include_debug=0 Include_tcltk=0 TargetDir=c:\py3
```

**Comment by mloskot** [comment]
@jefgen Awesome, thank you!

**Comment by mloskot** [comment]
I noticed that the `PrependPath=1` has no effect here:

```yaml
- script: |
    c:\py3-setup.exe /quiet PrependPath=1 InstallAllUsers=1 Include_launcher=1 InstallLauncherAllUsers=1 Include_test=0 Include_doc=0 Include_dev=0 Include_debug=0 Include_tcltk=0 TargetDir=c:\py3
- script: |
    python --version
    py -3 --version
```

and only `py -3` launcher recognises the newly installed Python, but 2.7 remains as `python.exe`  in PATH

![image](https://user-images.githubusercontent.com/80741/54641057-885cb080-4a91-11e9-95ac-52e2f399e4e1.png)

**Comment by jefgen** [comment]
Hmm, good catch. I *thought* it was working when I added it, but the builds have aged out so the logs don't exist anymore.

The data build scripts explicitly call the launcher with `py -3` which is perhaps why we didn't notice anything.

I wonder if calling with `py -2` would work?

**Comment by mloskot** [comment]
Unfortunately, the build configs I rely on (CMake, Boost.Build) require tools in PATH. The problem is, PATH modifications are not persisted between steps (or, I have not figured out yet how to make it such).

**Comment by mloskot** [comment]
I've just learned this trick and managed to modify `PATH`

```yaml
- script: |
    @echo ##vso[task.prependpath]C:\Python37
    @echo ##vso[task.prependpath]C:\Python37\Scripts
```

**Comment by jefgen** [comment]
Oh wow, that's awesome! Thank you @mloskot!

It seems to work well:
![image](https://user-images.githubusercontent.com/29107334/54652188-37d65a80-4a73-11e9-9f5c-e48aa7765d86.png)

I'll file a ticket to update the ICU azure-pipelines file with your fix. Thanks!

**Comment by mloskot** [comment]
@jefgen Clearly, it's a collaborative success :-) Thanks!

**Comment by lazka** [comment]
In case someone wants to go through choco, this installs chocolatey in the vs2015 image:

```yaml
- powershell: |
  $env:ChocolateyInstall="C:\choco"
  Set-ExecutionPolicy Bypass -Scope Process -Force; iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex
  Write-Host "##vso[task.prependpath]C:\choco\bin"
  choco feature enable -n allowGlobalConfirmation
displayName: Install choco
````
