### ISSUE TITLE
Testing: Add/update to Firefox Web Driver (geckodriver) 0.24.0 (or latest) (Linux)

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/azure-pipelines-image-generation#379]
Add/update to Firefox Web Driver (geckodriver) 0.21.0 (or latest) (Linux, macOS, Windows)

**Comment by kaylangan** [comment]
Closing. Current version is 0.24.0.

**Comment by kaylangan** [comment]
Re-opening and renaming for Linux only.

**Comment by kaylangan** [comment]
Not stale
