### ISSUE TITLE
Android: Add Android emulator (latest) (Linux, Windows)

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/azure-pipelines-image-generation#381]
Android: Add Android emulator (latest) (Linux, Windows)

**Comment by atownsend-iotic** [comment]
Is it possible to reopen this? This would be very useful for me right now.

**Comment by eric-labelle** [comment]
Please also consider [my issue](https://github.com/microsoft/azure-pipelines-image-generation/issues/1225) (for OSX). I would have submitted the PR but the OSX generation scripts are not available.

**Comment by eric-labelle** [comment]
Bump to keep this open!!
