### ISSUE TITLE
Android: Add Android SDK Build-Tools 28.0.3 (Linux, Windows)

### ISSUE THREAD

**Issue by DavidStaheli** [Microsoft/azure-pipelines-image-generation#385]
Android: Add Android SDK Build-Tools 28.0.3 (Linux, Windows)

**Comment by acortelyou** [comment]
+1

**Comment by ludovic-garcia** [comment]
+1

**Comment by JesusSpiegel** [comment]
A problem occurred configuring project ':app'.
Failed to install the following SDK components:
build-tools;28.0.3 Android SDK Build-Tools 28.0.3
The SDK directory is not writable (/usr/local/lib/android/sdk)

**Comment by nguyenlamlll** [comment]
Hi everyone, is there any progress on this issue?

I'm encountering this issue on Linux agent only, meaning build steps on Windows works fine. I opened a question [here](https://stackoverflow.com/questions/53870742/sdk-directory-is-not-writable-when-building-android-project-on-ubuntu-agent-of-a) in case someone needs more details.

On Windows, this works:
```
.\gradlew assembleDebug
```

On Linux (Hosted Ubuntu 1604), I'm using:
```
chmod 775 gradlew
./gradlew assembleDebug
``` 
and the build throws this exception:
```
* What went wrong:
A problem occurred configuring project ':app'.
> Failed to install the following SDK components:
      build-tools;28.0.3 Android SDK Build-Tools 28.0.3
  The SDK directory is not writable (/usr/local/lib/android/sdk)
```

**Comment by DavidStaheli** [comment]
@nguyenlamlll the 28.0.3 build tools should be available on hosted Linux in the next 3 weeks.  We're changing our processes to make rollout much faster than this going forward.
