### ISSUE TITLE
Containers: Update Docker to 18.09.1 (or latest) (Windows)

### ISSUE THREAD

**Issue by DavidStaheli** [Microsoft/azure-pipelines-image-generation#391]
Containers: Update Docker to 18.09.1 (or latest) (Windows)

**Comment by shashankbarsin** [comment]
I investigated this issue 2 days ago as 18.09 brings with it the option to use BuildKit backend (performance improvements and better handling of build-time secrets). The version will get bumped up in the next release of all our hosted agents

**Comment by shashankbarsin** [comment]
Got addressed as a part of #646
