### ISSUE TITLE
JavaScript and Node.js: Update to Node Version Manager (NVM) 4.9.1 (or latest) (Linux, Windows)

### ISSUE THREAD

**Issue by DavidStaheli** [Microsoft/azure-pipelines-image-generation#404]
JavaScript and Node.js: Update to Node Version Manager (NVM) 4.9.1 (or latest) (Linux, Windows)

**Comment by brkerr** [comment]
Currently NVM is not supported in Windows, and for Linux we already install n ([https://github.com/tj/n](https://github.com/tj/n)), which functions similarly.
