### ISSUE TITLE
Scripting: Add/update to MinGW-w64 7.2.0  (or latest) x86_64 (Windows)

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/azure-pipelines-image-generation#439]
This issue was created after a brief, cursory scan that found this missing.
Add/update to MinGW-w64 7.2.0  (or latest) x86_64 (Windows)

**Comment by tylerjereddy** [comment]
Related to the nature of the MinGW install -- would you expect 32-bit compilations to work with the currently-installed MinGW toolchain on the Hosted VS2017 pool? A sample 64-bit success and matching 32-bit failure for our initial testing with SciPy is available here: https://dev.azure.com/tylerjereddy/tyler-scipy-fork/_build/results?buildId=373&view=logs

**Comment by vtbassmatt** [comment]
@DavidStaheli I think your team owns this tool. I'm fine with it, but leaving it for you to approve.
