### ISSUE TITLE
Scripting: Add/update to shfmt 2.4.0 (or latest) (Linux)

### ISSUE THREAD

**Issue by DavidStaheli** [Microsoft/azure-pipelines-image-generation#441]
This issue was created after a brief, cursory scan that found this missing.
Add/update to shfmt 2.4.0 (or latest) (Linux)

**Comment by vtbassmatt** [comment]
Is this a compete thing, or is a customer asking for it?

**Comment by dakale** [comment]
This looks like a pretty niche dev dependency me.

**Comment by vtbassmatt** [comment]
You can pretty easily `go get` this. Going to pass for now.
