### ISSUE TITLE
Deployment: Add AWS CLI 1.16.54 (or latest) (Linux, Windows)

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/azure-pipelines-image-generation#442]
Deployment: Add AWS CLI 1.16.54 (or latest) (Linux, macOS, Windows)

**Comment by steven-cuthill-otm** [comment]
Dont want this to be closed. 

Please can the AWS CLI be added to all supported images 

**Linux**  / **MacOS**  / **Windows** 
AWS CLI
AWS PowerShell Core Module 
Boto3
Boto2

**Comment by tgolly** [comment]
For companies using Azure Pipelines in heterogeneous cloud environments this is a **must-have**.  Please keep this request open.

**Comment by cjheppell** [comment]
Looks like this has been added as of https://github.com/microsoft/azure-pipelines-image-generation/pull/1167 for Ubuntu, at least.

However, the Ubuntu 16.04 readme specifying the installed software hasn't been updated accordingly: https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/linux/Ubuntu1604-README.md

Would be great to update these issues, and also the documentation to include the latest available software as it's currently misleading.
