### ISSUE TITLE
Deployment: Add AzCopy (latest version) (Windows)

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/azure-pipelines-image-generation#443]
This issue was created after a brief, cursory scan that didn't find AzCopy already preinstalled on VS2017-Win2016.  Please close if I missed it.  Thanks.
Add AzCopy (latest version) (Windows)

**Comment by mahilleb-msft** [comment]
azcopy 10 is now noted as latest supported version, cf. https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10.
Are there plans to add this?
