### ISSUE TITLE
Packages: Add/update to NuGet 4.7.1 (or latest) (Linux, Windows)

### ISSUE THREAD

**Issue by DavidStaheli** [Microsoft/azure-pipelines-image-generation#449]
Packages: Add/update to NuGet 4.7.1 (or latest) (Linux, Windows)

**Comment by DavidStaheli** [comment]
@alexmullans I suspect this issue has already been addressed and can be closed?

**Comment by alexmullans** [comment]
Waiting on roll-out, but yes: https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/1374064
