### ISSUE TITLE
Common tools: Add/update to Qt tools: MinGW 5.3.0, MinGW 4.9.2 (or latest) (Windows)

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/azure-pipelines-image-generation#461]
Common tools: Add/update to Qt tools: MinGW 5.3.0, MinGW 4.9.2 (or latest) (Windows)

**Comment by ta2gch** [comment]
I success to use Qt5 on the image. We can use Qt5 with MSYS2 installed by Chocolatey. However It takes time, I hope you to add Qt.
