### ISSUE TITLE
Services: Add Windows Subsystem for Linux (WSL) (Windows)

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/azure-pipelines-image-generation#478]
Services: Add Windows Subsystem for Linux (WSL) (Windows)

**Comment by yodurr** [comment]
Here's a powershell example installing WSL.  The contents of this file may change as we're still evaluating the optimal way to have WSL and a distro installed from CLI. 
https://github.com/Microsoft/windows-dev-box-setup-scripts/blob/master/scripts/WSL.ps1

**Comment by pquentin** [comment]
If this was supported, I believe the trio project would use it!

**Comment by evilebottnawi** [comment]
Will be great have example in templates

**Comment by yodurr** [comment]
Here's the pipeline for WinAppDriver: 
https://marketplace.visualstudio.com/items?itemName=WinAppDriver.winappdriver-pipelines-task

Related blog post: 
https://blogs.windows.com/buildingapps/2019/05/13/announcing-ui-tests-in-ci-cd-for-desktop-app-developers

**Comment by evilebottnawi** [comment]
bump

**Comment by chuckatkins** [comment]
bump.
