### ISSUE TITLE
Please update the Visual Studio 2017 VM image to have 15.9.1 updates at least

### ISSUE THREAD

**Issue by eriawan** [Microsoft/azure-pipelines-image-generation#499]
# Please update the Visual Studio 2017 VM image to have 15.9.1 updates at least

We need to update the installed VS 2017 on the VM image for VS 2017 hosted agents because the latest VS2017 update of the 15.9.1 or later has support for nuget package lock, and we need this support as well when having CI on Azure DevOps instead of downloading new MSBUILD to accommodate this new features.

Building locally is fine, but using the default VS 2017 hosted agents doesn't have the same behaviors and results, also we can't use the newer MSBUILD parameter to enable package lock.

References: 

1. https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#locking-dependencies
2. https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#NuGet

## Tool info
- Tool name: VS 2017 image
- Add or update? Update
- Desired version: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 
  - Open source license type (Apache, MIT, GPL, etc.): 

## Areas and ecosystems

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [x] .NET Core or .NET Framework
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

## Hosted pools

- [ ] macOS
- [ ] Ubuntu
- [x] Windows

**Comment by eriawan** [comment]
Additional info:

Currently, my build log on using the VS 2017 hosted VM shows 15.8.x:

![image](https://user-images.githubusercontent.com/8773147/48939282-48077e80-ef46-11e8-8436-7f65fe614718.png)

**Comment by eriawan** [comment]
@vijayma 

Thanks! Is there any ETA date for VS 2017 15.9.1 VM image release?
I hope the VS2017 VM will be updated before the end of December  2018. 
This is quite crucial, because it's quite dragging my team quite a while since VS 2017 15.9.0 is released.

**Comment by NGame1** [comment]
Please upgrade the VS on Virtual Machines faster.
I need the new Windows 10 UWP SDK for the Windows 10 October update.

**Comment by eriawan** [comment]
@vijayma @azureDaveOps
 
Any updates on this issue? 

Because it's more than two weeks, and it's near end of year, And I'm afraid this issue will be delayed further on this December to be revisited again after new year holiday on January 2019.

Therefore, if I have to wait longer and I have to create my own hosted agents while wait for the updates would not be the best option on this December. 😞 

Please confirm.

I will create other issues to gather "checklist" to validate the update, because previous @NGame1 comment is also valid.

**Comment by Gert-Cominotto** [comment]
Any updates on when this might be fixed?

**Comment by eriawan** [comment]
@vijayma 

Any updates on this issue? please confirm, it's been more than a month since the last reply from you.
FYI, VS 2017 update now reaches 15.9.5.

Pardon, now I'm having the impressions that the VM images of VS 2017 is often having slow updates then, especially when dealing with holidays of December. 
Then all of us, users of Azure Pipelines that leverage VS2017 VM agent will be out of luck.  😞 
If this continue again, I'm afraid it will happen again in next year...

I know that this sound harsh, but VS 2017 is known to have rapid dev cadence, so if the VS 2017 VM image agent isn't updated for more than a month, it makes the current Azure Pipeline that use VS2017 VM image to be almost useless.

There are other ways to overcome this by having custom scripts to install latest MSBUILD, but this is not easy and we couldn't continue to maintain the script, because if MSBUILD itself has updates, then it will be tedious again to maintain ourself.

How long do we have to wait for VS 2017 update?
To speed up the processes, could we can participate on submitting PR to refresh the VS2017 VM image? I couldn't see any guidance or contribution guide for this.

cc @DavidStaheli @lokesh755

**Comment by eriawan** [comment]
@vijayma @DavidStaheli @lokesh755 

cc @vtbassmatt 

any further updates???

why it's been more than one month without any updates at all? IS this repo really active????
do I have to wait until VS 2019 goes RTM????? this is bad, guys...

This prolonged slow VM image updates and prolonged support silences really begin to force me to consider other CI services 😞

**Comment by lokesh755** [comment]
We've generated an image which has 15.9.5. Will be rolling out region by region. ETA is end of this week or early next week. We have hit multiple issues which caused the delay in rollout of images.

**Comment by eriawan** [comment]
@lokesh755 

Thanks! Please let us know if the image has been updated. Any specific date of the finished images rollout?

This is very important, because some developments have to be slowed down and downgraded if this VM VS2017 image is still not updated.

**Comment by gertcominotto** [comment]
@lokesh755 it is possible that this hasn't been completely rolled out yet?
`2019-01-25T15:31:29.3705286Z NuGet Version: 4.9.2.5706
2019-01-25T15:31:29.3705842Z MSBuild P2P timeout [ms]: 120000
2019-01-25T15:31:29.3706057Z MSBuild auto-detection: using msbuild version '15.8.169.51996' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
2019-01-25T15:31:29.3706268Z C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\msbuild.exe "C:\Users\VssAdministrator\AppData\Local\Temp\NuGetScratch\2hoj5w0v.bpr.nugetinputs.targets" /t:GenerateRestoreGraphFile /nologo /nr:false /v:q /p:NuGetRestoreTargets="C:\Users\VssAdministrator\AppData\Local\Temp\NuGetScratch\z5bkop33.il0.nugetrestore.targets" /p:RestoreUseCustomAfterTargets="True" /p:RestoreTaskAssemblyFile="C:\hostedtoolcache\windows\NuGet\4.9.2\x64\nuget.exe" /p:RestoreConfigFile="D:\a\1\Nuget\tempNuGet_77.config"
2019-01-25T15:31:29.3707690Z NuGet.CommandLine.ExitCodeException: Exception of type 'NuGet.CommandLine.ExitCodeException' was thrown.`

**Comment by eriawan** [comment]
@gertcominotto 

I think this February update has the updated MSBUILD 15.9.x.
Please try to queue build again.

@lokesh755 

I have tried today, and the MSBUILD is now using 15.9.20 (the one used by VS 2017 15.9.4, 15.9.5 and 15.9.6)

![image](https://user-images.githubusercontent.com/8773147/52549115-15ae4480-2e04-11e9-9a46-7bd68ed68749.png)

Thanks guys! I will close this.

cc @vijayma @DavidStaheli
