### ISSUE TITLE
Add Ubuntu 18.04 Image

### ISSUE THREAD

**Issue by svanzoest** [microsoft/azure-pipelines-image-generation#506]
[Ubuntu 18.04 LTS](http://releases.ubuntu.com/18.04/) has been out for a while now. 
It would be great to be able to use it for native builds that target newer versions of the linux runtime.
Let me know if I can help.

## Areas and ecosystems

- [ ] Android
- [x] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [x] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [x] Other

## Hosted pools

- [ ] macOS
- [x] Ubuntu
- [ ] Windows

**Comment by dakale** [comment]
@vtbassmatt Is Ubuntu 18 on the roadmap still? 

@svanzoest It would need to work with the existing Packer generation processes. Previously, I tried to experiment with 18, but hit a few big issues, heres one: https://github.com/Azure/WALinuxAgent/issues/1151#issuecomment-442588150

So we would need be able to ensure images generated by Packer from whatever latest Canonical Ubuntu 18 image skus (see https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/linux/ubuntu1604.json#L33 for eg) will work without issue in Azure. 

Feel free to experiment in this area, as it may be useful down the road if we do decide to support this

**Comment by vtbassmatt** [comment]
It's on our radar but keeps getting pre-empted by other priorities. The set of things that needs to happen:
1. an image is generated and vetted
2. the backing pools are stood up (CC @joebourneMS)
3. the new pool is added to new and existing accounts

@svanzoest we'd be happy to accept a PR for item 1, if you have the time and interest.

**Comment by svanzoest** [comment]
Thanks @vtbassmatt and @dakale 
I am familiar with packer, but not how it ties into Azure, but I'll see if I can get things going.
I really appreciate the feedback.

**Comment by sjackman** [comment]
I'd also love to see an image for Ubuntu 18.04 LTS (Bionic Beaver).

**Comment by joebourneMS** [comment]
We would too. We're currently chugging away on a new Windows image containing the preview for VS2019, but after we get that out the door we'll be focused on 18.04!

**Comment by sjackman** [comment]
Glad to hear it!

**Comment by roji** [comment]
Gentle ping, this is quite important for a modern build environment - 19.04 is already around the corner...

**Comment by vosst** [comment]
Pinging for a hosted 18.04 image, too. We would like to enable integration/acceptance testing scenarios, but need a proper VM to bootstrap test harnesses and dependencies using `docker`.

**Comment by joebourneMS** [comment]
Thanks, we're reviewing our schedule to see when we could enable this.

**Comment by expiron** [comment]
@joebourneMS Is there any news about hosted Ubuntu 18.04 image?

**Comment by joebourneMS** [comment]
Hi @expiron, this is still on our radar but still manages to get bumped by urgent/competing priorities. Stay tuned.

**Comment by jaycollett** [comment]
Ugh, just hit this wall as well, was surprised 16.04 was the only option...

**Comment by kmhofmann** [comment]
@joebourneMS This is incredible, in an utterly negative sense. It's easy: Just *make* this the highest priority. This really can't be that difficult or time consuming. It's already one whole year since 18.04 was released!

**Comment by joebourneMS** [comment]
Thanks for the feedback @kmhofmann, we absolutely understand how important this is for our customers and why it's on our [Azure Pipelines roadmap](https://docs.microsoft.com/en-us/azure/devops/release-notes/)

Usage of Hosted Pipelines has grown tremendously this year (even more than we've projected) and the team has been tirelessly spending the resources we have to scale our experience so that customers can always trust its reliability and performance.

We very much are hoping to ship a new pool for Ubuntu 18.04 late summer / early fall of this year. Please stay tuned, and don't hesitate to reach out with questions: 

- My twitter: [JoeB_in_NC](https://twitter.com/JoeB_in_NC)
- My email: [joe.bourne@microsoft.com](mailto:Joe.Bourne@microsoft.com)

**Comment by kmhofmann** [comment]
@joebourneMS Summer/early fall??!! I do maintain that this is something you should have shipped in May or June of 2018, pretty much after release of Ubnut 18.04.
I might be missing something, but this is not rocket science. It's just adding another base image.

**Comment by joebourneMS** [comment]
@kmhofmann I appreciate your passion here. Believe me, we know we need this and will get to it. Also, you're not wrong, adding another base image to this repository is not a herculean task. That said, adding the base image is not the bottleneck.

The TL;DR is that for each base image we add to our support list, we have to scale out global Azure infrastructure in order to offer that pool of machines reliably, in every Azure region, and with the same performance of our current image set. Scaling that global infrastructure is the difficult part takes time.

If you're really interested in going deeper, please shoot me a mail and I'm happy to hop on a call.

**Comment by bryanmacfarlane** [comment]
I would like to also point out that self hosted agents (on an Azure VM you acquire) is also an option.  It's not as convenient but if Ubuntu 18 or another OS is critical for your dev ops, it's an option.

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops

We also support running jobs in a container via yaml:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml

**Comment by sjackman** [comment]
I don't think that I knew about the `container: ubuntu:18.04` YAML. Thank you, Bryan! I learned something.

**Comment by kaylangan** [comment]
Related to #1051 
Please note, 18.04 is **not** yet available. #1051 adds the scripts, but we still need to do additional testing and validation, then set up the actual pools.

**Comment by Fmstrat** [comment]
Wow, how is this still going since Nov 2018? 18.04 is THE standard in deployments, how it's not in the build pipeline is beyond me. Azure is the only service I've worked with that doesn't use 18.04.

**Comment by sondreb** [comment]
The latest .NET Core SDK is also not available on the latest Ubuntu image, so the fix for Ubuntu 19.04 runtime (openssl 1.0 binding issue) is not available when building on Azure DevOps. Please update both the .NET Core SDK and get a container with 18.04 soon.

**Comment by thejoebourneidentity** [comment]
Adding @pasangh who is driving this.

**Comment by phil-harmoniq** [comment]
Is any progress being made on this at all? 20.04 will be releasing soon and we still haven't gotten support for 18.04 hosted agents.

**Comment by sjackman** [comment]
Just to repeat a previous workaround, in the mean time you can use Docker.
```yaml
container: ubuntu:18.04
```

**Comment by pasangh** [comment]
Ubuntu 18 is available across Azure DevOps. Thanks everyone for the patience.

(Feel free to create new issues because this issue is focused on adding ubuntu 1804 image)

**Comment by Allcharles** [comment]
@pasangh Can someone update the documents to reflect that ubuntu 18 is now available. Notably this page: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops&tabs=yaml%2Cbrowser. Assuming i have the correct page.
