### ISSUE TITLE
Verify Android environment variables are set: ANDROID_SDK_ROOT and ANDROID_HOME

### ISSUE THREAD

**Issue by DavidStaheli** [Microsoft/azure-pipelines-image-generation#511]
Request from Alex Cortelyou:

As a minor request, it would be helpful if the next set of images have both the ANDROID_SDK_ROOT and ANDROID_HOME environment variables defined.

Despite documentation to the contrary, my gradle build apparently ignores ANDROID_SDK_ROOT so I had to add “export ANDROID_HOME=$ANDROID_SDK_ROOT” beforehand.

**Comment by madhurig** [comment]
We add ANDROID_HOME on Windows and Linux

Windows: https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/scripts/Installers/Update-AndroidSDK.ps1#L37 

Linux: https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/linux/scripts/installers/android.sh#L18

The Linux one was added in Oct and is currently being deployed. 

Thanks,
Madhuri

**Comment by madhurig** [comment]
ANDROID_HOME is now set on Hosted VS2017, Hosted Ubuntu 1604 and Hosted macOS pools. Let us know if you see any issues with that. 

Thanks,
Madhuri
