### ISSUE TITLE
OSX Hosted Agent should set DOTNET_ROOT environment variable

### ISSUE THREAD

**Issue by AArnott** [microsoft/azure-pipelines-image-generation#531]
Per https://github.com/dotnet/cli/issues/9114, if .NET Core is installed in a non-default location, the `DOTNET_ROOT` environment variable must be set or .NET Core CLI tools will fail to run.

[Installing a local tool and running it](https://github.com/AArnott/Nerdbank.GitVersioning/blob/756b46a459d2fc596ff898265911e310bc9b6d07/azure-pipelines/xplattest-pipeline.yml#L48-L49) passes on Linux-based `microsoft/dotnet` docker images but [fails on Hosted OSX agents from Azure Pipelines](https://dev.azure.com/andrewarnott/OSS/_build/results?buildId=1882&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=82b9ed72-f1bb-511e-fc8d-cb3097d1e55d&l=14).

Since the OSX agent comes with .NET Core SDK pre-installed, can it also please pre-set the `DOTNET_ROOT` environment variable to match, so that the above example works across all hosted agents instead of failing on OSX?

**Comment by AArnott** [comment]
Yes, please keep it active!

**Comment by jnm2** [comment]
Yes, still waiting for a response.

**Comment by AArnott** [comment]
This is still a problem, and I updated the link above with a newer build that proves it.

**Comment by AArnott** [comment]
I don't know what's changed in the last week, but the problem has gotten worse somehow. A commit that [built fine last week](https://dev.azure.com/andrewarnott/OSS/_build/results?buildId=1878&view=results) is [now failing](https://dev.azure.com/andrewarnott/OSS/_build/results?buildId=1897&view=results).

**Comment by maxim-lobanov** [comment]
@AArnott ,
I can see the following line: `DOTNET_ROOT=/Users/vsts/.dotnet` in build log.
Where does it come from? Do you set it by yourself in some script?

Please pay attention, that `$USER` was changed on macOS VM images recently from `vsts` to `runner` so correct line should be `export DOTNET_ROOT=$HOME/.dotnet`

**Comment by AArnott** [comment]
Ah yes, that username change is what would explain how [my DOTNET_ROOT workaround](https://github.com/AArnott/Nerdbank.GitVersioning/blob/934a3d55b5d7a6f5fa44a32af2db61261b4f10ce/azure-pipelines.yml#L168) for this issue quit working recently.

**Comment by maxim-lobanov** [comment]
Yep, that it. Sorry for inconvenient and lack of notification here.
Probably we should consider defining `DOTNET_ROOT` variable or at least create symlink from `/usr/local/share/dotnet` to`$HOME/.dotnet`

**Comment by AlenaSviridenko** [comment]
Hi @AArnott !

We have rolled out new macOS image with created environment variable `$DOTNET_ROOT` set to `$HOME/.dotnet`. Please, check if this fix works for you.

Thanks!

**Comment by AArnott** [comment]
It works! Thanks.
