### ISSUE TITLE
Add deduplication support to Windows Container 1803

### ISSUE THREAD

**Issue by jerickmsft** [Microsoft/azure-pipelines-image-generation#532]
## Tool info
- Tool name: Windows Server Data Deduplication
- Add or update? Add
- Desired version: [builtiin to OS]
- If this is an add request:
  - Brief description of tool: "Data Deduplication, often called Dedup for short, is a feature of Windows Server 2016 that can help reduce the impact of redundant data on storage costs. When enabled, Data Deduplication optimizes free space on a volume by examining the data on the volume by looking for duplicated portions on the volume. Duplicated portions of the volume's dataset are stored once and are (optionally) compressed for additional savings. Data Deduplication optimizes redundancies without compromising data fidelity or integrity."
  - URL for tool's homepage: https://docs.microsoft.com/en-us/windows-server/storage/data-deduplication/overview

## Areas and ecosystems
- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [x] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

## Hosted pools
- [ ] macOS
- [ ] Ubuntu
- [x] Windows (1803 only)

It can be install by running:
```
Install-WindowsFeature -Name FS-Data-Deduplication
```

Doing so only makes the filter driver available, it does *not* schedule any jobs or change the contents or behavior of any of the disks.  It does let pipeline authors quickly set that up with a:
```
Enable-DedupVolume -Volume D: -UsageType Backup
```

**Comment by vtbassmatt** [comment]
Looks like this was already done?
