### ISSUE TITLE
C/C++: Add Boost 1.69.0 (or latest) (macOS)

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/azure-pipelines-image-generation#542]
C/C++: Add Boost 1.67.0 (or latest) (macOS)

**Comment by mloskot** [comment]
Ubuntu 16.04 and VS2017 images have Boost 1.69 pre-installed, so I think this task should aim for 1.69 as well. FYI, Boost 1.70 is already at RC2, soon to be released.

**Comment by kaylangan** [comment]
Not stale

**Comment by mloskot** [comment]
Bump

**Comment by mloskot** [comment]
Bump. Let's see if this gets addressed when Boost 1.100 is released ;)
