### ISSUE TITLE
Deployment: Add AWS CLI 1.16.54 (or latest) (macOS)

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/azure-pipelines-image-generation#561]
Deployment: Add AWS CLI 1.16.54 (or latest) (macOS)

**Comment by kaylangan** [comment]
Re-opening for: https://github.com/microsoft/azure-pipelines-image-generation/issues/442#issuecomment-487644070

**Comment by kaylangan** [comment]
We added it to Linux in https://github.com/microsoft/azure-pipelines-image-generation/pull/1167. We should keep this open.
