### ISSUE TITLE
Languages: Add Rust 1.30.1 (or latest) (macOS)

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/azure-pipelines-image-generation#577]
Languages: Add Rust 1.30.1 (or latest) (macOS)

**Comment by calebcartwright** [comment]
Are there any plans to re-open this now that Rust has been added to the Ubuntu and Windows images?

**Comment by calebcartwright** [comment]
un-stale 😄

**Comment by kaylangan** [comment]
We've moved development to the `actions/virtual-environments` repo. You can follow the issue there: https://github.com/actions/virtual-environments/issues/6
