### ISSUE TITLE
Ruby: Add Ruby 2.6 (coming December 2018) (macOS)

### ISSUE THREAD

**Issue by DavidStaheli** [Microsoft/azure-pipelines-image-generation#592]
Ruby: Add Ruby 2.6 (coming December 2018) (macOS)

**Comment by xiazek** [comment]
I would love to see the same for i:linux. I'm guessing no ruby team is going to use the platform if ruby 2.3 (released in 2015) is the newest supported version 😕

**Comment by ncouraud** [comment]
Ruby 2.6.1 is default currently.
