### ISSUE TITLE
Version control: Update to Mercurial 4.9 (or latest) (macOS)

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/azure-pipelines-image-generation#604]
Version control: Update to Mercurial 4.8 (or latest) (macOS)

**Comment by willsmythe** [comment]
@DavidStaheli - it would great to get Mercurial added to the hosted macOS image (like it is in the Ubuntu image and the upcoming Windows image update). For projects that build across Windows, Linux, and macOS (like [facebook/jest](https://github.com/facebook/jest)), having it pre-installed would avoid the need for a special, macOS-specific step, which isn't necessarily hard to add, but increases complexity in the YAML and creates another potential point of failure.

**Comment by ncouraud** [comment]
@nrajpurkar  we should take this up soon, should be a quick add.
