### ISSUE TITLE
Hosted VS2017 and Windows SDK version failures.

### ISSUE THREAD

**Issue by simonjchapman** [Microsoft/azure-pipelines-image-generation#606]
Our builds are auto-generated with the Hosted VS2017 agent, but as of yesterday, there are continual failures on the availability of Windows SDK 17134 on C++ compilation. Even if I use previous successful changesets, the build fails. The build script itself is unchanged, so the seems to be a breaking change with the Hosted VS2017 agent as it is missing the SDK.

Here is the error:

`2018-12-11T21:11:03.6491369Z ##[error]C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.targets(46,5): Error MSB8036: The Windows SDK version 10.0.17134.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".`

If I downgrade to a previous SDK (Windows SDK 10.0.14393) I then get the following error that the dependency is missing:

`2018-12-12T15:28:13.6307099Z ##[error]LINK(0,0): Error LNK1104: cannot open file 'msvcprt.lib'`

What has changed on the Hosted VS2017 agent, and is this going to be fixed?

## Areas and ecosystems

- [ ] Android
- [X] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [X] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

## Hosted pools

- [ ] macOS
- [ ] Ubuntu
- [X] Windows

**Comment by simonjchapman** [comment]
It is now working, thanks. Glad you have rolled back the image as there were other things that were also failing, even after changing to 17763, such as some C++ runtimes. But it is all good now.

**Comment by rido-min** [comment]
@lokesh755  what was the reason for the rollback? What's the ETA for having the RS5 SDK available?

**Comment by lokesh755** [comment]
Currently there's deployment freeze due to holidays. Our next update will be around first week of Jan 2019.

**Comment by wickste** [comment]
Any update on this?

**Comment by lokesh755** [comment]
We're still working generating and testing latest image.

**Comment by rido-min** [comment]
Any updates? I'm looking for a build agent with the latest Windows SDK (1809). Will the new VS2019 agent include that?

**Comment by joebourneMS** [comment]
The latest VS2017 updates should have what you need, let us know if you're seeing otherwise. https://github.com/Microsoft/azure-pipelines-image-generation/releases/tag/1901

**Comment by rido-min** [comment]
I sill see this error when targeting 17763 (RS5 SDK) from UWP.

```
Error CS0234: The type or namespace name 'ApplicationModel' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
```

How can I know if the agent has been updated to use the latest image?
