### ISSUE TITLE
Future plans on new Az module?

### ISSUE THREAD

**Issue by riezebosch** [Microsoft/azure-pipelines-image-generation#609]
https://azure.microsoft.com/en-us/blog/azure-powershell-cross-platform-az-module-replacing-azurerm/

Questions we have are:
* Will all Azure & AzureRM cmdlets be removed?
* How will the [Azure Pipelines Tasks](https://github.com/Microsoft/azure-pipelines-tasks) cope with that? Because there is some magic in it for resolving specific `AzureRM` versions.

**Comment by RoopeshNair** [comment]
If your scripts are still working with AzureRM powershell modules, it will continue to work with the existing version of the Azure PowerShell task. We will be shipping a new major version of Azure PowerShell task with the new `Az` modules support soon.
