### ISSUE TITLE
Vs2017-Server2016-Readme.md doesn't specify bitness of Node

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/azure-pipelines-image-generation#611]
# Help us route

This is the template for requesting new or updated tools on the hosted images.
If you intended to file a bug, please switch to the Bugs template: https://github.com/Microsoft/azure-pipelines-image-generation/issues/new?template=bugs.md

# If this is a request for a new tool or tool version...

## Tool info
- Tool name: Node.js
- Add or update? Clarify
- Desired version: N/A

Please specify whether Node.js is an x86 or x64 version of Node.js that is installed as listed at https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md#nodejs .

## Areas and ecosystems

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [x] Other

## Hosted pools

- [ ] macOS
- [ ] Ubuntu
- [x] Windows

**Comment by DavidStaheli** [comment]
Fixed by PR #712.
