### ISSUE TITLE
Cached images in VSTS Windows Container(1803) image

### ISSUE THREAD

**Issue by IanMercer** [Microsoft/azure-pipelines-image-generation#613]
It would be nice if the "Windows Container (1803) image" included cached images for 1709 versions of the windowscore (and related) docker images. 

I can build simple overlay images `FROM microsoft/windowsservercore:1709` using the agent Windows Container (1803) image BUT they take 30 minutes to run and then cause the pipeline to timeout.

Any reason the 1709 images can't be included in the cache?

It would also be nice if the readme used friendly names like "microsoft/windowsservercore:1709" with abbreviated SHA hashes instead of full SHA hashes and no human readable description.

**Comment by eriawan** [comment]
> It would also be nice if the readme used friendly names like "microsoft/windowsservercore:1709" with abbreviated SHA hashes instead of full SHA hashes and no human readable description.

I agree! 👍
