### ISSUE TITLE
Extremely slow VS 2017 image generation due to Windows Defender scan

### ISSUE THREAD

**Issue by NateB2** [Microsoft/azure-pipelines-image-generation#616]
## Description
When generating a VS2017 image, even using Premium_LRS storage and a fast VM, it can take >8 hours to run the Windows Defender scan, causing the image generation to take 13 hours or more. During the scan, the IOPs are not maxed out and the CPU hovers around 20%.

## Expected Behavior
Windows Defender should utilize up to 100% of the CPU and/or max out the available IOPs in order to finish the scan in a reasonable time.

## Actual Behavior
Defender throttles the CPU, causing the scan to take an inordinate amount of time to complete.

I changed the Run-Antivirus.ps1 script, adding in a command to change the appropriate setting - in my testing, with Premium_LRS storage, the images take a little over 50% less time to build - a significant performance gain.  I submitted a PR here with the change: https://github.com/Microsoft/azure-pipelines-image-generation/pull/615

**Comment by ryanspletzer** [comment]
This is great.

**Comment by lokesh755** [comment]
Merged PR.
