### ISSUE TITLE
Powershell Core missing from Windows Container Image

### ISSUE THREAD

**Issue by MarkDordoy** [Microsoft/azure-pipelines-image-generation#622]
## Tool info
- Tool name: pwsh.exe
- Add or update? Add
- Desired version: latest (6.1) (currently doesn't exist on Windows Container(1803) image)
- If this is an add request:
  - Brief description of tool: Powershell core 6.1 
  - URL for tool's homepage: https://blogs.msdn.microsoft.com/powershell/2018/09/13/announcing-powershell-core-6-1/

## Areas and ecosystems

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [x ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

## Hosted pools

- [ ] macOS
- [ ] Ubuntu
- [x ] Windows

(This is already in place on macOS and Ubuntu)

Please can we have powershell core installed by default on the windows container image. This allows us to write generic powershell that can then run on any hosted agent

**Comment by vtbassmatt** [comment]
@MarkDordoy what specifically are you trying to do? We expect the Windows container image to be used only for running containers, in which case you'd be the one bringing pwsh to your container.

**Comment by MarkDordoy** [comment]
I was planning to use it to run a custom release task. I have used it previously for the same kind of stuff, but with powershell 5.1.

I've now updated my code to use powershell core but noticed its missing. 

The script is simply grabbing a function apps host key and storing it in a key vault, post release of a function app. 

I use windows container over hosted vs 2017 as its much faster

**Comment by vtbassmatt** [comment]
Gotcha, thanks for the details. Part of the reason it's faster is how little software is installed there 😁 . It's really intended for use with a container. There's nothing particularly "wrong" about using it for other purposes, but I'm not inclined to add packages to support those use cases. (As a workaround, maybe try one of the containers on Docker Hub that have pwsh installed, and run as a [container job](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=vsts&tabs=yaml).)
