### ISSUE TITLE
Canary builds needed (to be assigned)

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/azure-pipelines-image-generation#623]
## Guidelines for canary builds

- If it’s a framework or programming language, use a simple yet realistic sample project.  GitHub or the “getting started” documentation are good places to look.
- If it’s a command-line tool, just run a script that calls the tool.
- Put the build in the appropriate folder so it gets run during the test pass.
- Set up a schedule for the build to run every day.

## Need canaries (Hosted VS2017 and VS2019)
Mercurial
MinGW
Go
Subversion
CF CLI
GitVersion

## Need canaries (Hosted Ubuntu 16.04):
Erlang + rebar3
Firefox
Go
Google Chrome
Haskell
Helm
Heroku CLI
ImageMagick
kubectl
Mercurial
Mono
MySQL
Parcel
PhantomJS
PHP
Pollinate
PyPy 2 and 3
rsync
SpellCheck
Sphinx
Subversion
Webpack
Yarn
HipHop VM
Scala

**Comment by kaylangan** [comment]
Not stale. FYI @alepauly
