### ISSUE TITLE
When are the hosted agents updated?

### ISSUE THREAD

**Issue by chris5287** [Microsoft/azure-pipelines-image-generation#627]
Just wondered when the hosted agents are updated? Is it announced anywhere I can follow? The GitHub release was last updated in august but suspect this isn’t correct?

**Comment by DavidStaheli** [comment]
Hi @chris5287.  Lack of communication around this is a big weakness.  We're going to communicate this much better going forward.  Images should be deployed every 3 weeks (our sprint length).  We're working toward getting them out weekly.  I'll update this issue with the method of communication ASAP.  I'm thinking of using a webpage with an RSS feed or some other way for people to subscribe, but suggestions are very welcome.

**Comment by DavidStaheli** [comment]
Releases are now being tracked in GitHub releases [here](https://github.com/Microsoft/azure-pipelines-image-generation/releases).  This is just one piece of upcoming improvements.
