### ISSUE TITLE
Improve docker pull performance on Windows

### ISSUE THREAD

**Issue by mcooley** [Microsoft/azure-pipelines-image-generation#635]
Our team is interested in using Windows Containers to build C++ projects. Container images with the Visual Studio build tools and compilers are several gigabytes on top of the base image. These huge containers perform poorly in the win1803 hosted pool.

For one container image we're testing, the "Initialize container" step takes 45 minutes. It looks like only about two minutes of that time is spent downloading the images over the network, and the rest is spent extracting the image. I'm wondering if I/O performance can be improved to reduce the "docker pull" time.

Currently, it looks like docker is configured to store all its data on the C:\ volume. Is it possible to move docker's data-root to the ephemeral SSD on D:\? That would break the current method of caching images on the machine, although maybe the perf tradeoff is worth it, or an alternative solution could be found (running a docker registry on localhost?)

Also, docker writes a large temp file while it's pulling container images, and TEMP currently also is on C:\. Is it feasible to move TEMP to D:\?

**Comment by Croydon** [comment]
Hi @mcooley! We are currently struggling to get Windows containers with VS build tools working. Are the containers you are using publicly available?

**Comment by mcooley** [comment]
@Croydon no, I don't think our Visual Studio license allows us to publicly distribute the build tools. However, we were successful following the steps in the [official documentation](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2017). We also had to limit the install to the particular [component IDs](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2017) we needed.

**Comment by DavidStaheli** [comment]
@joebourneMS is it correct to assign this to you since it's related to disk IO?

**Comment by mcooley** [comment]
@joebourneMS Is improving performance for Windows containers on the roadmap? This issue is painful for us, and we're willing to help investigate further or prototype a fix given some direction. Also can discuss internally if you'd prefer (alias: macool).

**Comment by joebourneMS** [comment]
Hi Matt, we absolutely are prioritizing containers and build speed performance. We want pipelines to be the best for container build scenarios. Let's discuss this internally, please set up time with myself and Ross Brodbeck
