### ISSUE TITLE
Turn off auto-update check by Homebrew in hosted macOS image

### ISSUE THREAD

**Issue by willsmythe** [microsoft/azure-pipelines-image-generation#637]
Homebrew, which is pre-installed on the hosted macOS image, fails to install a package if there is a newer version of Homebrew available. When this happens, "brew install" exits with a non-zero exit code (which usually causes the build to fail) with a message telling the user to "re-run the brew install command again". This behavior makes sense on a developer machine, but not on a CI system since users can't update Homebrew without adding extra steps (which would be silly to ask them to do).

Here's how the failure gets reported:

```
2019-01-11T13:38:31.4375630Z Please don't worry, you likely hit a bug auto-updating from an old version.
2019-01-11T13:38:31.4376520Z Rerun your command, everything is up-to-date and fine now.
2019-01-11T13:38:31.4437900Z ##[error]Bash exited with code '1'.
2019-01-11T13:38:31.4498240Z ##[section]Finishing: CmdLine
```

This is especially problematic because a build that works one minute can fail the next because Homebrew pushed an update.

To avoid making everyone turn off this auto-update behavior (for this tool that we pre-install), we should consider setting the `HOMEBREW_NO_AUTO_UPDATE` environment variable to `1` on the image by default.

**Comment by ncouraud** [comment]
hey @willsmythe  - so I believe the latest images should've pushed past this issue in the immediate term, as we're running >2.0, but I think that the general enhancement of setting `HOMEBREW_NO_AUTO_UPDATE` is still possibly a good idea. 

@nrajpurkar - have we triaged this yet?
