### ISSUE TITLE
Azul Zulu OpenJDK update around 16 April 2019

### ISSUE THREAD

**Issue by DavidStaheli** [Microsoft/azure-pipelines-image-generation#639]
Azul Zulu OpenJDK update around 16 April 2019

**Comment by andydkelly-ig** [comment]
@DavidStaheli what is the plan here around JAVA_HOME? Right now i have >75 different tasks across my pipelines where i have set JAVA_HOME for Java 11 and amended PATH. With these now frequent it seems updates is there an alternative to this as it's a tedious task to keep updating.

**Comment by DavidStaheli** [comment]
Hi @andydkelly-ig .  Sorry for the delay while I was out for a while.  I can see how this is a big pain since JAVA_HOME is set to Java 8 on these images by default.  Do your pipelines use the [Maven](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=azure-devops) or [Gradle](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/gradle?view=azure-devops) tasks that are built into Azure Pipelines?  They should never be required... I'm just curious as we think through ways to overcome the pain you're hitting today.

**Comment by DavidStaheli** [comment]
@andydkelly-ig , this might help until we have something better.  These environment variables point to the latest installed version's location.  So, you could set JAVA_HOME to the value of these and get the latest minor version:

`JAVA_HOME_8_X64`
`JAVA_HOME_11_X64`

On Linux, your pipelines could use: ` echo ##vso[task.setvariable variable=JAVA_HOME]$JAVA_HOME_11_X64`
On Windows, your pipelines could use: `echo ##vso[task.setvariable variable=JAVA_HOME]%JAVA_HOME_11_X64%`
(Caveat: I haven't actually tried the above.)

**Comment by andydkelly-ig** [comment]
@DavidStaheli Thanks for this. This would indeed solve the issue - although at present i am having trouble setting the Environment Variable as the value of another Variable. Setting `PATH~ as `%PATH%;C:\temp` works fine, but for some reason when setting `JAVA_HOME` as `%JAVA_HOME_11_X64%` i end up with a variable of JAVA_HOME with the literal value %JAVA_HOME_11_X64%

**Comment by andydkelly-ig** [comment]
@DavidStaheli ignore last part of the above - i was being stupid :) This fix works for us so will keep testing for a day or so then roll out across the pipelines. Thanks for this steer.

**Comment by DavidStaheli** [comment]
@andydkelly-ig I was wondering the same thing!  😊  Sorry for the original frustration though.  We're very close to having an RSS feed available on this repo to notify people of upcoming changes beyond the release notes under Releases.

**Comment by DavidStaheli** [comment]
Ubuntu images get this update automatically.  The update was added to Windows images with #866.
