### ISSUE TITLE
Image for Azure DevOps extension on Azure CLI

### ISSUE THREAD

**Issue by geverghe** [Microsoft/azure-pipelines-image-generation#645]
## Tool info
- Tool name: Azure DevOps extension for Azure CLI
- Add or update? Add
- Desired version: Azure CLI 2.0.55 (latest) with Azure DevOps extension preview included (az extension add --name azure-devops)
- If this is an add request:
  - Brief description of tool: Azure DevOps extension on Azure CLI provides allows users to experience Azure DevOps from the command line 
  - URL for tool's homepage: https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/?view=azure-cli-latest
  - Open source license type (Apache, MIT, GPL, etc.): MIT
## Areas and ecosystems

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [X] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

## Hosted pools

- [X] macOS
- [X] Ubuntu
- [X] Windows

**Comment by willsmythe** [comment]
Having a smooth "login" experience is important. Can we plan to either document or provide an out-of-the-box solution that enables a smooth experience (that is safe/secure)? For example, if the OAuth access token (which is optionally made available to builds) is appropriate to use here, can it be consumed by the extension and does it have the necessary scopes/permissions to perform all commands?

**Comment by DavidStaheli** [comment]
@RoopeshNair I assigned this to you since it's regarding the Azure CLI, but please let me know otherwise.  When ready to move forward with this, we can create a copy of this issue for macOS and assign it to nrajpurkar who is the PM over the macOS image.

**Comment by sanderaernouts** [comment]
We were running into the same thing today. We would love to be able to use the Azure DevOps extension for Azure CLI extension in the VS2017. We are looking into workarounds right now.  Is there any kind of ETA on this? If it will be available soon we might not have to use workarounds after all :)

**Comment by geverghe** [comment]
@sanderaernouts - in case you are interested in a work around, do have a look at https://github.com/Microsoft/azure-devops-cli-extension/blob/master/doc/samples.md#use-the-azure-devops-extension-in-a-release-pipeline and https://github.com/Microsoft/azure-devops-cli-extension/blob/master/doc/samples.md#use-the-azure-devops-extension-with-yaml

**Comment by kmkumaran** [comment]
@geverghe - Can you raise a PR for this?
+ @sachinma

**Comment by DavidStaheli** [comment]
This was addressed with PR #725.
