### ISSUE TITLE
Update Xamarin.Android Version

### ISSUE THREAD

**Issue by jellis-fox** [Microsoft/azure-pipelines-image-generation#647]
# Help us route

This is the template for requesting new or updated tools on the hosted images.
If you intended to file a bug, please switch to the Bugs template: https://github.com/Microsoft/azure-pipelines-image-generation/issues/new?template=bugs.md

# If this is a request for a new tool or tool version...

## Tool info
- Tool name: Xamarin.Android (current version 9.1.0.38)
- Add or update? update
- Desired version: 9.1.4.2

The reason for this request is the security advisory posted here: https://docs.microsoft.com/en-us/xamarin/android/release-notes/9/9.1#december-11-2018---xamarinandroid-9142

## Areas and ecosystems

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [x] Xamarin
- [ ] Other

## Hosted pools

- [x] macOS
- [ ] Ubuntu
- [ ] Windows

**Comment by wis-jellis** [comment]
Also noticed that Xamarin.Android 9.1.0-38 (latest installed on hosted agent) uses Mono 5.14, which is not on the agent.  Based on: https://docs.microsoft.com/en-us/xamarin/android/release-notes/9/9.1#november-13-2018---xamarinandroid-91038

So updating to either Mono 5.16 or Xamarin.Android 9.1.0.38 does not seem to work?  It appears we are currently limited to Mono 5.12 and Xamarin.Android 9.0.0-20, unless I'm missing something.

Xamarin.Android 9.1.4.2 also uses Mono 5.14, so perhaps 5.14 is required to add as well with this change?

**Comment by wis-jellis** [comment]
Some more background - the real root of the current issue trying to use Mono 5.16 appears to be possibly some misconfiguration with the Xamarin.Android build?

The error we get is:
```
error MSB4226: The imported project "/Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/xbuild/Xamarin/Android/Xamarin.Android.CSharp.targets" was not found. Also, tried to find "Xamarin/Android/Xamarin.Android.CSharp.targets" in the fallback search path(s) for $(MSBuildExtensionsPath) - "/Library/Frameworks/Mono.framework/External/xbuild/" . These search paths are defined in "/Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/MSBuild.dll.config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.
```

This stems from our project file including:  
```
<Import Project="$(MSBuildExtensionsPath)\Xamarin\Android\Xamarin.Android.CSharp.targets" />
```

This has worked previously ok.  I've also noticed that the updated Mono.framework uses a newer msbuild "Microsoft (R) Build Engine version 16.0.40-preview+ge6c3a1f9e4 for Mono", which does not seem to match the previous 15.x (non preview) version.

**Comment by nrajpurkar** [comment]
Xamarin.Android is now updated to 9.2.0.5
