### ISSUE TITLE
The hosted agents now ignore all demands from tasks

### ISSUE THREAD

**Issue by rajbos** [Microsoft/azure-pipelines-image-generation#651]
Refering to #315 since I cannot reopen the issue.

@davidstaheli: can you link to something explaining the reasoning behind this? By itself this seems really strange to me. Curious to see if there is a good reason to do so.

**Comment by DavidStaheli** [comment]
Thanks Bryan!

**Comment by rajbos** [comment]
Ok, so it's only the **hosted agents** that now ignore the demands
