### ISSUE TITLE
Host macOS - Mono Framework SDK 5.16.0.221

### ISSUE THREAD

**Issue by asfilo** [Microsoft/azure-pipelines-image-generation#654]
# Help us route

This is the template for requesting new or updated tools on the hosted images.
If you intended to file a bug, please switch to the Bugs template: https://github.com/Microsoft/azure-pipelines-image-generation/issues/new?template=bugs.md

# If this is a request for a new tool or tool version...

## Tool info
- Tool name: Mono Framework SDK
- Add or update? Update
- Desired version: 5.16.0.221
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 
  - Open source license type (Apache, MIT, GPL, etc.): 

## Areas and ecosystems

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [X ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [X ] Xamarin
- [ ] Other

## Hosted pools

- [X ] macOS
- [ ] Ubuntu
- [ ] Windows

**Comment by knocte** [comment]
Mono version in the stable channel on macOS now is `5.18.1.3 (2018-08/fdb26b0a445 Wed Mar 20 10:02:02 EDT 2019)`, while the VMs in AzureDevOps pipelines still have `5.12.0.301 (2018-02/4fe3280bba1 Fri Jul 20 08:25:42 EDT 2018)`. When is this planned to be fixed??

**Comment by nrajpurkar** [comment]
@knocte this will get updated in our next deployment.

**Comment by nrajpurkar** [comment]
Latest Mono version on the agents is now 5.18.1.3
