### ISSUE TITLE
Please support windows server 2019/1809+

### ISSUE THREAD

**Issue by AceHack** [Microsoft/azure-pipelines-image-generation#656]
This includes for host and containers.
Thanks.

https://github.com/Microsoft/vsts-agent-docker/issues/157

**Comment by joebourneMS** [comment]
Hello,

We're working on a Win Server 2019 image right now actually for at least the host scenario. We are going to be including the VS 2019 preview as part of this image and then upgrading that preview to the final release when the VS ships it. I expect the 2019 image to roll out sometime over the next 3 weeks.

**Comment by ntragas** [comment]
Does that mean that with the new release the Azure SDK tools v3 will be available? I wanted to update to Os Family 6 but Visual Studio 2017 has the v 2.9 of Azure SDK preinstalled which are not compatible with Windows 2019 Family.

**Comment by joebourneMS** [comment]
We've shipped a VS 2019 image. We have 1809 on our backlog. If you'd like to keep an issue open, please make one specifically about 1809 for Windows Containers
