### ISSUE TITLE
~/bin is not in PATH in linux & windows  Mac images.

### ISSUE THREAD

**Issue by rasjani** [microsoft/azure-pipelines-image-generation#661]
## Description

Having some tools that are installed at build time, they typically can be and by default are installed or linked into ~/bin/ 

On Mac, this directory is in the path by default. On Linux & Windows its not. 

## Expected Behavior

~/bin/ should be in PATH on all os's 

## Actual Behavior

~/bin/ is not in PATH

**Comment by joebourneMS** [comment]
@DavidStaheli , I'm renaming this to focus specifically on Linux images.
