### ISSUE TITLE
Add Terraform to Windows 2016 and 2019 images

### ISSUE THREAD

**Issue by markgossa** [microsoft/azure-pipelines-image-generation#663]
**Tool infomation**
- Tool name: Terraform
- Add or update? Add
- Desired version: Latest version
- If this is an add request:
  - Brief description of tool: Terraform is used for provisioning Azure infrastructure
  - URL for tool's homepage: https://www.terraform.io/

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [x] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
Add the appropriate label for the image or images that should be updated (e.g., mac, ubuntu, window).

VS2017

**Workaround**
Create a script task in the release pipeline to run __choco install terraform__ to install terraform on the fly before running the terraform commands.

**Comment by andydkelly-ig** [comment]
Plus 1 from me - will save a couple of minutes on my infrastructure pipelines to not have to install Terraform via Chocolatey

**Comment by kaylangan** [comment]
Related to #679

**Comment by RoopeshNair** [comment]
There is a first class Terraform tools installer step that is available in the [extension](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks).
