### ISSUE TITLE
Add well-known SSH host keys to known_hosts

### ISSUE THREAD

**Issue by congyiwu** [microsoft/azure-pipelines-image-generation#667]
**Describe the bug**
Unless a pipeline explicitly modifies known_hosts or disables host key checking, accessing repos via SSH will fail.  One customer reported that it hangs indefinitely while prompting for verification.

https://man.openbsd.org/ssh.1 mentions that both ~/.ssh/known_hosts and /etc/ssh/ssh_known_hosts are read.  For Mac and Linux images, it looks like we could edit known_hosts at image generation time.

On Windows, The Azure Pipelines Agent provides a copy of MinGit, which provides a copy of SSH.  I ran procmon and it checks:
* C:\Users\congyiw\.ssh\known_hosts
* C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\etc\ssh\ssh_known_hosts (which is under the MinGit folder)

So on Windows, I'm not sure if we can fix this in the image itself.

**Expected behavior**
Accessing repos via SSH on Azure Repos from Azure Pipelines should succeed :).  I would expect the same for other Git providers that we integrate tightly with, like GitHub and BitBucket.  That is, unless users generally expect 100% control over their known_hosts file.

**Actual behavior**
1. Add a shell script to your pipeline that does `git ls-remote <ssh remote url>`.
2. Queue the pipeline.

**Image impacted**
All

**Comment by chrisrpatterson** [comment]
Given we don't really have support for SSH as part of our Source integration I am not sure we should do anything here. If we explicitly add support for SSH or recommend SSH for certain scenarios like submodules we would need to take this into account.  

A user can easily run ssh-keyscan to update their known-hosts file.

**Comment by congyiwu** [comment]
> Given we don't really have support for SSH as part of our Source integration...

Users are already cloning with SSH from pipelines anyway, for submodules and also from custom steps for things like CocoaPods and Terraform, regardless of whether we explicitly recommend it.  To be fair, the percentage of users doing this could be trivial [1], so I'm fine with deferring this issue until there's obvious demand.

> A user can easily run ssh-keyscan to update their known-hosts file.

However, without explicitly verifying the contents of known_files afterwards, there's no guarantee the contents are correct.  For hosted agents scoped to individual builds [2], ssh-keyscan will run from scratch for each build.  If there is a MITM attack, the agents will blindly accept the attacker's host key.

Adding a step in your pipeline to verify the host keys in known_files wouldn't make sense - you might as well bypass ssh-keyscan and write them directly to known_files.

[1] In Kusto I see a 1:10 ratio between VSIDs that fetch w/ SSH and HTTPS overall, but I don't have a way to scope this to hosted builds.

[2] OTOH, for long-lived agents, blindly trusting ssh-keyscan will almost always work in practice.  As long as the initial ssh-keyscan results are correct, future MITM attacks will still be detected.
