### ISSUE TITLE
Cannot `apt-get install libclang-6.0-dev` due to unsatisfiable dependency

### ISSUE THREAD

**Issue by thedataking** [Microsoft/azure-pipelines-image-generation#672]
The Ubuntu 16.04 image installs clang 6 from the debian packages provided by the LLVm project (see [clang.sh](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/linux/scripts/installers/clang.sh)). My project needs the `libclang-6.0-dev` package and apt will try to install the Ubuntu package and thus runs into the following dependency problem:

    # apt-get install libclang-6.0-dev

which fails with the following error:

```
  libclang-6.0-dev : Depends: libclang1-6.0 (= 1:6.0-1ubuntu2~16.04.1) but 1:6.0.1~svn334776-1~exp1~20181018153226.114 is to be installed
                     Depends: libclang-common-6.0-dev (= 1:6.0-1ubuntu2~16.04.1) but 1:6.0.1~svn334776-1~exp1~20181018153226.114 is to be installed
 E: Unable to correct problems, you have held broken packages.
```

**Comment by austin-jensen** [comment]
I'm pretty sure this isn't an issue with our ecosystem really. It's just that there is a dependency discrepancy between the main version of clang-6.0 we have installed and the dev version. I ran through this a few times and it seems like a solution for you is to run the commands below before your install command. They have mismatched dependencies, so the easiest solution seems to be to uninstall the already installed version and its dependencies and then yours should install correctly

sudo apt-get remove -y clang-6.0  libclang-common-6.0-dev libclang1-6.0 libllvm6.0
sudo apt-get autoremove

**Comment by gkelly** [comment]
I think it's an ecosystem issue in that there are now packages in the default apt respositories that have unsatisfiable dependencies.  If you built clang-format-6.0 at your development version tag, or published a package that had an acceptable dependency on your internally-built version, then this wouldn't be an issue.

Moving from the ubuntu 16.04 to 18.04 image surfaced this issue for us.  Why does only 18.04 have this custom LLVM build on it?  Does anything actually have a dependency on it?
