### ISSUE TITLE
Java 10.0.2 not shipping with Hosted Agent

### ISSUE THREAD

**Issue by andydkelly-ig** [Microsoft/azure-pipelines-image-generation#687]
The Java 10.0.2 package is not currently shipping with the Windows 2017 Hosted Agent.

This happened intermittently last week but has happened solid all day today. Error being thrown is cannot recognise java.

Running a DIR on c:\program files\java shows only jdk1.8.0_192 and we are using jdk-10.0.2.

This is an urgent issue for us as we have a lot of releases that are all currently failing.

![commands](https://user-images.githubusercontent.com/42772281/52296908-6a227180-2977-11e9-93c1-592cfe1c75e9.jpg)
![no java](https://user-images.githubusercontent.com/42772281/52296910-6abb0800-2977-11e9-9fc4-7baabd786fc3.jpg)

**Comment by DavidStaheli** [comment]
@andydkelly-ig, we're so sorry for this disruption.  We've got to find a clearer way to communicate these things, or a different process for removing deprecated tools.  Oracle/others dropped support for Java 10.  They're only going with Java 8 and 11 now.  They [state](https://www.oracle.com/technetwork/java/javase/archive-139210.html):

> WARNING: These older versions of the JRE and JDK are provided to help developers debug issues in older systems. They are not updated with the latest security patches and are not recommended for use in production.

Is your project able to move to Java 11?  So sorry this disrupted you...

**Comment by andydkelly-ig** [comment]
> @andydkelly-ig, we're so sorry for this disruption. We've got to find a clearer way to communicate these things, or a different process for removing deprecated tools. Oracle/others dropped support for Java 10. They're only going with Java 8 and 11 now. They [state](https://www.oracle.com/technetwork/java/javase/archive-139210.html):
> 
> > WARNING: These older versions of the JRE and JDK are provided to help developers debug issues in older systems. They are not updated with the latest security patches and are not recommended for use in production.
> 
> Is your project able to move to Java 11? So sorry this disrupted you...

Thanks David - we have a worked around this be using the new Zulu for Azure JDK that you are shipping as luckily for this we on;y actually needed the Java runtime for running Liquibase, not compiling our own code. 

I have no issue with this being removed, but as you say, the communication needs to change as i looked on every link i know of for this stuff and could't find a single mention.

Thanks for responding

**Comment by DavidStaheli** [comment]
No doubt about it, @andydkelly-ig.  Thanks for your flexibility.  It's top priority for us to improve the communication.  Until we have something better, a 2nd-best option is "watching" this repo's releases to get emails on upcoming releases and their changes:

![image](https://user-images.githubusercontent.com/1767415/52642208-8ad35580-2ea8-11e9-8aa3-628ec5cd7f6c.png)

**Comment by andydkelly-ig** [comment]
@DavidStaheli what is going on with Java on these agents??? Having fixed all my Releases when you dropped Oracle Java 10 they are now all failing again as the hosted agents have been upgraded from zulu-11-azure-jdk_11.2.3-11.0.1-win_x64 to zulu-11-azure-jdk_11.2.3-11.0.2-win_x64!! Where was the announcement for this as i can't see anything again and what is the frequency of these changes? This is causing us production issues.
