### ISSUE TITLE
Enable 8.3 names on drive C:

### ISSUE THREAD

**Issue by duracellko** [Microsoft/azure-pipelines-image-generation#692]
**Describe the bug**
Enable creation of 8.3 names on drive C:
Xamarin.Android Ahead-of-Time compiler requires 8.3 names in file system prior installing Visual Studio 2017. Otherwise it fails with error:
```
[aot-compiler stderr] Cannot open assembly 'Visual': No such file or directory.
##[error]C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2730,3): Error XA3001: Could not AOT the assembly: 
```

**Expected behavior**
Enable 8dot3name creation before installation of Visual Studio 2017. Using [fsutil.exe](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil).
[Microsoft support article](https://support.microsoft.com/en-us/help/121007/how-to-disable-8-3-file-name-creation-on-ntfs-partitions)

**Actual behavior**
A description with steps to reproduce the issue.

1. Create Xamarin.Android project.
2. Enable AOT and linking of SDK assemblies only.
3. Create build pipeline with Visual Studio Build task.

Build fails with error mentioned above.

**Image impacted**
Windows-VS2017

**Notes**
This worked with image release/1812. I don't see in history any change regarding 8dot3name change. Maybe Azure base image changed.

**Comment by DavidStaheli** [comment]
@alepauly do you know if the fix for this made it to production yet?

**Comment by alepauly** [comment]
> @alepauly do you know if the fix for this made it to production yet?

Not yet, @shadyysf is driving that deployment.

**Comment by DavidStaheli** [comment]
The fix for this is in the process of deploying to production, so I will close this issue.

**Comment by duracellko** [comment]
Can PR #693 be closed? Is there another fix for this?

**Comment by DavidStaheli** [comment]
@madhurig do you know, and whether I closed this prematurely?

**Comment by madhurig** [comment]
We have a fix for this already merged here: https://github.com/Microsoft/azure-pipelines-image-generation/commit/48aa4fcec6cb7a5f8840c4f2d3bc81ba98872abe
