### ISSUE TITLE
Update Docker to 18.09.2

### ISSUE THREAD

**Issue by shashankbarsin** [Microsoft/azure-pipelines-image-generation#699]
**Tool infomation**
- Tool name: Docker
- Add or update? Update
- Desired version: 18.09.2
- If this is an add request:
  - Brief description of tool: Security fix for Docker Engine
  - URL for tool's homepage: https://docs.docker.com/engine/release-notes/#18092

**Comment by DavidStaheli** [comment]
@shashankbarsin I'll close this now, since the image generation scripts install the latest version of Docker.  Please re-open if needed.  Thanks!
