### ISSUE TITLE
Error response from daemon: manifest for mcr.microsoft.com/azure-pipelines/vsts-agent:latest not found

### ISSUE THREAD

**Issue by jochenvanwylick** [Microsoft/azure-pipelines-image-generation#711]
Hi,
I'm trying to deploy the Azure DevOps agent Docker image, but are not successful. I'm following the instructions here: [on Docker hub](https://hub.docker.com/_/microsoft-azure-pipelines-vsts-agent)

But this results in:
```
C:\_CODE>docker run mcr.microsoft.com/azure-pipelines/vsts-agent
Unable to find image 'mcr.microsoft.com/azure-pipelines/vsts-agent:latest' locally
docker: Error response from daemon: manifest for mcr.microsoft.com/azure-pipelines/vsts-agent:latest not found.
See 'docker run --help'.
```
I left out the environment variables obviously because that does not add the issue.

What do I need to do differently?

**Comment by dakale** [comment]
We are in the process of migrating those images from dockerhub to MCR. I will investigate why the `latest` tag is not getting pushed correctly, but in the meantime, you can either pull:

`mcr.microsoft.com/azure-pipelines/vsts-agent:ubuntu-16.04-standard` which should be also tagged latest, and is the image with many software packages preinstalled, but is very large (~10gb I think)

or `mcr.microsoft.com/azure-pipelines/vsts-agent:ubuntu-16.04` is just the base ubuntu with an agent installed, and is much much smaller, You would have to either extend that image, or install your dependencies as part of your pipeline

**Comment by dakale** [comment]
@jochenvanwylick I pushed `latest` again, and on my VMs I can now pull/run:

`mcr.microsoft.com/azure-pipelines/vsts-agent` 

It should work for you now. Sorry for the inconvenience. Feel free to re-open this issue and tag me if you have any more issues with that image

**Comment by jochenvanwylick** [comment]
Yup - works ! Thanks.
