### ISSUE TITLE
Scripts should refer to VssAdministrator

### ISSUE THREAD

**Issue by DavidStaheli** [Microsoft/azure-pipelines-image-generation#715]
These files from PR #670 have 3 occurrences of `VssAdmisnitrator` which should be `VssAdministrator`.

- images/win/scripts/Installers/Validate-DotnetSDK.ps1
- images/win/scripts/Installers/Install-DotnetSDK.ps1

**Comment by hiyadav** [comment]
Fixed the TYPO !

**Comment by DavidStaheli** [comment]
Thanks a lot, Himanshu!
