### ISSUE TITLE
Install SQLPower[Ss]hellTools.ps1

### ISSUE THREAD

**Issue by tehho** [microsoft/azure-pipelines-image-generation#717]
**Describe the bug**
Unable to validate or build win2017 since diffrent naming standard for Validate and Install SQLPower[Ss]hellTools.ps1

**Expected behavior**
Packer to handle case insensitive files

**Actual behavior**
Validate Borken. 404 File no fund.

**Image impacted**
windows 2017

![snapshot](https://user-images.githubusercontent.com/1776012/52940204-3f1c2280-3366-11e9-9c49-0cee54cacee4.jpg)

**Comment by kaylangan** [comment]
Fixed in #816
