### ISSUE TITLE
Add 7z to Ubuntu

### ISSUE THREAD

**Issue by midgleyc** [Microsoft/azure-pipelines-image-generation#721]
**Tool information**
- Tool name: 7z
- Add or update? Add
- Desired version: Ideally the version on the VS2017 box, for exactly the same behaviour on VS2017 and Ubuntu
- If this is an add request:
  - Brief description of tool: Archiver used in the "Archive Files" task
  - URL for tool's homepage: https://www.7-zip.org/

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [x] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
Ubuntu

**Information**
I posted [an issue on the Tasks project](https://github.com/Microsoft/azure-pipelines-tasks/issues/9567), but was told that they deliberately don't modify the environment of the agents. The workaround is to run `apt install p7zip-full`, but as it's already installed in the VS2017 agent it would be nice to have it by default in the Ubuntu one as well.

**Comment by DavidStaheli** [comment]
Installation:
`apt-get install -y p7zip p7zip-full p7zip-rar`
