### ISSUE TITLE
Consolidate and update the hosted agents' images that use Windows with Microsoft's Docker Windows images

### ISSUE THREAD

**Issue by eriawan** [microsoft/azure-pipelines-image-generation#722]
Hi guys,

I believe this matter is urgent.
We have to consolidates the VM images, and we must have newer hosted agents based on Windows Server 2019, to sync up with latest development of MIcrosoft's Docker image on Docker Hub and Microsoft's MCR. 

Currently, Microsoft has pushed `microsoft/windowsservercore:latest` to use Windows Server 2019, and some child images such as `microsoft/dotnet-framework:latest` is also updated to use Windows Server 2019.

This is quite harmful to my need, because many build will be broken.

## Related past problems/issues

The problems on keeping up with the Windows images had occurred before. See also my closed issue of #536 about "Please update the cache the docker image of Windows Server 2016 LTSC".

cc @DavidStaheli, @vtbassmatt, @lokesh755

# Problems on current cached docker Windows based images in Windows based agents

Apologize if this is TL;DR. 
I have been closely watching the latest Microsoft docker images on docker hub and Microsoft's MCR is updated to use Windows Server 2019, and this will definitely break my build.

Looking at my current CI build (with added `docker image ls --digests`) on Azure DevOps, I see this:

```
2019-02-18T16:13:54.4716684Z "Get list of cached docker images"
2019-02-18T16:14:00.2237877Z REPOSITORY                    TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
2019-02-18T16:14:00.2238405Z microsoft/dotnet-framework    latest              sha256:f937dbfb092e5a04ca6ac93d49ab0b6c375bdaf9cd4d9f7bd9d4a9407eb36585   ec599075a73c        5 weeks ago         13.2GB
2019-02-18T16:14:00.2238798Z microsoft/windowsservercore   latest              sha256:05de0a0ac13d3652bd1f2281b8589459ebb611092e3fe4d8f1be91f1f6984266   ea9f7aa13d03        5 weeks ago         11GB
2019-02-18T16:14:00.2239445Z microsoft/aspnet              latest              sha256:a4d6856b978e5b9858ca294c97c5f4bc9ecfe3b062a7a015eaf625801573bc11   ddabd3e10c02        3 months ago        13.7GB
2019-02-18T16:14:00.2240532Z microsoft/nanoserver          latest              sha256:2b783310e6c82de737e893abd53ae238ca56b5a96e2861558fb9a111d6691ddb   4c872414bf9d        4 months ago        1.17GB
2019-02-18T16:14:00.2241035Z microsoft/aspnetcore-build    1.0-2.0             sha256:9ecc7c5a8a7a11dca5f08c860165646cb30d084606360a3a72b9cbe447241c0c   5d8be0910d37        6 months ago        3.99GB
```

Note the date and time marker. I ran this build on 18th February.

## Problem on the `microsoft/windowservercore:latest` cached on the hosted build agent of vs2017-win2016
Also note the SHA1 of `microsoft/windowservercore:latest` on the agent:

```
microsoft/windowsservercore   latest              sha256:05de0a0ac13d3652bd1f2281b8589459ebb611092e3fe4d8f1be91f1f6984266
```

On my local system, this is what I have now:

```
F:\ Tue 02/19/2019 11:49:06.89>docker image ls --digests
REPOSITORY                    TAG                                        DIGEST                                                                    IMAGE ID            CREATED             SIZE
microsoft/dotnet              2.2-sdk                                    sha256:790bbf273314de5f0a8b33df0659253f06ea0a54e2ef1259dde73b065d8edce9   409be5f5f635        6 days ago          1.76GB
microsoft/dotnet              2.1-sdk                                    sha256:32a9395d39f70a6e4988ad485e6de84e0771baaa59c3fbf6cc6acb732b6c030e   66a4ea40ad22        6 days ago          1.75GB
microsoft/dotnet-framework    4.7.2-runtime-windowsservercore-ltsc2016   sha256:1b2e8ce25edeab5784624ceff16c1ccf4a8d45cf215dca8f9c1966d5d45f8a74   6e449628b3c5        6 days ago          13.2GB
microsoft/dotnet-framework    latest                                     sha256:3c3fe0db41aa3500539a9667e0f1c2f6c2cc411bb658502bef8629f01f78b70e   dc903d18b688        6 days ago          4.28GB
microsoft/windowsservercore   10.0.14393.2791                            sha256:c72c12ef6613f0fd2d4fbd1e64e3cf550be4443347d696f08697849186c348b9   2b98a92e72d0        6 days ago          11GB
microsoft/windowsservercore   ltsc2016                                   sha256:c72c12ef6613f0fd2d4fbd1e64e3cf550be4443347d696f08697849186c348b9   2b98a92e72d0        6 days ago          11GB
microsoft/dotnet              2.1.503-sdk                                sha256:7d809ee21332fb44353c15779955dd951a431456366fb485df09b0ed847220b2   34ede0b322e7        11 days ago         1.75GB
microsoft/aspnet              4.7.2-windowsservercore-ltsc2016           sha256:915174e0bd25104bd309affbf49e98cec6717b26c8431442d776debfc1c9ec71   b4a0859630fa        5 weeks ago         13.8GB
microsoft/iis                 windowsservercore-1803                     sha256:14cc9818e65854276d8c779f6a7d68e3b07da80361da14ca24080b0c5372cec0   a6174e794f92        5 weeks ago         5.24GB
microsoft/windowsservercore   1803                                       sha256:260689daae3d9fb5bfca2881cab21e7ca07ae83849bb0511220b83ec6fe99bd5   22137d574e5f        5 weeks ago         4.97GB
microsoft/windowsservercore   latest                                     sha256:05de0a0ac13d3652bd1f2281b8589459ebb611092e3fe4d8f1be91f1f6984266   ea9f7aa13d03        5 weeks ago         11GB

```
I have looked at the history of `microsoft/dotnet-framework:latest`, and it clearly uses Windows Server 2019:

```
F:\ Tue 02/19/2019 11:49:16.37>docker history microsoft/dotnet-framework:latest
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
dc903d18b688        6 days ago          cmd /S /C #(nop)  ENV COMPLUS_NGenProtectedP…   41kB
<missing>           11 days ago         Install update ltsc2019-amd64                   804MB
<missing>           5 months ago        Apply image 1809-RTM-amd64                      3.47GB

```

Now I decided to compare it further.

The current state of cached `microsoft/windowsservercore:latest` image within the current `vs2017-win2016` agent is 

```
REPOSITORY                    TAG                 DIGEST   
microsoft/windowsservercore   latest              sha256:05de0a0ac13d3652bd1f2281b8589459ebb611092e3fe4d8f1be91f1f6984266
```

And checking on the official microsoft/windowsservercore on hub.docker.com and trying to look at least the recent 3 tags for Windows Server 2016 (14393) related tag and try to find the closest one of that previous SHA1, I get this:

```
REPOSITORY                    TAG                 DIGEST                                                                IMAGE ID      CREATED
microsoft/windowsservercore   10.0.14393.2724     sha256:05de0a0ac13d3652bd1f2281b8589459ebb611092e3fe4d8f1be91f1f6984266   ea9f7aa13d03        5 weeks ago    
``` 
And this `10.0.14393.2724` is the same as the cached image within the VS 2017 hosted agents.
So the VS 2017 hosted agents has the old cached image of `microsoft/windowsservercore:latest`, as indicated by both of the SHA1.

Due to the fact that the underlying OS of the container requires at least the same or higher OS, if we use the same image:tag of microsoft/windowsservercore:latest, the image will not be able to build.

For example: if I just use `microsoft/windowsservercore:latest` as base image for my dockerfile, then it will always fail to build on the current hosted agent of VS2017 WIn2016, because the pulled image uses Windows Server 2019, but the underlying OS of the hosted agent is using Win 2016.  

## Problem on cached image of `microsoft/dotnet-framework:latest` cached on the hosted build agent of vs2017-win2016

Looking at the current cached image of `microsoft/dotnet-framework:latest` on my machine, I have this:

```
REPOSITORY                    TAG                                        DIGEST                                                                    IMAGE ID            CREATED             SIZE
microsoft/dotnet-framework    latest                                     sha256:3c3fe0db41aa3500539a9667e0f1c2f6c2cc411bb658502bef8629f01f78b70e   dc903d18b688        6 days ago          4.28GB
```
And looking at the history of that image, I have this:
```
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
dc903d18b688        6 days ago          cmd /S /C #(nop)  ENV COMPLUS_NGenProtectedP…   41kB
<missing>           11 days ago         Install update ltsc2019-amd64                   804MB
<missing>           5 months ago        Apply image 1809-RTM-amd64                      3.47GB
```
It is using **Windows Server 2019** as the base OS! Then, it will always fail and break the build.

Unless we are using the specific tag, the update will always break. 
Fortunately, I use specific tag of .NET Framework 4.7.2 on Windows Server 2016 because I have to use Windows Server 2016 as the latest Windows Server supported containers for Azure Container Instances. The image:tag I use is `microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-ltsc2016`.

Now go back to my machine and check the latest `microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-ltsc2016`, looking at the Created date, it's updated 6 days before.

Looking at the history, it uses `10.0.14393.2791` as indicated in the image history:

```
F:\ Tue 02/19/2019 12:04:42.55>docker history microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-ltsc2016
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
6e449628b3c5        6 days ago          cmd /S /C \Windows\Microsoft.NET\Framework64…   998MB
<missing>           6 days ago          cmd /S /C #(nop)  ENV COMPLUS_NGenProtectedP…   41kB
<missing>           6 days ago          cmd /S /C powershell -Command         $Error…   353MB
<missing>           6 days ago          cmd /S /C powershell Invoke-WebRequest -Uri …   882MB
<missing>           7 days ago          Install update 10.0.14393.2791                  3.32GB
<missing>           5 months ago        Apply image 10.0.14393.0                        7.68GB
```

Previously as described in my previous issue, it had been solved, because the cached image of `microsoft/dotnet-framework:latest` on the build agent has the same SHA1 with `microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-ltsc2016` that I use as the base image of my container.

Due to these facts that the hosted agent:
1. It doesn't have cached image of `microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-ltsc2016`, again, previously it has the same SHA1 of   ``microsoft/dotnet-framework:latest` as before, and now it's not the same.
2. Based on the issue last year, the cached image is always using more general tag of `latest`, and this is dangerous.

Now, it is not the same anymore because the current image from Microsoft (not the cached image) of `microsoft/dotnet-framework:latest` has these facts:

1. It is based on WIndows Server 2019
2. It will not be built on the current agent of VS2017-WIn2016, because the OS of the agent is using Win 2016.
3. Based on previous issues, all of the `latest` tag won't be guaranteed to have the same OS version for long. For example: on November 2018 the `microsoft/dotnet-framework:latest` is based on Windows Server 2016, but then since  February 18, 2019 the `microsoft/dotnet-framework:latest` is based on Windows Server 2019.

# PROPOSED SOLUTION

We need to take actions soon, and I don't want to create and use my own agent, because Azure DevOps Pipelines should always be able to keep up with the progresses, updates and any changes on Microsoft official docker images especially those images that based on Windows.

These are my proposal:
1. Avoid any usages of `latest` tag on the VS2017-Win2016, as this will always break based on the problems above.
2. Release newer (separated) build agent that has VS2017 at least 15.9.5, based on Windows Server 2019. This will have greater compatibility and also support for building images based on Windows Server 2019 container.
3. Still related to point 2, the newer build agent of VS2017 on Win 2019 should have cached images of Windows Server 2019 based images only, with the additional necessary images to choose. For example: if I want to use IIS, then I will always have slow build because current cached images on VS2017-Win2016 doesn't have cached image of `microsoft/iis:windowsservercore-ltsc2016`, This should be also done for Win2019 based images.
4. Always have regular consolidation and updates on the build agents to update cached images, preferably **at least every 2 weeks**. Otherwise, all of the Azure DevOps Pipelines will always be trapped and forced to wait for the images to be pulled for every build. If we look at previous issue of #536, it had updated for more than 2 months and this is not enough. It surely can;t keep up with VS 2017, not just having updated cached images. Again, having long time/period to update the cached images and the agents it will make Azure DevOps Pipelines looked useless because it can't keep up quite well.
5. Always prefer to cache specificity image with tags not latest, to prevent failing build. For example,  `microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-ltsc2016` for Win2016 based agent and `microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-ltsc2019` also Win2019 agent. Therefore the cached images should not have more generic tag such as `4.7.2-runtime`, because it has no guarantee that it will work/build if OS is updated again. I could understand that if the underlying OS container has updates, then I have to wait some time to pull image layers. But the wait time should be minimized, if we have regular/periodic updates as in point 4.

Ok, I am done for now, and I'll update this issue if I find other things to consider/add.
I welcome feedback.

**Comment by eriawan** [comment]
I have submitted a feedback to MS Developer Community web: 
https://developercommunity.visualstudio.com/content/problem/462204/cached-docker-images-on-azure-devops-pipelines-age.html

So I hope this issue will be solved soon...

**Comment by vtbassmatt** [comment]
Tagging a few folks to look at this: @joebourneMS for the base image, @shashankbarsin and @azooinmyluggage as our container experts/owners.

**Comment by azooinmyluggage** [comment]
Thanks @vtbassmatt . Let me discuss this internally.

**Comment by eriawan** [comment]
@DavidStaheli  @vtbassmatt @joebourneMS @shashankbarsin  @azooinmyluggage 

Is there any update on this issue? 
FYI, looks like I'm not alone about not using `latest` tag. For my team, latest tag is more like anti pattern instead of convenience. To put this in summary:

1. It has no specificity like: What OS version? Which OS patch it has?
2. We have no control on what will be the next base OS used by `latest` tag, especially on the case of `microsoft/dotnet-framework:latest` above.
3. As caused by number 1 and 2: therefore there is no guarantee that the build will always work.

There are many articles on the web:

1. https://vsupalov.com/docker-latest-tag/
2. https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375

The second article has this good advice:

![image](https://user-images.githubusercontent.com/8773147/53325789-ab72c500-3916-11e9-8f55-6c02f9efeae1.png)

--------

Ok, back to the problem.

On today's image update, the `microsoft/windowsservercore:latest` is not the actual latest update of the Windows Server 2016. So looks like this image:tag is based on Windows Server 2016, but it is not the actual latest when compared to other image that I have cached on my machine, such as `microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-ltsc2016`.

This is confusing, because `microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-ltsc2016` is using Windows Server 2016 with patch of `10.0.14393.2791`, but the `microsoft/windowsservercore:latest` is using older update of `10.0.14393.2724`. So, this latest tag on ``microsoft/windowsservercore` is not guaranteed to use the latest one. So now currently even if I use specific tag of `microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-ltsc2016`, my build will always be slow. Because current tag of `microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-ltsc2016` has Windows Server 2016 with patch of `10.0.14393.2791`, and again I won't be able to use existing `microsoft/dotnet-framework:latest` because this image:tag is based on Windows Server 2019, currently.

Therefore this proves that it is always dangerous to rely on `latest` tag, and event the latest tag of `microsoft/windowsservercore:latest` is not using Windows Server 2019, and to make the matter more confusing is the fact that current `microsoft/windowsservercore:latest` is still using `10.0.14393.2724`, not the update of ``10.0.14393.2791`, as it's currently used by `microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-ltsc2016`.

So now the problems are multiple:

1. This proves more about my proposal previously, that `latest` tag is dangerous and should be avoided. Therefore must not be cached in the VM image.
2. The latest tag itself is inconsistent. It is NOT THE ACTUAL latest, even on Windows Server 2016. This means that current MCR or the MS repo on Docker Hub has this flaw too. 
3. Having specificity may not be fast enough to build, if the underlying OS patch is not cached. For example: current latest `microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-ltsc2016` has update of 2791, whereas the `microsoft/windowsservercore:latest` has 2724. So there's no guarantee that the image build will always be fast/quick.
4. Due to the fact that current cached image all has `latest` tag model, any specificity I have will always not the latest one, and I will have slow build almost every time.

Ok, here's the simple proof that the latest image of `microsoft/windowsservercore:latest` from MS is still using Windows Server 2016 today:

```
F:\ Mon 02/25/201919:00:53.31 >docker image ls
REPOSITORY                    TAG                                        IMAGE ID            CREATED             SIZE
microsoft/aspnet              4.7.2-windowsservercore-ltsc2016           f4f2412cb1c5        12 days ago         13.8GB
microsoft/dotnet              2.2-sdk                                    409be5f5f635        12 days ago         1.76GB
microsoft/dotnet              2.1-sdk                                    66a4ea40ad22        12 days ago         1.75GB
microsoft/dotnet-framework    4.7.2-runtime-windowsservercore-ltsc2016   6e449628b3c5        12 days ago         13.2GB
microsoft/dotnet-framework    latest                                     dc903d18b688        12 days ago         4.28GB
microsoft/iis                 windowsservercore-1803                     666fd6086c78        12 days ago         5.24GB
microsoft/windowsservercore   1803                                       072c57eb11e2        12 days ago         4.97GB
microsoft/windowsservercore   10.0.14393.2791                            2b98a92e72d0        12 days ago         11GB
microsoft/windowsservercore   ltsc2016                                   2b98a92e72d0        12 days ago         11GB
microsoft/dotnet              2.1.503-sdk                                34ede0b322e7        2 weeks ago         1.75GB
microsoft/windowsservercore   10.0.14393.2724                            ea9f7aa13d03        6 weeks ago         11GB
microsoft/windowsservercore   latest                                     ea9f7aa13d03        6 weeks ago         11GB

F:\ Mon 02/25/201919:00:59.12 >docker pull microsoft/windowsservercore:latest
latest: Pulling from microsoft/windowsservercore
Digest: sha256:05de0a0ac13d3652bd1f2281b8589459ebb611092e3fe4d8f1be91f1f6984266
Status: Image is up to date for microsoft/windowsservercore:latest

F:\ Mon 02/25/201919:01:19.31 >docker history microsoft/windowsservercore:latest
IMAGE               CREATED             CREATED BY                       SIZE                COMMENT
ea9f7aa13d03        6 weeks ago         Install update 10.0.14393.2724   3.31GB
<missing>           5 months ago        Apply image 10.0.14393.0         7.68GB

F:\ Mon 02/25/201919:01:56.32 >docker history microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-ltsc2016
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
6e449628b3c5        12 days ago         cmd /S /C \Windows\Microsoft.NET\Framework64…   998MB
<missing>           12 days ago         cmd /S /C #(nop)  ENV COMPLUS_NGenProtectedP…   41kB
<missing>           12 days ago         cmd /S /C powershell -Command         $Error…   353MB
<missing>           12 days ago         cmd /S /C powershell Invoke-WebRequest -Uri …   882MB
<missing>           13 days ago         Install update 10.0.14393.2791                  3.32GB
<missing>           5 months ago        Apply image 10.0.14393.0                        7.68GB

```

So please fix this.

For me it's not just a potential bug, it also can be seen as showstopper due to the fact that the build can break anytime and it always can't keep up with the update from MCR/Docker Hub.

I really want to know, not just from the Azure Pipelines team, but also I hope those teams that maintains the updates on MS MCR and MS repo on Docker Hub pay attention to this matter.

Again, is there definite plan to have fixes on this issue? Or what will be the considerations of not caching the specific tags?

**Comment by eriawan** [comment]
@DavidStaheli @vtbassmatt @azooinmyluggage 

Any update or progress on this issue? It's been more than 2 weeks, please confirm...

**Comment by shashankbarsin** [comment]
@eriawan we discussed this issue in the team and we are exploring a couple of options to address the issue - 

- Further shortening the release window for hosted image generation
- Splitting out the process of hosted image generation and caching images on the hosted images (as a pos step to generation of images)
- In the long term, trigger image generation and/or caching of images based on notifications of image push to MCR repositories (we are working with MCR team for this)

I will keep you posted as soon as I have an update on this issue

cc: @joebourneMS

**Comment by SteveLasker** [comment]
Hi @eriawan 
Sorry for your frustration. With the multiple versions of windows, using `:latest` as a lot of instability. A best practice involves using the specific version tag. You can see the tags on the repo listing here: https://hub.docker.com/_/microsoft-windows-servercore
Binding to a specific versioned tag will give you the latest OS patch, without fighting the version compatibility issues noted above. 
Steve

**Comment by eriawan** [comment]
@SteveLasker 

Yes, I already know about that. 

Unfortunately, all cached images in the Azure Pipelines agent are all using `latest` tag, and this is wrong.
Those cached images will always can't keep up with the pace of the images from Docker hub and MCR.

My main problem still remains because of the fact that all of the cached images are not specific, therefore I have to always download the newer layers. I really want to have frequent updates on the images, as this will speed up my CI build considerably, and if the CI build has to always download the whole layers, then it will be quite useless if the pipelines is always downloading newer images, as it will always take 12 to about 20 minutes to just download newer images.

For example, look at this CI build on March 22:
https://dev.azure.com/rxcommunica/rxpubliccrepo/_build/results?buildId=140

Especially this:
![image](https://user-images.githubusercontent.com/8773147/54971220-fc2e1a00-4fb7-11e9-953d-6447c7019df4.png)

So the agent itself doesn't comply the practices of not using `latest` tag, and the current cached images are always left behind for more than a month.

On my machine, at the time of this comment writing, the image of `microsoft/dotnet-framework:latest` is using Windows 2019:

![image](https://user-images.githubusercontent.com/8773147/54971482-29c79300-4fb9-11e9-84fa-dbd4d4f61515.png)

Therefore, if anyone use the `microsoft/dotnet-framework:latest`, it will render the CI as error because I'm using VS2017-WIn2016 as the image.

My main problem is simple, and my proposal is straightforward: 
don't use `latest` tag as the cached image on the agent, and always update the images **_specific to the base OS used as the agent_**, frequently. 

Frequently at least 2 weeks, because this will always ensure the updates of cached images, including those for

For example: I would like to have cached images of `microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-ltsc2016` instead of just having `microsoft/dotnet-framework:4.7.2-runtime`. And also the base OS image of WIn2016 has to be updated, therefore `microsoft/windowsservercore:ltsc2016` must be cached too.

**Comment by eriawan** [comment]
@davidstaheli @vtbassmatt @shashankbarsin 

Guys, are there any updates on this issue? It's been more than 2 months without any updates! 😞 

Is there any problem? Please confirm....
