### ISSUE TITLE
Docker image for linux

### ISSUE THREAD

**Issue by tehho** [Microsoft/azure-pipelines-image-generation#723]
Hi.

Since https://github.com/Microsoft/vsts-agent-docker is deprecated is it possible to add a dockerfile for the images here?

Would be nice for us that run our buildagents in AKS.

**Comment by vtbassmatt** [comment]
This will be part of our work on fully deprecating that image.

**Comment by davemedvitz** [comment]
Will the other, now deprecated, docker pieces be updated while this is in progress.  We are unable to use public build agents for security and compliance reasons, and have been using the docker images for some time.  Not having a viable alternative will be problematic for us.

**Comment by vtbassmatt** [comment]
We weren't updating them even before they were marked deprecated, so this isn't a change in behavior -- just in how we communicate.

**Comment by junkiebev** [comment]
Is this still being worked on?

**Comment by vtbassmatt** [comment]
Thank you for the reminder! We've published docs here: https://docs.microsoft.com/azure/devops/pipelines/agents/docker
