### ISSUE TITLE
Add the Azure DevOps extension to the Azure CLI (macOS)

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/azure-pipelines-image-generation#729]
Deployment: Add the Azure DevOps extension to the Azure CLI (macOS).
This was done for Linux and Windows in this PR: #725.
After the Azure CLI is installed, the Azure DevOps extension can be added with this command:
`az extension add -n azure-devops`

**Comment by atbagga** [comment]
@nrajpurkar @davidstaheli This seems to be closed accidently without the changes going in. Can you reopen this issue.
