### ISSUE TITLE
Script folder of new pip version not on Windows path

### ISSUE THREAD

**Issue by cstratopoulos** [Microsoft/azure-pipelines-image-generation#731]
**Describe the bug**
Between yesterday and today the installed version of `pip` on `vs2017-win2016` appears to have gone from 10.0.1 to 19.0.1, and the pip script folder is no longer in `PATH`. 

**Expected behavior**
Installed scripts are available in PATH

**Actual behavior**
Installation of a pip package warns that this is not the case:
```
[command]"C:\Program Files\Git\bin\bash.exe" --noprofile --norc /d/a/_temp/2753734e-0031-4c0a-b8e8-f0a3bd7d2d25.sh
+ python -m pip --version
pip 19.0.1 from C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\pip (python 3.6)

+ python -m pip install --upgrade setuptools wheel
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/d1/6a/4b2fcefd2ea0868810e92d519dacac1ddc64a2e53ba9e3422c3b62b378a6/setuptools-40.8.0-py2.py3-none-any.whl (575kB)
Collecting wheel
  Downloading https://files.pythonhosted.org/packages/96/ba/a4702cbb6a3a485239fbe9525443446203f00771af9ac000fa3ef2788201/wheel-0.33.1-py2.py3-none-any.whl
Installing collected packages: setuptools, wheel
  Found existing installation: setuptools 40.6.2
    Uninstalling setuptools-40.6.2:
      Successfully uninstalled setuptools-40.6.2
  The script wheel.exe is installed in 'C:\hostedtoolcache\windows\Python\3.6.8\x64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed setuptools-40.8.0 wheel-0.33.1
You are using pip version 19.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Steps to reproduce**

1. Install a pip package, e.g., `pip install conan'
2. Try to run the just installed package: `conan --version`

**Image impacted**
- `vs2017-win2016`

**Comment by brcrista** [comment]
@cstratopoulos thanks for reporting.  Could you post the logs of your Use Python Version step?  Running with system.debug=true would be helpful.

**Comment by cstratopoulos** [comment]
@brcrista this is a python invocation through a bash script, there's no use python version step anywhere in my pipeline currently. 

If you like you can see [here](https://dev.azure.com/ossiaco/ossiaco/_build/results?buildId=1900) for debug logs of the relevant python steps. Note that I first tried removing the `pip --upgrade pip` part (and the issue persisted) but the only logs of that I have are from a private project.

For now I've deployed a hotfix to add the missing path to `PATH`.

Also I'm leaving on vacation after today so I won't be posting updates back here for a while, but thanks for the prompt reply nonetheless!

**Comment by brcrista** [comment]
Ah, I see.  We made a change to how "system Python" is installed on the latest version of the hosted image.  That must be the problem here.

In the meantime, if you add this task to your pipeline, it will set your PATH up correctly:

```yaml
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
  displayName: Use Python 3.6
```

**Comment by madhurig** [comment]
A fix for the issue has been deployed to all regions last week. You should not see errors even if you are not using the `UsePythonVersion` task now, so closing this issue.
