### ISSUE TITLE
windows-2019 VS2019 does not install all available windows SDK versions.

### ISSUE THREAD

**Issue by glennawatson** [microsoft/azure-pipelines-image-generation#734]
**Describe the bug**
A number of the Windows SDKs arent' installed in the new hosted VS2019 installation.

**Expected behavior**
To have all the windows SDK installed that the 2019 installation supports:
Windows 10 Preview SDK (10.0.18323.0)
Windows 10 SDK (10.0.16299.0)
Windows 10 SDK (10.0.17134.0)
Windows 10 SDK (10.0.17763.0)

**Actual behavior**
Only has the default installation options here. Does not include the other Windows SDK options.

**Image impacted**
windows-2019

**Comment by kaylangan** [comment]
The image now has Windows 10 SDKs:

- 16299
- 17134
- 17763
- 18362

Closing as complete.
