### ISSUE TITLE
Increase the limit of open files on Hosted Ubuntu 1604

### ISSUE THREAD

**Issue by rwa-avaleo** [microsoft/azure-pipelines-image-generation#737]
While running nodejs karma tests on agent from pool Hosted Ubuntu 1604 we encounter error Error: `EMFILE: too many open files`. It seems that the open file limit is set to 4096 files which is quite low. If possible we would like to have it set to unlimited or at least to some value around 50000. If it is impossible to change the images default value can we somehow change it manually for our needs? We tried running ulimit command as a part of the build but we receive `Operation not permitted` error.

**Areas and ecosystems**
- [x] Javascript, Node.js, Karma and AngularJS

**Image impacted**
Ubuntu

**Comment by yubbz** [comment]
I am having the same issue. I am able to REDUCE the ulimit -n to anything below 4096 but will not let me increase it. Please help...

**Comment by pasangh** [comment]
Thanks for the input! I am working on this here - #1026

**Comment by pasangh** [comment]
The limit increase change be rolled out with the next deployment. ETA 8/9.

**Comment by vladhor** [comment]
Since systemd ignores limits configured in places such as limits.conf, limits.d, sysctl etc. you have to make that change specifically in your daemon systemd file:

[Service]
LimitNOFILE=65536
