### ISSUE TITLE
Add Docker on macOS

### ISSUE THREAD

**Issue by vkrasnov** [microsoft/azure-pipelines-image-generation#738]
**Tool infomation**
- Tool name: Docker
- Add or update? Add
- Desired version: Any version
- If this is an add request:
  - Brief description of tool: Docker
  - URL for tool's homepage: https://www.docker.com/

**Areas and ecosystems**

- [x] iOS, macOS, and Apple-specific tools
- [X] Testing and code coverage
- [X] Other

**Image impacted**
mac

**Comment by vkrasnov** [comment]
Just to add some detail, I have a multi platform project that relies heavily on docker for testing. Windows and Linux have docker, but mac does not, and that makes it difficult to use for testing. It is also impossible to install docker or another vm as part of the build script.

**Comment by nrajpurkar** [comment]
Cool, thanks for the suggestion @vkrasnov. I'll leave this open to track further interest about implementing this.

**Comment by cheenamalhotra** [comment]
This should be supported. Our teams also need docker to pull docker images in macOS.

Related feature request: https://developercommunity.visualstudio.com/content/idea/536214/support-for-docker-on-self-hosted-macos-agents.html

**Comment by yitam** [comment]
The project msphpsql has set up [Azure Pipelines](https://github.com/Microsoft/msphpsql/blob/dev/azure-pipelines.yml) but can not run any tests in hosted macOS agents precisely because docker is not available.

**Comment by bryanmacfarlane** [comment]
When docker runs a container image on macOS it's Linux.  I'm curious what it means to test a container on macOS.  Running docker on macOS is a dev scenario for writing and testing Linux apps but on mac.

**Comment by yitam** [comment]
For our testing purposes we want to test against SQL Server in mac agents @bryanmacfarlane , which is achievable by using docker

**Comment by bryanmacfarlane** [comment]
Are you running the mac app in the host but trying to spin up SQL server in a linux based container as a service?

**Comment by yitam** [comment]
yes @bryanmacfarlane  for testing we want to connect to any SQL Server instance but in a CI env perhaps the easiest is to communicate to the server in a linux based container

**Comment by bryanmacfarlane** [comment]
OK - that makes sense.  Thanks for clarifying

**Comment by AlexHagerman** [comment]
We have a similar need for `pymssql` which I was working to migrate to Azure Pipelines so we could test and build for Windows, Linux and MacOS in one pipeline. Similar use case, building and running test on the host, but using docker to create a SQL Server instance for integration test. 

https://github.com/AlexHagerman/pymssql/blob/pipelines/azure-pipelines.yml

**Comment by Anumita** [comment]
We are in the process of adding docker in mac OS agents. Till we get that done, for a workaround you can use this script to install docker on mac os during the job and use it.

brew cask install docker
sudo /Applications/Docker.app/Contents/MacOS/Docker --quit-after-install --unattended
/Applications/Docker.app/Contents/MacOS/Docker --unattended &

while ! docker info 2>/dev/null ; do
    sleep 5
    echo "Waiting for docker service to be in the running state"
done

**Comment by cheenamalhotra** [comment]
We used the above script to install Docker, but recently the builds are failing a lot: https://dev.azure.com/sqlclientdrivers-ci/mssql-jdbc/_build/results?buildId=1510

Can you help us resolve this?

**Comment by satrapu** [comment]
Hey @cheenamalhotra,

Just restart the build in case the Docker installation script seems to enter a loop.
It did the trick for me!

**Comment by satrapu** [comment]
I have re-run my build to see how good this approach is and unfortunately I see 3 out of 6 tries have succeeded in installing Docker via the aforementioned script; the rest of the 3 tries enter a loop when checking whether Docker service is running.
IMO having 50% chance of successfully running such a script is not good enough; on the other hand, we do have a workaround, it just need to be refined a little.

@Anumita: Any thoughts about the loop and a way to avoid it?

**Comment by cheenamalhotra** [comment]
We usually re-run them to get around the issue but as you also mentioned recently its failing quite often than usual, hence I thought of notifying here.

Do you have any timelines for releasing Official Docker support in Azure Hosted MacOS Agents?

**Comment by stephenrwalli** [comment]
I do not understand the use case. Docker for Mac is a free product with a restrictive EULA produced and distributed by Docker Inc. As was pointed out by @bryanmacfarlane, Docker for Mac is building and running Linux containers in a Linux VM on MacOS. There are no MacOS containers as Apple and Docker have never worked to build such kernel abstractions. This is why one cannot use Microsoft-hosted MacOS agents to build MacOS container images -- MacOS containers don't exist. If Azure Pipelines installed Docker for Mac on Microsoft-hosted MacOS agents (and the Docker EULA prevents Microsoft from so doing), an Azure Pipelines customer would only be able to build and run Linux container images, something better supported on Microsoft-hosted Linux agents.

**Comment by vkrasnov** [comment]
In my case there is a product that produces native binaries for macOS, Windows and Linux.
As part of the test harness, it need to connect to a docker container, that indeed runs a Linux binary of a peer service. This way we can test they interop correctly inside the VM.
There are hundreds of projects that need to communicate with Linux based services. The contents of the container are *not* the product, but are critical for the CI process.

**Comment by yitam** [comment]
It's the same for our CI process. We just want to test communication between our drivers and SQL Server, which in macOS is available in a Linux container.

**Comment by shashankbarsin** [comment]
Docker for Mac is a free product from Docker, but is associated with this [End User License Agreement](https://www.docker.com/legal/docker-software-end-user-license-agreement).

With the approach of script based installation of Docker on the macOS hosted agent followed by running of Docker task/script failing frequently, for now we recommend setting up a [self-hosted macOS agent](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-osx?view=azure-devops), installing [Docker for Mac](https://docs.docker.com/docker-for-mac/install/), and running the jobs on the same.

**Comment by MaceWindu** [comment]
Guys, if you see docker run fails for you for last several days, it is due to something broken with recent docker version from brew. To fix it just use specific version to install till it is now fixed:
```
# 2.1.0.1,37199 is current version and crashes on start (same for previous 2.1.0.0,36874)
# brew cask install docker
# below is a link to 2.0.0.3-ce-mac81,31259 version, which is two versions below and still works
brew cask install https://raw.githubusercontent.com/Homebrew/homebrew-cask/b8c67034bd78f9585b1316564f223b97055bc0dc/Casks/docker.rb
```

Basically docker 2.0 works, 2.1 crashing and it would be nice if azure team could look into crashing issue. Probably it is something with agent configuration.

**Comment by ViceIce** [comment]
@MaceWindu Can you post a fully functional install script? Thanks.

**Comment by MaceWindu** [comment]
it's https://github.com/microsoft/azure-pipelines-image-generation/issues/738#issuecomment-496211237, just modified `brew install` line to use specific version

**Comment by ViceIce** [comment]
@MaceWindu  Thanks. Now only one warning left: `The STDIO streams did not close within 10 seconds of the exit event from process '/bin/bash'. This may indicate a child process inherited the STDIO streams and has not yet exited.`

Maybe we need to redirect the daemon io?

**Comment by MaceWindu** [comment]
I observe this message too, but didn't looked into it, because it works fine anyway
