### ISSUE TITLE
windows-2019 image has problems using git in powershell step

### ISSUE THREAD

**Issue by jwillemsen** [microsoft/azure-pipelines-image-generation#740]
**Describe the bug**
We are using the commands below to install vcpkg as part of an azure devops pipeline job but it seems this doesn't work
```
  - powershell: |
      git clone --depth 1 git://github.com/Microsoft/vcpkg.git $(Build.SourcesDirectory)\vcpkg
      .\vcpkg\bootstrap-vcpkg.bat
      .\vcpkg\vcpkg.exe install --recurse --triplet $(vcpkgarch) openssl xerces-c
    displayName: vcpkg
```

It fails with the error below, see https://github.com/DOCGroup/ACE_TAO/pull/845

```
##[section]Starting: vcpkg
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Windows, macOS, or Linux.
Version      : 2.140.2
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613736)
==============================================================================
Generating script.
##[command]"C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'd:\a\_temp\ddacbda7-3637-49e2-9f93-b43dd1f4b571.ps1'"
##[error]git : Cloning into 'd:\a\1\s\vcpkg'...
##[error]At D:\a\_temp\ddacbda7-3637-49e2-9f93-b43dd1f4b571.ps1:2 char:1
+ git clone --depth 1 git://github.com/Microsoft/vcpkg.git d:\a\1\s\vcp ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Cloning into 'd:\a\1\s\vcpkg'...:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 

##[error]PowerShell exited with code '1'.
##[section]Finishing: vcpkg
```

**Expected behavior**
Be able to install vcpkg

**Actual behavior**

See https://github.com/jwillemsen/ATCD/blob/jwi-vs2019/azure-pipelines.yml

**Image impacted**
windows-2019

**Comment by letmaik** [comment]
I'm facing the same issue. This is not related to vcpkg but rather running the git command. It looks like it exits because of stderr output, but I checked and I don't have fail on stderr enabled.

**Comment by DavidStaheli** [comment]
Side note: the Windows 2016 image has vcpkg preinstalled.  I just noticed the Windows 2019 image doesn't have it for some reason, and added it with PR #749.

**Comment by jwillemsen** [comment]
Great! Didn't know vcpkg is already preinstalled now, seems to have to update our azure-pipelines.yml file

**Comment by jwillemsen** [comment]
Any updates? This prevents us from testing with vs2019 on azure

**Comment by jwillemsen** [comment]
Using `git clone -q` instead of `git clone` can be used as workaround

**Comment by joebourneMS** [comment]
It looks like the PR #749 was never merged. Looking into this now.

**Comment by Foxtrek64** [comment]
Hate to drag this along further, but I'm trying to run `git` commands through powershell to build my docfx instance and I'm running into this same issue.

Running `git clone -q` fixes it with that step, but I feel I shouldn't have to run all of my git commands silently.

I'm more than willing to share my powershell script here, but the gist is that it clones the gh-pages branch into a new folder, runs `git rm -r *` on that folder to clean it, copies the compiled site from `/docs/_site` into that folder, then force pushes to the gh-pages branch.

**Comment by gabrieldausque** [comment]
Same issues here. Any updates from microsoft on that issues ?

**Comment by jwillemsen** [comment]
Any updates?

**Comment by alepauly** [comment]
> Any updates?

@jwillemsen Sorry about the delay, we're looking.

**Comment by JamesYangLim** [comment]
Hi, I am facing the same issue when using git command in powershell script with windows-2019 pool. Note that the exact same scipt runs in Hosted VS2017 pool.

**Comment by villasante** [comment]
I'm seeing the same issue when running git checkout -b mybranch:
Calling: git checkout -b mybranch
git : Switched to a new branch 'mybranch'
At D:\a\1\s\mypowershell.ps1:43 char:1
+ git checkout -b mybranch
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Switched to a n...mybranch':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError


Any update?

**Comment by ryanspletzer** [comment]
Trying to move to vs2019 from vs2017 currently where we do currently use git in the PowerShell step, so watching this one closely. 👀 

In our case we tried to emulate the built-in clone step as closely as possible (we're using repo's not accessible on the public internet, internal GitHub Enterprise instance, hence the need for a custom clone step -- that's a whole other long story). We create a dummy empty repo in Azure Repos with the same name of our internal repo to associate the build to.

In this approach the commands are written out the same way the built-in Get Sources task does it, so you get the nice blue output of the commands being run.

I could add `-q`'s to all these git commands I suppose.

```powershell
$repoUrlFormat = '{0}://{1}/{2}/{3}.git'
# Set GitHub_Scheme, GitHub_Hostname and GitHub_Organization in build variables
# e.g. 'https', 'git.contoso.com', 'myorg'
# Build_Repo_Name comes from the name of the dummy repo in Azure Repos
$repoUrl = $repoUrlFormat -f $env:GitHub_Scheme, $env:GitHub_Hostname, $env:GitHub_Organization, $env:Build_Repository_Name

Write-Output -InputObject '##[command]git version'
git version
Write-Output -InputObject '##[command]git lfs version'
git lfs version
if (-not (Test-Path -Path ([System.IO.Path]::Combine($env:System_DefaultWorkingDirectory, '.git')))) {
    Write-Output -InputObject "##[command]git init $env:System_DefaultWorkingDirectory"
    git init $env:System_DefaultWorkingDirectory
}
Write-Output -InputObject '##[command]git config --get remote.origin.url'
$url = git config --get remote.origin.url
if ($null -eq $url) {
    Write-Output -InputObject "##[command]git remote add origin $repoUrl"
    git remote add origin $repoUrl
}
if ($url -ne $repoUrl) {
    Write-Output -InputObject "##[command]git remote origin --set-url $repoUrl"
    git remote set-url origin $repoUrl
    Write-Output -InputObject "##[command]git remote set-url --push origin $repoUrl"
    git remote set-url --push origin $repoUrl
}
Write-Output -InputObject "##[command]git config gc.auto 0"
git config gc.auto 0
Write-Output -InputObject "##[command]git config --get-all http.$repoUrl.extraheader"
git config --get-all "http.$repoUrl.extraheader"
Write-Output -InputObject "##[command]git config --get-all http.proxy"
git config --get-all http.proxy
Write-Output -InputObject '##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --tags --prune --progress --no-recurse-submodules origin'
$authHeader = '$(build-service-account-name):$(build-service-account-github-enterprise-personal-access-token)'
$base64EncodedAuthHeader = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($authHeader))
git -c http.extraheader="AUTHORIZATION: basic $base64EncodedAuthHeader" fetch --tags --prune --progress --no-recurse-submodules origin
# Build_SourceBranch comes from the branch you pick for the build queuing UI modal
$refName = $env:Build_SourceBranch
$refsPrefix = "refs/heads/"
$remoteRefsPrefix = "refs/remotes/origin/"
if ([string]::IsNullOrEmpty($refName)) {
    $refName = $remoteRefsPrefix + "master";
} elseif ($refName.Equals("master", [StringComparison]::OrdinalIgnoreCase)) {
    $refName = $remoteRefsPrefix + $refName;
} elseif ($refName.StartsWith($refsPrefix, [System.StringComparison]::OrdinalIgnoreCase)) {
    $refName = $remoteRefsPrefix + $refName.Substring($refsPrefix.Length);
}
Write-Output -InputObject "##[command]git rev-parse $refName"
$commitId = git rev-parse $refName
Write-Output -InputObject "##[command]git checkout --progress --force $commitId"
git checkout --progress --force $commitId
```

**Comment by alepauly** [comment]
@ryanspletzer, @villasante, @JamesYangLim , @jwillemsen, @gabrieldausque: After looking into this a bunch, the only thing that works is adding ```$env:GIT_REDIRECT_STDERR = '2>&1'``` at the top of any of our Powershell scripts that run Git commands. That tells the Git client to redirect stderr internally for all commands (that adhere to the setting) and in all our testing has been successful at mitigating the issue.

**Comment by ryanspletzer** [comment]
I will use this, thanks @alepauly !

**Comment by damccorm** [comment]
To follow up on what @alepauly said, it looks like this is somewhat just how the newest versions of git and PowerShell play together - see https://github.com/dahlbyk/posh-git/issues/109 for a more detailed discussion. The recommendation there is also `$env:GIT_REDIRECT_STDERR = '2>&1'`, so I'm not sure how much we can do on the image side to avoid this.

**Comment by letmaik** [comment]
@damccorm Can this be baked into the images? Alternatively, if PowerShell can be (globally) convinced not to treat stderr output as oh-my-god-the-world-crashed then that would be even better.

**Comment by bneumann** [comment]
Hi, as stated in #10670 I am seeing this also on other calls then git. Redirecting to stdout doesn't work unfortunately
