### ISSUE TITLE
README.md contains broken link

### ISSUE THREAD

**Issue by jwillemsen** [Microsoft/azure-pipelines-image-generation#753]
**Describe the bug**
In README.md there is the following link which is broken
```
- [Instructions to build VS2017-Win16 images](docs/vs2017.md)
```
**Expected behavior**
A link that works

**Actual behavior**
404 error

**Image impacted**
None

**Comment by DavidStaheli** [comment]
@jwillemsen thank you for reporting this!  It is now fixed.
