### ISSUE TITLE
Windows-2019 needs CMake version >=3.14.0

### ISSUE THREAD

**Issue by blowekamp** [Microsoft/azure-pipelines-image-generation#754]
**Describe the bug**
Make 3.13.4 does not have the "Visual Studio 16 2019" Generator. CMake version 3.14.0 is required.

**Image impacted**
Windows-2019

**Comment by schultetwin1** [comment]
It looks like the version of cmake in windows-2019 depends on the version of cmake in chocolately when the VM image is built.

https://github.com/Microsoft/azure-pipelines-image-generation/blob/2546f4792c559cd8cabcfde51e33d2b2651d06dd/images/win/scripts/Installers/Install-Cmake.ps1#L1-L7

Looking at the [cmake feed on chocolatey](https://chocolatey.org/packages/cmake) CMake 3.14 is now in that feed. That feed was updated March 14. Therefore the latest [VS2019 release](https://github.com/Microsoft/azure-pipelines-image-generation/releases/tag/vs2019%2F149.2), released today should include CMake 3.14.

That being said, the release notes for the latest [VS2019 release](https://github.com/Microsoft/azure-pipelines-image-generation/releases/tag/vs2019%2F149.2) don't mention CMake being updated. @vijayma can you confirm if that release also updated CMake to 3.14?

**Comment by harrysummer** [comment]
I was trying to build a personal project just now using the Hosted Win2019 with VS2019. And the cmake is still not supporting VS2019.

**Comment by jwillemsen** [comment]
Can confirm that the Hosted Win2019 doesn't have CMake 3.14, we can't use the Visual Studio 16 2019 generator, see https://github.com/objectcomputing/OpenDDS/pull/1053

**Comment by BrianMouncer** [comment]
This is an issue for my project as well.
I would like to move up to the hosted VS 2019 agent pools, but we use CMake for our daily CiCd process, so not having CMake 3.14 or higher makes all the newer vs 2018 agents useless for us.

They are also missing the windows desktop ARM/ARM64 compiler tools and Win 10 SDK workd loads, but the is a separate blocking issue.  

Please update the version of CMake ASAP.

Thanks....

**Comment by seanmiddleditch** [comment]
Just converted over to the new images (and also converted to using Ninja so this issue wouldn't be relevant anyway), but in my build scripts I'm seeing:

```
> cmake --version
cmake version 3.14.1
```

Looks like it's updated and this issue is out of date? (I know it definitely wasn't updated a couple weeks ago, so I'm guessing it's a recent image deployment.)

**Comment by scpeters** [comment]
yeah, I'm seeing cmake 3.14 in the `windows-2019` `vmimage`s too. I think this can be closed now

**Comment by BrianMouncer** [comment]
What about ARM64 build tools.
Did the new images pickup these too?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by blowekamp** [comment]
The latest `windows-2019` image has the required CMake 3.14.1 to use MSVC 2019. My project no longer needs to use chocolatey to install the latest CMake.
