### ISSUE TITLE
Issue with marketplace modules and loading and extended type date file

### ISSUE THREAD

**Issue by scott1138** [Microsoft/azure-pipelines-image-generation#755]
I have two Azure DevOps extensions I got from the market place and they were working yesterday but today I am getting this non-terminating error on both of them:

##[error]The following error occurred while loading the extended type data file: Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.Abstractions.IAzureContextContainer": The TypeConverter was ignored because it already occurs.

It appears to be happening before the task even executes and it actually completes successfully but because an error is written back to the pipeline it fails to continue to the next step.

**Comment by DavidStaheli** [comment]
Hi Scott, thank you for reporting this and I'm sorry for not replying until now.  To get the right people looking into it, could you please post it on the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)?  That will route it to the right team.
