### ISSUE TITLE
Unable to run C++ tests on vs2015-win2012r2 image due to issue loading ole32.dll

### ISSUE THREAD

**Issue by peetw** [microsoft/azure-pipelines-image-generation#761]
**Describe the bug**
As part of our CI build on Azure Pipelines, we run some C++ unit tests. The unit tests are written using Google Test and are compiled into EXEs. Most of the unit test EXEs run fine. However, one of the them fails to run (it exits with error code -1073741511 when running using cmd.exe).

Looking at the Dependency Walker report for the failing EXE (generated during the CI build on the hosted agent), it appears that the reason for this failure is that one the dependencies (`C:\Windows\System32\ole32.dll`) cannot be loaded since it (`ole32.dll`) is trying to import the following (non-existent) functions from `api-ms-win-core-com-private-l1-1-0.dll`:

  * InternalIrotEnumRunning2
  * InternalIrotGetObject2
  * InternalIrotGetTimeOfLastChange2
  * InternalIrotIsRunning2

However, `api-ms-win-core-com-private-l1-1-0.dll` only exports the above functions without the trailing '2' in the function name.

**Expected behavior**
`ole32.dll` loads without issue. On a local (i.e. non-hosted) Win Server 2012 R2 VM, `ole32.dll` does indeed load correctly (the functions it tries to import from `api-ms-win-core-com-private-l1-1-0.dll` do not have the trailing '2' in the function name).

**Actual behavior**
A description with steps to reproduce the issue.

1. Load `ole32.dll` in Dependency Walker (x64) on the vs2015-win2012r2 hosted agent image

I have attached a Dependency Walker (x64) image file for `ole32.dll`, generated on a vs2015-win2012r2 hosted agent: [DepWalkerReport.zip](https://github.com/Microsoft/azure-pipelines-image-generation/files/2936553/DepWalkerReport.zip)

**Image impacted**
vs2015-win2012r2

**Comment by DavidStaheli** [comment]
@peetw, thank you for reporting this.  The vs2015-win2012r2 image receives little-to-no maintenance now.  Are you able to move to the VS2017/Win2016 or VS2019/Win2019 image?

**Comment by peetw** [comment]
@DavidStaheli Unfortunately we are stuck with the vs2015-win2012r2 image for this project (due to other dependencies). It is odd that this issue appears to be with the system DLLs though.

**Comment by DavidStaheli** [comment]
Got it.  Thank you for investigating it so thoroughly and for the helpful repro steps.

**Comment by cltshivash** [comment]
Are you sure you aren't running into the pitfalls called out here ? https://ofekshilon.com/2016/03/27/on-api-ms-win-xxxxx-dll-and-other-dependency-walker-glitches/

**Comment by joebourneMS** [comment]
Peet, can you detail the dependencies that you're missing that keep you on the vs 2015 image? If there are gaps I'd like to close them with the 2017/2019 images.

**Comment by peetw** [comment]
> Are you sure you aren't running into the pitfalls called out here ? https://ofekshilon.com/2016/03/27/on-api-ms-win-xxxxx-dll-and-other-dependency-walker-glitches/

@cltshivash Fairly certain. I'm already aware of those pitfalls and normally ignore any warnings relating to the API sets. However, in this case, DependencyWalker is actually reporting it as an error (not a warning). Furthermore, I am able to run my test EXE without issue (and DependencyWalker does not show an error) on a fresh, self-hosted Win Server 2012 R2 VM using the same steps as listed in my Azure Pipelines YAML file.

> Peet, can you detail the dependencies that you're missing that keep you on the vs 2015 image? If there are gaps I'd like to close them with the 2017/2019 images.

@joebourneMS For this project, we must compile with VS 2015 due to C++/CUDA (we are currently limited to CUDA 8.0, which is itself limited to the VS 2015 VC++ 14 compiler; see [here](https://docs.nvidia.com/cuda/archive/8.0/cuda-installation-guide-microsoft-windows/index.html#system-requirements)).

**Comment by peetw** [comment]
Bump to prevent auto-close

**Comment by PBoraMSFT** [comment]
Removing my assignment so that an appropriate ecosystem owner can be assigned.

**Comment by kaylangan** [comment]
Thanks for the feedback. We are no longer updating the VS2015 image.

**Comment by peetw** [comment]
Issue was fixed after upgrading to the VS 2017 image
