### ISSUE TITLE
Support managed image since VHD is being depricated in packer

### ISSUE THREAD

**Issue by tehho** [Microsoft/azure-pipelines-image-generation#765]
**Describe the bug**
"Warning: You are using Azure Packer Builder to create VHDs which is being deprecated, consider using Managed Images. Learn more http://aka.ms/packermanagedimage"

**Expected behavior**
use managed disk as in your tutorial: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/build-image-with-packer

**Actual behavior**
Get warning message about deprecated process
1. Step 1
Add this json to builders:
            "managed_image_name": "{{user `image_name`}}-{{user `image_version`}}",
            "managed_image_resource_group_name": "{{user `resource_group`}}",
2. Step 2
Add this json to variables:
  "image_name": "{{env `ARM_IMAGE_NAME`}}",
  "image_version": "{{env `ARM_IMAGE_VERSION",`}}

**Image impacted**
Windows 2015,2017,2019,Container
Probably Linux aswell.

**Comment by joebourneMS** [comment]
Similar to my feedback on the other issue. This seems to be related to you building the images, which isn't something we'll support in our repo here. Let me know if forking this repo and making the changes you need doesn't work for you 👍
