### ISSUE TITLE
 Warning: Use Cipheriv for counter mode of aes-256-ctr on Hosted VS2017

### ISSUE THREAD

**Issue by SamirFarhat** [Microsoft/azure-pipelines-image-generation#775]
**Describe the bug**
When running a deployment (Azure App Service Deploy), there is a warning that keep logging every few seconds. Look like the VS 2017 hosted agent node version needs to be updated

**Expected behavior**
No warnings
**Actual behavior**
Use the "Azure App Service Deploy" task to deploy an Azure Function for example, you will hit repetitive Warnings:
(node:796) Warning: Use Cipheriv for counter mode of aes-256-ctr
![image](https://user-images.githubusercontent.com/14938496/54071694-b7dd1300-4270-11e9-85c3-ad67381cd782.png)

**Image impacted**
Hosted VS2017

**Comment by damianun** [comment]
Same happening on **Hosted Windows 2019 with VS2019**

**Comment by DavidStaheli** [comment]
Thanks for reporting this, @SamirFarhat.  I believe it has been fixed.  @vtbassmatt and @joebourneMS can you confirm?

**Comment by vtbassmatt** [comment]
We rolled out an agent change which caused this warning on many of our in-box tasks. We're rolling back that change -- sorry for the inconvenience. ETA is later this week for most customers. Ring 5 could bleed into next week if we're unlucky.

In the meantime: the warning itself is harmless, and your builds shouldn't be impacted.
