### ISSUE TITLE
cmake.sh should always install the latest version (Ubuntu)

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/azure-pipelines-image-generation#785]
cmake.sh installs an old version. It should always install the latest.
https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/linux/scripts/installers/cmake.sh
https://cmake.org/download/

**Comment by themightyoarfish** [comment]
The old cmake version has bitten me. One must manually install a newer one, and take care that it installs to /usr/local, and not somewhere else, in order to override the builtin one.
