### ISSUE TITLE
Add 'Az' Azure PowerShell Module to Azure DevOps Linux Hosted Build Agent image (Ubuntu 16.04)

### ISSUE THREAD

**Issue by cbellee** [microsoft/azure-pipelines-image-generation#786]
**Tool infomation**
- Tool name: 'Az' Azure PowerShell module
- Add or update? Add
- Desired version: 1.5.0+
- If this is an add request:
  - Brief description of tool: Cross-Platform .Net Core 'Az' Azure PowerShell module
  - URL for tool's homepage: https://github.com/Azure/azure-powershell

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [x ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ x] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
Azure Devops Hosted Linux Image -> Ubuntu 16.04

**Comment by johncrim** [comment]
For anyone that comes across this issue, and needs an immediate fix, here's what I've done to use the Az modules in DevOps Ubuntu 16.04 agents:

https://stackoverflow.com/a/55435794/605067

**Comment by 20shivangi** [comment]
@johncrim We have updated the hosted agent images with Az powershell modules.

**Comment by dirkslab** [comment]
@20shivangi does not seem to be on the latest version of ubuntu. If you have any more detail on this, I would appreciate.

had to use Install command to install az.
Install-Module Az -Force -AllowClobber

**Comment by johncrim** [comment]
That's great @20shivangi - thank  you.

**Comment by dirkslab** [comment]
> @20shivangi does not seem to be on the latest version of ubuntu. If you have any more detail on this, I would appreciate.
> 
> had to use Install command to install az.
> Install-Module Az -Force -AllowClobber

@20shivangi Please can you assist

**Comment by 20shivangi** [comment]
@dirkslab Which version of Az module do you want ?

**Comment by dirkslab** [comment]
Thanks @20shivangi,

Latest available version according to docs, should be fine. Maybe just
outline how to utilize the released versions?
https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/linux/Ubuntu1804-README.md


   - Az Module (1.0.0)
   Az Module (1.6.0)
   Az Module (2.3.2)
   Az Module (2.6.0)

**Comment by reyou** [comment]
I am having same issue with `Ubuntu 16.04.6 LTS` and following task fails: `AzurePowerShell@5` and latest version installed of the module is  `az_2.6`.

Can you please help?

**Comment by reyou** [comment]
Hey @johncrim, I tried your script, but I am still getting error like below;

![image](https://user-images.githubusercontent.com/6571483/71392886-76371200-25cf-11ea-8fe0-c494d8fecbfc.png)

and when I print `user` folder I have following `az` versions.

![image](https://user-images.githubusercontent.com/6571483/71392908-923ab380-25cf-11ea-87a9-326f33a3a6e8.png)

Do you have an idea how to fix this one?

**Comment by 20shivangi** [comment]
@reyou 
I tried the task AzurePowerShellV5 on Hosted Ubuntu, it is not showing any error.
Please share the debug logs by setting variable system.debug to true in your pipeline.

**Comment by dirkslab** [comment]
@reyou please see https://github.com/microsoft/azure-pipelines-image-generation/issues/1208#issuecomment-528333866

Looks like there is a big "assume every body knows" part, that never gets mentioned.
Let me know if this help or if you need a more in detail example.

**Comment by reyou** [comment]
In my case I was trying to stop/delete a running WebJob.
So, I was trying to run `Stop-Process -Name 'cmd'` command at remote/azure machine.

Instead of doing this, as a workaround I am running $PS script on agent to call WebJob Rest API to stop/delete WebJob.

I may try what you suggested as well.

**Comment by 20shivangi** [comment]
@reyou Please share the debug logs by setting variable system.debug to true in your pipeline.

**Comment by reyou** [comment]
@20shivangi here is the output:

`##[debug]Agent.Version=2.163.1
##[debug]agent.tempDirectory=/home/vsts/work/_temp
##[debug]check path : /home/vsts/work/_temp
##[debug]which 'pwsh'
##[debug]found: '/usr/bin/pwsh'
##[debug]which '/usr/bin/pwsh'
##[debug]found: '/usr/bin/pwsh'
##[debug]which '/usr/bin/pwsh'
##[debug]found: '/usr/bin/pwsh'
##[debug]/usr/bin/pwsh arg: -NoLogo
##[debug]/usr/bin/pwsh arg: -NoProfile
##[debug]/usr/bin/pwsh arg: -NonInteractive
##[debug]/usr/bin/pwsh arg: -ExecutionPolicy
##[debug]/usr/bin/pwsh arg: Unrestricted
##[debug]/usr/bin/pwsh arg: -Command
##[debug]/usr/bin/pwsh arg: . '/home/vsts/work/_temp/ce70553d-7d4b-428d-9dae-204551ea541b.ps1'
##[debug]exec tool: /usr/bin/pwsh
##[debug]arguments:
##[debug]   -NoLogo
##[debug]   -NoProfile
##[debug]   -NonInteractive
##[debug]   -ExecutionPolicy
##[debug]   Unrestricted
##[debug]   -Command
##[debug]   . '/home/vsts/work/_temp/ce70553d-7d4b-428d-9dae-204551ea541b.ps1'
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command . '/home/vsts/work/_temp/ce70553d-7d4b-428d-9dae-204551ea541b.ps1'
Could not find the module path with given version.
At /home/vsts/work/_tasks/AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62/5.162.1/Utility.ps1:42 char:17
+ ...             throw ("Could not find the module path with given version ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Could not find the \u2026with given version.:String) [], RuntimeException
+ FullyQualifiedErrorId : Could not find the module path with given version.
 
##[debug]Exit code 1 received from tool '/usr/bin/pwsh'
##[debug]STDIO streams have closed for tool '/usr/bin/pwsh'
##[debug]task result: Failed
##[error]PowerShell exited with code '1'.
##[debug]Processed: ##vso[task.issue type=error;]PowerShell exited with code '1'.
##[debug]Processed: ##vso[task.complete result=Failed;]PowerShell exited with code '1'.
Finishing: Stop-WebJobs-Process`

Visual:

![image](https://user-images.githubusercontent.com/6571483/71461034-fbf3c280-2773-11ea-8369-92f9f0f0ecd9.png)

**Comment by 20shivangi** [comment]
@reyou 
Did you try this :
$env:PSModulePath = "/usr/share/az_2.6.0:" + $env:PSModulePath;

**Comment by 20shivangi** [comment]
@reyou 
From the logs attached, you have selected option specify other version and not provided any value of version.
2019-12-26T06:08:00.8649845Z ##[debug]TargetAzurePs=OtherVersion
2019-12-26T06:08:00.8650180Z ##[debug]CustomTargetAzurePs=null

Please use the latest installed version option, the task should run successfully.

**Comment by 20shivangi** [comment]
@reyou Any update ?

**Comment by reyou** [comment]
This seems like working now (for another pipeline I tried)
I will let you know if any problem occurs.
Thanks.

**Comment by 20shivangi** [comment]
Closing this issue, feel free to reopen if face any.
