### ISSUE TITLE
Update Ansible to latest version in ado Linux server build

### ISSUE THREAD

**Issue by chadhellyea** [microsoft/azure-pipelines-image-generation#788]
Please pip upgrade Ansible to latest version for the ADO Linux pool server.

**Comment by chadhellyea** [comment]
Looking at the script for ansible install, it looks like it is using apt-get to install ansible instead of pip. So it could go 2 ways. Either shange to install ansible via pip, or update via apt.

**Comment by chadhellyea** [comment]
created PR to fix this: https://github.com/Microsoft/azure-pipelines-image-generation/pull/824

**Comment by kaylangan** [comment]
Closing since fixed in #284.
