### ISSUE TITLE
Add 7zip on macOS

### ISSUE THREAD

**Issue by vtbassmatt** [microsoft/azure-pipelines-image-generation#791]
**Tool infomation**
- Tool name: 7zip
- Add or update? add
- Desired version: latest
- If this is an add request:
  - Brief description of tool: compressed file utility, used in ExtractFiles and ArchiveFiles tasks
  - URL for tool's homepage: https://7-zip.org

Already exists on Windows and Ubuntu images (added in #721), should be added to Mac as well.

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [x] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [x] Other

**Image impacted**
macos-10.13

**Comment by ravitej-senseon** [comment]
May I ask why the masOS image definition (packer json) is not stored in this repository? I mean Windows and Linux image definitions are part of this repository. It would make it easy to submit PRs for macOS image updates as well of course, after reading the contribution guide!

**Comment by nrajpurkar** [comment]
Hey @ravitej-senseon, thanks for pointing that out. Some different sets of people worked on the separate images before they came together and this is one of the differences that remained. We're discussing open-sourcing these at the moment.

**Comment by ravitej-senseon** [comment]
Hey @nrajpurkar, thanks for getting back to me promptly. That's wonderful news. Any estimates of how long that might be? We are looking to setup on-prem macOS build agents for Azure Pipelines because of some challenges with secrets. It would be really wonderful to be able to base our on-prem build agents on official Microsoft Hosted macOS build agents and make the necessary changes. And also, it would be much easier to request add/update features/tools to existing agent images by way of PRs going forward.

**Comment by nrajpurkar** [comment]
@ravitej-senseon I don't have an ETA to share at this moment unfortunately

**Comment by ravitej-senseon** [comment]
:cry:

**Comment by ihnorton** [comment]
Please reopen, 7-zip is still not available on macOS.

**Comment by vtbassmatt** [comment]
This repo is no longer in use. You'll want to post in https://github.com/actions/virtual-environments

**Comment by ihnorton** [comment]
Hmm, I started to post an issue there but noticed the `10.15` image comes from here. Will post over there. Thanks.
