### ISSUE TITLE
Hosted VS2017 should have the vcpython27 Chocolatey package by default

### ISSUE THREAD

**Issue by brcrista** [Microsoft/azure-pipelines-image-generation#793]
This includes the VC++ libraries needed to compile C extensions for Python 2.7 on Windows.  You need to do this when precompiling wheels for Windows or when installing sdist packages that have C code.

See discussion on https://github.com/Microsoft/azure-pipelines-tasks/issues/9674

**Comment by brcrista** [comment]
Without it:

![image](https://user-images.githubusercontent.com/33549821/54557408-71cf3000-4991-11e9-8e47-06cc50d202b2.png)

**Comment by brcrista** [comment]
I looked into this and the package is no longer supported by Microsoft, so we don't want to depend on it.  Builds that need it can install with `choco install vcpython27 --yes`.

**Comment by asottile** [comment]
@brcrista whether or not it is supported that package **is necessary** to have a functioning python2.7 -- that azure pipelines doesn't provide a function python2 out of the box is a big problem for projects looking to use azure pipelines

**Comment by altendky** [comment]
If this isn't going to be provided then `UsePythonVersion` for py2 is only partially supported?  This really doesn't seem good.  I understand that py2 is going EOL and that it's going to be tough on all ends but it should either all be supported or not as opposed to some conditional extra we need to slip into only our Windows/py27 builds.  I strongly encourage Azure Pipelines over alternatives because it's the only option that does actually support all the platform/py-version combinations.  :|

**Comment by brcrista** [comment]
I understand the need for this.  I think caching will be the right solution for this problem rather than installing directly on the image.  It's currently in preview: https://docs.microsoft.com/azure/devops/pipelines/caching/

**Comment by asottile** [comment]
I don't see how caching helps here, a toolchain needs to be *installed* (unless you happen to know all the paths that it touches and the registry edits it makes you're not going to be able to cache that)

**Comment by brcrista** [comment]
I'm sorry, but I can't justify the maintenance cost of having the images carry it when Microsoft isn't supporting it anymore.  While I agree that this is an annoying issue, I haven't yet seen the data to indicate that it's that critical.

The hosted images are all about opportunity cost: each thing we install means there's something else we're not going to install.  We try to provide enough extensibility points that the set of pre-installed software isn't limiting.
