### ISSUE TITLE
On different Azure DevOps account, the list of MS hosted agents are not the same and it doesn't have Windows 2019 agent

### ISSUE THREAD

**Issue by eriawan** [microsoft/azure-pipelines-image-generation#796]
**Describe the bug**
On different Azure DevOps account, the list of MS hosted agents are not the same and it doesn't have Windows 2019 agent.

**Expected behavior**
Both of my Azure DevOps account should show the same list of agent, especially Windows .

**Actual behavior**
This is the screenshot on both account, using these steps:

1. Create CI on both accounts, using web designer
2. The listings are not the same

![image](https://user-images.githubusercontent.com/8773147/54593625-867af900-4a61-11e9-91d2-34200119812a.png)

**Image impacted**
I think the image impacted isn't related to this issue.

**Comment by eriawan** [comment]
Based on the screenshot, is this Windows 2019 agents aren't fully deployed on all Azure DevOps accounts?
If this is true, then the documentations about this should also mention this fact. 

IMHO, I would rather not announce the availability of this Windows 2019 agent if the deployment aren't fully available. And so does the documentation.

I have submitted this problem on Azure DevOps docs: MicrosoftDocs/vsts-docs#3683

**Comment by joebourneMS** [comment]
Our deployment of VS2019 has been fully complete for a while. Could you check something for me?

1. Look to see if the VS 2019 pool shows up in your **Organization settings** page for the account where you're not seeing it in the build definition drop down
`https://dev.azure.com/{your org}/_settings/agentpools`

2. Try and recreate the VS 2019 agent pool in the **Project Settings** for the project where it is missing.
https://dev.azure.com/{your org}/AzureDevOps/_settings/agentqueues

- Click new 'New Agent Pool'
- Select 'base on an existing organization agent pool
- Select VS 2019
- Confirm it's showing in your agent pools list

3. Try to recreate the pipeline

**Comment by eriawan** [comment]
hi @joebourneMS 

About this:

> Look to see if the VS 2019 pool shows up in your Organization settings page for the account where you're not seeing it in the build definition drop down
> https://dev.azure.com/{your org}/_settings/agentpools

Yes, I see it is available:

![image](https://user-images.githubusercontent.com/8773147/54659412-4caefe80-4b04-11e9-915a-21ef8e866c6f.png)

Thanks!

But for this:

> Try and recreate the VS 2019 agent pool in the Project Settings for the project where it is missing.
https://dev.azure.com/{your org}/AzureDevOps/_settings/agentqueues

- Click new 'New Agent Pool'
- Select 'base on an existing organization agent pool
- Select VS 2019
- Confirm it's showing in your agent pools list

I can't do the "_Select 'base on an existing organization agent pool_", because the option for "base on an existing organization agent pool" is always disabled:

![image](https://user-images.githubusercontent.com/8773147/54659602-1c1b9480-4b05-11e9-9dac-a7e1c166f5bb.png)

I have also checked my other account, and that "_Select 'base on an existing organization agent pool_" option is always disabled too.

Please help.

**Comment by joebourneMS** [comment]
Hey, issue is reopened until we figure this out. I see a warning in the background indicating you may have a permissions issue. Please take a read through the docs and ensure you have all the right permission levels: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops#creating-agent-pools

Another item to try would be from the FAQ on that page.

**I'm trying to create a project agent pool that uses an existing organization agent pool, but the controls are grayed out. Why?**
On the 'Create a project agent pool' dialog box, you can't use an existing organization agent pool if it is already referenced by another project agent pool. Each organization agent pool can be referenced by only one project agent pool within a given project collection.

**Comment by joebourneMS** [comment]
Also, can you provide us with your org name? I'm adding @alepauly to help investigate

**Comment by eriawan** [comment]
@joebourneMS 

Could I send you the organization name outside this issue using email?

**Comment by joebourneMS** [comment]
Of course. Please send to joe.bourne@microsoft.com

**Comment by Astrophizz** [comment]
I think the issue might be whether your user is in a group that has a User or Administrator role on the agent pool.
> Members of this role can use the project agent pool when authoring build or release pipelines.

[Agent Pools: Security of agent pools](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops#security)

**Comment by alepauly** [comment]
Closing, @eriawan please reach out if you are still having issues. Thanks!

**Comment by artemious7** [comment]
### On Aug 14 I was still able to use Hosted Windows 2019 with VS2019 agent pool, but it's not in the list:

![image](https://user-images.githubusercontent.com/16724889/63723265-aeb32300-c85d-11e9-9428-9ac43b871fb1.png)

### Though it's there in the list of project's agent pools:

![image](https://user-images.githubusercontent.com/16724889/63723298-bd99d580-c85d-11e9-8f7a-c46fa99ca3bf.png)

![image](https://user-images.githubusercontent.com/16724889/63723338-df935800-c85d-11e9-8107-e5dec7c54417.png)

![image](https://user-images.githubusercontent.com/16724889/63723364-f5a11880-c85d-11e9-93cb-3544384b9d0d.png)

**Comment by artemious7** [comment]
Now I get it. [Here they say ](https://developercommunity.visualstudio.com/content/problem/699404/build-agent-missing-hosted-vs-2017-agent-pool.html) that they moved all of them to Azure Pipelines agent pool.
