### ISSUE TITLE
vs2017-win2016 Python venv

### ISSUE THREAD

**Issue by greengumby** [Microsoft/azure-pipelines-image-generation#797]
Hi,

Trying to get a venv activated so that when i run below it will create the site-packages under the venv location.
- script: pip3 install -r requirements.txt 

What I notice is that it seems to ignore the venv and put them in the hostedtoolscache directory.

Any ideas?

**Comment by brcrista** [comment]
Could you share your YAML?  My guess is that you are activating the virtual env and installing packages in separate steps.  Remember that each step runs in its own process, so you would have to re-activate the environment.

That said, you probably don't need to create a virtual env on a hosted agent.  You're running on a VM that will get recycled when the job is done.

**Comment by brcrista** [comment]
Thanks.  Since you're in the virtual env, shouldn't you be using just pip instead of pip3?  You can check the bin directory of the env to see what's in there

**Comment by brcrista** [comment]
I am pretty sure this isn't a bug -- `pip3` is the one in PATH by default, `pip` should be virtual env's pip.  Feel free to reopen if you have more info.
