### ISSUE TITLE
LFS 2.7.1 doesn't include extra header from git config in requests

### ISSUE THREAD

**Issue by mitesch** [microsoft/azure-pipelines-image-generation#800]
**Describe the bug**
https://github.com/git-lfs/git-lfs/issues/3571
LFS 2.7.1 contains a bug which breaks authentication in later build tasks when using `Allow scripts to access the OAuth token`

**Expected behavior**
LFS can authenticate using the bearer token stored in the git config.
On Windows: It hangs forever on a password prompt
On Linux/Mac: It fails immediately because it couldn't find credentials

**Actual behavior**
Create a new empty build pointing to an LFS repository.
DO NOT check `Checkout files from LFS` on Get sources
DO check `Allow scripts to access the OAuth token` on the Agent job
Add a Command Line task that executes `git lfs fetch`
Run the build

**Image impacted**
Windows/Ubuntu/Mac

**Workaround**
Downgrade LFS to 2.6.1

On Windows add a task that runs:
```
git lfs --version
choco uninstall git
choco uninstall git.install
choco install git --version 2.20.1
git lfs --version
```

**Comment by juliobbv** [comment]
Hey @davidstaheli and @madhurig,

Is there an ETA to update the `git-lfs` version bundled with the Azure Pipelines images to 2.7.2? We got a report of a customer that hit this issue a few days ago 😢.

**Comment by kaylangan** [comment]
@juliobbv Git and Git LFS always pull latest with each image generation so the update is gated on the deployment timeline. Here's the status:

- **Mac**: updated, see [README](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md)
- **Ubuntu**: updated in M152 release, which has one more ring to go
- **Windows**: was updated in M152, but we're skipping that and releasing M153 instead. Should start this week.

**Comment by juliobbv** [comment]
Thanks @kaylangan for the status report! I'll let the affected customers know of the deployment timeline.

**Comment by DrBarnabus** [comment]
Just been affected by this issue using the windows-2019 image. Any news on when the update image will be rolled out?

**Comment by alepauly** [comment]
> Just been affected by this issue using the windows-2019 image. Any news on when the update image will be rolled out?

@DrBarnabus - can you please email me your Azure Pipelines org name to alpauly@microsoft.com so I can dig into it? All machines are reporting updated in the last 12 hours but I want to verify your build ran in the latest windows-2019 image. Thanks.
