### ISSUE TITLE
Please support 1903 for Windows Containers

### ISSUE THREAD

**Issue by AceHack** [microsoft/azure-pipelines-image-generation#802]
Please support 1809 for Windows Containers

Was asked to open this again.
https://github.com/Microsoft/azure-pipelines-image-generation/issues/656

**Comment by joebourneMS** [comment]
Thanks, we've got this on our backlog. No firm ETA quite yet

**Comment by martshaw** [comment]
@joebourneMS Any update on when this may happen?

**Comment by joebourneMS** [comment]
@martshaw We do not have an ETA on doing this upgrade yet, but in the meantime are you able to leverage the Windows 2019 image? Many of the Windows Container scenarios can be done there as well.

**Comment by adnan-kamili** [comment]
@thejoebourneidentity 

I tried using the Windows 2019, but it gets stuck indefinitely:


docker run -v d:\a\1\s':'d:\a\1\s -w d:\a\1\s -i cryptlex/vs2010-buildtools:latest d:\a\1\s/Packages/scripts/build.bat |  
-- | --
  | ========================== Starting Command Output =========================== |  
  | "C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "d:\a\_temp\5188def4-92c7-4145-b405-b39c40cbc326.cmd"" |  
  | Unable to find image 'cryptlex/vs2010-buildtools:latest' locally |  
 
  | d7e241535ad2: Waiting |  
  | 35ab8a3cedc1: Waiting |  
  | ec4d2246908e: Waiting |  
  | 14e21adc1c3d: Waiting |  
  | 4d6e6ca8295a: Waiting |  
  | a0a2bf98be3b: Waiting |  
  | a05d96fd1712: Waiting |  
  | 684007ab80f5: Waiting |  
  | d346635efe48: Waiting |  
  | d21d511aa9fb: Waiting |  
  | e29dfee49aca: Waiting |  
  | 8b6cd10143b2: Verifying Checksum |  
  | 8b6cd10143b2: Download complete |  
  | b7fd2ad0878d: Verifying Checksum |  
  | b7fd2ad0878d: Download complete |  
  | 3f52a73f7492: Verifying Checksum |  
  | 3f52a73f7492: Download complete |  
  | fbeadacaa688: Download complete |  
  | 877bc5161746: Verifying Checksum |  
  | 877bc5161746: Download complete |  
  | a4cedc97ee54: Verifying Checksum |  
  | a4cedc97ee54: Download complete |  
  | cbe256e37b0f: Verifying Checksum |  
  | cbe256e37b0f: Download complete |  
  | a632e7fa656f: Verifying Checksum |  
  | a632e7fa656f: Download complete |  
  | d8b44fb3139e: Verifying Checksum |  
  | d8b44fb3139e: Download complete |  
  | 7e8a9c31adf6: Verifying Checksum |  
  | 7e8a9c31adf6: Download complete |  
  | 643873566c7f: Verifying Checksum |  
  | 643873566c7f: Download complete |  
  | 5ad023c1c43b: Verifying Checksum |  
  | 5ad023c1c43b: Download complete |  
  | 8fe202d4e033: Verifying Checksum |  
  | 8fe202d4e033: Download complete |  
  | d7e241535ad2: Verifying Checksum |  
  | d7e241535ad2: Download complete |  
  | 35ab8a3cedc1: Verifying Checksum |  
  | 35ab8a3cedc1: Download complete |  
  | 0f6c17eeb854: Verifying Checksum |  
  | 0f6c17eeb854: Download complete |  
  | ec4d2246908e: Verifying Checksum |  
  | ec4d2246908e: Download complete |  
  | 4d6e6ca8295a: Verifying Checksum |  
  | 4d6e6ca8295a: Download complete |  
  | 14e21adc1c3d: Verifying Checksum |  
  | 14e21adc1c3d: Download complete |  
  | a05d96fd1712: Download complete |  
  | a0a2bf98be3b: Verifying Checksum |  
  | a0a2bf98be3b: Download complete |  
  | d346635efe48: Verifying Checksum |  
  | d346635efe48: Download complete |  
  | e29dfee49aca: Verifying Checksum |  
  | e29dfee49aca: Download complete |  
  | 684007ab80f5: Verifying Checksum |  
  | 684007ab80f5: Download complete |  
  | d21d511aa9fb: Verifying Checksum

**Comment by ssa3512** [comment]
This issue is not resolved - I am unable to build images on top of 4.8-windowsservercore-1930 (from here: https://github.com/microsoft/dotnet-framework-docker/)

##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(492,5): Error DT1001: Service 'xyz' failed to build: a Windows version 10.0.18362-based image is incompatible with a 10.0.17763 host

It seems the .NET 4.8 on windows 1803, 1903 ltsc-2016 and ltsc-2019 images are all currently supported base images for developing containerized .NET framework applications. It would seem to make sense that we should be provided the ability to build any of these with a hosted build agent.
