### ISSUE TITLE
Update Xcode

### ISSUE THREAD

**Issue by naknut** [Microsoft/azure-pipelines-image-generation#808]
**Tool infomation**
- Tool name: Xcode
- Add or update? Update
- Desired version: 10.2
- If this is an add request:
  - Brief description of tool: The latest version of Xcode
  - URL for tool's homepage: https://developer.apple.com/xcode/

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [X] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [X] Xamarin
- [ ] Other

**Image impacted**
Mac

**Comment by SeanAsby** [comment]
+1. Have customers awaiting our SDK built with Xcode 10.2

**Comment by alombard** [comment]
+1 - Hi there we have builds waiting to go out with 10.2 as well.  Thanks in advance for looking at this!

**Comment by nrajpurkar** [comment]
Related to #300 as Xcode 10.2 only builds on Mojave. We're working on getting this out ASAP!

**Comment by snap608** [comment]
Ouch.. Really stuck due to this. Hopefully the changes in Swift 5 compiler with ABI will help us in the future.

**Comment by nrajpurkar** [comment]
macOS Mojave is now available with Xcode 10.2 (and some prior versions) installed! Check out how to [switch to Mojave](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent) and the [compatible Xcode versions](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md#xcode) available.
