### ISSUE TITLE
Add Azul Zulu Java 12 (macOS)

### ISSUE THREAD

**Issue by DavidStaheli** [microsoft/azure-pipelines-image-generation#811]
Java 12 is in preview, but has significant features.
https://www.azul.com/downloads/azure-only/zulu/

**Comment by nrajpurkar** [comment]
macOS images now use [Azul Zulu OpenJDKs](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md#image-changes)
