### ISSUE TITLE
Add Azul Zulu Java 12 (Windows)

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/azure-pipelines-image-generation#812]
Java 12 is in preview, but has significant features.
https://www.azul.com/downloads/azure-only/zulu/
So far, the JDK is only available as an .MSI, but our scripts rely on a .zip.

**Comment by fthevenet** [comment]
This would be great if this could be looked at, as the Windows image is the only one that doesn't provide a Java 12 JDK at the moment.
For multi-platform projects that target Java 12, the workaround is currently to deploy a new JDK for each build (I use chocolatey for that, for instance) which makes building on Windows significantly longer that on macOS or Linux.

**Comment by kaylangan** [comment]
@davidstaheli any chance we might add this soon-ish?

**Comment by davidstaheli** [comment]
I'm hopeful we can add JDK 12 to the Windows image soon.  The delay is because Azul has [provided it](https://repos.azul.com/azure-only/zulu/packages/zulu-12) as an .MSI installer, but not as a .zip file like they have for other JDK versions and which our [image scripts](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/win/scripts/Installers/Install-JavaTools.ps1) use.
