### ISSUE TITLE
Xcode 10.2

### ISSUE THREAD

**Issue by avetyansos** [Microsoft/azure-pipelines-image-generation#815]
**Tool infomation**
- Tool name: <Xcode>
- Add or update? <Update>
- Desired version: <10.2>
- If this is an add request:
  - Brief description of tool: <I am trying to build swift 5 files with newest version of Xcode and cannot build because in Devops center there aren't any Xcode 10.2 Please Update>
  - URL for tool's homepage: <https://developer.apple.com/xcode/>

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [V ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
Add the appropriate label for the image or images that should be updated (e.g., mac, ubuntu, window).

**Comment by bazscott** [comment]
To be honest, given the amount of money we pay MS for this service, it's very disappointing they are not on top of this on the day the new version of Xcode comes out - it shouldn't take people raising issues to get things updated.

**Comment by nathan-alden-hp** [comment]
> To be honest, given the amount of money we pay MS for this service, it's very disappointing they are not on top of this on the day the new version of Xcode comes out - it shouldn't take people raising issues to get things updated.

Apparently we're not paying enough.

**Comment by nrajpurkar** [comment]
Hi folks, copy of #808 and related to #300 as Xcode 10.2 only builds on Mojave. We're working hard on getting this out ASAP!

**Comment by mtrossbach** [comment]
Hi all, we are really in need of Swift 5 / Xcode 10.2, too!

**Comment by zamboOlino** [comment]
It would be great to have the new Xcode 10.2 because need an update to Swift 5 :)

**Comment by mcguire-james** [comment]
@nrajpurkar Any update on this? It's April already and no sign of macOS 10.14 Mojave, Xcode 10.2 and Swift 5. This is an urgent need for us as well. Especially considering the Xcode 10.2 beta has been out since Jan and macOS 10.4 Mojave has been stable since September 2018.

**Comment by alombard** [comment]
If there's anything I can do to assist in testing - please let me know.  This is huge for us too - thanks again for your efforts.

**Comment by christoff-1992** [comment]
> If there's anything I can do to assist in testing - please let me know. This is huge for us too - thanks again for your efforts.

Ditto, if Azure pipelines is to be competitive against other CI solutions then it really needs to step up and implement the latest IDE testing against the beta so things are ready for general release on day one. More than happy to assist in testing etc if it helps in the efforts.

**Comment by adamayoung** [comment]
Is there any ETA on this yet? It's been 2 weeks since the release of Xcode 10.2 and Swift 5.

**Comment by adamayoung** [comment]
I've raised this issue on Microsoft's Service Hub as a Support Request to try and get a response as to when Xcode 10.2 will be available on macOS Build Agents.

**Comment by adamayoung** [comment]
Issue also raised in the Microsoft Visual Studio Developer Community:

https://developercommunity.visualstudio.com/content/problem/515994/install-xcode-102-on-hosted-macos-build-pipeline.html

**Comment by hewigovens** [comment]
@joebourneMS I think you should prepare when Xcode 10.2 was still in beta stage

**Comment by bazscott** [comment]
Yep, I agree @hewigovens. I've only been using Azure for about 6 months and this debacle has me seriously worried about how we we are going to get on between WWDC and the release of iOS 13.

**Comment by salbahra** [comment]
@bazscott agreed, last year we had to go without CI for months after WWDC and was really hoping Microsoft would pick up the pace this year around but doesn’t seem to be the case. Still holding out for an update this week though.

**Comment by nrajpurkar** [comment]
We generally aim for a quick turn-around when new software comes out. For instance we landed same day support for Xcode 10 GM after WWDC last year. We've been a little late with Xcode 10.2 due to some infrastructure changes that came in with macOS Mojave. We understand you're looking to jump on the latest and greatest as soon as updates are available and we will continue to work on our update speed. Appreciate the patience as we've been working diligently on getting this out.

**Comment by allenhumphreys** [comment]
All the other CIs I’ve used for Apple products have provided images containing the Xcode betas and have kept them updated throughout the beta cycle. They all suffered a delay when they needed to roll out a new OS system image to support the new Xcode, but the delay only affected people who wanted to use the beta in CI, which is a subset of users.

**Comment by koystinen** [comment]
Today our iOS builds suddenly broke with an error: "module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler:". Which was a sign that hosted mac agents got updated with Xcode 10.2. So thank you, Microsoft for getting it done. so quickly!

If anyone would like to stay on 10.1 Xcode version for compatibility sake, it could be done by changing the Build Step property "XCode version" from "Xcode 10" to "Specify path", and setting "Xcode developer path" to /Applications/Xcode_10.1.app

**Comment by nrajpurkar** [comment]
macOS Mojave is now available with Xcode 10.2 (and some prior versions) installed! Check out how to [switch to Mojave](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent) and the [compatible Xcode versions](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md#xcode) available.
