### ISSUE TITLE
Add Windows 8.1 SDK (Windows)

### ISSUE THREAD

**Issue by nathan-alden-hp** [microsoft/azure-pipelines-image-generation#817]
Right now I can't build my Visual C++ DLL solutions on the `windows-2019` image because it apparently doesn't contain the Windows 8.1 SDK. I didn't have this issue with the `vs2017-win2016` image. I am targeting 17763 (RS 5).

```
##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VC\v150\Microsoft.Cpp.WindowsSDK.targets(46,5): Error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".
```

**Tool infomation**
- Tool name: Windows 8.1 SDK
- Add or update? Add
- Desired version: Latest

**Areas and ecosystems**
- [ ] Android
- [x] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
`windows-2019`

**Comment by ransagy** [comment]
I've come across the same issue; Is there a way to add the SDK in a pipeline?

**Comment by nevyn** [comment]
Same here, requesting the same fix.
