### ISSUE TITLE
Document Azul 12 with ubuntu

### ISSUE THREAD

**Issue by mercer** [Microsoft/azure-pipelines-image-generation#819]
Is Azul 12 actually shipped with ubuntu image? Documentation doesn't reflect this, however it seems that java_tool.sh installs it.

Also, a question, how do I get the newer  image? Is it automatically provisioned? We're using the hosted agents with Azure DevOps.

Also, the second question, I'm interested in using Azul 12, so, if not yet shipped, then is there a plan to ship it?

![image](https://user-images.githubusercontent.com/95358/55411545-7e957b80-556e-11e9-87fc-b9c4aa6234b4.png)

**Comment by DavidStaheli** [comment]
Hi @mercer, yes Azul 12 will soon be on the Ubuntu, macOS, and Windows images.  It's already been added to the Ubuntu image, but the images currently deploy every 3 weeks.  You can follow the releases here (watch --> releases):  https://github.com/Microsoft/azure-pipelines-image-generation/releases
