### ISSUE TITLE
Server Core Docker image cached on Windows-2019 image does not match kernel version (latest tag is pointing to Server 2016 and not 2019)

### ISSUE THREAD

**Issue by joebourneMS** [microsoft/azure-pipelines-image-generation#820]
At a quick glance it looks like the windowsservercore docker image ‘latest’ tag is still using Server 2016.
 
In the short term, we should use the ‘1809’ tag so the VS 2019 hosted image includes the server 2019 base docker image

**Comment by ds-ms** [comment]
This has been updated here: https://github.com/microsoft/azure-pipelines-image-generation/pull/956
