### ISSUE TITLE
UseRubyVersion task fails on hosted macOS image (no versions of Ruby in the tool cache)

### ISSUE THREAD

**Issue by willsmythe** [microsoft/azure-pipelines-image-generation#834]
**Describe the bug**
The `UseRubyVersion` task fails on the hosted macOS image (no Ruby tools in the cache), but works as expected on the hosted Ubuntu and Windows (VS2017) images. Here is how the task is defined:

YAML:
```yaml
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.4'
  displayName: Install Ruby
```

**Expected behavior**
This `UseRubyVersion` task, which is in a shared step template, should work consistently across all hosted images (i.e. hosted macOS should not behave differently from the hosted Ubuntu and Windows images).

**Actual behavior**
On the hosted macOS image, the step fails with this message:

```
##[error]Version spec >= 2.4 for architecture %s did not match any version in Agent.ToolsDirectory.
Available versions: /Users/vsts/hostedtoolcache

```

For a simple repro of this, see: https://github.com/willsmythe/azure-pipeline-playground/tree/ruby-task-issue

**Image impacted**
macOS-10.13

**Comment by nrajpurkar** [comment]
Thanks @willsmythe, we're taking a look at this.

**Comment by nrajpurkar** [comment]
This has been fixed.
