### ISSUE TITLE
Status of Azure Pipelines Agent images

### ISSUE THREAD

**Issue by pascalberger** [microsoft/azure-pipelines-image-generation#835]
What is the status of the [Azure Pipelines Agent images](https://hub.docker.com/_/microsoft-azure-pipelines-vsts-agent) published to Docker Hub? They seem to not have received an update for several months including no update to Azure DevOps Server 2019, and the linked GitHub repository has been marked as deprecated and points to this repository.

Are these images still supported or what is the way forward to run Azure Pipelines Agents in a Docker container?

**Comment by vtbassmatt** [comment]
That Docker image was never really "correct", and we've deprecated it. (I'm sorry to see that it's not clearly marked as such on Docker Hub, and I'll see if I can get that corrected.)

The path forward is documented here: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops
