### ISSUE TITLE
cmake picking up GCC toolset instead of MSVC

### ISSUE THREAD

**Issue by devhawk** [microsoft/azure-pipelines-image-generation#836]
Running CMake inside of a VS CMD prompt on the hosted VS 2017 build image picks up chocolatey installed GCC compiler instead of MSVC. 

Project Repo: http://github.com/Microsoft/xlang
Example build: https://dev.azure.com/msft-xlang/public/_build/results?buildId=1354
executed build commands:
``` cmd
set vswherepath="%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"
for /f "usebackq delims=" %%i in (`%vswherepath% -latest -property installationPath`) do (
  if exist "%%i\Common7\Tools\vsdevcmd.bat" (
    call "%%i\Common7\Tools\vsdevcmd.bat"
    cmake ./src -B_build -GNinja -DCMAKE_INSTALL_PREFIX=install -Wno-dev
    ninja -C _build install -v
  )
)
```
Build Logs: [log_5_1354.zip](https://github.com/Microsoft/azure-pipelines-image-generation/files/3049174/log_5_1354.zip)

**Comment by lukka** [comment]
@devhawk that is because the usage of the Ninja generator, you need to use the VS generator to pick msvc instead. Running in vsdevprompt does not help, but you could work around this by passing to CMake the paths to cl.exe you want to use.
