### ISSUE TITLE
Add VC++ 14.0 compiler tools to Windows images

### ISSUE THREAD

**Issue by brcrista** [microsoft/azure-pipelines-image-generation#837]
**Tool infomation**
- Tool name: VC++ 14.0 (VS2015 C++ compiler)
- Add or update? add

**Areas and ecosystems**

- [ ] Android
- [x] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
VS2017

I've gotten feedback that many projects are still using the VS2015 image for its C++ compiler tools.  They need binary compatibility with other code built with that compiler.  However, we are no longer investing in that image (no Python, no Chocolatey, etc.) and this is a big blocker for these projects.

I think the right fix is to provide the VC++ 14.0 tools on the VS2017 image.

**Comment by DavidStaheli** [comment]
# ❗️ 
This is blocking people.

**Comment by austin-jensen** [comment]
@DavidStaheli if we're removing the VS2015 image and want to to put the VC++ 14 tools on the VS2017 image are we going to limit it to just that or end up doing more work to put anything else that might have been different from the VS2015 image onto the VS2017 image?

**Comment by brcrista** [comment]
The VS2015 image doesn't have much on it.  Is there anything in particular you had in mind?
