### ISSUE TITLE
Document available versions of Boost 1.66.0 - 1.69.0 following #732 update

### ISSUE THREAD

**Issue by mloskot** [Microsoft/azure-pipelines-image-generation#845]
Apparently, the Linux and Windows images have been updated with latest 4 versions of Boost 1.66.0 - 1.69.0 in #732

But, the docs still list only Boost 1.69
* https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/linux/Ubuntu1604-README.md
* https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md
* https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2019-Server2019-Readme.md

Please, could this list be kept up to date more eagerly?

The 'silent' changes to AzP images do have potential to break builds e.g.
https://developercommunity.visualstudio.com/content/problem/525582/ubuntu-1604-image-changed-and-comes-with-usrlocals.html

**Comment by kaylangan** [comment]
After the PR you mentioned was merged, we [decided to add only Boost 1.69](https://github.com/Microsoft/azure-pipelines-image-generation/commit/0d6501cf3055f1a0c5117d485f363c4e6d107d56#diff-5413e45fcff9db8f778da6131b2a4ccc).

**Comment by mloskot** [comment]
I see. Thanks for the confirmation.

(I'm never sure if the snapshot of Microsoft repo(s) on GitHub are latest and what is actually deployed or they are just used as staging area, so I preferred to ask than rely on diffs.)
