### ISSUE TITLE
[doc] PATH: contains the location of Boost version

### ISSUE THREAD

**Issue by mloskot** [microsoft/azure-pipelines-image-generation#846]
The listings of software packages for the Windows images

* https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md
* https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2019-Server2019-Readme.md

include this statement for Boost:

> * PATH: contains the location of Boost version

What does it actually mean location of Boost is contained in `PATH`?
If this means Boost tools like `b2.exe` are in the `PATH`, then this statement should be re-phrased to make that dead clear.

**Comment by mloskot** [comment]
This is still a valid issue.

**Comment by kaylangan** [comment]
@gekeugen since you added the boost scripts, can you answer/clarify this?

**Comment by mloskot** [comment]
Bump. This is still a valid issue.
