### ISSUE TITLE
Add Microsoft Edge preview builds to hosted images

### ISSUE THREAD

**Issue by mustjab** [microsoft/azure-pipelines-image-generation#848]
**Tool infomation**
- Tool name: Microsoft Edge preview
- Add or update? Add
- Desired version: 74.1.96.24
- If this is an add request:
  - Brief description of tool: Microsoft Edge browser Chromium based
  - URL for tool's homepage: https://www.microsoftedgeinsider.com/en-us/ 

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [x] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
Windows

**Comment by vtbassmatt** [comment]
This isn't really "testing/code coverage" as we use it. If we had an ecosystem for generic "web programming", that's what it would be. This is basically installing another browser on the image.

**Comment by bahmutov** [comment]
Can we reopen this issue please? Now that Microsoft Edge has gone to general availability https://blogs.windows.com/windowsexperience/2020/01/15/new-year-new-browser-the-new-microsoft-edge-is-out-of-preview-and-now-available-for-download/ it would be nice to have it. We are adding built-in Edge support to Cypress.io test runner and would love to run sanity checks to make sure we are not releasing broken software.

**Comment by kaylangan** [comment]
@bahmutov Development has moved to https://github.com/actions/virtual-environments. Can you open up an issue there? Thanks!
