### ISSUE TITLE
Random docker engine errors in vs2017 agent

### ISSUE THREAD

**Issue by XaviOutside** [microsoft/azure-pipelines-image-generation#852]
Hi,

Sometimes we got an error when we try to execute docker in the pipeline. This is the error log:

`error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/build?...: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.`

We are using the agent pool: Hosted VS2017

The first step in the pipeline is docker build container and it was running ok for the last year but a week ago started to give some random errors (2 or 3 errors per day)

**Comment by XaviOutside** [comment]
Since Monday It seems is working fine again. Any update about it?

**Comment by dzoech** [comment]
Any updates on this? I'm currently experiencing this issue on every build with the Hosted VS2017 agent.

**Comment by bansalaseem** [comment]
We have fixed this in the latest code and the fix should get rolled out on Azure Devops in next 3 weeks.

**Comment by dzoech** [comment]
Thank you for the update. Since I get this error on every build, is there a workaround to build docker images on hosted windows agents?

**Comment by bansalaseem** [comment]
You can use a powershell script similar to one mentioned below to workaround the problem for next 3 weeks. 

- powershell: |
   $ServiceName = 'docker';
   $dockerService = Get-Service -Name $ServiceName
   
   if ($dockerService.Status -ne 'Running'){
     $ServiceStarted = $false
    }
   Else{
     $ServiceStarted = $true
   }
   
   while ($ServiceStarted -ne $true)
   {
      Start-Service $ServiceName
      write-host $dockerService.status
      write-host 'Service started'
      Start-Sleep -seconds 10
      $dockService = Get-Service -Name $ServiceName 
      if ($dockService.Status -eq 'Running')
      {
         $ServiceStarted = $true
      }
   }
   
   docker version
