### ISSUE TITLE
Azure DevOps Xamarin iOS Documentation...

### ISSUE THREAD

**Issue by tstivers1990** [microsoft/azure-pipelines-image-generation#853]
First, the link here is broken: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#how-can-i-manually-select-versions-of-tools-on-the-hosted-macos-agent

Second, this link claims the readme tells you "the Mono version that is associated with the Xamarin SDK version that you need." Yet it does no such thing.

Third, following the steps in this documentation simply doesn't work.

https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md#xamarin

**Comment by ncouraud** [comment]
@nrajpurkar - can we take a look at these docs?
