### ISSUE TITLE
Add setuptools (Python 3)

### ISSUE THREAD

**Issue by Naatan** [microsoft/azure-pipelines-image-generation#855]
**Tool infomation**
- Tool name: setuptools (Python 3)
- Add or update? add
- Desired version: 40.*
- If this is an add request:
  - Brief description of tool: setuptools is widely used by python packages
  - URL for tool's homepage: https://setuptools.readthedocs.io/en/latest/

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [x] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**

I imagine this would count for all images, but I'm affected by ubuntu atm.

**Further Info**

Currently installing a package which requires setuptools will fail, eg:

requirements.txt:

```
psutil == 5.6.1
```

Running `install -r requirements.txt` will result in 
```
Collecting psutil==5.6.1 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/2f/b8/11ec5006d2ec2998cb68349b8d1317c24c284cf918ecd6729739388e4c56/psutil-5.6.1.tar.gz (427kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named 'setuptools'
```

I can work around this by running `sudo apt-get install python3-setuptools`, but this adds a whopping 50 seconds to my build time.

**Comment by cbrnr** [comment]
As far as I can tell, `setuptools` is already installed on `ubuntu-16.04` after the `UsePythonVersion@0` task is executed (my log says `Found existing installation: setuptools 40.6.2`). I usually still upgrade afterwards with `pip install -U setuptools`.

**Comment by Naatan** [comment]
@cbrnr it's working for you when using Python 3, not 2.. ?

**Comment by cbrnr** [comment]
Yes, I'm using Python 3.

**Comment by cbrnr** [comment]
Here's my config: https://github.com/cbrnr/mnelab/blob/master/azure-template.yml

**Comment by Naatan** [comment]
Thanks @cbrnr, gonna give this a try next week. Maybe all I'm missing is the `UsePythonVersion@0` task.
