### ISSUE TITLE
Hosted macOS and Visual Studio 2019

### ISSUE THREAD

**Issue by arek-avanade** [Microsoft/azure-pipelines-image-generation#857]
Even though the hosted macOS agent has been updated to Mojave recently, it still contains old Visual Studio 2017, Xamarin and MSBuild. 

When can we expect an update of these tools to the latest? We've just started a new project with VS 2019 and Xamarin and we cannot build it on DevOps. Hope this can be addressed ASAP, since these are all Microsoft tools anyway.

**Comment by ncouraud** [comment]
Hey there - we're in the process of cutting an image with these tooling updates now - they should go out with the next image update.

**Comment by arek-avanade** [comment]
@ncouraud Thanks! Is there a specific date when the new image is going to be released? Like 4th Monday of the month (which would be April 22nd) as specified in your process schedule?

**Comment by arek-avanade** [comment]
@ncouraud @nrajpurkar Could you guys provide an ETA of that please?

**Comment by nrajpurkar** [comment]
@arek-avanade we're in the middle of the deployment process for the images with those updates at the moment. Barring no major issues, you should see this in a few days.

**Comment by nrajpurkar** [comment]
Current agents include:
- Visual Studio for Mac: 8.0.2.23
- Mono Version: 5.18.1
- Xamarin.iOS SDK Version: 12.6.0.25
- Xamarin.iOS SDK Version: 12.8.0.0
- Xamarin.Android SDK Version: 9.2.0-5
- Xamarin.Mac SDK Version: 5.6.0.25
- Xamarin.Mac SDK Version: 5.8.0.0
