### ISSUE TITLE
Update/Add Chrome and associated webdriver

### ISSUE THREAD

**Issue by sebastianhaas** [microsoft/azure-pipelines-image-generation#861]
**Tool infomation**
- Tool name: Chrome
- Add or update? Update
- Desired version: latest, always

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [x] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [x] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
Add the appropriate label for the image or images that should be updated (e.g., mac, ubuntu, window).
At least hosted VSTS 2017 and 2019.

Why can't we simply choose the version to use from configuration like on Travis CI? Why isn't it updated to the latest version automatically?
The installed Chrome version appears to be 5 months old. It is rather hard to try and match the installed version on my local machine. Same goes for webdriver.

**Comment by sebastianhaas** [comment]
Is there any news on this? I find it quite weird that the software on your images is updated once each month, but comes with a Chrome version that is more than half a year old.

Also, the funky way the image is provisioned with the static powershell scripts and firewall rules that prevent updates and further manual installations makes it kind of hard to update Chrome during build time.

**Comment by minichma** [comment]
Same here. People use this infrastructur for verifying, whether their code works with technology that their customers use (or will use). It's usually not so relevant to know, whether it works with technology that was used half a year ago. Please keep your tooling up to date!

**Comment by kaylangan** [comment]
We definitely want to keep this more up-to-date. I'm going to tentatively slate this feature for next week. 

The plan will be to replace the existing version with the [latest stable desktop version](https://chromereleases.googleblog.com/2019/04/stable-channel-update-for-desktop_30.html). We will drop the version that is currently installed.

**Comment by molant** [comment]
@kaylangan what is the plan going forward? Chrome updates at least once every 6 weeks and it seems like even the version is not the same across hosted agents:

| OS | Version |
| ----| -------|
| Ubuntu 1604 | 73.0.3683.86 |
| macOS High Sierra | N/A (see #250) |
| VS2017 | 71.0.3578.98 |

> that prevent updates and further manual installations makes it kind of hard to update Chrome during build time.

At least on macOS we can use `brew` to get the latest version, was shocked when `choco install googlechrome` didn't work 😞

**Comment by kaylangan** [comment]
> @kaylangan what is the plan going forward? Chrome updates at least once every 6 weeks and it seems like even the version is not the same across hosted agents:
> 
> OS	Version
> Ubuntu 1604	73.0.3683.86
> macOS High Sierra	N/A (see #250)
> VS2017	71.0.3578.98

The first set of work will be to update/install the latest stable Chrome version for Ubuntu 16.04, macOS 10.13, macOS 10.14, VS2017, and VS2019. For tools that are installed on multiple images, we want them to offer the same versions (obviously not currently the case).

In terms of updates after that, ideally we'd get the images updated _and deployed_ within week or so of a new update being released (recall, the current deployment cadence is every 3 weeks). We currently investing in process improvements that will help us deploy that frequently. We're just not there yet. 😄 

> At least on macOS we can use `brew` to get the latest version, was shocked when `choco install googlechrome` didn't work 😞

This sounds like a bug. Can you open an issue with details on the failure you're getting?

**Comment by molant** [comment]
I've opened https://developercommunity.visualstudio.com/content/problem/561830/cant-manually-upgrade-chrome-on-windows.html already, want me to do the same here?

**Comment by kaylangan** [comment]
@molant Developer Community is perfect. I've moved the ticket to the right team. In the absence of more timely updates to our hosted images, I agree you should have the ability to install a more recent version yourself.

**Comment by sebastianhaas** [comment]
Please don't forget about webdriver for Chrome when updating and thinking about an update process for the future. Webdriver and Chrome versions are somewhat tighlty coupled and the actual reason for this ticket was a webdriver bug (which are probably more frequent that bugs in Chrome itself) which I can't get rid of since I can't update the Chrome webdriver without updating Chrome as well.

**Comment by sebastianhaas** [comment]
@kaylangan apparently, between May 21 and May 23 you have updated both Chrome and the related webdriver. Without any notice, without any comment in this or other tickets and without any update to your readme which caused all of my builds to fail and took me two hours to investigate the reason. This is just not anything that I would expect to happen on a professional CI service. I am using both Travis and AppVeyor and never experienced something like that. The way you are retrieving software for your builds from some magic blob storage URI that somebody else is maintaining and updating is just severely broken (as @MatthewSteeples has explained in more detail in #628).

Don't get me wrong, it is fine to update software but 
* I need to be in control
* I need to at least have the chance to look up the version that is currently in used by other means than looking into your provisioning scripts, download binaries from some random blob storage of yours and inspect file details to find out the actual build number for basic software like a web browser on a CI image
* I need to be informed about the update cycle. No update for 6 months and then without any notice is not an option. How is it possible that versions of your image can change without any change to your repository? This is broken.

**Comment by kaylangan** [comment]
Hi @sebastianhaas,

I completely understand your frustration. One of our internal teams maintains that blob store and I've asked them to look into making the process more transparent. FYI @PBoraMSFT. 

We're in the midst of using a new release process. Previously, no release information was available so we're trying to make the process more visible. There has certainly been friction and there's definitely room to improve. Right now, we create candidate releases out of `releases/{image-name}/{release-tag}` and create a pre-release. Once the release has reached all rings, we update the README in master and mark the release as an official release. Of course, this process causes confusion as to when the latest release hits _your_ account. It's a bit hidden, but one way to find what tools are being used for your account is to check the Agent Pools tab (https://dev.azure.com/{your-org}/{your-project}/_settings/agentqueues), clicking on the particular image, then Details.

Some improvements that we plan to make:

- In the pre-release/release, post approximate dates for each ring.
- In the Agent Pools tab that I linked above, make it more obvious which release/tag your org is on.

We're definitely open to other suggestions that would make the experience better for you.

**Comment by DanielHabenicht** [comment]
I hope that's the right issue to comment on. 

My builds are suddenly failing since yesterday evening because of chrome not running in the same version as before and I think this issue is part of why.

Is there a way for me to verify if this is really my problem?
Is there a way I can tell which capabilities the Build Agent my previous (succeeding) Build did run on? (Everything I get in the build is the link to the agent queue, which does only contain the capabilities of the current Agents)
Can you provide a way to see which version of the Build Agent the build did run on? (e.g. Instead of just displaying `Agent: Hosted Agent` something like `Agent: Hosted Agent - v1.2.3` with a link to the release)

**Comment by sebastianhaas** [comment]
@DanielHabenicht just move to a different CI environment as long as you can.

**Comment by sebastianhaas** [comment]
@kaylangan Cheers for removing the details section from the agent queues settings, I actually had a chance to retrieve some useful information from there, so you did a good job removing it. 👏

**Comment by DanielHabenicht** [comment]
@sebastianhaas just moved to AzureDevOps Pipelines, because I had a pretty solid experience so far. 
They should [let us build our own build Containers at the start of the pipeline](https://developercommunity.visualstudio.com/idea/371868/add-ability-to-use-dockerfile-in-azure-devops-cont.html) and they wouldn't have to deal with such problems. 
I can't see the details of the agent queues anymore as well. @kaylangan.

**Comment by kaylangan** [comment]
@DanielHabenicht / @sebastianhaas sorry for the inconvenience. The details being removed was not intentional. We're in the process of fixing it.

**Comment by DanielHabenicht** [comment]
@kaylangan is there an ETA when it will be fixed? Still can't see it. 

Can you answer some of my questions [two posts above](https://github.com/microsoft/azure-pipelines-image-generation/issues/861#issuecomment-505552154)?

**Comment by kaylangan** [comment]
@DanielHabenicht it should be fixed on all accounts now. Let me know if you still can't see it.

We're adding an environment variable that will print out what version of the image is currently running, but right now, there isn't a good way to see what a prior build ran on. This is only a first step though; what you mentioned--integrated info in the UI--is a better solution.

Regarding Google Chrome 74.0.3729.157 not being in the repo, this is because we currently download from blob storage ([see comment here](https://github.com/microsoft/azure-pipelines-image-generation/issues/628#issuecomment-467659448)). The team that maintains Chrome is aware of the issue -- @kaadhina FYI.

**Comment by DanielHabenicht** [comment]
@kaylangan The details are gone again for the `Azure Pipelines` Queue.

**Comment by DanielHabenicht** [comment]
@kaylangan still there is no info about the installed chrome drivers. But I am gettings errors again. 
I will reconsider using Azure Pipelines for future projects.

**Comment by DanielHabenicht** [comment]
@kaylangan any updates?

**Comment by sbollap1** [comment]
@kaylangan any updates?[https://stackoverflow.com/questions/59669097/can-chrome-browser-be-updated-on-microsoft-hosted-agent-vs2017-win2016](stackoverflow post)

**Comment by kaylangan** [comment]
We've recently updated the way that Chrome is installed on the Windows agents so it should pull the latest version at the time that the image is generated: https://github.com/actions/virtual-environments/pull/185.

**Comment by molant** [comment]
Nice!
@kaylangan how often are the images generated?

**Comment by kaylangan** [comment]
> how often are the images generated?

Approximately weekly, but there may be delays if we hit deployment blocking bugs or have a code freeze (like we did over the holidays, for example).

**Comment by molant** [comment]
and how long until they get deployed?

**Comment by kaylangan** [comment]
Approximately weekly.

**Comment by molant** [comment]
So there could be a 2 week delay between a new Chrome version and when it gets deployed to ADO, right?
That's a great improvement to the current status. Thanks a lot!

**Comment by kaylangan** [comment]
Ah, sorry. I misunderstood your first question. We actually generate images daily, but we promote and deploy approximately weekly. So there should be about a one week delay.

**Comment by DanielHabenicht** [comment]
Will the version be shown in the worker information?
