### ISSUE TITLE
iOS 10.2 unit tests not starting on macOS 10.14 agent

### ISSUE THREAD

**Issue by MarnixArnold** [microsoft/azure-pipelines-image-generation#863]
**Describe the bug**
We are in the process of moving our build pipeline to the hosted [macOS 10.14 agent](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md) (from [macOS 10.13](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.13-Readme.md)). We are no longer able to get our unit tests to start on the iOS simulator 10.2. (on the iOS simulator 12.2, the tests run fine).

**Expected behavior**
Unit tests start on iOS simulator 10.2 when executing the pipeline on the hosted macOS 10.14 agent, as they do on the macOS 10.13 agent.

**Actual behavior**
The iOS simulator 10.2 does not start properly:
```
2019-04-17 11:51:12.254 xcodebuild[1498:10282] [MT] IDETestOperationsObserverDebug: (35077692-A429-4E78-B49D-DF6E3016618C) Beginning test session abcdefgTests-35077692-A429-4E78-B49D-DF6E3016618C at 2019-04-17 11:51:12.254 with Xcode 10B61 on target <DVTiPhoneSimulator: 0x7fa9ba55a460> {
		SimDevice: iPhone 5 (4BA2FD49-654C-452D-8966-8F77DCC12BDC, iOS 10.2, Shutdown)
} (10.2 (14C89))
2019-04-17 11:52:11.987 xcodebuild[1498:10282] [MT] IDETestOperationsObserverDebug: 59.746 elapsed -- Testing started completed.
2019-04-17 11:52:11.987 xcodebuild[1498:10282] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2019-04-17 11:52:11.987 xcodebuild[1498:10282] [MT] IDETestOperationsObserverDebug: 59.746 sec, +59.746 sec -- end
2019-04-17 11:52:11.988 xcodebuild[1498:10282] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted, NSUnderlyingError=0x7fa9b9b30e90 {Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Test runner exited before starting test execution." UserInfo={NSLocalizedDescription=Test runner exited before starting test execution., NSLocalizedRecoverySuggestion=If you believe this error represents a bug, please attach the result bundle at /Users/vsts/Library/Developer/Xcode/DerivedData/abcdefgSDK-fnqytsipmhfbuyfrimotpkurkwij/Logs/Test/Test-abcdefg-2019.04.17_11-50-58-+0000.xcresult}}}

Testing failed:
	abcdefgKYCTest.app (1793) encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted. (Underlying error: Test runner exited before starting test execution.))
** TEST FAILED **
```
(As an aside, how can I download the result bundle xcresult from the build?)

**Image impacted**
macOS 10.14

**Comment by nrajpurkar** [comment]
Thanks for filing this issue @MarnixArnold. We are taking a look at this.

**Comment by nrajpurkar** [comment]
@MarnixArnold we haven't been able to reproduce this. Can you provide any additional information? Logs, any repro steps or command that is used to run tests, or sample project?

**Comment by MarnixArnold** [comment]
> Logs, any repro steps or command that is used to run tests, or sample project?

That's one of the problems, I don't know how to get the ```.xcresult``` bundle from out of the CI environment.

**Comment by nrajpurkar** [comment]
Thanks for this information @MarnixArnold, we are taking another look into this.

**Comment by nrajpurkar** [comment]
Hi @MarnixArnold, we took a deeper look into this. Our investigation showed that Xcode 10 doesn’t work with old simulators(iPhone 5 - 10.2). We tried to run tests with iPhone 5s - 12.2 , and that worked correctly. macOS Mojave supports Xcode versions >=9.4.1. We were able to reproduce this on local agents too with the same settings(Mojave + Xcode 10 + Simulator 10.2), so this doesn't appear to be a Pipelines issue.

As solution you can:
1. Run tests on a High Sierra build agent
2. Use a supported simulator on a Mojave build agent (e.g. iPhone 5s -12.2)

**Comment by MarnixArnold** [comment]
@nrajpurkar Thanks for looking into this. At the moment we are indeed using the High Sierra build agent to run our unit tests on iOS 10 (your solution option 1). However, this will become impossible once we migrate our codebase to Swift 5, since Xcode 10.2 and Mojave are required for Swift 5 support. Effectively, we will not be able to run our unit tests for iOS 10 on Azure Pipelines anymore, which is not a good situation since we are obligated to support iOS 10, 11 and 12.

I am a bit puzzled by your finding that running the tests on the combination Mojave + Xcode 10 + Simulator 10.2 does not work. Unit testing the sample project I uploaded is working just fine on my local machine (Mac OS Mojave 10.14.4, Xcode 10.2.1, Simulator 10.2). This is the case for both running the tests from Xcode and running them from the command line with xcodebuild.

**Comment by bryanmacfarlane** [comment]
> we will not be able to run our unit tests for iOS 10 on Azure Pipelines anymore

Note that private agents are supported.  It is not as convenient and you need a mac (physical or get on from one of the hosted providers) but it will work with azure pipelines.  

I just wanted to point out it's not a limitation of azure pipelines - more of an issue with the specific hosted pool.  It's not a hard block.

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-osx?view=azure-devops

**Comment by nrajpurkar** [comment]
@MarnixArnold Wanted to let you know that we took another look here. This only seems to be an issue with iPhone 5 running iOS 10.2 on Mojave. When tested with iPhone 5s, iPhone 5SE, and iPad running iOS 10.2 on Mojave, we were able to have this work correctly. Perhaps switching to a different device simulator would solve your issue?
