### ISSUE TITLE
Update/Add PowerShell Core to 6.2.0

### ISSUE THREAD

**Issue by adityapatwardhan** [microsoft/azure-pipelines-image-generation#867]
**Tool infomation**
- Tool name: PowerShell Core
- Add or update? Add for Windows Server 2012R2, update for Windows Server 2016 and Windows Server 2019
- Desired version: 6.2.0
- If this is an add request:
  - Brief description of tool: PowerShell Core
  - URL for tool's homepage: https://github.com/PowerShell/PowerShell/

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [X] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
Add the appropriate label for the image or images that should be updated (e.g., mac, ubuntu, window).

windows-2019, vs2017-win2016 and vs2015-win2012r2

**Comment by kaylangan** [comment]
This will be available with the M151 release.
