### ISSUE TITLE
VS2017-Win2016 image python is missing parts of the stdlib?

### ISSUE THREAD

**Issue by mattip** [microsoft/azure-pipelines-image-generation#871]
**Describe the bug**
When running an [azure pipeline task for NumPy](https://dev.azure.com/numpy/numpy/_build/results?buildId=2986&view=logs) with the VS2017-Win2016 image, I get the following error

```
=================================== ERRORS 
_______________ ERROR collecting core/tests/test_multiarray.py ________________
ImportError while importing test module 'C:\hostedtoolcache\windows\Python\3.6.8
                                      \x64\lib\site-packages\numpy\core\tests\test_multiarray.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\numpy\core\tests
                                              \test_multiarray.py:43: in <module>
    from test.support import gc_collect
E   ModuleNotFoundError: No module named 'test'
------- generated xml file: D:\a\1\s\build\test\junit\test-results.xml --------
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!
1 error in 16.95 seconds
```
Note the line `from test.support import gc_collect' and the error
`E   ModuleNotFoundError: No module named 'test'`. That function is part of the python stdlib, and should be importable on all versions of python.

**Expected behavior**
I expect `from test.support import gc_collect` to succeed.

**Actual behavior**
`from test.support import gc_collect` fails, but only on the window images of NumPy's CI, which includes x86 linux, ppc linux, and macos.

**Image impacted**

windows VS2017-Win2016

**Comment by shoyer** [comment]
To quote this module's documentation (https://docs.python.org/3/library/test.html):

> Note The test package is meant for internal use by Python only. It is documented for the benefit of the core developers of Python. Any use of this package outside of Python’s standard library is discouraged as code mentioned here can change or be removed without notice between releases of Python.

**Comment by brcrista** [comment]
@zooba any thoughts on this issue?  Looks like these are just the versions we install with the Windows installer.

I tested this on my dev machine (Python 3.7.2 with the Windows installer) and the module is there.
