### ISSUE TITLE
Update / Add PyPy 3.6 to Hosted Ubuntu

### ISSUE THREAD

**Issue by kapilt** [microsoft/azure-pipelines-image-generation#872]
Following up from the merge of https://github.com/Microsoft/azure-pipelines-image-generation/pull/792/files

which added pypy2 / pypy3.5 the request would be to add pypy 3.6 (v7.1.1 latest release).

**Areas and ecosystems**

- [x] Python

**Image impacted**

Hosted Ubuntu 16.04

**Comment by stefangordon** [comment]
Would be nice to see this updated.

**Comment by stefangordon** [comment]
ping

**Comment by kapilt** [comment]
when bots are quality control and pm...

**Comment by kapilt** [comment]
fwiw, we tried docker deploy here, but that was a massive test exec time perf regression, eod. if this isn't resolved. its probably easier to leave the platform and build a gh web hook action over a different execution platform.

**Comment by asottile** [comment]
for what it's worth, it looks like this was completed here: https://github.com/microsoft/azure-pipelines-image-generation/pull/1401
