### ISSUE TITLE
Add Windows 10 SDK Update version 1903

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/azure-pipelines-image-generation#873]
Windows 10 SDK Update version 1903 can be installed with the 'Individual components' section of the Visual Studio 2019 installer.

The SDK includes XAML Islands v1, whereas the version for Windows 10 version 1809 was in preview. There are also improvements to the Windows Subsystem for Linux commands, and Windows UI Library 2.1.

**Comment by DavidStaheli** [comment]
@vijayma , @azureDaveOps, @kaylangan, @joebourneMS this is important to include in the next Windows 2019 release if possible.

**Comment by jevansaks** [comment]
This would keep us from needing to install a custom SDK during our pipeline on the hosted agent and save 5 minutes on each build. Do you have an ETA for when this will happen?

**Comment by amerkoleci** [comment]
Need this 18362 SDK as well here!

**Comment by kaylangan** [comment]
Merged. Will release with M152.

**Comment by jevansaks** [comment]
When will this be live? It looks like the agents in our instance still don't have this SDK installed.

**Comment by shadyysf** [comment]
@jevansaks , could you please provide your organization name? I would like to investigate why the 152 version hasn't reached you yet.

**Comment by jevansaks** [comment]
Sure, we’re running in the “ms” organization. Here’s an example pipeline: https://dev.azure.com/ms/microsoft-ui-xaml/_build/results?buildId=19260

**Comment by shadyysf** [comment]
@jevansaks , ahhh I see what's happening. The M152 release of the VS2017 and VS2019 images has been skipped this sprint since we were working on automating the release of the images to make delivering spring payloads faster. The M153 release is rolling out at the moment and should have those changes. ETA for that is early next week. I apologize for the inconvenience this has caused.

**Comment by jevansaks** [comment]
No problem, thanks for the update!

**Comment by MichaelLHerman** [comment]
@kaylangan @shadyysf  Should the documentation on https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2019-Server2019-Readme.md have been updated to include 18362 as part of #953 , or does that only happen after 153 is rolled out to the public ring?   When is that scheduled to happen?   

Thanks

**Comment by shadyysf** [comment]
@MichaelLHerman, we update the readme file in the release branch when the new image is generated. We only merge that back into master once the image has made it all the way through all of our production scale units. So the docs for the  M153 version for the VS2019 image are here 

https://github.com/microsoft/azure-pipelines-image-generation/blob/releases/vs2019/153.1/images/win/Vs2019-Server2019-Readme.md

**Comment by FrancoisM** [comment]
Hi.
Is there a "ring" that I can be added to somehow at that already has the SDK?
Users who upgraded their windows cannot install my UWP app that targets version 1809 and I need to release patches :-(

**Comment by kaylangan** [comment]
@FrancoisM sorry for the delayed reply. 1903 should now be available on all accounts. Please let me know if you're not seeing it.
