### ISSUE TITLE
Environment variable VCPKG_ROOT suddently blanked on VS2017 host

### ISSUE THREAD

**Issue by johanlindfors** [Microsoft/azure-pipelines-image-generation#878]
**Describe the bug**
A couple of days ago I configured a job leveraging VCPKG to install prerequisites to a project in C++. The documentation of the VS2017 host clearly specifies in the bottom that the environment variable VCPKG_ROOT should be set which then can be used to find the VCPKG toolchain file for cmake. That worked just fine until somewhen between the 18'th and 21'st of April when the VCPKG_ROOT environment variable echoes as blank.

**Expected behavior**
VCPKG_ROOT should point to the root of the VCPKG.exe installation

**Actual behavior**
VCPKG_ROOT is not set

**Image impacted**
Windows with Visual Studio 2017

**Comment by al-cheb** [comment]
Hello, Johan.

[Rename predefined environment variable $VCPKG_ROOT to $VCPKG_INSTALLATION_ROOT](https://github.com/Microsoft/azure-pipelines-image-generation/pull/780)
