### ISSUE TITLE
Missing osx 10.13 sdk from 24/04/2019 on all osx images

### ISSUE THREAD

**Issue by danwalmsley** [Microsoft/azure-pipelines-image-generation#886]
**Describe the bug**
From today builds are failing with missing 10.13 sdk

\[command]/usr/bin/xcodebuild -sdk macosx10.13 -configuration Release -workspace /Users/vsts/agent/2.150.0/work/1/s/native/Avalonia.Native/src/OSX/Avalonia.Native.OSX.xcodeproj/project.xcworkspace -scheme Avalonia.Native.OSX build -derivedDataPath ./ CODE_SIGNING_ALLOWED=NO | /usr/local/lib/ruby/gems/2.6.0/bin/xcpretty -r junit --no-color
xcodebuild: error: SDK "macosx10.13" cannot be located.
##[error]Error: /usr/bin/xcodebuild failed with return code: 64\

**Expected behavior**
macosx10.13 sdk should be installed.

**Actual behavior**
seems not to be.

**Image impacted**
osx10.13 and osx10.14

**Comment by nrajpurkar** [comment]
@danwalmsley thanks for reporting this. The team is investigating.

**Comment by al-cheb** [comment]
Hello, danwalmsley

High Sierra(**default Xcode 10.1)**:
Xcode 10.1
	macOS 10.14                   	-sdk macosx10.14

Mojave(**default Xcode 10.12.1**)
Xcode 10.2.1
	macOS 10.14                   	-sdk macosx10.14

You should set Xcode 9.4.1 version to use macosx10.13 sdk:

`
/bin/bash -c sudo xcode-select --switch /Applications/Xcode_9.4.1.app/Contents/Developer

xcodebuild -showsdks
  macOS SDKs:
  macOS 10.13                   	-sdk macosx10.13
`

**Comment by nrajpurkar** [comment]
@danwalmsley looks like this is due to the [change](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.13-Readme.md#upcoming-image-changes) that came through to update default Xcode to latest Xcode. You should set Xcode 9.4.1 version to use macosx10.13 sdk:

```
/bin/bash -c sudo xcode-select --switch /Applications/Xcode_9.4.1.app/Contents/Developer

xcodebuild -showsdks
macOS SDKs:
macOS 10.13 -sdk macosx10.13```
