### ISSUE TITLE
ubuntu-16.04 missing libxkbcommon-x11-0

### ISSUE THREAD

**Issue by cbrnr** [microsoft/azure-pipelines-image-generation#897]
**Describe the bug**
Running `pytest` for code using PyQt5 (or PySide2) on `ubuntu-16.04` results in a Python error caused by the missing package `libxkbcommon-x11-0` (see also https://github.com/pytest-dev/pytest-qt/issues/259).

**Expected behavior**
I expected the test to run without errors, as is the case for the Windows and macOS agents on Azure Pipelines.

**Actual behavior**
1. Install prerequisites:
```
python -m pip install --upgrade pip setuptools wheel
pip install PyQt5
pip install pytest pytest-azurepipelines pytest-qt pytest-xvfb
```
2. Run this test (stored in a file called `test.py`) with `pytest -s test.py` on `ubuntu-16.04`:
```
from PyQt5.QtWidgets import QWidget

def test_pyqt(qtbot):
    widget = QWidget()
```

**Image impacted**
Only `ubuntu-16.04` has this bug.

**Solution**
The image should have `libxkbcommon-x11-0` pre-installed (currently, I work around this by manually installing it via `sudo apt install libxkbcommon-x11-0`).

**Comment by j9ac9k** [comment]
I gave the thumbs up, but also wanted to reiterate that this is somewhat critical for any kind of GUI testing w/ Qt.  I happened to stumble across another post elsewhere indicating this package was needed.

**Comment by cbrnr** [comment]
Not sure if this has been resolved, so let's keep it open. Also, there's a new Ubuntu 18.04 image which I need to test, maybe this lib is already installed by default there.

**Comment by j9ac9k** [comment]
Does not look like this library is installed on ubuntu-18.04 (or ubuntu-16.04).  I would like this issue to remain open in hopes that this package is added.
