### ISSUE TITLE
Add Python 3.8-dev to hosted images (Linux, macOS, Windows)

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/azure-pipelines-image-generation#905]
This is to add the latest Python 3.8 prerelease version on the hosted images.

The developer preview versions are available on python.org: https://www.python.org/downloads/release/python-380a3/

**Comment by ijl** [comment]
This is still needed.

**Comment by ijl** [comment]
Is there any expectation of when this will be released? The 3.8 release calendar lists a final release on 2019-10-21.

**Comment by JamieMagee** [comment]
Python 3.8 has now been released https://www.python.org/downloads/release/python-380/

**Comment by vtbassmatt** [comment]
This issue is obsoleted by #1317. Also, I'm very sorry that we didn't get to it during the dev lifecycle of 3.8.
