### ISSUE TITLE
Update Docker to 18.09.6 (or latest) for Ubuntu

### ISSUE THREAD

**Issue by mabasic** [microsoft/azure-pipelines-image-generation#909]
**Describe the bug**
`ubuntu-latest` image uses an ancient version of Docker:

```
Docker version 3.0.3, build 48bd4c6d
docker-compose version 1.22.0, build f46880fe
```

**Expected behavior**
Maybe the latest version 18.09.5.

**Actual behavior**
Run these commands to get the above output.

1. docker -v
2. docker-compose -v

**Image impacted**
ubuntu

**Comment by fwilhe** [comment]
I'm wondering if an issue I have is related to this.

I push an image to a locally started registry and try to run an container from that (works on travis and locally, not on azure).

```
2019-05-06T10:29:37.6279130Z + docker run --rm '' --mount source=/home/vsts/work/1/s/infrastructure-tests,target=/cx-server/mount,type=bind --workdir /cx-server/mount --volume /var/run/docker.sock:/var/run/docker.sock --env DEVELOPER_MODE --env host_os=unix --env cx_server_path=/home/vsts/work/1/s/infrastructure-tests --env-file custom-environment.list localhost:5000/ppiper/cx-server-companion /cx-server/cx-server-companion.sh start
2019-05-06T10:29:37.6811634Z docker: invalid reference format.
2019-05-06T10:29:37.6814684Z See 'docker run --help'.
```

**Comment by mabasic** [comment]
I think that this is related to my issue of not being able to connect to a mysql instance running in a container.

I get `mysql server has gone away` if I try to connect from the host or `connection refused` if I try to connect from inside the container.

**Comment by fwilhe** [comment]
My issue seems to be resolved by removing the empty quotes which came from a not-clean way of inserting the `-it` flag when a terminal is present. Still a bit strange this works on travis.

**Comment by mabasic** [comment]
Managed to manually update the version to `Docker version 18.09.5, build e8ff056`, but I still have the same issue with my mysql container.

This is what I used:

```
- script: |
    sudo apt-get remove docker docker-engine docker.io containerd runc -y
    sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    sudo apt-get update
    sudo apt-get install docker-ce docker-ce-cli containerd.io
    docker -v
  displayName: 'Install latest docker'
```

**Comment by mabasic** [comment]
@fwilhe Does this solve your issue?

**Comment by fwilhe** [comment]
> @fwilhe Does this solve your issue?

My issue was solved by removing the leftover quotes, so I have not tried upgrading Docker.

**Comment by mabasic** [comment]
I use this code to get the latest atm version of docker-compose:

```
sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
docker-compose --version
```

**Comment by azooinmyluggage** [comment]
Ack!! we will set up a schedule for updating these

**Comment by shashankbarsin** [comment]
Version 3.x.x is because of shift from docker engine to Moby because of legal requirements. In fact the script for installing Moby picks up the latest version in stable channel with every release of images for hosted agents
