### ISSUE TITLE
Ubuntu 16.04 readme incorrectly lists Python, Ruby tools in the "Cached container images" section

### ISSUE THREAD

**Issue by willsmythe** [microsoft/azure-pipelines-image-generation#914]
**Describe the bug**
The [readme](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/linux/Ubuntu1604-README.md) for the software installed on the Ubuntu 16.04 image  incorrectly lists Python, Ruby, pip, etc in the "Cached container images" section:

![image](https://user-images.githubusercontent.com/2503052/57299556-e0cc2980-70a2-11e9-8cf0-9baf78be2b8b.png)

**Expected behavior**
Only a list of cached container images should be listed in this section.

Fix may just involve changing the ordering of steps in the packer .json for this image.

**Actual behavior**
See description.

**Image impacted**
ubuntu

**Comment by kaylangan** [comment]
Fixed in [release branch](https://github.com/microsoft/azure-pipelines-image-generation/blob/releases/ubuntu/151.2/images/linux/Ubuntu1604-README.md). Will be ported back to master once the release is ready.
