### ISSUE TITLE
Error about Xamarin.iOS 11.4 while version 12.4 is supposed to be installed

### ISSUE THREAD

**Issue by FrancoisM** [microsoft/azure-pipelines-image-generation#916]
**Describe the bug**
I have a building error:

> MTOUCH : error MT0074: Xamarin.iOS 11.14.0 does not support a deployment target of 12.2 for iOS (the maximum is 11.4)

**Expected behavior**
I don't expect any error as this repo says that the macOS image has Xamarin.iOS 12.4 installed.

**Actual behavior**
The error.

**Image impacted**
macOS

**Comment by nrajpurkar** [comment]
Hi @FrancoisM, thanks for reporting this. We'll take a look.

**Comment by nrajpurkar** [comment]
Hi @FrancoisM, thanks for your patience on this. Xamarin.iOS 11.4 is the default version on the hosted agents. You can use 12.4 and it is on the agent, but you'll need to switch to that version. You can follow these [instructions](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=designer#xamarin) to switch versions.

**Comment by nbevans** [comment]
Wow this was not obvious at all and the solution for it is a giant hack. Why is an ancient version of Xamarin.iOS the default? Shouldn't the vLatest always be the default? Why doesn't the Xamarin.iOS VSTS/DevOps task let you select what version you want to compile with?
