### ISSUE TITLE
Cannot build an android app on Hosted 2019

### ISSUE THREAD

**Issue by FrancoisM** [microsoft/azure-pipelines-image-generation#917]
**Describe the bug**
Buidling a Xamarin.Android apps fails in Hosted 2019.

**Expected behavior**
That is builds ok as it does on my machcine with VS 2019.

**Actual behavior**
It fails with error:

> Error XA5101: Could not locate the Android NDK. Please make sure the Android NDK is installed in the Android SDK Manager, or if using a custom NDK path, please ensure the $(AndroidNdkDirectory) MSBuild property is set to the custom path.

**Image impacted**
Hosted Windows 2019 with VS2019

**Comment by FrancoisM** [comment]
Note that it builds fine on macOS.

**Comment by FrancoisM** [comment]
Note that I realized that while my solution built locally in debug, I had the same error message as on the hosted agent with VS2019 in Release mode on my machine.
I installed NDK through the android SDK manager and then it built.

![image](https://user-images.githubusercontent.com/3176568/57477348-cb205500-7298-11e9-984c-69d4296c884c.png)

**Comment by madhurig** [comment]
Android NDK is installed at this location on the Hosted 2019 VMs:
ANDROID_NDK_HOME=C:\Microsoft\AndroidNDK64\android-ndk-r16b
ANDROID_NDK_PATH=C:\Microsoft\AndroidNDK64\android-ndk-r16b

In the Xamarin Android build, please try passing /p:AndroidNdkDirectory=$(ANDROID_NDK_PATH) as additional msbuild arguments to see if your builds succeed.

**Comment by FrancoisM** [comment]
Tks and it seems to work that way.

**Comment by EmilAlipiev** [comment]
> Android NDK is installed at this location on the Hosted 2019 VMs:
> ANDROID_NDK_HOME=C:\Microsoft\AndroidNDK64\android-ndk-r16b
> ANDROID_NDK_PATH=C:\Microsoft\AndroidNDK64\android-ndk-r16b
> 
> In the Xamarin Android build, please try passing /p:AndroidNdkDirectory=$(ANDROID_NDK_PATH) as additional msbuild arguments to see if your builds succeed.

when i check the yaml generated, it says that below warning. should we ignore it?

> #Your build pipeline references an undefined variable named ‘ANDROID_NDK_PATH’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
