### ISSUE TITLE
Is the "VS 2017 + Windows Server 2016" image available in docker hub?

### ISSUE THREAD

**Issue by jasjuang** [microsoft/azure-pipelines-image-generation#927]
I am in the middle of migrating our CI which is based on Jenkins + EC2 to Azure pipelines. One question I have is [Azure Pipelines Hosted VS2017 image](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md) available in docker hub or anywhere public? The reason being I want to create a custom image with pre-built vcpkg libraries, if I took a [similar approach to pcl](https://github.com/PointCloudLibrary/pcl/blob/master/.ci/azure-pipelines/build-windows.yml) and install the dependent libraries for every CI run, it will take forever to complete because the long build time of libraries like OpenCV/Boost/PCL. 

If the Azure Pipelines Hosted VS2017 image is not available anywhere public, can I get a pointer to which windows image that comes with standard build tools like visual studio, cmake, git etc so I don't have to create the windows image from scratch?

**Comment by qidydl** [comment]
There's a "containers" folder that looks to hardly have anything to do with the rest of the repository, and the image templates seem to be very strongly coupled to generating Azure virtual machines, with no provision for generating Docker containers instead. This represents a significant loss of functionality compared to the deprecated "vsts-agent-docker" project.

**Comment by vtbassmatt** [comment]
We no longer ship a pre-built Docker image. You're going to want to customize the tools and packages available on it anyhow, so we offer a starter Docker file instead. http://docs.microsoft.com/azure/devops/pipelines/agents/docker
