### ISSUE TITLE
Show image version in job

### ISSUE THREAD

**Issue by letmaik** [microsoft/azure-pipelines-image-generation#930]
I can't find a way to see which version of the hosted image is running in a particular job. Without that information it's rather pointless to create version tags in this repository. Am I missing something? If not, can the version be shown somewhere ideally with link to GitHub, e.g. https://github.com/microsoft/azure-pipelines-image-generation/tree/VS2019/151.2?

**Comment by kaylangan** [comment]
If you go to the Agent pools page in your account, you can see what software is installed: https://dev.azure.com/{your-account}/{project-name}/_settings/agentqueues. We should update this view (which just pulls in the README) to use the tag explicitly though.

**Comment by kaylangan** [comment]
We added this in the M155 update as an environment variable: https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/pipelines/sprint-155-update#updates-to-hosted-pipelines-images
