### ISSUE TITLE
MPI on macOS fails because local hostname missing in /etc/hosts

### ISSUE THREAD

**Issue by letmaik** [microsoft/azure-pipelines-image-generation#932]
I am encountering this issue: https://stackoverflow.com/questions/23112515/mpich2-gethostbyname-failed. MPI doesn't run reliably on Hosted macOS images (High Sierra and new image).

On Travis CI, `/etc/hosts` contains `127.0.0.1	Traviss-Mac-913.local` where the hostname is `$(sudo scutil --get LocalHostName).local`. This entry is missing on Azure Pipelines and because of that I run into issues with MPI, if the stackoverflow answers are correct.

To fix it, I added `echo "127.0.0.1 $(sudo scutil --get LocalHostName).local" | sudo tee -a /etc/hosts` in an early step in my pipeline. However, this seems to throw off networking completely and cancels the job at a random point. To reproduce, add a single bash task with:

```sh
echo "127.0.0.1 $(sudo scutil --get LocalHostName).local" | sudo tee -a /etc/hosts
cat /etc/hosts
sleep 60
```
See https://dev.azure.com/WRF-CMake/WRF/_build%2Fresults?buildId=232&_a=summary for an example job.

This happens both on the High Sierra and the new macOS image.

**Comment by letmaik** [comment]
For reference, an actual error:
```
Fatal error in MPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(565)..............: 
MPID_Init(224).....................: channel initialization failed
MPIDI_CH3_Init(105)................: 
MPID_nem_init(324).................: 
MPID_nem_tcp_init(178).............: 
MPID_nem_tcp_get_business_card(425): 
MPID_nem_tcp_init(384).............: gethostbyname failed, Mac-492.local (errno 1)
```

**Comment by letmaik** [comment]
I unblocked myself temporarily with a work-around: if I detect this error then I sleep a bit and re-run the mpi program.

**Comment by letmaik** [comment]
My retry-workaround doesn't always seem to work: https://dev.azure.com/wrf-cmake/WRF/_build/results?buildId=271&view=logs&jobId=f6e85cde-e336-56b3-9f3e-a859ca944b28&taskId=f63ba3fe-b27a-5e8a-fda9-30513a649ced&lineStart=52&lineEnd=174&colStart=1&colEnd=1

Any updates on this?

**Comment by nrajpurkar** [comment]
@letmaik mind running this build again after removing the "Fix hostname" task and providing the link to that?

**Comment by letmaik** [comment]
@nrajpurkar The last build I linked to doesn't have the "Fix hostname" task.

**Comment by nrajpurkar** [comment]
Hmm this doesn't seem to be a macOS specific problem. @kaylangan can you take a look?

**Comment by kaylangan** [comment]
I can't see the latest build. Is this also happening on the Windows/Linux images, @letmaik?

@nrajpurkar is adding `$(sudo scutil --get LocalHostName).local` to `/etc/hosts` not an option?

**Comment by letmaik** [comment]
@kaylangan No, macOS only.

**Comment by letmaik** [comment]
Another data point. I switched from MPICH to OpenMPI and the error manifests differently there but I think it's ultimately the same root cause:

```
A system call failed during shared memory initialization that should
not have.  It is likely that your MPI job will now either abort or
experience performance degradation.

  Local host:  Mac-481.local
  System call: unlink(2) /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T//ompi.Mac-481.501/pid.34459/1/vader_segment.Mac-481.a9d70001.3
  Error:       No such file or directory (errno 2)
```
(https://dev.azure.com/WRF-CMake/WRF/_build/results?buildId=474&view=logs&jobId=598e19a6-f325-5f51-d108-0725e4236b28&taskId=8579edd5-5c45-59da-ffa4-cc9dd024f04a&lineStart=27&lineEnd=33&colStart=1&colEnd=51)

**Comment by letmaik** [comment]
Ping.

**Comment by letmaik** [comment]
I'm still getting failures, roughly 10% of my macOS jobs are failing due to this. I never had similar on Travis CI. Did anyone figure out what could cause this?

**Comment by letmaik** [comment]
I found a work-around for the Open MPI issue (it may be an Open MPI bug but I'm not 100% sure):

```sh
export OMPI_MCA_btl=self,tcp
```
References:
https://github.com/open-mpi/ompi/issues/6518
https://github.com/open-mpi/ompi/issues/5798
https://www.mail-archive.com/devel@lists.open-mpi.org/msg20760.html
