### ISSUE TITLE
Update kubectl

### ISSUE THREAD

**Issue by PeterRockstars** [microsoft/azure-pipelines-image-generation#933]
**Tool infomation**
- Tool name: kubectl
- Add or update? update
- Desired version: 1.14.0

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [x] Container tools
- [ ] Database servers or clients
- [x] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
ubuntu-16.04-docker-17.12.0-ce-standard

**Comment by azooinmyluggage** [comment]
Ack!!

**Comment by shashankbarsin** [comment]
kubectl binary is currently on 1.14.2 on hosted Ubuntu 16.04 image. In fact we have automated the process of installation of latest version of kubectl client with every release of images used for hosted agents - [source code](https://github.com/microsoft/azure-pipelines-image-generation/blob/a373311832e031acdbe66d0472f41f5dfb7d10d9/images/linux/scripts/installers/kubernetes-tools.sh#L12)
