### ISSUE TITLE
Windows path d:\a appearing on Linux and breaking build

### ISSUE THREAD

**Issue by letmaik** [microsoft/azure-pipelines-image-generation#948]
Some jobs are failing on Hosted Ubuntu 1604 (doesn't seem to affect all agents/jobs) because a Windows path somehow got into the pipeline: https://dev.azure.com/wrf-cmake/WRF/_build/results?buildId=271&view=logs&jobId=f8cb0715-5928-550f-9ff8-59076a216b99&taskId=298fb761-f52d-542b-c1f1-6888bc015d2a&lineStart=13&lineEnd=22&colStart=1&colEnd=1

> [command]/bin/bash --noprofile --norc /home/vsts/agents/2.150.3/d:\a/_temp/f27d748a-a2d6-49e9-ad19-ec6b94c46968.sh

What's `d:\a` doing in there?

Also, the source folder is apparently "/home/vsts/agents/2.150.3/d:/a/1/s" which then let's CMake fail as the folder actually doesn't exist. Something weird is broken here.

**Comment by Gismork** [comment]
I had the same issue yesterday and opened a ticket on the support forum : https://developercommunity.visualstudio.com/content/problem/571062/hosted-ubuntu-agent-failure-on-nodejs-tool-install.html.
Today that's Azure DevOps that is completely broken here 😢

**Comment by kaylangan** [comment]
Assigning to @alepauly to resolve once the fix deploys.

**Comment by alepauly** [comment]
This was due to some miconfigured pools. @letmaik, @Gismork can you please confirm you're not seeing this issue any longer? If you are, please email me your Azure DevOps org name so I can check. Thanks!

**Comment by letmaik** [comment]
@alepauly All fine for me, thanks.

**Comment by Gismork** [comment]
@alepauly Seems fine here too, didn't see any failed build on this pool. Thanks for the follow up !
