### ISSUE TITLE
"windows-2019" image includes Python 3 contrary to readme

### ISSUE THREAD

**Issue by gsnedders** [microsoft/azure-pipelines-image-generation#963]
**Describe the bug**
https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2019-Server2019-Readme.md notes [these](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2019-Server2019-Readme.md#python) versions of Python are available "through the Use Python Version task", and [these](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2019-Server2019-Readme.md#python-64-bit) versions of Python are available (with no constraint, unlike the others).

Currently, the latter includes only Python 2.7.15. However, `python.exe --version` on Azure Pipelines on the "windows-2019" image returns `Python 3.6.8`. This is unexpected, given Python 3.6.8 should only be available through the "Use Python Version" task. I consider this a bug because the documentation should reflect the image available.

And, to be clear, I care much less about what version of Python is the default on the PATH than I do the documentation telling me what version of Python will be there!

**Expected behavior**
The documentation accurately reflects the image available.

**Actual behavior**
The documentation disagrees with the image.

**Image impacted**
* windows-2019

**Comment by gsnedders** [comment]
This is still true.

**Comment by kaylangan** [comment]
I think this is fixed? Python 3.7.4 is listed: https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2019-Server2019-Readme.md#python-64-bit

Am I misunderstanding?

**Comment by gsnedders** [comment]
Bleh bleh bleh, I can't read. I'm sorry.
