### ISSUE TITLE
[windows-2019] MinGW is not installed in C:\tools\mingw64\bin or at all

### ISSUE THREAD

**Issue by mloskot** [microsoft/azure-pipelines-image-generation#966]
## Issue 1: MinGW location is unknown

The current [Vs2019-Server2019-Readme.md](https://github.com/microsoft/azure-pipelines-image-generation/blob/a87c8ab8226e109f12734b1c199f5d9e2d5df860/images/win/Vs2019-Server2019-Readme.md) says

> MinGW
> Version: 8.1.0
> Environment:
>    PATH: contains location of the MinGW 'bin' directory

But, it does not say anything about where the MinGW is deployed, is it the mingw32 or mingw64 variant, etc.

One need to look into the installer history to find out that initially it was:

https://github.com/microsoft/azure-pipelines-image-generation/blob/28018e710894303204fd89161079080dcfc8e53a/images/win/scripts/Installers/Install-MinGW.ps1#L9-L11

but now only the comment indicates the location:

https://github.com/microsoft/azure-pipelines-image-generation/blob/c8bdf279aa9fe005d44b24c6ba60a1bd1c05fcac/images/win/scripts/Installers/Install-MinGW.ps1#L4-L10

## Issue 2: How to use the (presumably) deployed MinGW (with CMake)

Trying to figure out how to specify a build job using MinGW:

```
  - job: 'mingw_cxx11'
    pool:
      vmImage: 'windows-2019'
    steps:
    - script: |
        cmake -H. -B_build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
```

This is failing  with

```
##[error]CMake Error at C:/Program Files/CMake/share/cmake-3.14/Modules/CMakeMinGWFindMake.cmake:12 (message):
##[error]  sh.exe was found in your PATH, here:

  C:/Program Files/Git/bin/sh.exe

  For MinGW make to work correctly sh.exe must NOT be in your path.

  Run cmake from a shell that does not have sh.exe in your PATH.

  If you want to use a UNIX shell, then use MSYS Makefiles.

Call Stack (most recent call first):
  CMakeLists.txt:2 (project)
```

The (common) workaround as `set PATH=C:\tools\mingw64\bin;%PATH%` does not fix the issue.

## Issue 3: Inspecting MinGW location

Modifying slightly the previous YAML to inspect the MinGW location(s):

```
  - job: 'mingw_cxx11'
    pool:
      vmImage: 'windows-2019'
    steps:
    - script: |
        dir C:\tools\
        dir C:\tools\mingw64
        dir C:\tools\mingw64\bin
        set PATH=C:\tools\mingw64\bin;%PATH%
        set
        cmake -H. -B_build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=11
```

confirms there is no `C:\tools\mingw64`:

```
Directory of C:\tools

04/08/2019  10:56 PM    <DIR>          .
04/08/2019  10:56 PM    <DIR>          ..
04/08/2019  10:56 PM    <DIR>          php
               0 File(s)              0 bytes
               3 Dir(s)  22,706,958,336 bytes free
 Volume in drive C is Windows
 Volume Serial Number is AA9E-CDC6

 Directory of C:\tools

##[error]File Not Found
##[error]The system cannot find the file specified.
```

## Issue 4: Inspecting PATH

Inspcetion of `PATH` confirms the only MinGW-related path is `C:\Program Files\Git\mingw64\bin`

## Issues summary

1. Documentation is outdated or incorrect
2. The `Installer-MinGW` script comment is outdated or incorrect
3. It is practically very or impossible to figure out how to use MinGW on Azure Pipelines

**Comment by spl** [comment]
I found this issue in a web search. I can't help with the majority of your issues, but I'd just like to add that another common workaround for the MinGW/`sh.exe` issue is to add the CMake argument `-DCMAKE_SH="CMAKE_SH-NOTFOUND"`.

**Comment by mloskot** [comment]
Bump

**Comment by mloskot** [comment]
Bump

**Comment by mloskot** [comment]
Is this really such a difficult issue to receive answer and get this closed?
I could even update the docs or the README myself with a subsequent PR.
Amazing!

**Comment by vineetbansal** [comment]
Bump. Documentation should mention the correct path `C:\Program Files\Git\mingw64\bin`
