### ISSUE TITLE
/ not owned by root

### ISSUE THREAD

**Issue by AndyMoore** [microsoft/azure-pipelines-image-generation#969]
**Describe the bug**
using ubuntu 16.04 hosted agent, I've been hitting a problem doing snap install. Digging it seems like / isn't owned by root:root:

drwxr-xr-x 26 vsts staff 4096 May 23 20:32 /

This is breaking various builds

**Expected behavior**

/ should be root owned

**Actual behavior**
A description with steps to reproduce the issue.

1. Step 1
2. Step 2

**Image impacted**
ubuntu 16.04

**Comment by ihnorton** [comment]
Also seeing this. Here's a public repo/build if it helps: https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=478&view=logs (the `linux_hdfs` job)

**Comment by ihnorton** [comment]
Related:
- https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1811580
- https://askubuntu.com/questions/1094776/systemd-tmpfiles-wont-start

I was able to work around this issue with the suggestion in the 2nd link (run `sudo chown root.root /` 🙃)

**Comment by ihnorton** [comment]
if the stale bot would leave this alone, that would be great

**Comment by alepauly** [comment]
Closing since this isn't an issue in 18.04 which is the newer image and workaround works well enough for 16.04. If needed please reopen issue in actions/virtual-environments.
