### ISSUE TITLE
Update-DockerImages.ps1 don't report errors when failing to cache requested images

### ISSUE THREAD

**Issue by alepauly** [microsoft/azure-pipelines-image-generation#970]
**Describe the bug**
If a container image repo doesn't contain or cannot serve an image as requested by the commands in Update-DockerImages.ps1 (for both VS2017 and VS2019 images), then the script doesn't error out and the image generation continues, creating an incomplete image.

**Expected behavior**
The script throws an error and halts image build when it cannot cache a container image

**Actual behavior**
Error message displays in log but image build continues

**Image impacted**
VS2017, VS2019

**Comment by ds-ms** [comment]
Fixed it here: https://github.com/microsoft/azure-pipelines-image-generation/pull/1021
