### ISSUE TITLE
Container Job: Initialize Container fails with 'container not running'

### ISSUE THREAD

**Issue by davidtom** [microsoft/azure-pipelines-image-generation#972]
**Describe the bug**
I am trying to run a container job with a private image running on alpine. The `Initialize containers` step gets as far as running `/usr/bin/docker exec [id] sh -c "command -v bash"`, but fails there with `Error response from daemon: Container[id] is not running`. When I follow a similar command sequence locally as what is being done on the agent, I do not get an error.

**Expected behavior**
Agent running `/usr/bin/docker exec [id] sh -c "command -v bash"` should succeed.

**Actual behavior**
Agent running `/usr/bin/docker exec [id] sh -c "command -v bash"` on an alpine image (specifically `golang:alpine`) fails because the `container is not running'

**Image impacted**
Ubuntu 1604

**Comment by shashankbarsin** [comment]
@davidtom initialisation of the container job is failing as golang:alpine doesn't meet the [pre-requisites needed for container jobs](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml#requirements) when using Linux-based containers - 
- Bash
- glibc-based
- Can run Node.js (which the agent provides)
- Does not define an ENTRYPOINT

golang:alpine fails on one of these pre-requisites as it doesn't include bash.

Following is a workaround I'd suggest - 
- Author a Dockerfile with golang:alpine as the base image
- Add the following line to the Dockerfile
```RUN apk add --no-cache bash nodejs```
- Build the image and push to a container registry
- Specify this image as the one to be used by container jobs

**Comment by davidtom** [comment]
Hi @shashankbarsin, so sorry for the delayed response on this.

I had seen those requirements before, but somehow missed that golang:alpine is lacking bash. Thanks for pointing that out!

I'll give this another try with the directions you specified. Thank you so much for the detailed response!

**Comment by Julio-Guerra** [comment]
I am having the same issue and I still have the "Initialize containers" failing.
Here is the Dockerfile I use to create the golang alpine image: https://github.com/sqreen/azure-pipelines-container-golang/blob/master/alpine/1.13/Dockerfile
I started by also adding `nodejs` but it didn't change anything, it seems to be mounted by azure pipelines into the container (https://dev.azure.com/sqreenci/Go%20Agent/_build/results?buildId=694).

Any idea?

**Comment by Julio-Guerra** [comment]
@shashankbarsin I got stuck at this step:

> Try create an user with UID '1001' inside the container.
> ##[command]/usr/bin/docker exec  ab023993fd7a4922a20882f6d814a7e89bab6d3ed871f65bd35466400b964a23 bash -c "grep 1001 /etc/passwd | cut -f1 -d:"
> ##[error]Docker exec fail with exit code 1

Here is the Dockerfile of the alpine container being used https://github.com/sqreen/azure-pipelines-container-golang/blob/master/alpine/1.12/Dockerfile

I can locally `execute every `docker exec` commands performed by the container initialization :thinking:

**Comment by milanjaros** [comment]
To resolve pre-requisites follow https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/non-glibc-containers.md
