### ISSUE TITLE
Chocolatey Hangs for 1m on first run

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/azure-pipelines-image-generation#977]
**Describe the bug**
Running any chocolatey command hangs on "[Pending] Removing all pending packages that should not be considered installed..." message in debug, taking at least 1 minute to complete before moving on

**Expected behavior**
Chocolatey is initialized and indexed and ready to install software quickly on the build host

**Actual behavior**
A description with steps to reproduce the issue.

azure-pipelines.yaml
```yaml
- powershell: cinst -yvd terraform --version '0.12'
  displayName: Chocolatey Install Terraform 0.12
```

**Image impacted**
Windows

**Comment by kaylangan** [comment]
Are you seeing this on both the VS2017 and VS2019 image?

**Comment by JustinGrote** [comment]
Yes, just ran in VS2017 image and it got stopped in the same spot:
[image: image.png]

**Comment by gep13** [comment]
@JustinGrote would you be able to provide the full set of logs for when this is happening?

**Comment by JustinGrote** [comment]
Sure, though it should be pretty easy to reproduce using the YAML I
provided.

**Comment by ferventcoder** [comment]
Is this something that should be logged over at https://github.com/chocolatey/choco as an issue?

**Comment by ferventcoder** [comment]
Or do we think it is related to azure pipelines? 

My ventured guess here is that the profile is loading (might be best to be sure that it is not setup on azure pipelines)

**Comment by JustinGrote** [comment]
I'm thinking something in the packer image build is not cached or
incorrectly cached and chocolatey is having to clean it up. This doesn't
happen outside of AzDO build hosts, and subsequent runs after the first one
on the same host seem to be fine (performant)

**Comment by hbuckle** [comment]
I finally tracked this down. As part of the `RemovePendingPackagesTask` chocolatey calls `Directory.EnumerateFiles` on `C:\ProgramData\chocolatey\lib`
The `gradle` and `mingw` folders take about 45 seconds to enumerate on the first run. Subsequent runs are much quicker, presumably due to caching.
Adding this script before running choco speeds things up

```powershell
      if (Test-Path "$env:ChocolateyInstall\lib\gradle") {
        Move-Item "$env:ChocolateyInstall\lib\gradle" -Destination "C:\gradle" -Force
      }
      if (Test-Path "$env:ChocolateyInstall\lib\mingw") {
        Move-Item "$env:ChocolateyInstall\lib\mingw" -Destination "C:\mingw" -Force
      }
```

(I tried just deleting the folders, but that takes just as long. Moving is much quicker)

**Comment by JustinGrote** [comment]
@gep13 @kaylangan Can we get a revisit on this? @hbuckle's workaround works but should there be a precache step in the build process so that people dont *have* to workaround it?

**Comment by kaylangan** [comment]
I've opened this issue in the new repo. You can follow status there: https://github.com/actions/virtual-environments/issues/253
