### ISSUE TITLE
Unable to build ubuntu packer image 

### ISSUE THREAD

**Issue by anand5555** [microsoft/azure-pipelines-image-generation#982]
Ubuntu packer exits out at the python installation. 

![image](https://user-images.githubusercontent.com/31290069/58678090-7ec2b500-832c-11e9-8eeb-e131b6561ea7.png)

**Comment by kaylangan** [comment]
Appears to be same as https://github.com/microsoft/azure-pipelines-image-generation/issues/952#issuecomment-495083525 which was fixed in #968.
