### ISSUE TITLE
Building simple dynamic C++ DLL not possible on VS2019 hosted agent

### ISSUE THREAD

**Issue by doMConSwiss** [microsoft/azure-pipelines-image-generation#992]
The VS 2019 template project of a "Dynamic-Link Library" C++ can't be built on a VS 2019 hosted agent.

Error message:
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\winnt.h(34,0): Error C1083: Cannot open include file: 'ctype.h': No such file or directory

Somehow the files in C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt are not found...

Any suggestion?

**Comment by kaylangan** [comment]
@moswald I believe you're already investigating this one (related to [this Developer Community issue](https://developercommunity.visualstudio.com/content/problem/539158/hosted-windows-2019-with-vs2019-is-failing-builds.html)).

Looks like we do something special [for Windows WDK for VS2017](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/win/scripts/Installers/Vs2017/Install-WDK.ps1#L36) that we've [commented out for VS2019](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/win/scripts/Installers/Vs2019/Install-WDK.ps1#L37). Not sure why, but perhaps a place to start.

**Comment by moswald** [comment]
Thanks @kaylangan, I am investigating the same thing. I missed the window to fix it for the next deployment of the vms, but I'm targeting getting this fix in before the end of our current sprint.

**Comment by moswald** [comment]
Thanks for the reminder stale bot - this has been fixed already. I'll close this, but you can reopen if you're still having issues.
