### ISSUE TITLE
Add QEMU on Linux Image

### ISSUE THREAD

**Issue by cor3ntin** [microsoft/azure-pipelines-image-generation#995]
**Tool information**
Adding QEMU (+binfmt) on linux host would help cross compilation and test of non-x86 architectures
My personal use case is flatpak but it would also enable building docker arm containers, for example for rpi, cross compilation of snappy packages, android emulation and so forth

Command to install qemu on ubuntu:

`apt-get install qemu binfmt-support qemu-user-static` 

**Areas and ecosystems**

- [x] Android
- [ ] C / C++
- [x] Container tools
- [ ] Database servers or clients
- [x] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [x] Testing and code coverage
- [ ] Xamarin
- [x] Other

**Image impacted**
ubuntu

**Workaround**

None, binfmt (which allows the kernel to run non-x86 binaries) is implemented as a kernel module of the host and as such cannot be installed in a container

**Are you willing to submit a PR?**

**Comment by martinwoodward** [comment]
What a few folks do today is make use of the `container` tag in Azure Pipelines to pull in a clean container and use qemu in that.  See the following for examples from @ethomson:

 - https://devblogs.microsoft.com/devops/cross-platform-container-builds-with-azure-pipelines/
 - https://github.com/libgit2/libgit2/blob/master/azure-pipelines/nightly.yml#L176-L189

**Comment by cor3ntin** [comment]
I think the limiting factor is the lack of binfmt support rather than qemu per-say - `/proc/sys/fs/binfmt_misc` needs to be mounted by the host

See for example https://yen3.github.io/posts/2017/build_multi_arch_docker_image/
https://en.wikipedia.org/wiki/Binfmt_misc

**Comment by martinwoodward** [comment]
So big health warning that I haven't done this myself yet so I am probably being very dumb here, but what is it that you are not able to do?  I know that a few folks create non x86 images using this approach today in Azure Pipelines. 

Few examples of them doing it (including using binfmt_misc)

 - https://headmelted.com/continuous-delivery-with-azure-pipelines-and-github-releases-20a0155360d8
 - https://github.com/home-assistant/hassio-homeassistant/blob/master/azure-pipelines.yml#L102-L111
 - https://github.com/conda-forge/lightgbm-feedstock/blob/master/.azure-pipelines/azure-pipelines-linux.yml#L30-L32

**Comment by cor3ntin** [comment]
Oh, i see what you mean - i would have to run the container myself entirely.

**Comment by martinwoodward** [comment]
The container tag helps you easily get the container running and file systems mounted to your build output so that you can access your source files etc. But means you completely control what is installed in that container and you get complete control of which image you use. Means that the thing you do your builds in doesn't even have the job agent and it's pre-requisites installed so allows you do do super clean builds.  Another good post to read is this one:

 - https://devblogs.microsoft.com/devops/using-containerized-services-in-your-pipeline/

Good luck!

**Comment by cor3ntin** [comment]
yeah, but using that container tag (which I currently do, it's great) - I can't set up binfmt on the host before hand so my only choice would be not to use it, which i wanted to avoid.
So for my use case I thing i need to fallback to invoking docker run myself.

I imagine an alternative solution to install qemu and associated binfmt support on the image would be to have a way to run a job on the container host before launching the container

**Comment by bryanmacfarlane** [comment]
maybe I'm missing something (likely since I'm just jumping in here :) ) - why can't binfmt and other tools by in the container that the job is specified to run in>

**Comment by cor3ntin** [comment]
the supported binary formats are controlled by /proc/sys - not something you can change from within a container

**Comment by bryanmacfarlane** [comment]
@TingluoHuang for thoughts.

**Comment by TingluoHuang** [comment]
I think we can add a feature to allow you run some setup script before we start the container. :)
