### ISSUE TITLE
python regression missing sqlite libraries in image

### ISSUE THREAD

**Issue by kapilt** [microsoft/azure-pipelines-image-generation#996]
For the last few days we've been seeing intermittent errors across ubuntu 16.04 workers (python project), with the job failing due to inability to import the python stdlib sqlite3 module.

https://dev.azure.com/cloud-custodian/cloud-custodian/_build/results?buildId=2349
https://dev.azure.com/cloud-custodian/cloud-custodian/_build/results?buildId=2351

the custom error message is a try/except around importing sqlite3 module. It looks like a recent change (~last week) has caused an image regression for python, as this is a standard lib module. The error appears across python versions supported (2.7, 3.6, 3.7), the error appears to be intermittent.

**Comment by kaylangan** [comment]
We're currently in the process of reverting the change that caused the regression and will roll out the update soon.

To double check though--we identified the issue in 2.7, 3.5, and 3.7. Are you also seeing this in 3.6?

**Comment by kapilt** [comment]
digging through it looks like just 2.7 and 3.7, thanks.

**Comment by kapilt** [comment]
is there any work around we can do in our pipeline.yml ? i've tried installing sqlite3 and libsqlite3-0 but to no avail, we continue to see the following errors (atm just 2.7)

```
    import sqlite3
/opt/hostedtoolcache/Python/3.7.3/x64/lib/python3.7/sqlite3/__init__.py:23: in <module>
    from sqlite3.dbapi2 import *
/opt/hostedtoolcache/Python/3.7.3/x64/lib/python3.7/sqlite3/dbapi2.py:27: in <module>
    from _sqlite3 import *
E   ModuleNotFoundError: No module named '_sqlite3'
```

**Comment by gaborbernat** [comment]
@kaylangan any ETA on that rollback? 🤔

**Comment by trallard** [comment]
hey @kaylangan 👋🏼

I just followed through and this issue is only affecting Python 3.5 and 3.7.  The 3.6 version is working as expected

**Comment by kapilt** [comment]
fwiw, more reports of the same, https://developercommunity.visualstudio.com/content/problem/588219/sqlite3-importerror-python-357-and-373.html

it appears the only work around is to disable python linux tests where version != 3.6

**Comment by kaylangan** [comment]
@gaborbernat When we deploy it--yes, Python 3.7 will go back to 3.7.2.

Please follow this issue on our Developer Community site for updates: https://developercommunity.visualstudio.com/content/problem/598264/known-issue-azure-pipelines-images-missing-sqlite3.html

We will be posting a workaround shortly because the deployment will take time to hit all rings.

**Comment by kaylangan** [comment]
Workaround has been posted on Developer Community: https://developercommunity.visualstudio.com/content/problem/598264/known-issue-azure-pipelines-images-missing-sqlite3.html

**Comment by kapilt** [comment]
is there an eta on the actual rollback/final fix being fully rolled out?

The work around, which is great to have, is a bit heavy handed in that its a remove, download, install over existing installations of python at runtime, which adds significant latency for ci. I did two builds this morning (sans workaround), one of which worked on 2.7/3.7 and one of which failed, so there does appear to be some movement.

**Comment by techalchemy** [comment]
So this is definitely still broken:

https://dev.azure.com/sarugaku/requirementslib/_build/results?buildId=244&view=logs&j=a4b3e8ff-201a-5dea-7076-88cd0823a905

And the proposed fix doesn't work anymore because the files I'm supposed to copy over don't exist:

https://dev.azure.com/sarugaku/requirementslib/_build/results?buildId=243&view=logs&j=113bde7e-0bff-5098-c384-1c9613dbc697

So I can't even build anything on azure that involves python, how should I proceed?

**Comment by hynek** [comment]
It's true, you broke it again after it worked for a few days: https://dev.azure.com/the-hynek/pem/_build/results?buildId=104&view=logs&jobId=8cbc8936-4a42-5e55-22bd-a734f2f1826f&taskId=f2dccee2-fc71-5465-5054-b7fa9c1aaf28&lineStart=34&lineEnd=35&colStart=1&colEnd=1

Time for deadsnakes again I guess…

**Comment by kaylangan** [comment]
We cannot apologize enough for the delay in getting this fix out. We completely understand your frustrations and thank you for your patience. We have fully rolled out new versions of Python that include sqlite3. We plan to publish a postmortem about how this bug got introduced, why it took so long to deploy a fix, and what we're doing to make sure that it doesn't happen again. I will update this issue with a link to the postmortem when it is available.

If you are still experiencing problems, please let us know.

**Comment by kaylangan** [comment]
Hi all, thanks for the patience. Here is the link to the postmortem: https://status.dev.azure.com/_event/130756107
